Add hook in the processIndexPHP method for a very early plugin entryp…
ILIAS-eLearning/ILIAS pull request #1041
Opened 2018-04-25 14:12 UTC by amichelsdatabay

…oint

2018-04-25 14:18 UTC, mjansenDatabay commented
@amichelsdatabay  Please check your indent style.

2018-04-25 14:42 UTC, chfsx reviewed
Just my two cents

2018-04-25 14:42 UTC, chfsx commented on Services/Init/classes/class.ilStartUpGUI.php
> +        if (isset($DIC["ilPluginAdmin"]))
You could use `$DIC->offsetExists("ilPluginAdmin");` instead

2018-04-25 14:42 UTC, chfsx commented on Services/Init/classes/class.ilStartUpGUI.php
> +        if (is_object($ilPluginAdmin)) {
How about a check for `$ilPluginAdmin instanceof ilPluginAdmin`

2018-04-25 15:18 UTC, mjansenDatabay requested changes

2018-04-25 15:18 UTC, mjansenDatabay commented on Services/Init/classes/class.ilStartUpGUI.php
> +        //
@amichelsdatabay Please remove this line.

2018-04-25 15:18 UTC, mjansenDatabay commented on Services/Init/classes/class.ilStartUpGUI.php
> +		global $ilIliasIniFile, $ilAuth, $ilSetting, $DIC;
@amichelsdatabay You could use the `$DIC` to also fetch `$ilIliasIniFile, $ilAuth, $ilSetting`.

2018-04-25 17:48 UTC, mjansenDatabay commented
@amichelsdatabay What is the purpose of this? Do you need this to manipulate the generated HTML? Oder do you just need some kind of hook?

2018-05-13 08:14 UTC, alex40724 requested changes
Hi, thank you for this pr. However this more looks like a request for the event Hook plug-in slot. And this point no HTML is generated. Could you explain the purpose of this request in more detail? Thanks.

2018-05-15 09:50 UTC, amichelsdatabay commented
I took the UI hook as seen in the ilUtil::redirect method because this hook is used to replace (the visible part) the routing of ILIAS.
But i see that multiple slots will fit here. Please decide yourself (or with the technical board) which is the best slot. I will change it to your choice.

2018-06-04 08:37 UTC, alex40724 commented on Services/Init/classes/class.ilStartUpGUI.php
> +        }
Pleas check your indentation style

2018-06-04 08:49 UTC, alex40724 commented
Could you explain the purpose of this request in more detail? If you cannot do this, I have to simply close this. What is the use case? Why does it use the getHTML method? Why is $resp not being processed?

I think the code in redirect is a misuse of the interface, since it does not deal with HTML but uses getHTML and modifyHTML. It would be better to extend the interface of the slot with additional methods, imo. I guess this would also be appropriate for your case. But since the purpose is unclear to me, I cannot make any suggestions.

2018-10-09 12:12 UTC, mjansenDatabay commented
@amichelsdatabay Can you please give some feedback here?

2018-10-09 17:54 UTC, PurHur commented
Matter has been solved using the hook within the ilUtil redirect method. Sadly this is by far from being a good practice. Kindly acknowledge that these discussion are anything but a productive approach in developing a good piece of art (software ;-) ).
Will not participate any further in this discussion, just treat this matter as closed.

2018-11-14 08:36 UTC, chfsx commented
@alex40724 this seems to be outdated since @amichelsdatabay is no longer interested in changing this.

2018-11-14 08:36 UTC, closed without merging