added get in front of URI Data object property methods and adapted tests accordingly
ILIAS-eLearning/ILIAS pull request #1085
Opened 2018-06-06 13:34 UTC by dkloepfer

2018-06-06 13:35 UTC, dkloepfer commented
@legionth Ping!

2018-06-11 07:06 UTC, legionth requested changes
While the changes of the method names LGTM. I would suggest to open two separated PRs. Even if the changes are removing or refactoring tests(See `test_with_authority_invalid_2` and `test_with_host_invalid_2`).

2018-06-11 07:06 UTC, legionth commented on tests/Data/URITest.php
> -	public function test_with_host_invalid_2()
Why is this method removed? Is `null` now a valid value? What has this todo with the current changes?

2018-11-23 14:37 UTC, klees approved these changes
LGTM! Needs approval by JF, since this is a breaking change.

2018-12-03 12:54 UTC, matthiaskunkel commented
Jour Fixe, 03 DEC 2018 : PR is highly appreciated. Please merge into trunk.

2018-12-12 08:25 UTC, merged