UI Input Password, Constraints
ILIAS-eLearning/ILIAS pull request #1095
Opened 2018-06-18 12:04 UTC by nhaagen

This adds constraints to the password-input to enforce lower/upper/special chars and numbers.

2018-06-29 09:46 UTC, klees requested changes
I like very much. Tests for constraints are missing. Will still take this to JF.

2018-06-29 09:46 UTC, klees commented on src/UI/Implementation/Component/Input/Field/Password.php
> +            $pw_validation->hasMinLength($min_length),
Indentation please.

2018-06-29 09:46 UTC, klees commented on src/UI/Component/Input/Field/Factory.php
> +	/**
:+1:

2018-07-16 11:31 UTC, matthiaskunkel commented
Jour Fixe, 16 JUL 2018 : New rules are accepted by JF

2018-07-18 08:00 UTC, klees commented
@Amstutz: Wanna have a look into this?

2018-07-20 11:21 UTC, klees approved these changes

2018-07-20 11:30 UTC, Amstutz commented
@nhaagen Thx a lot for this contribution!

2018-07-20 11:30 UTC, merged