UI Input,  Password with Revelation
ILIAS-eLearning/ILIAS pull request #1119
Opened 2018-07-20 12:11 UTC by nhaagen

Especially on mobile devices, I like to reveal the entered chars; this PR introduces the eye-closed/open glyphs and adds the revelation-option to password inputs.

![secret](https://user-images.githubusercontent.com/3328364/43001755-b44a7530-8c26-11e8-8ca9-99a0e9456bd1.png)
![revealed](https://user-images.githubusercontent.com/3328364/43001758-b6290010-8c26-11e8-858f-1467ce934a88.png)

2018-07-20 14:23 UTC, mjansenDatabay commented
I like!

As far as I know @bheyser plans to use this type of field for the process described here: https://ilias.de/mantis/view.php?id=23242

2018-07-30 09:05 UTC, Amstutz requested changes
LGTM. Some minor remarks about description.

However, there is one major point:
- I believe the aria label here is crucial for blind people. Imagine somebody without sight sitting in a public place revealing the password to other people without knowing, since the label for revealing or not was not clear. Would be bad. Improve the aria label.

2018-07-30 09:05 UTC, Amstutz commented on src/UI/Component/Glyph/Factory.php
> +	 *       The EyeClosed Glyph is used to toggle the revelation-mode of password fields.
"Eye Closed" in clear text.

2018-07-30 09:05 UTC, Amstutz commented on src/UI/Component/Glyph/Factory.php
> +	 *       The EyeClosed Glyph is used to toggle the revelation-mode of password fields.
Which mode is Eye Close? Letters are shown, clearly state so (effect further down indicates this I know, but make this more to the point here).

2018-07-30 09:05 UTC, Amstutz commented on src/UI/Component/Glyph/Factory.php
> +	 *          The aria-label MUST be 'eye closed'.
There should be some indication about the state by the aria attributes. I would prefer something like "Eye closed - charactors of inputs fields visible".

2018-07-30 09:05 UTC, Amstutz commented on src/UI/Component/Glyph/Factory.php
> +	 *       The EyeOpen Glyph is used to toggle the revelation-mode of password fields.
Eye Open

2018-07-30 09:05 UTC, Amstutz commented on src/UI/Component/Glyph/Factory.php
> +	 *       The EyeOpen Glyph is used to toggle the revelation-mode of password fields.
Same as above, leave some state indication.

2018-07-30 09:05 UTC, Amstutz commented on src/UI/Component/Glyph/Factory.php
> +	 *          The aria-label MUST be 'eye open'.
Same as above, make state clear here for blind people.

2018-07-30 11:55 UTC, matthiaskunkel commented
Jour Fixe, 30 JUL 2018 : We highly appreciate this PR. Please consider Timon's comments and offer a solution before committing it to trunk.

2018-08-09 14:18 UTC, klees commented
@Amstutz May we merge this?

2018-08-09 14:21 UTC, merged