5 4 ks reset glyph
ILIAS-eLearning/ILIAS pull request #1123
Opened 2018-07-24 11:35 UTC by tfamula

Introducing a new Reset Glyph, coming from [Responsive Table Filters](https://www.ilias.de/docu/goto.php?target=wiki_1357_Responsive_Table_Filters#ilPageTocA121)

2018-07-30 08:06 UTC, Amstutz requested changes

2018-07-30 08:06 UTC, Amstutz commented on src/UI/Component/Glyph/Factory.php
> +	 *          The Reset Glyph SHOULD not come without an Apply Glyph and vice versa.
Why?

2018-07-30 08:06 UTC, Amstutz commented on src/UI/Component/Glyph/Factory.php
> +	 *          greying out the Reset Glyph.
Add aria state.

2018-07-30 08:08 UTC, Amstutz commented
Exactly the same reasoning as with the apply. Not sure about the choice of glyph the map the function, however since Christophe and Yvonne seem to be fine, I will not object.

Two things:
- Why does this has to always come with the reset glyph?
- Add some aria attribute for the disabled state (e.g. aria-disabled).

2018-07-30 09:18 UTC, tfamula commented on src/UI/Component/Glyph/Factory.php
> +	 *          The Reset Glyph SHOULD not come without an Apply Glyph and vice versa.
see [Apply Glyph](https://github.com/ILIAS-eLearning/ILIAS/pull/1122)

2018-07-30 12:04 UTC, matthiaskunkel commented
We highly appreciate this suggestion and accept it for trunk. Please add the aria state to support accessiblility and introduce the 'withUnavailableAction' for glyphs before committing to trunk.

2018-08-02 13:12 UTC, alex40724 commented on src/UI/templates/default/Glyph/glyph.less
> +		filter: alpha(opacity=20); /* For IE8 and earlier */
No need to support IE8.

I guess a color: @il-glyph-disabled-color; would make more sense than using opacity.

2018-08-02 13:16 UTC, alex40724 commented on src/UI/templates/default/Glyph/tpl.glyph.standard.html
> +<a class="glyph<!-- BEGIN highlighted --> highlighted<!-- END highlighted --><!-- BEGIN disabled --> disabled<!-- END disabled -->"<!-- BEGIN with_action --> href="{ACTION}"<!-- END with_action --> a
I think there is nothing like a disabled a-tag. We should use a span or omit the container tag completely instead imo.

2018-08-02 13:24 UTC, alex40724 commented on src/UI/templates/default/Glyph/tpl.glyph.standard.html
> +<a class="glyph<!-- BEGIN highlighted --> highlighted<!-- END highlighted --><!-- BEGIN disabled --> disabled<!-- END disabled -->"<!-- BEGIN with_action --> href="{ACTION}"<!-- END with_action --> a
Ok, I saw the discussion in the other PR. We might keep it this way.

2018-08-13 08:00 UTC, Amstutz commented
Hi @tfamula, I think this is ready to be merged, right? Please run the tests one final time and resolve the 3 conflicts and then we merge this. Thanks a lot for this contribution!

2018-08-16 08:52 UTC, tfamula commented
Ready for merging, @alex40724 will do this and resolve the conflicts.

2018-08-23 15:37 UTC, Amstutz approved these changes

2018-08-23 15:50 UTC, merged