[WIP] UI Framework: Introduced lightbox text page
ILIAS-eLearning/ILIAS pull request #1132
Opened 2018-08-09 11:52 UTC by mjansenDatabay

For the implementation of [User: Criteria-based »User Agreement« documents
](https://www.ilias.de/docu/goto_docu_wiki_wpage_5225_1357.html) I would like to introduce a new **page type** for the Lightbox modal UI component.

Currently the contents of a *Terms of Service* document is presented with a `\ilModalGUI` legacy UI class.

![Current Implementation](https://mjansenDatabay.github.io//ILIAS/UI/Modal/Lightbox/TextPage/current_impl_with_ilmodalgui.png)

This approach is used in *Administration » User Management » User Profile* (1 usage) and *Terms of Service* (2 usages)

While revising the ILIAS UI of the global *Terms of Service* administration, I would like (and should according to the *JourFixe* decision as described on the wiki page linked above) to replace the legacy modal implementation with a lightbox modal. At the time being there is only a `LightboxImagePage`component. For the purpose described above, a new page type for a simple text content should be introduced.

Rules:
![Description](https://mjansenDatabay.github.io//ILIAS/UI/Modal/Lightbox/TextPage/lightbox_textpage_description.png)

Code Example:
![Code Example](https://mjansenDatabay.github.io//ILIAS/UI/Modal/Lightbox/TextPage/lightbox_textpage_example.png)

UI:
![UI Example](https://mjansenDatabay.github.io//ILIAS/UI/Modal/Lightbox/TextPage/lightbox_textpage_example_ui.png)

2018-08-09 12:22 UTC, mjansenDatabay commented
What can be discussed is a split of `LightboxPage` into `LightboxPage` and `LightboxDescriptivePage` as implemented here: https://github.com/mjansenDatabay/ILIAS/commit/ea3616d7753273552f038107349c52189d0eec9f

2018-08-13 08:20 UTC, Amstutz requested changes
@mjansenDatabay Thanks a lot for this contribution. I think this can be a useful asset for the future. 

To be accepted by the JF please:
-> Slightly change the purpose description of the lightobx (see my comment).

To be merged:
- Note that currently only single lightbox text pages seem to work. However, for lightboxes: 
> Multiple media items inside a Lightbox modal MUST be presented in carousel like manner allowing to flickr through items.

I would require this also for this newly introduce text page. The CSS/Less needs to be slightly addapted, so please fix and also present an example showing multiple text pages, or even better, text and images pages.

2018-08-13 08:20 UTC, Amstutz commented on src/UI/Component/Modal/Factory.php
> +	 *     A Lightbox text page represents an document like content/text inside a Lightbox modal.
This contradicts the lightbox description: 
> The Lightbox modal displays media data such as images or videos.

Not meaning, we just did not think at this possibility at the time. However, if we introduce this, we should adapt the lightboxes description slightly to:

"The Lightbox Modal displays media data such as images or videos. It may also display text that has a purely descriptive nature and does not offer interaction."

2018-08-13 08:20 UTC, Amstutz commented on src/UI/Component/Modal/Factory.php
> +	 *       A Lighbox text page MUST have a text content and a short title.
Add here, other than other lightbox pages, the lightbox text page MUST not use a description.

2018-08-13 08:21 UTC, matthiaskunkel commented on src/UI/Component/Modal/Factory.php
> +	 *     A Lightbox text page represents an document like content/text inside a Lightbox modal.
… a document …

2018-08-13 08:21 UTC, Amstutz commented on src/UI/Component/Modal/Factory.php
> +	 *     A Lightbox text page represents an document like content/text inside a Lightbox modal.
Not that also rule 3 of the lightbox needs a slight adaption:
> Multiple media items inside a Lightbox modal MUST be presented in carousel like manner allowing to flickr through items.

To 
"Multiple items inside a Lightbox modal MUST be presented in carousel like manner allowing to flickr through items."

2018-08-13 08:21 UTC, matthiaskunkel commented on src/UI/Component/Modal/Factory.php
> +	 *     The page consists of the text and a title
The page consists of text and a title

2018-08-13 08:22 UTC, matthiaskunkel commented on src/UI/Component/Modal/Factory.php
> +	 *       A Lighbox text page MUST have a text content and a short title.
… have text content and a short …

2018-08-13 11:34 UTC, Amstutz approved these changes

2018-08-13 12:15 UTC, matthiaskunkel commented
Jour Fixe, 13 AUG 2018 : We highly appreciate this PR and accept it for 5.4. We prefer to split off LightboxPage into LightboxPage and LightboxDescriptivePage.

2018-08-13 14:12 UTC, mjansenDatabay commented
@Amstutz I hope that all the issues you mentioned have been addressed with my latest commits. I had to change the border color of the `.carousel-indicators` because the background color of the `LighboxTextPage` is white.

2018-08-20 06:58 UTC, mjansenDatabay commented
@Amstutz Can I/you merge this, or are there any objections left?

2018-08-20 07:47 UTC, Amstutz commented
Looks good, thx a lot.

2018-08-20 07:48 UTC, merged