UI, Radio Input
ILIAS-eLearning/ILIAS pull request #1133
Opened 2018-08-09 12:02 UTC by nhaagen

This implements a radio-field with sub-forms dependant on options.

![bildschirmfoto_2018-08-09_14-01-48](https://user-images.githubusercontent.com/3328364/43897578-d04b1684-9bdc-11e8-8eb2-888b343360ce.png)

Rules are here:

2018-08-14 16:15 UTC, Amstutz requested changes
Thanks a lot for this PR! I have some proposal for rules. Consider them, if you do not think them of any value, I can live with it. Some minor comments about capitalization.

Comment about the implementation: On Safari the checkboxes look really funny (large and ugly). However, you did not add any less, do you know why this is?

2018-08-14 16:15 UTC, Amstutz commented on src/UI/Component/Input/Field/Factory.php
> +	 *     A radio-input is used to depict a choice of options excluding each other.
Radio Input.

2018-08-14 16:15 UTC, Amstutz commented on src/UI/Component/Input/Field/Factory.php
> +	 *     The radio is considered as one field with a label and a number of
capitalize the name of the described component. Here Radio or Radio Input.

2018-08-14 16:15 UTC, Amstutz commented on src/UI/Component/Input/Field/Factory.php
> +	 *     as sub form).
Again capitalize Radio, Dependant Section and even Sub Form.

2018-08-14 16:15 UTC, Amstutz commented on src/UI/Component/Input/Field/Factory.php
> +	 *     Checkbox field: Use a checkbox field for a binary yes/no choice.
Checkbox Field. Checkbox.

2018-08-14 16:15 UTC, Amstutz commented on src/UI/Component/Input/Field/Factory.php
> +	 *       or needs further cconfiguration, stick to radios.
cconfiguration.

2018-08-14 16:15 UTC, Amstutz commented on src/UI/Component/Input/Field/Factory.php
> +	 *
I have some more:

usage:

- A Radio Input SHOULD contain 3 to 5 options. If there are more, the Select Input might be the better option.
- They MAY also be used to select between two options where one is not automatically the inverse of the other (such as “Order by Date” and “Order by Name”).

wording:
1: Good, but give an example to make the point really clear here.
- Each option in a Radio Input MUST be labeled. 
 - This label SHOULD not consist of more than 5 words. 
- The label of the options SHOULD not simply repeat the label of the Radio. A meaningful labeling SHOULD be chosen instead.

Ordering:
- The presumably most relevant option SHOULD be the first option.

2018-08-14 16:15 UTC, Amstutz commented on src/UI/Implementation/Component/Input/Field/Radio.php
> +		return true;
Hmm, can we no do better here? Not sure however, give it a thougth if it's possible to restrict that somewhat more.

2018-08-15 07:16 UTC, nhaagen commented
@Amstutz Thanks for looking through this and your suggestions. I'll merge the renderer and straighten out capitals ;)
The large input can also be found in checkboxes - this is a side effect of CSS class "form-control" with height:25px; I'll fix that, too.

2018-08-15 11:42 UTC, nhaagen commented
This is much better now, in both description and looks...

2018-08-27 12:59 UTC, matthiaskunkel commented
Jour Fixe, 27 AUG 2018 : We highly appreciate this PR and accept it for 5.4.

2018-09-05 12:04 UTC, merged