UI - MultiSelect Input
ILIAS-eLearning/ILIAS pull request #1136
Opened 2018-08-10 09:50 UTC by nhaagen

Use a list of labeled checkboxes for the user to take picks from a finite list.

![bildschirmfoto_2018-08-10_11-46-13](https://user-images.githubusercontent.com/3328364/43951498-9c057ea2-9c93-11e8-9bd7-fc0c32cd0b9b.png)

More in the rules:

2018-08-14 16:32 UTC, Amstutz requested changes
For JF: Some minor details in the description. 

For the Merge: Please add the tests.

2018-08-14 16:32 UTC, Amstutz commented on src/UI/Component/Input/Field/Factory.php
> +	public function multiselect($label, array $options, $byline = null);
Make two words of it by using lower camelCase: multSelect

2018-08-14 16:32 UTC, Amstutz commented on src/UI/Component/Input/Field/Factory.php
> +	 *     A multi-select is used to allow users to pick several options from a list.
Multi Select (there are many further down, I will not mark them all to not clutter the description too much.

2018-08-14 16:32 UTC, Amstutz commented on src/UI/Component/Input/Field/Factory.php
> +	 *     Select field: Use a select input when the user's choice is limited to one option.
or: "... the options are mutually exclusive".

2018-08-14 16:32 UTC, Amstutz commented on src/UI/Component/Input/Field/Factory.php
> +	 *
wording:
- Also add here the only postive... rule you proposed for the Radio Input

2018-08-15 14:19 UTC, Amstutz commented on src/UI/Implementation/Component/Input/Field/Renderer.php
> +		global $DIC;
Why/how is this used here?

2018-08-27 13:08 UTC, matthiaskunkel commented
Jour Fixe, 27 AUG 2018 : We highly appreciate this PR and accept it for 5.4.

2018-09-05 12:07 UTC, Amstutz commented
@nhaagen all lights are green for merge. Resolve the conflicts run the tests one final time and then you may click the merge button to avoid new conflicts.

2018-09-05 12:07 UTC, Amstutz approved these changes

2018-09-05 12:36 UTC, nhaagen commented
Thanks, @Amstutz. 
Tests are failing horribly, though.
Manually checking in examples, everything is fine...

2018-09-06 09:47 UTC, klees commented
Hi @nhaagen, @fneumann merged the PR fixing the test failures in the meantime. Regards!

2018-09-06 11:30 UTC, nhaagen commented
Hi @klees, @fneumann , this looks much better, now. Would you please hit the button? Thanks.

2018-09-10 07:50 UTC, merged