UI, Input Date
ILIAS-eLearning/ILIAS pull request #1142
Opened 2018-08-13 14:36 UTC by nhaagen

Date uses bootstrap datetimepicker to select a date or time (or both).
![bildschirmfoto_2018-08-13_16-33-45](https://user-images.githubusercontent.com/3328364/44038408-02f33a5c-9f17-11e8-88e1-bcbea1361b89.png)

2018-08-23 10:54 UTC, klees requested changes
LGTM in general, THX!!!

Please have a look at your `Transformation`s, they ought to throw, not silently forward empty strings if input is not what is expected.

2018-08-23 10:54 UTC, klees commented on src/Transformation/Transformations/Date.php
> +		return '';
This is bad. The transformation promises to return a \DateTime, this ain't one. Please just throw an `\InvalidArgumentException` if the input to `transform` is not as expected.

2018-08-23 10:54 UTC, klees commented on src/UI/Component/Input/Field/Duration.php
> +	 */
What is a valid format here? I certainly can't just pass _any_ string, right? Is it anything related to phps `\DateTime`? Just say so...

2018-08-23 10:54 UTC, klees commented on src/UI/Component/Input/Field/Duration.php
> +	 * Limit accepted values to dates past given $date.
_Past given date_ means given date is excluded?

2018-08-23 10:54 UTC, klees commented on src/UI/Component/Input/Field/Duration.php
> +	 * Return the lowest date the input accepts.
This to me implies _including_ the given date.

2018-08-23 10:54 UTC, klees commented on src/UI/Component/Input/Field/Duration.php
> +	 * Limit accepted values to dates before given $date.
I think we have the same including/excluding problem here.

2018-08-23 10:54 UTC, klees commented on src/UI/Implementation/Component/Input/Field/Date.php
> +		$this->checkStringArg('format', $format); //2do: check on date-format
Do it!

2018-08-23 10:54 UTC, klees commented on src/UI/Implementation/Component/Input/Field/Date.php
> +		return is_string($value);
The client side delivers values as strings according to the format, right? This should be reflected here.

2018-08-23 10:54 UTC, klees commented on src/UI/Implementation/Component/Input/Field/Duration.php
> +			return '';
This is odd. So the field either contains a `\DateDuration` or an empty string? Please throw here if input is not what you expected.

2018-08-23 10:54 UTC, klees commented on src/UI/Implementation/Component/Input/Field/Duration.php
> +			"start must be earlier than end"
Please add me a marker TODO: i18n here to i18n this.

2018-08-23 10:54 UTC, klees commented on src/UI/Implementation/Component/Input/Field/Duration.php
> +				return $v['start'] < $v['end'];
These are `\DateTime`s here, right? Does the `<`-Operator treat them properly?

2018-08-23 16:45 UTC, Amstutz requested changes
The examples look great. Thx a lot for this @nhaagen. There is one major point: I believe the name "date" to be misleading, should be "DateTime" since it is possible to enter both (also, closer to the PHP naming of the according classes for the data types). The rest is minor stuff. We can discuss all of this on monday.

One thing I believe to be also slighty interface related is the behaviour off the Duration Input if end is set smaller than start. I would wish this to be impossible. Currently it is (in the example). If we can not prevent this for some reason, I think we should a least correct autamitcally (e.g. by setting end to start). We should discuss this point also in the JF. Note in the examples of the library, this is impossible to enter wrongly: https://eonasdan.github.io/bootstrap-datetimepicker/#linked-pickers

2018-08-23 16:45 UTC, Amstutz commented on src/UI/Component/Input/Field/Duration.php
> +	 */
maybe even add some link, like: http://php.net/manual/de/datetime.format.php or http://php.net/manual/de/class.datetime.php

2018-08-23 16:45 UTC, Amstutz commented on src/UI/Component/Input/Field/Date.php
> +interface Date extends Input {
Is it not DateTime? To me Date only excludes time (which is part of the conrol).

2018-08-23 16:45 UTC, Amstutz commented on src/UI/Component/Input/Field/Date.php
> +	public function withFormat(string $format) : Date;
This method is of crucial importance, it defines the kind of data that is accepted here (time, dates, both). This should be made more explicit here. Add some more explanation. Maybe even some little dummy example.

2018-08-23 16:45 UTC, Amstutz commented on src/UI/Component/Input/Field/Factory.php
> +	 *     A Date Input is used to enter dates.
and/or time.

2018-08-23 16:45 UTC, Amstutz commented on src/UI/Component/Input/Field/Factory.php
> +	 *     Dependant on the format, the inputs will accept dates, times or datetimes.
There is something missing like:

The start point must take place before the endpoint. Invalid input will be corrected automatically.

2018-08-24 06:58 UTC, klees commented
Removed JF label to clean up issues first.

2018-10-28 17:23 UTC, Amstutz commented
Is this in a deadlock state? Anything needed from my part?

2018-10-29 07:11 UTC, klees commented
No deadlock, just no time to clean up issues till now.

2019-01-09 13:38 UTC, nhaagen commented
Hi @Amstutz ,
it certainly took a while, but now - from my perspective - this is good to go.
Would you have a look?

2019-01-11 13:24 UTC, Amstutz commented
Hi @nhaagen 

Thanks a lot for the revision. As far as I am concerned, all my remarks on the interface are taken care of. To me, this is JF ready, I'll attached the according label.

Note, that I will give a final review on the implementation as soon as the interface is accepted by the JF.

Thx a lot.
@Amstutz

2019-01-18 16:00 UTC, klees commented
Hi everybody, I'm still no happy with the current state of this, so I removed the JF label. We will get back to this soon try to present this on JF 2019-02-04.

2019-02-28 13:35 UTC, Amstutz commented
Any Update? Note that this is the oldest PR by now ;-)

2019-04-16 08:41 UTC, Amstutz commented
There has been no update for almost three month on this, to keep the list of PR's clean, Ill close this down for the moment. You may reopen this or make a new PR as soon as there is something new to discuss.

2019-04-16 08:41 UTC, closed without merging