fixed bug visible and read permissions in administration - external s…
ILIAS-eLearning/ILIAS pull request #1180
Opened 2018-09-11 14:35 UTC by chfsx

…ervices and module developers

This replaces PR #862 and tackles https://www.ilias.de/mantis/view.php?id=21941

2018-09-11 16:58 UTC, mjansenDatabay requested changes
LGTM in general, only a few remarks/questions.

Thx a lot for your work!!!

2018-09-11 16:58 UTC, mjansenDatabay commented on Modules/Chatroom/classes/admingui/class.ilChatroomAdminSmileyGUI.php
> +		if ($DIC->rbac()->system()->checkAccess("write", $this->gui->ref_id)) {
You should be able to access  `$this->rbacsystem` from parent class.

2018-09-11 16:58 UTC, mjansenDatabay commented on Modules/Chatroom/classes/class.ilChatroom.php
> +				$hasAccess = $DIC->rbac()->system()->checkAccess($permission, $refId);
I'm not sure about this. The `$usrId` is passed as an argument, why changing the method call here?

2018-09-11 16:58 UTC, mjansenDatabay commented on Modules/Chatroom/classes/class.ilChatroom.php
> +				$hasAccess = $DIC->rbac()->system()->checkAccess($permission, $refId);
I'm not sure about this. The `$usrId` is passed as an argument, why changing the method call here?

The comment should be removed.

2018-09-11 16:58 UTC, mjansenDatabay commented on Services/Mail/classes/class.ilMailTemplateTableGUI.php
> +		if($this->dic->rbac()->system()->checkAccess('write', $_GET['ref_id'])) {
We should try to avoid accessing `$_GET` and use the HttpRequest from `$DIC` instead. I also suggest an (int) cast here.

2018-09-11 16:58 UTC, mjansenDatabay commented on Services/Saml/classes/class.ilSamlSettingsGUI.php
> +		$this->rbacsystem    = $DIC->rbac();
The member variable should be named `rbac` if you don't assign an instance of `\ilRbacSystem`.

2018-09-11 16:58 UTC, mjansenDatabay commented on Services/Saml/classes/class.ilSamlIdpTableGUI.php
> +	public function __construct($a_parent_obj, $a_parent_cmd = "", $a_template_context = "")
Why changing this? Is there an issue with the `$mayEdit` parameter?

2018-09-12 12:37 UTC, chfsx commented
Thanks @mjansenDatabay I updated the PR after your comments, there was some merging/cherry-picking related stuff

2018-12-18 14:26 UTC, mjansenDatabay commented
@alex40724 @shecken @mbecker-databay @smeyer-ilias : Can you please review this PR?

When done: @chfsx Can you please fix the conflicts?

2018-12-19 07:53 UTC, alex40724 commented
@chfsx Thanks a lot for your work. For me it is fine to merge this PR to the trunk anytime. I would test things in the trunk afterwards if this is ok.

2018-12-19 07:53 UTC, alex40724 approved these changes

2019-01-22 13:13 UTC, alex40724 commented
@nmatuschek @mbecker-databay @smeyer-ilias @shecken 
Could you please give feedback on this issue? Thanks.

2019-01-22 16:11 UTC, smeyer-ilias approved these changes
Sorry for the late response and thanks a lot for your work. 
Looks good to me and can merged anytime.

2019-02-26 13:57 UTC, mbecker-databay approved these changes
Fine for me, thank you!

2019-02-26 15:20 UTC, shecken approved these changes

2019-04-09 12:46 UTC, mjansenDatabay commented
Should be okay for @nmatuschek .

2019-05-08 12:16 UTC, Amstutz commented
@chfsx This PR popped-up in our TB meeting today since open for a while. Note, we are catching up, september is not that old ;-). 

Nevertheless, what is the state of this PR? Can this be merged? Since to be accepted from all reviewers, but seems to have one failing test.

[Edit]: Sry: Almost all accepted, there are some other open suggestions as well.

2019-05-09 08:17 UTC, chfsx commented
@mjansenDatabay I think your re-review is missing, I tackled all the points you mentioned.

2019-07-01 10:41 UTC, mjansenDatabay approved these changes

2019-07-01 10:41 UTC, mjansenDatabay commented
Thx @chfsx LGTM!

2019-07-17 06:48 UTC, swiniker commented
@chfsx: This PR came up in our TB-Meeting as one of the older ones. I think now all reviews are there and we would kindly ask you to take the next step at your earliest convenience. Thank you very much!

2019-07-17 08:57 UTC, chfsx commented
Thanks! I squashed the changes merged them manually

2019-07-17 08:57 UTC, closed without merging