implement ilKioskModeService
ILIAS-eLearning/ILIAS pull request #1191
Opened 2018-09-18 12:58 UTC by nhaagen

2018-10-04 11:07 UTC, klees requested changes
LGTM in general, but some nitpicking.

Please be so kind and have a quick look into the README.md as well, adjust the TOC and spend a minute or two thinking about if some information is missing in there. Thx!

2018-10-04 11:07 UTC, klees commented on Services/Init/classes/class.ilInitialisation.php
> +				$c->access(),
Please use array-access here. The methods on the `DIC` will go away at some point.

2018-10-04 11:07 UTC, klees commented on Services/KioskMode/classes/class.ilKioskModeService.php
> +	protected $obj_definition;
Please add typehints here.

2018-10-04 11:07 UTC, klees commented on Services/KioskMode/classes/class.ilKioskModeService.php
> +		illanguage $language,
`illanguage` -> `ilLanguage`

2018-10-04 11:07 UTC, klees commented on Services/KioskMode/classes/class.ilKioskModeService.php
> +		$full_class = "il".$class."KioskModeView";
Is it correct that `$class` *does not* contain an `il`-Prefix here?

2018-10-04 11:07 UTC, klees commented on Services/KioskMode/classes/class.ilKioskModeService.php
> +		return file_exists($class_path);
I think you could just check if `class_exists` and don't need the location. The location should already be resolved via the autoloader anyway.

2018-10-04 11:08 UTC, klees commented
Hi @smeyer-ilias, we'll make a rather standard addition to `ilInitialisation`here. Is that fine  with you?

2018-10-08 13:51 UTC, klees commented on Services/KioskMode/classes/class.ilKioskModeService.php
> +		$location = $this->obj_definition->getLocation($object_type);
We don't need `$location` anymore.

2018-10-12 10:46 UTC, klees commented
@smeyer-ilias Any objections to the addition to `ilInitialisation`?

2018-10-25 12:44 UTC, klees commented
@smeyer-ilias Could you have a quick look into this? There's nothing really interesting, I promise.

2018-10-25 13:08 UTC, smeyer-ilias commented
@klees : Yes, LGTM. You can merge directly.

2018-10-25 13:09 UTC, merged