[Certificates] Add check for certificate date based on creation date of the user
ILIAS-eLearning/ILIAS pull request #1259
Opened 2018-10-26 14:11 UTC by legionth

Adds a check for the certificate migration. New users (after installing the persisting certificate feature) won't see the migration option.

2018-10-26 14:13 UTC, legionth commented
Ping @mjansenDatabay

2018-10-26 14:42 UTC, mjansenDatabay requested changes

2018-10-26 14:42 UTC, mjansenDatabay commented on Services/Certificate/classes/Migration/class.ilCertificateMigrationValidator.php
> +	public function isMigrationAvailable(ilObjUser $user)
@legionth RTD is missing here

2018-10-26 14:42 UTC, mjansenDatabay commented on Services/Certificate/classes/Migration/class.ilCertificateMigrationValidator.php
> +			$introducedTimestamp = $this->certificateSettings->get('persisting_cers_introduced_ts');
@legionth Maybe you should use a meaningful default here as 2nd parameter

2018-10-26 14:43 UTC, mjansenDatabay commented on Services/Certificate/classes/Migration/class.ilCertificateMigrationValidator.php
> +		$userCreationDate = $user->getCreateDate();
@legionth / @qdittrich : Maybe other *preconditions* should be added here as well

2018-10-29 13:47 UTC, mjansenDatabay approved these changes

2018-10-29 13:50 UTC, legionth commented
Resolved Merge Conflicts :shipit: .

2018-10-29 14:01 UTC, mjansenDatabay commented
@legionth :shipit: not possible due to conflict

2018-10-29 14:05 UTC, legionth commented
Fast now @mjansenDatabay :sweat_smile:

2018-10-29 14:08 UTC, merged