UI - Panel - Data
ILIAS-eLearning/ILIAS pull request #1397
Opened 2019-01-06 17:29 UTC by bheyser

This PR introduces a new UI component to be used when any kind of information is to be shown that follows a label/value structure. This UI component can avoid the use of tables to show just a single data row. Also the abuse of a form to present non editable data will be past having this new UI component.

`function base() {
	
	global $DIC;
	
	$factory = $DIC->ui()->factory();
	$renderer = $DIC->ui()->renderer();
	
	$dataPanel = $factory->panel()->data('Any Label/Value Statistic');
	
	$dataPanel->withAdditionalEntry(
		$factory->legacy('First Label'),
		$factory->legacy('Good Value')
	);
	
	$dataPanel->withAdditionalEntry(
		$factory->legacy('Second Label'),
		$factory->legacy('More Well Value')
	);
	
	$dataPanel->withAdditionalEntry(
		$factory->legacy('A Last Label'),
		$factory->legacy('Any Last Value')
	);
	
	$html = $renderer->render($dataPanel);
	
	return $html;
}`

![image](https://user-images.githubusercontent.com/2587908/50739436-a5971800-11e0-11e9-8f67-ec862e5da6d7.png)

The new UI component is located at `UI > Panel > Data` within the UI component taxonomy.

2019-01-06 17:31 UTC, bheyser commented
The link to the rules for purpose and usage:
https://github.com/ILIAS-eLearning/ILIAS/pull/1397/files#diff-e6c01f5f06c4826ee5016bd001f1725a

2019-01-07 09:13 UTC, Amstutz requested changes
Hi @bheyser 

Congrats for your first UI-Component (it is the first, right)! Thanks a lot This is already looking quite good imo, a few things bellow. 

First of all, concerning your question regarding the context. If you can define a context, it would be nice to state it here. Where are those things currently used in ILIAS. You are right in stating, that many UI-Components lack such a context at their current state. However, some do have one (e.g. Scale Bars). If you believe you do not need one, you can tell the tests so by adapting ilias/tests/UI/Component/Panel/PanelFactoryTest.php. 

Please consider the following suggestions. You do not need to follow those, but but please indicate shortly why you prefer to do otherwise:
- [ ] Use the Descriptive Listing. The descriptive Listing already gives you the complete structure for a listing as you need it, including rendering. No need  to reinvent the wheel here. Just use some CSS to make the list look a little different in this context. If you want to use a custom rendering in this context, you can also do so an just use the data structure of the descriptive list. However, maybe I am missing something here.

Please implement the following changes:
- [ ] Extend from Panel. All panels should extend from the Panel component. This makes it easy to tell e.g. some content area to accept panels, without telling which exact one it must be.
- [ ] Add Unit Tests. You can wait with this until a JF decision has been made. Before merging, we need the Unit Tests.

As soon as we agree on the interface, we can put this to the JF.

kindly,
@amstutz

2019-01-07 09:25 UTC, klees commented
Hi @bheyser, I'm working on my review but won't be able to complete it until the JF today. I think you'll get my feedback tomorrow. Regards!

2019-01-07 12:46 UTC, matthiaskunkel commented
Jour Fixe, 07 JAN 2019 : Thanks to Björn for his first KS PR. But we need some more time to review this suggestion and schedule it for the next JF at 21 JAN 2019. As Timon already suggested, please consider also the use of the Descriptive List.

2019-01-09 10:43 UTC, klees requested changes
Hi @bheyser!

Thanks a lot for contributing to the UI-framework of ILIAS. I'm especially happy to see you first contribution of a component here and hope to see more in the future!

Some of my stuff overlaps with @Amstutz review and could be solved by his suggestions IMO. I still kept my points, since they seem to add a little more context.

Please answer the following questions:
- [ ] Is there a reason that your new panel does not implement `ILIAS\UI\Implementation\Component\Panel\Panel`? If not, do so, as @Amstutz suggests.
- [ ] How could `getContent` return a `Component` or a list thereof if I add key/value pairs of components via `withAdditionalEntry`? What are these components? This problem will vanish if you use the `Descriptive Listing`, as @Amstutz suggests.
- [ ] What is supposed to be used as labels, what as values? Do you intend to use plain-text only or do you want to use more complex `Components` (e.g. images) as well in the one or the other place? This problem will vanish with the `Descriptive Listing` as well.
- [ ] Do we really need both, `getContent` and `getEntries`? Also: `Descriptive Listing`...

Please consider the following suggestions. You do not need to follow those, but but please indicate shortly why you prefer to do otherwise:
- [ ] The typehinting on `withAdditionalEntry` seems to be way to broad. We surely do not want *any* `Component` as label or value. Replace it by something more specific, if possible. Or use the `Descriptive Listing` as @Amstutz suggests.
- [ ] Already allow the constructor to take key/value pairs. We try to make the `Component`s in the UI-Framework correct by construction, where possible, to make it hard for consumers to construct components that look odd or do not work properly. A panel with a title only will certainly
look odd and when using the `Descriptive Listing` it will be an easy change to add an according parameter to the constructor.

Please implement the following changes:
- [ ] Your PR contains changes that seem to be unrelated to the UI element. Please remove them.
- [ ] Please use PHP7-typehints where possible.
- [ ] Please remove the superfluous `data` prefix on the parameters to the `withAdditionalEntry`-method. We know it's data, `$label` and `$value` will suffice and be more brief.
- [ ] Please explain a little clearer what `getEntries` is supposed to return. I can guess that it somehow returns a nested array, but the notation you use here seems to be uncommon. This should also be solved by using the `Descriptive Listing`.

So after all, most of my comments boil down to "use `Descriptive Listing`" =)

As a more general comment, and food for thought, we certainly won't be able to solve here, I wonder whether we want to keep these key-value lists in the long term.

I see several problems with them:
* As raised by @atoedt in the discussion about the statistics in the Test, plain numbers or values need interpretation and some numbers are hard to interpret for the uniniated. This somehow also appeared in the discussion of the info-tab, e.g. when we talked about the question why a user would need to know the owner of an object.
* These key-value pairs just aren't pretty, you do not really want to look at them. It would be nicer to have graphs, or images, red-yellow-green-indicators, or...
* We tend to use them as an excuse to offer actions to the users. Instead of having an action that says: "Show me the questions that I should edit" we show some value and hope that this indicates to the user to do just that. Instead of having an action that says "Open a chat with the person that is ultimately reponsible for this object" we just display the owner. This in general tends to degrade our application to a mere display for some data we have instead of showing ways to the user how to interact with the data in meaningful ways.

I see that we currently need a panel like this, but I also think we should think about how to display our data in more meaningful ways and how to offer meaningful interactions with the data.

I you need support with the specifics of this PR, feel free to contact @Amstutz and me for a skype-call.

Best regards!
@klees

2019-01-09 10:43 UTC, klees commented on src/UI/Component/Panel/Data.php
> +	public function getTitle();
```suggestion
	public function getTitle() : string;
```

2019-01-20 15:59 UTC, Amstutz commented
@bheyser do you know when you find time to work in our suggestions? For the moment, I think there is not much new to discuss here and I remove the JF label for the moment, I hope this is i.O., reattach if you believe it to be otherwise.

2019-04-16 08:51 UTC, Amstutz commented
There has been no update for almost three month on this, to keep the list of PR's clean, Ill close this down for the moment. You may reopen this or make a new PR as soon as there is something new to discuss.

2019-04-16 08:51 UTC, closed without merging