Return configured http_path if it is set in ilUtil::_getHttpPath
ILIAS-eLearning/ILIAS pull request #1667
Opened 2019-03-14 11:16 UTC by OctopusCloud

Because the constant ILIAS_HTTP_PATH is not set correctly i fixed the return value of the ilUtil::_getHttpPath Method.

The ilUtil::_getHttpPath will now return the path confiured in the ilias.ini.php. (If its set and this schould be mandatory)

ILIAS_HTTP_PATH is not correctly set to the dir containing the standard ilias php files (e.g. index.php goto.php ilias.php). Nevertheless, the source code assumes that ILIAS_HTTP_PATH is always pointing to the docroot.

I think this pull request dont comply with the development processes. Feel free to close or convert this pull request.

2019-03-14 15:19 UTC, klees commented
Hi @OctopusCloud,

thanks a lot for contributing and welcome to ILIAS. It would help a lot if you had a ticket in [our tracker](https://mantis.ilias.de) that is fixed by this PR and link it here. [These are our general guidelines for contributions](https://github.com/ILIAS-eLearning/ILIAS/blob/trunk/docs/documentation/contributing.md), btw.

Best regards!

2019-03-14 15:19 UTC, klees commented
Hi @chfsx and @alex40724,

you are listed as implicit maintainers for Service/Utilities, thus I assigned you.

Regards!

2019-03-14 15:21 UTC, amichelsdatabay commented
@maxbecker Do you have some ticketnumbers ready?

2019-03-14 15:29 UTC, mbecker-databay commented
@amichelsdatabay Not to my (admittedly very limited) knowledge. I understand we found the behavior today and you came forward with that fix without paper-trail.

2019-03-14 15:57 UTC, amichelsdatabay commented
[Working software over comprehensive documentation](https://agilemanifesto.org/iso/en/manifesto.html)

2019-03-14 16:49 UTC, smeyer-ilias requested changes
@OctopusCloud : Thanks for your contribution, but this change overwrites the dynamically determined "HTTP_PATH" for all HTTP request with the value in the ini-File. 

What was the reason for this change? Please can you add a mantis ticket and provide steps to reproduce.

2019-03-14 16:54 UTC, alex40724 commented
ILIAS_HTTP_PATH is used in over 200 places in the code. If there is any problem with this constant we need to fix the definition of the constant itself, imo.

2019-03-14 17:07 UTC, amichelsdatabay commented
Yes the constant should be fixed.
But i didnt want to mage a change to ilInitialisation. The constant is set wrong there.

2019-03-14 18:01 UTC, mjansenDatabay commented
The question is: What exactly is the **meaning** of the **name** of constant `ILIAS_HTTP_PATH` (and of course `ilUtil::_getHttpPath()` and `ilInitialisation::buildHTTPPath()`)?

1. The absolute HTTP path to the folder of the the currently executing PHP script
2. The absolute HTTP path to the root folder of ILIAS

Currently it is 1., because the generation relies on `$_SERVER['REQUEST_URI']`.

@OctopusCloud / @amichelsdatabay I'm sure you are expecting 2., because the issue in your scenario is the value of this constant when your executing PHP script is located somewhere in the `Customizing` folder.

 Maybe the name of the constant and methods mentioned above is not clear enough.

2019-03-14 18:09 UTC, amichelsdatabay commented
I'm not expecting 2. because of my scenario. @alex40724 pointed out that this constant is used for years to point to the ilias docroot. The occurrences of `ILIAS_HTTP_PATH ` are a lot of hardcoded links. If this constant would point somewhere else than the docroot there would be 200 bugs in Ilias.

2019-03-15 08:39 UTC, alex40724 commented
Since you got some "scenario" it would be good to have a bug report on this describing the scenario. I put this on the JourFixe agenda, but if there is no bug filed, I expect this will not make it to the code in any way.

@klees I do not consider this being ab "improvement". If something constant is **not set correctly**, this should get the "bugfix" lable imo.

2019-03-15 08:56 UTC, klees commented
@alex40724 I just tagged this as "improvement" because there currently is no ticket in mantis.

2019-03-15 08:58 UTC, alex40724 commented
Ok, I understand.

2019-03-15 09:24 UTC, mjansenDatabay commented
@OctopusCloud / @amichelsdatabay : I don't find any statement of @alex40724 regarding `document root`

IMO in an ideal world we would have some kind of 'HttpService' depending on `./src/HTTP` where developers could request:
* The HTTP path to the document root (directory pointing to the main document tree visible from the web)
* The HTTP path to the ILIAS root directory (may equal the document root)
* The HTTP path to the executing script (may equal the ILIAS root directory is most cases)
* ...

But indeed `ILIAS_HTTP_PATH` is a very dynamic constant (:smile:) we should replace with a call to such a `HttpService` in the future.

at all: What do you think?

2019-03-15 09:39 UTC, klees commented
> The HTTP path to the ILIAS root directory (may equal the document root)

The ILIAS-root would better have no HTTP-path at all at some point imo. Ideally the doc-root would just contain a very minimal set of (~ 1) entry-points that use other files from elsewhere (= outside doc-root). People should not access unit tests from the internet, e.g..

2019-03-15 09:42 UTC, mjansenDatabay commented
@klees This should be part of the ideal world, you are right :smiley:

2019-03-25 13:47 UTC, matthiaskunkel commented
Jour Fixe, 25 MAR 2019 : We reject and close this pull request for two reasons: (1) the procedure for pull requests has been ignored. Either a PR is labeled as a bug. Then a related bug report should be mentioned. Or the PR is considered as an improvement. In this case a related feature wiki page should be mentioned that describes the problem and the suggested solution. (2) As far as we have understood this PR (a clear description of the problem is missing) it will have a deep impact into existing features and break several of them that are currently fundamental for ILIAS, e.g. sub domain support, public section feature depending on sub domains, ... If you need a better support for your plugins, please create a feature wiki entry and respect the procedures that we have agreed upon in this project.

2019-03-25 13:47 UTC, closed without merging