UI Tree
ILIAS-eLearning/ILIAS pull request #1685
Opened 2019-03-19 13:32 UTC by nhaagen

Dear all,
this is my version of a tree. It is based on ul-lists, includes async-loading and has a quite small JS-footprint. Construction can be done with any kind of data by using an anon-class for recursion.
In the second example, I load the repository asynchronously and add type-based icons.

The only node I implemented here is the "Simple Node" with a label and optional icon - this is meant to be extended by e.g. an "Item Node" or an "Input Node" for the object picker.

Here are the (admittedly short) rules.

![Bildschirmfoto_2019-03-19_14-24-01](https://user-images.githubusercontent.com/3328364/54609266-e5854180-4a52-11e9-9c23-e06245c4dbd7.png)
![Bildschirmfoto_2019-03-19_14-24-26](https://user-images.githubusercontent.com/3328364/54609271-e7e79b80-4a52-11e9-8340-5863b3c715ec.png)

2019-03-19 15:49 UTC, Amstutz requested changes
Hi @nhaagen

Thank you a lot for this contribution to ILIAS.

I really like (almost fell in love on first sight) with the proposed way of using TreeRecursions along with Environments to fill the tree with live and reuse code in different scenarios. Good work there, congrats. Your example makes the proof of concept for this pattern by directly implementing the UI tree for $ilTree, loving it. That is how testable units are made ;-). 

Note that this review only tackles the interface discussed in the JF, nevertheless I had a short glimpse at the implementation and like what is evolving there (especially the easy to read JS part).

Please answer the following questions:

- [x] Tree vs. Drilldown: Similar to https://github.com/ILIAS-eLearning/ILIAS/pull/1620, I wondered, why those components differ so much, especially to consumer code. This seems to me like an issue, since to me, they are closely related and offer just a different view upon data that is structured in almost the same way. Can we not bring those two close together. E.g. would it not be possible to use much of the (powerful) TreeRecursion/Environment pattern also for Drilldowns? E.g. why are Menus/Submenues not just (probably more powerfull) versions of nodes?
- [ ]  TreeRecoursions vs. Transformations: As mentioned above, I did not have a close look at the implementation. However, by just looking over the implementation, it looks to me, as if your TreeRecursions are Transformations (see: https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/src/Transformation) transforming the triplet of NodeFactory, record and environment to a concrete node. Why do those TreeRecursion implement transformations and maybe even located close to the other transformations (see next question)?
- [ ]  Location of TreeRecursions: I guess there will be a list of rather commonly used TreeRecursions (e.g. like to one used in the example dealing with JS code, or the one loading async content from the repository by using ilTree). What is your vision, where the logic of those will be placed to make reuse easy? In the respective services (e.g. ilTree)? Could there be standard TreeRecursions (e.g. such as the ones you used with the array example), where would those be stored (e.g. in transformations)?

Please consider the following suggestions. You do not need to follow those, but but please indicate shortly why you prefer to do otherwise:

- [ ]  Extend Tree Description: The descriptions (especially usage) of tree seem a little under-developed to me. Can you think of a little more meat describing when to use trees, and when not?

Please implement the following changes:

- [ ]  Enhance Descriptions of TreeRecursion:  The Descriptions provided on the TreeRecursion interface need some more love. Maybe even provide an xxs example of such a transformation or point the place where one can find one. For both functions, but especially for build, explain the params (especially $record but maybe also $environment). Where do they come from? E.g. how those record relate to withData of the Tree?

@rklees: I will not be present during the next JF. Especially the Tree vs. Drilldown question and how much code-reuse there can be seems rather fundamental to me. If you want to put this on the JF for monday, feel free to do so, but then maybe we should have a short skype session discussing our point of view in this matter beforehand.

kindly,
@Amstutz

2019-03-21 09:22 UTC, Amstutz commented
We (@klees and @Amstutz ) discussed the relation between the Tree and the Drilldown and came to
the following conclusions: 

* "Drilldown" can be understood in two different ways. Either as
"Pattern" or as "Menu". What CaT implemented (and what is also required
for ILIAS) is the "Menu", while we want to support a "Drilldown Pattern"
for trees as well.
* We are looking to create a new category in the UI-framework called
"Menu" that subsumes `Dropdown` and `Drilldown` and could be the home
for the `Toolbar` as well. @nhaagen: Please provide a seperate PR for
this move after the `Drilldown` is completed.
* We are looking to expand the `Tree` with a `Drillable Tree` variety
besides the currently implemented `Expandable Tree`. @nhaagen: Please
tackle this task in a separate PR after we discussed (and hopefully
agreed on) the current Tree-PR in the JF.
* We feel that it will give us conceptual leeway to keep the `Tree`, as
a component to visualize data, and the `Menu`, as a component that
provides opportunities to manipulate data, separate from each other.
Although these two things definitely overlap at the "Drilldown Pattern",
they seem to have fairly different ends when it comes to other cases.
The "Menu", e.g., might feature real input elements some time, while the
"Tree" will require dealing with situations where users need to pick
elements from it. Unifying them conceptually seems to make it
unnecessarily hard to implement these requirements conceptually. They
might share more patterns and code (e.g. the `Recursion`) then they
currently do in the future, though.

2019-03-21 09:49 UTC, Amstutz commented
We (@klees and @Amstutz) discussed the relation between the Tree and the Drilldown and came to
the following conclusions:

* "Drilldown" can be understood in two different ways. Either as
"Pattern" or as "Menu". What CaT implemented (and what is also required
for ILIAS) is the "Menu", while we want to support a "Drilldown Pattern"
for trees as well.
* We are looking to create a new category in the UI-framework called
"Menu" that subsumes `Dropdown` and `Drilldown` and could be the home
for the `Toolbar` as well. @nhaagen: Please provide a seperate PR for
this move after the `Drilldown` is completed.
* We are looking to expand the `Tree` with a `Drillable Tree` variety
besides the currently implemented `Expandable Tree`. @nhaagen: Please
tackle this task in a separate PR after we discussed (and hopefully
agreed on) the current Tree-PR in the JF.
* We feel that it will give us conceptual leeway to keep the `Tree`, as
a component to visualize data, and the `Menu`, as a component that
provides opportunities to manipulate data, separate from each other.
Although these two things definitely overlap at the "Drilldown Pattern",
they seem to have fairly different ends when it comes to other cases.
The "Menu", e.g., might feature real input elements some time, while the
"Tree" will require dealing with situations where users need to pick
elements from it. Unifying them conceptually seems to make it
unnecessarily hard to implement these requirements conceptually. They
might share more patterns and code (e.g. the `Recursion`) then they
currently do in the future, though.

With the Drilldown vs. Tree question out of the way, I believe this to be in  a state, were we can discuss it in the next jf. I attached the according label.

2019-03-22 13:44 UTC, mjansenDatabay commented
LGTM, I will need a special type of `Node` for the forum, where the icon can be either a user profile image or a letter avatar, and the content of the node contains of two lines:

1. A linked subject
2. A by-line with the name of the author and a creation date

2019-03-25 14:08 UTC, matthiaskunkel commented
Jour Fixe, 25 MAR 2019 : We highly appreciate this PR and accept it for 6.0. Please add the possibility of highlighting the current position of the user within the repository (as already known from the existing tree implementation). And we invite all users to add additional PR in case the implementation of the UI tree for features in 6.0 leads to problems or make workarounds necessary.

2019-04-16 15:26 UTC, Amstutz commented
Hi @nhaagen

Thank you a lot for this contribution to ILIAS. Special thanks for the enhanced descriptions!

Please answer the following questions:

- [ ]  Clickable node title: The titles (text) of nodes is not clickable (expandable on click) at the moment. I can live with it for the moment, but guess this will be something that needs to be re-evaluated as soon as we have some user feedback. Note that currently nodes are clickable. What do you think, do we need to change that here?

Please implement the following changes:

- [ ]  Missing PHPDocs: There are PHPDocs missing in several places in the implementation or renderer, e.g. Node, add them.
- [ ]  Node Padding: The used default 40px ul padding is IMO too much for trees, since horizontal space will often be scarce. Reduce the default to something like 20px and add a less variable for it (this will be almost certainly adapted in several cases).

@klees you may merge as soon as you are good with the changes.

kindly,
@Amstutz

2019-04-18 09:57 UTC, nhaagen commented
Hi @Amstutz ,
thanks for your comments. 
The nodes are clickable, though. Maybe the example-titles are a little short ("1"), I admit.
I added the pointer-cursor to the whole title-line, so it should  be more obvious.

@klees I added some docs and fixed the padding; if you find the time, please have a look over it.

2019-04-18 12:20 UTC, klees commented
I think this will work for now, but we definitely require some styling for this.

@nhaagen Please look into the styling with @catkrahl and provide a new PR for the styling. I will merge this for now to allow other people (@tfamula) to move on with dependent projects (tree selector...).

2019-04-18 12:20 UTC, merged