UI: Play and pause glyph added
ILIAS-eLearning/ILIAS pull request #1719
Opened 2019-03-28 17:02 UTC by backermann1978

Added glyph icons for play and pause at dev conf in Cologne.

2019-04-08 09:18 UTC, Amstutz requested changes
Hi @backermann1978 

Thank you a lot for contributing to the UI Framework of ILIAS.

It's nice to see such a well worked out PR sparking from the workshop at the last Dev-Conf.

Please answer the following questions:
- [ ] Use Case: Do you see a concrete use case in ILIAS, where this glyph will be used? Is there some use case in an upcoming feature?
- [ ] Inside Video Frame: Can you be a bit more specific on what "Inside a video frame means?"
- [ ] Replacement of Glyphs: Since you will not want to reload the complete page if one clicks pause, you will have to do that with JS. Is the plan here, to attach manually some JS handling the player and the glyph?

Please implement the following changes:
- [ ] Effect Play: Move the description: "The Play Glyph should be replaced by Pause Glyph while the video is played." to Effect. Same for pause.

Note that this is just the review for the interface. If the JF accepts the interface we will provide an other review on the implementation before merging.

kindly,
@Amstutz

2019-04-08 12:24 UTC, matthiaskunkel commented on src/UI/Component/Glyph/Factory.php
> +     *          The Play Glyph MUST NOT be shown when the video is playable, but not already playing.
Please change to: The Pause glyph MUST NOT be shown when the video is already playing.

2019-04-08 12:26 UTC, matthiaskunkel commented
Jour Fixe, 08 APR 2019 : Pull request is highly appreciated and accepted for trunk. Please include Timon's requests and change the rule according to Matthias' comment.

2019-04-16 09:15 UTC, Amstutz commented
Let me know if any help assistance is needed with this PR.

2019-06-21 14:03 UTC, Amstutz commented
Any update?

2019-07-02 10:45 UTC, klees commented
As @backermann1978 does not seem to work on this, I would propose to close this.

Maybe someone (@nhaagen, @Amstutz, me) could duplicate the branch to our own repositories so we won't lose the code even if @backermann1978 should disappear =)

2019-07-02 12:16 UTC, backermann1978 commented
Hi @Amstutz and @klees, sorry that I couldn't work on my PR in the last weeks and didn't answer to your messages. I would like to resume work if this is still ok?! And I will try to not disappear... ;-)

2019-08-15 09:07 UTC, Amstutz commented
Since this seems inactive for a while, I close this down. Please re-open as soon as this can be re-evaluated. thx a lot for your contribution.

2019-08-15 09:07 UTC, closed without merging