Fix/23298/5 3/save confirmation anonymous
ILIAS-eLearning/ILIAS pull request #1811
Opened 2019-05-01 07:54 UTC by theodortruffer

Discussion see: https://github.com/ILIAS-eLearning/ILIAS/pull/1720

@chfsx the changes are the same as for 5.4/trunk. The cherry-pick didn't work because of small differences in the code style (i guess).

2019-05-02 17:53 UTC, chfsx commented on resources
> +Customizing/global/plugins/Services/Repository/RepositoryObject/OpenCast/node_modules/paellaplayer/build/player/resources/
@theodortruffer I think this is by mistake?

2019-05-02 17:54 UTC, chfsx requested changes
@theodortruffer  see my comment about the line which should not be part of this PR

2019-05-03 06:34 UTC, theodortruffer commented
@chfsx thanks, i removed it. Do you need a new PR or do you squash it anyway?

2019-05-03 06:34 UTC, chfsx commented
@theodortruffer if it's ok for you I'll squash it

2019-05-03 07:07 UTC, merged