mantis 25426: Group export / import does not export several settings
ILIAS-eLearning/ILIAS pull request #1841
Opened 2019-05-17 10:24 UTC by ClemensRobbenhaar

Pull request for https://mantis.ilias.de/view.php?id=25426

Please see details about the exact settings affected in the mantis issue.
I am not overly happy with the part loading the container settings from the DB and writing them back in the group object, but the alternative would have been a large switch (or nested if) statement inside an already big switch statement in the ``ilGroupXMLParser::handlerEndTag``. However I can change the code to call the ``group_obj->setNewsWhatever`` in the ``handlerEndTag``, if you prefer.

Please review and give me advise how to imporve the pull request where you see room for improvement.

2019-05-17 10:27 UTC, ClemensRobbenhaar commented
I forgot: the fix only applies cleanly to the trunk. I can send separate pull requests for the ``release_5-4`` and ``release_5-3`` branches, if this pull request is deemed acceprtable. (Are there other supported branches which which a pull requrest will e appreciated?)

2019-12-17 15:15 UTC, mjansenDatabay commented
@smeyer-ilias Any update on this? Please provide feedback/ask questions, close the PR, or merge it.

2020-03-16 12:29 UTC, klees commented
Send reminder to @smeyer-ilias today.

2020-03-16 18:32 UTC, ClemensRobbenhaar commented
I remember having discussed this PR with @smeyer-ilias on the phone, and he feels this solution is somewhat a bit ad hoc, and there is some metadata refactoring in progress that might make this PR unnecessary.

2020-03-31 11:49 UTC, smeyer-ilias requested changes
Thanks again for this PR. 
I will reuse parts of your work and integrate them in ILIAS 6.
But im/export of the container settings need another implementation since they should be handled by the container service and not within the course/group components.

2020-03-31 11:50 UTC, smeyer-ilias commented
I close this PR due to the reasons mentioned in my last note.

2020-03-31 11:50 UTC, closed without merging