UI, Bulky Link
ILIAS-eLearning/ILIAS pull request #2053
Opened 2019-08-08 15:05 UTC by nhaagen

The main advantage of Bulky Links, of course, is the possibility to open slate-entries in a new tab ;)
![Bildschirmfoto_2019-08-08_17-01-43](https://user-images.githubusercontent.com/3328364/62714174-56c39200-b9fe-11e9-9baa-f9fe632ddaf3.png)
![Bildschirmfoto_2019-08-08_16-50-56](https://user-images.githubusercontent.com/3328364/62714183-59be8280-b9fe-11e9-8d6d-5d888fcf5d1e.png)

2019-08-11 15:34 UTC, Amstutz commented
Thx a lot @nhaagen I am fine with the proposed interface change. I perform the review on the implementation as soon as the interface is accepted. @klees If you are fine with the interface changes as well, you can attach the JF label to put it on the upcoming JF tomorrow.

2019-08-12 05:35 UTC, klees requested changes
Hi @nhaagen,

LGTM in general plus some minor change requests. I'll show this on the JF today. Would be nice if the changes are already implemented then. Thx!!

Best regards!

2019-08-12 05:35 UTC, klees commented on tests/UI/Component/Link/BulkyLinkTest.php
> +
Remove this whitespace, please.

2019-08-12 05:35 UTC, klees commented on src/UI/Component/Link/Factory.php
> +	public function bulky(Symbol $symbol, string $label, string $action): Bulky;
Lets use `Data\URI` here instead of the string. Let's rename `$action` to `$target`. A link has a target, right?.

2019-08-12 05:35 UTC, klees commented on src/UI/Component/Link/Factory.php
> +	 *     The Bulky Link is built as a Link around an icon or glyph and a (small) text.
How is the link build "around" the symbol and the text?

2019-08-12 05:35 UTC, klees commented on src/UI/Component/Link/Factory.php
> +	 *     1: The icon/glyph and the text of the Bulky Link MUST be corresponding.
```suggestion
	 *     1: The symbol and the text of the Bulky Link MUST be corresponding.
```

2019-08-12 05:35 UTC, klees commented on src/UI/Component/Link/Factory.php
> +	 *        On screens larger than small size, Bulky Links MUST contain an icon or glyph plus text.
```suggestion
	 *        On screens larger than small size, Bulky Links MUST contain a symbol and text.
```

2019-08-12 05:35 UTC, klees commented on src/UI/Component/Link/Factory.php
> +	 *        On small-sized screens, Bulky Links SHOULD contain only an icon or glyph.
```suggestion
	 *        On small-sized screens, Bulky Links SHOULD contain only a symbol.
```

2019-08-19 14:37 UTC, klees approved these changes
LGTM, thx! Does @Amstutz want to have a look as well?

2019-08-26 11:55 UTC, matthiaskunkel commented
Jour Fixe, 26 AUG 2019: We highly appreciate this PR and accept it for 6.0. Please merge to trunk.

2019-08-26 12:55 UTC, merged