[Refinery] Create URI to string transformation, to get the origin string to create e.g. a href element from the URI object
ILIAS-eLearning/ILIAS pull request #2067
Opened 2019-08-13 08:54 UTC by legionth

This PR as proposal to create a transformation to transform an `Data\URI` object into a `string`.

The original idea was born during the development of #2042 , because there was no actual functionality to pass an `Data\URI` object around and be able to get the origin entered string back

Tell me what you think :+1:

2019-08-13 10:12 UTC, mjansenDatabay commented
Hi @legionth,

I highly apprecitate this. Putting this to a `Transformation` is IMO the superior approach compared to a  `UrlToStringBuilder` (or something similar) in `./src/Data`, `./src/HTTP`  or `./Services/Http`.

Kind regards,
@mjansenDatabay

2019-08-13 10:12 UTC, mjansenDatabay approved these changes

2019-08-13 15:25 UTC, mjansenDatabay requested changes
Hi @legionth,

I highly appreciate this. Putting this to a `Transformation` is IMO the superior approach compared to a  `UrlToStringBuilder` (or something similar) in `./src/Data`, `./src/HTTP`  or `./Services/Http`.

Please provide a section in the README file.

Kind regards,
@mjansenDatabay

2019-08-14 05:41 UTC, klees approved these changes
Hi @legionth,

I'm fine with this too. Would you introduce the according factories as well and wire them up in the main factory of the refinery? I would suggest to call the `Transformation` `toString` then, this will lead to `$factory->uri()->toString()`.

Thanks!!

2019-08-14 08:27 UTC, mjansenDatabay commented on src/Refinery/URI/Group.php
> +    public function string()
According to @klees this should be name `toString()`

2019-08-14 08:27 UTC, mjansenDatabay commented
Thx @legionth for the additions. Please use `declare(strict_types=1);` and return type declarations where possible (e.g. in the factories and unit tests).

2019-08-14 08:59 UTC, mjansenDatabay approved these changes

2019-08-14 09:04 UTC, merged