New features StudyProgramme port from relase 5.4
ILIAS-eLearning/ILIAS pull request #2235
Opened 2019-10-08 14:15 UTC by dkloepfer

2019-10-09 11:40 UTC, klees commented
Hi @dkloepfer!

Please rebase this upon the current trunk (and then force-push) to get rid of those merge-commits. Please also Prefix the commits with "Prg", if applicable, or other component shortnames. Please try to clean the commit history by squashing stuff.

Thx!

2019-10-21 10:50 UTC, dkloepfer commented
Will be reopened after rebase.

2019-10-21 11:31 UTC, klees commented
Dear @mstuder,

this contains marginal changes in the OrgUnits:

2019-10-21 11:33 UTC, klees commented
Dear @mstuder,

this contains some marginal changes in the OrgUnits:

* [add context for prg](https://github.com/ILIAS-eLearning/ILIAS/pull/2235/files#diff-223ea256077180a69fd4d33974f1128c)
* [raise events when positions are set](https://github.com/ILIAS-eLearning/ILIAS/pull/2235/files#diff-7a82b855c0a0101b389bd060b0329057)

Please approve the changes or tell us what to do differently.

Thx!

2019-10-21 12:21 UTC, mstuder commented
Hi @klees 

The changes concerning the organizational units are OK for me.

Best regards
Martin

2019-10-21 12:35 UTC, klees commented
Hi @smeyer-ilias,

this contains changes in your components:
* [add "Organisational Unit" as option in user search](https://github.com/ILIAS-eLearning/ILIAS/pull/2235/files#diff-17ae9d33dbef5b18ccccd4d89c2c4368)
* various marginal changes in Services/Repository, Services/Object and  Services/ContainerReference to make reference objects for Study Programmes happen

Please approve the changes or tell us what to do differently.

Thx!

2019-10-21 12:36 UTC, klees commented
Hi @mjansenDatabay,

this contains various marginal changes in Services/Certificate to make certificates for Study Programmes happen.

Please approve the changes or tell us what to do differently.

Thx!

2019-11-12 10:20 UTC, mjansenDatabay approved these changes
LGMT @klees .

FYI: I added some missing information to the README in `Services/Certificate` 1-2 weeks ago. I hope the pain for adding a new consumer was not too big without this documentation. Sorry for this.

2019-11-12 10:20 UTC, mjansenDatabay commented on Services/Certificate/classes/Form/Repository/class.ilCertificateSettingsScormFormRepository.php
> +    public function createForm(ilCertificateGUI $certificateGUI, ilCertificate $certificateObject)
Do you really need this?

2019-11-12 10:23 UTC, mjansenDatabay commented on Services/Certificate/classes/class.ilCertificateAppEventListener.php
> +            if (true === $template->isCurrentlyActive()) {
@klees Maybe `\ilCertificateAppEventListener::processEntry` could be called here instead?

2019-11-27 08:39 UTC, smeyer-ilias commented
No objections from my side.

2019-12-04 15:24 UTC, klees commented
Hi @alex40724,

could you have a look here regarding the integration in the dashboard in Services/Dashboard/classes/class.ilDashboardGUI.php?

Thx!

2019-12-04 15:50 UTC, alex40724 requested changes
Dashboard related changes seem to be ok, but why is there a new class Modules/Category/classes/class.ilCategoryExplorerGUI.php ?

I am out of office for today...

2019-12-04 15:54 UTC, klees commented
Hi @alex40724,

sry, did not notice that myself until just now, but you were faster.

For [this feature](https://docu.ilias.de/goto_docu_wiki_wpage_5787_1357.html) a category needs to be selected. But I think this should be doable without a new `ExplorerGUI`. Will have a look and inform you tomorrow.

Have a nice evening!

2019-12-04 17:01 UTC, klees commented
Hi @alex40724,

I removed that stuff by replacing it with `ilRepositorySelector2InputGUI`. Sorry again.

There are also some minor changes in `Services/ContainerReference` and `Services/Repository`to accomodate the new `StudyProgrammeReference`.

Best regards!

2019-12-04 19:17 UTC, alex40724 approved these changes
Looks good. Thanks.

2019-12-05 10:35 UTC, smeyer-ilias approved these changes
LGTM

2019-12-05 11:28 UTC, merged