Feature/6/ui mode info
ILIAS-eLearning/ILIAS pull request #2328
Opened 2019-11-18 07:06 UTC by chfsx

@klees and @Amstutz this is a call for ultra fast lane review :D as discussed last friday, ILIAS may need a ModeInfo Component:

![image](https://user-images.githubusercontent.com/6661332/69031357-31b9c480-09da-11ea-882b-c32c6ae36ae1.png)

The following PR contains the Interface-Chynge on StandardPage and for a new component ModeInfo.

2019-11-18 07:07 UTC, chfsx commented
Changes:
- New Methods on StandardPage: https://github.com/ILIAS-eLearning/ILIAS/pull/2328/files#diff-cd550c325169e2bd54eb3649a292c6b2R92
- Description of new component ModeInfo: https://github.com/ILIAS-eLearning/ILIAS/pull/2328/files#diff-19b7a6034a22226f59300948731bc31fR322
- Interface of ModeInfo: https://github.com/ILIAS-eLearning/ILIAS/pull/2328/files#diff-4c70382d72d36359cee2f2476400ca8cR15

2019-11-18 08:14 UTC, klees approved these changes
Hi @chfsx!

LGTM, left some very minor change requests.

Thanks for this!

2019-11-18 08:14 UTC, klees commented on src/UI/Component/MainControls/Factory.php
> +     *     The Mode Info MUST allow the user to leave the mode.
Please move to `rules.interaction`.

2019-11-18 08:14 UTC, klees commented on src/UI/Component/MainControls/Factory.php
> +     *     The ModeInfo MUST also contain a Close Button to leave the
Please RFC 2119-language in the rules section and less formal language in the description.

2019-11-18 08:14 UTC, klees commented on src/UI/Component/MainControls/Factory.php
> +     * @return ModeInfo
Please remove the docstrings. They just duplicate information from the (executable) type hints.

2019-11-18 08:28 UTC, Amstutz requested changes
Hi @chfsx 

Where do you take the time from? Your output is insane, congrats!

Other than the comments of @klees I would like to have 2 accessability rules on the Mode Info, so plz add:
- [x] Accessabilty Role: Since for blind People, this Info is IMO critical, plz add a rule requiring to add the proper WAI-Role to this element. Since I am not expert on this either, we best ask the JF for a decision on this here.
- [x] ARIA Label: Finde a proper label for this. E.g. something like Mode Info.

As mentioned, I would like to discuss this in the upcoming JF and hope that it will be accepted. Thx a lot.

2019-11-18 08:50 UTC, chfsx commented
Hi @Amstutz 
Thanks for those additions, I'll tray to tackle them. but concerning the WAI-Role, I do not find any matching: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles. Best I can find is AlertRole (which I'll propose this afternoon). Any better Idea?

2019-11-18 09:14 UTC, Amstutz commented
No, that is why, I moved the question along forward to the JF. I know, that there are people hopefully attending with more expertise then I have (e.g. @atoedt ). If we do not find anything, we have to drop this proposal of mine I am afraid.

2019-11-18 15:46 UTC, matthiaskunkel commented on src/UI/Component/MainControls/Factory.php
> +     *     role="alert" MUST be implemented.
We remove the last sentence in 'accessibility' to keep the discussion open which way is the best to make this UI component accessible.

2019-11-18 15:48 UTC, matthiaskunkel commented
Jour Fixe, 18 NOV 2019 : We highly appreciate the suggested PR and accept it for ILIAS 6. We removed the last sentence in 'Accessibility' to keep the discussion open which way is the best to make this UI component accessible.

2019-11-28 14:32 UTC, chfsx commented
see #2359 which includes this PR as well

2019-11-28 14:32 UTC, closed without merging