Authentication/SOAP: Fix SOAP Auth.
ILIAS-eLearning/ILIAS pull request #2448
Opened 2020-01-20 13:09 UTC by mjansenDatabay

Mantis Issue: https://mantis.ilias.de/view.php?id=24422

2020-03-05 08:43 UTC, mjansenDatabay commented
@smeyer-ilias Any objections? The SOAP auth. is currently available/configurable for administrators but completely broken.

2020-07-21 10:52 UTC, mjansenDatabay commented
Hi @smeyer-ilias  , the TB regularly monitors the list of PRs for old ones. Coud you please merge this or request feedback if you have any objections.

2020-09-15 10:28 UTC, smeyer-ilias commented
Thanks for the PR. I will try to check/test the changes until Sep 18th.

2020-09-29 09:32 UTC, smeyer-ilias requested changes

2020-09-29 09:32 UTC, smeyer-ilias commented on Services/Authentication/classes/Frontend/class.ilAuthFrontendCredentialsSoap.php
> +        $cmd = (string) ($this->httpRequest->getQueryParams()['cmd'] ?? '');
"??" requires PHP 7

2020-09-29 09:32 UTC, smeyer-ilias commented on Services/Init/classes/class.ilInitialisation.php
> +            if (false === strpos($a_target, $param . '=') && isset($GLOBALS['DIC']->http()->request()->getQueryParams()[$param])) {
isset on method calls is not suported.

2020-09-29 09:32 UTC, smeyer-ilias commented on Services/Init/classes/class.ilStartUpGUI.php
> +        $credentials = new ilAuthFrontendCredentialsSoap($GLOBALS['DIC']->http(), $this->ctrl, $ilSetting);
According to the constructor this should be $DIC->http()->request()

2020-09-29 09:32 UTC, smeyer-ilias commented on Services/Init/classes/class.ilStartUpGUI.php
> +        $credentials->setUsername(ilUtil::stripSlashes($_GET['ext_uid'] ?? ''));
PHP >= 7

2020-09-29 09:34 UTC, smeyer-ilias commented
Sorry, but I cannot merge this due to issues for PHP 5.6 support.

2020-09-29 10:02 UTC, mjansenDatabay reviewed
Thx @smeyer-ilias ! I fixed all issues.

2020-09-29 10:02 UTC, mjansenDatabay commented on Services/Init/classes/class.ilInitialisation.php
> +            if (false === strpos($a_target, $param . '=') && isset($GLOBALS['DIC']->http()->request()->getQueryParams()[$param])) {
This is not a method call, but array dereferencing.

2020-09-29 10:41 UTC, smeyer-ilias commented on Services/Init/classes/class.ilInitialisation.php
> +            if (false === strpos($a_target, $param . '=') && isset($GLOBALS['DIC']->http()->request()->getQueryParams()[$param])) {
Correct. But fails with fatal: PHP Fatal error:  Cannot use isset() on the result of a function call (you can use "null !== func()" instead) in 5.6

2020-10-14 06:37 UTC, swiniker commented
At yesterdays TB-Meeting we stumbled over this PR that has been around for a while: @smeyer-ilias could you please have a look at this again and merge if you agree. @mjansenDatabay has fixed the issues with PHP 5.6 and it would be a pity if we would run into merge errors, because we leave this too long.

2020-12-15 10:39 UTC, klees commented
Hi @smeyer-ilias,

this came up again in our last TB meeting on the 12-07. Is there anything new regarding this PR? Is there anything we could do to speed up the process?

Best regards!

2021-01-12 12:14 UTC, smeyer-ilias approved these changes
Thanks. Merged to >= 5.4

2021-01-12 12:15 UTC, smeyer-ilias commented
Already merged into >= 5.4

2021-01-12 12:15 UTC, closed without merging