prg - mantis_27695 - ajust settings by orgu
ILIAS-eLearning/ILIAS pull request #2534
Opened 2020-02-27 13:45 UTC by daniwe4

2020-02-27 16:20 UTC, klees requested changes
Hi @daniwe4,

this looks quite good already. I was unsure regarding the new settings-class, because it looks as if it really belongs to the OrgUnits. But I think we can keep it for now. I left some change requests inline. Please get back to me, if you have questions or need to discuss anything.

Thanks for working so diligently on this!

2020-02-27 16:20 UTC, klees commented on Modules/StudyProgramme/classes/class.ilObjStudyProgrammeSettingsGUI.php
> +                    $orgu_object_settings->update();
I think this rather should be located in `ilStudyProgrammeSettingsDBRepository`. Conceptually the repository is the entity that controls the "truth" about some circumstance, so pushing objects into it should affect the truth, not using some GUI. You already have that half-right, because you already read that setting in the repository class.

2020-02-27 16:20 UTC, klees commented on Modules/StudyProgramme/classes/class.ilObjStudyProgramme.php
> +        $this->updateSettings();
Why do we need this call here? We just created the settings. Why update them directly?

2020-02-27 16:20 UTC, klees commented on Modules/StudyProgramme/classes/model/Settings/class.ilStudyProgrammeSettingsDBRepository.php
> +        $acces_ctrl_by_orgu_positions = new \ilStudyProgrammeAccessCtrlByOrguPositionSettings();
```suggestion
        $access_ctrl_by_orgu_positions = new \ilStudyProgrammeAccessCtrlByOrguPositionSettings();
```

And in other locations as well.

2020-02-27 16:20 UTC, klees commented on Modules/StudyProgramme/classes/class.ilObjStudyProgrammeAutoCategoriesGUI.php
> +        );
This file contains whitespace-only changes. Drop them.

2020-03-03 05:49 UTC, daniwe4 commented on Modules/StudyProgramme/classes/class.ilObjStudyProgrammeAutoCategoriesGUI.php
> +        );
There is also a change at the const that is used. F_CATEGORY_ORIGINAL_REF to F_CATEGORY_REF

2020-03-03 07:23 UTC, daniwe4 commented on Modules/StudyProgramme/classes/class.ilObjStudyProgramme.php
> +        $this->updateSettings();
Your right, that is a remnant of the debugging process.

2020-03-03 07:24 UTC, daniwe4 commented on Modules/StudyProgramme/classes/model/Settings/class.ilStudyProgrammeSettingsDBRepository.php
> +        $acces_ctrl_by_orgu_positions = new \ilStudyProgrammeAccessCtrlByOrguPositionSettings();
Sry, i thought i clean that up already.
Done

2020-03-03 07:25 UTC, daniwe4 commented on Modules/StudyProgramme/classes/class.ilObjStudyProgramme.php
> +        $this->updateSettings();
Done

2020-03-03 08:11 UTC, daniwe4 commented on Modules/StudyProgramme/classes/class.ilObjStudyProgrammeSettingsGUI.php
> +                    $orgu_object_settings->update();
Done

2020-03-03 12:07 UTC, merged