UI/Standard Page: focus content area on page load (#27270)
ILIAS-eLearning/ILIAS pull request #2550
Opened 2020-03-09 15:54 UTC by klees

This fixes hopefully helps with [#27279](https://mantis.ilias.de/view.php?id=27270) by focusing the content area on page load and also adds an according rule. This seems to fit the semantics of html `<main>` as well.

2020-03-09 15:56 UTC, klees commented
@atoedt Is there anyone with assistive technology that could check if this improves behavior of the page?

2020-03-09 16:07 UTC, Amstutz requested changes
Hi @klees 

Thanks a lot for this contribution. I approve the change of rule and also the technical part of focusing main. However: 

- [x] plz move the JS from inline in the tpl to the according js in stdpage.js

after that you may directly merge if tests are passing.

2020-03-10 05:58 UTC, klees commented
Hi @Amstutz!

I didn't put the code in the `stdpage.js` because for me these files seem to contain code for modules that is only executed on demand. Also, the concrete code I added is highly dependent on the html in the template-file. I thus decided to bundle that code with the other code executed on load in that template because I see a stronger connection there than to the `stdpage.js`. I haven't got a strong opinion here, tough, and there are of course arguments to put the code into `stdpage.js`. I just wanted to highlight my reasoning to strengthen our common understanding.

Best regards!

2020-03-10 07:07 UTC, Amstutz commented
Hi @klees 

Concerning the first point of the js files only containing code to be executed on demand. I do not think so; Note that every function we define there on the outmost scope of each module is a self executing function. Obviously doing mostly doing not much more done setting up the scope and global singletons for later use, but they execute nevertheless. However, note that there are also examples of doing more (see button.js).

Conserning the second point; Unfortuanately we have the strong coupling between js and DOM all over the place. We could think about if we would like to introduce a standard why of handling this dep. or maybe get rid of it altogether but currently it is there.

My reason to move it are the following:

- Consistency: I do not want to setup the practice of having inline js in templates. This turned out to be source of really hard to track issues in the status quo. I am aware that the currently used patterns in the js files are not perfect, but one knows where to track js. The only exception I know we have so far of having js in tpl files is also in the standard page the il.Util.addOnload code. When we introduced this, I thought about if it would be benificial to factor this out as well (e.g. to ui.js). However, in this very special case, I thought, that having one defined place in the page itself to place out all those events, might be a good idea. So they might be easier to find for somebody not tightly involved with the components in case of an issue. However, they currently tend to clutter the output of the page somewhat, so I might to propse to factor this out as well at some point.
- Testing: We do not have tests for the standard page rendering. I understand why. However, note that inline js would be even a bigger issue if we would have.
- Clean templates: JS in templates is just cluttering up the semantics here. Our templates should be clean to read and not be cluttered with js. 
- Extendability: Note that especially standardpage could be one of those templates that could get customized in several szenarios. If so, one currently has to copy along those additional js lines as well. 

I have a rather strong opinion to move the js. However, happy to spar some further rounds ;-) I always enlightening.

Thx

2020-03-22 09:44 UTC, merged

2020-03-22 09:47 UTC, Amstutz commented
cherry picked to 6 as well.