UI, Input: disabled DateTime/Duration (fixes 27970)
ILIAS-eLearning/ILIAS pull request #2582
Opened 2020-03-23 16:24 UTC by nhaagen

https://mantis.ilias.de/view.php?id=27970

2020-03-24 12:42 UTC, klees requested changes
Hi @nhaagen,

thanks for looking into this. The solution in general looks as if it should work. Thanks for adjusting the examples as well.

There is one thing I like you to change: Currently we are storing the `DefaultRenderer`, passed to `render`, in a property on the `Renderer` object, later on modify it and use it to render a glyph for the Input. This approach, however, might cause problems in the future. There only is one `Renderer` per component (or at least we have to assume this) and calls to `render` could be nested, so one `Renderer` might be used in various positions on the call stack. If `render` modifies the instance, we might end up with other states of the `Renderer` instance then we'd expect. In fact, using a property here is just a backdoor to implicitly pass on the `DefaultRenderer` from `render` down to `renderDateTimeInput`, it is not any state the instance need to keep track of. Please explicitely pass the `DefaultRenderer` down to where you need it instead of using this backdoor.

In general that `Renderer` looks extremely messy, which wasn't introduced in this PR. Maybe we should clean up here some times soon.

Best regards!

2020-03-24 14:28 UTC, Amstutz commented
Hi @nhaagen 

Thanks a lot for caring for this. 

At we do not have Testrail cases for this, so there is nothing to be adapted. However, we this be the right time to add them?

@nhaagen You may merge as soon as the point of @klees is taken care of.

2020-03-25 06:34 UTC, klees approved these changes
Hi @nhaagen,

good catch removing that `$DIC` dependency in other locations as well. Thx! Will hit merge in a minute.

Best regards!

2020-03-25 06:34 UTC, klees commented on src/UI/Implementation/Component/Input/Field/Renderer.php
> +
```suggestion
```

2020-03-25 07:06 UTC, merged