Update IASS with ui form and inputs
ILIAS-eLearning/ILIAS pull request #2586
Opened 2020-03-24 14:06 UTC by shecken

2020-03-24 15:11 UTC, klees requested changes
Hallo @shecken, hallo @daniwe4,

vielen Dank für die Mühen mit dem Umbau. Ich glaube wir sind auf einem guten Weg aber noch nicht fertig. Ich habe einige diesbezügliche Kommentare inline hinterlassen. Lasst uns nochmal gemeinsam überlegen, was in diesem Rahmen noch Sinn machen würde.

Beste Grüße!

2020-03-24 15:11 UTC, klees commented on Modules/IndividualAssessment/classes/Members/class.ilIndividualAssessmentMember.php
> +     * @return	ilIndividualAssessmentMember
Die können mMn zu Type Hints gemacht werden.

2020-03-24 15:11 UTC, klees commented on Modules/IndividualAssessment/classes/class.ilIndividualAssessmentMemberGUI.php
> +		ilToolbarGUI $toolbar
```suggestion
        ilToolbarGUI $toolbar
```

2020-03-24 15:11 UTC, klees commented on Modules/IndividualAssessment/classes/class.ilIndividualAssessmentMemberGUI.php
> +            $grading = array_shift($result);
Ich denke, dass gehört einfach als Transformation an das Formular dran. Das gesamte Formular liefert ein Grading zurück, würde ich denken...

2020-03-24 15:11 UTC, klees commented on Modules/IndividualAssessment/classes/class.ilIndividualAssessmentMemberGUI.php
> +        $notify = (bool) $member->notify();
Das wirkt irgendwie noch nicht so besonders rund, oder? Müsste nicht vielmehr das `Member` einfach ein `Grading` haben?

2020-03-24 15:11 UTC, klees commented on Modules/IndividualAssessment/classes/class.ilIndividualAssessmentMemberGUI.php
> +            )
Verstehen wir die Parameter hier? Ich bin vor allem über die `"identifier"` und 64 arg überrascht.

2020-03-24 15:11 UTC, klees commented on Modules/IndividualAssessment/classes/ilIndividualAssessmentUserGrading.php
> +        bool $finalize = false
Müsste das nicht `$finalized` heißen?

2020-03-24 15:11 UTC, klees commented on Modules/IndividualAssessment/classes/ilIndividualAssessmentUserGrading.php
> +class ilIndividualAssessmentUserGrading
Für diese Klasse fehlt ein automatisierter Test.

2020-03-25 14:45 UTC, shecken commented on Modules/IndividualAssessment/classes/class.ilIndividualAssessmentMemberGUI.php
> +            )
Die 64 habe ich ersetzt. Bekomme auch keinen Fehler. Der $identifier kommt vom AbstractCtrlAwareUploadHandler. Die function muss man implementieren. Ich hab keine Ahnung wo die den da her holen und ob Daniel das so richtig gemacht hat.

2020-03-26 14:49 UTC, merged