new Datatype: Order
ILIAS-eLearning/ILIAS pull request #2656
Opened 2020-04-15 09:39 UTC by nhaagen

A tuple of subject and direction to express ordering

2020-04-17 14:05 UTC, mjansenDatabay commented
I highly appreciate this. I hate it to re-validate strings (passed from the UI layer into persistence layer, maybe crossing a few other layers) and use code like this: `if (!in_array(strtolower($oderDirection), [desc', 'asc'])) {$oderDirection = 'asc';}`.

2020-04-20 10:25 UTC, klees requested changes
Hi @nhaagen,

LGTM in general, just two minor nitpicks, then I'll be happy =)

Thx and best regards!

2020-04-20 10:25 UTC, klees commented on src/Data/Factory.php
> +     * @return Order
```suggestion
     * @param mixed $direction Order::ASC|Order::DESC
```

[We MAY drop doc-blocks if they do not add any information.](https://github.com/ILIAS-eLearning/ILIAS/blob/release_6/src/README.md) Also, this very much clarifies how doc-blocks could be a problem: The block talks about `$id`, while the parameters use the name `$subject`. If we don't duplicate the typehint the problem vanishes as well =)

2020-04-20 10:25 UTC, klees commented on src/Data/Order.php
> +    public function join(callable $fn, $prefix)
Let's switch the two parameters. Conceptually, `$prefix` comes left to the function we are using and the function itself also uses that order in its parameters. Also, add a doc-block for this method. Finally, let's rename `$prefix` to `$init` (if you could not think of anything better) to make unambiguously clear that we indeed do not care if this creates a string or anything else.

2020-04-24 07:21 UTC, merged