Tree: Optimize ilMaterializedPathTree::getSubtreeInfo
ILIAS-eLearning/ILIAS pull request #2674
Opened 2020-04-22 11:35 UTC by mjansenDatabay

This PR optimizes `ilMaterializedPathTree::getSubtreeInfo` on (at least) `MariaDB` installations, by splitting up the slow query into seperate queries, and by applying a tree filter in PHP, not in SQL.

This improves the performance of large installations.

Credits to @fneumann

2020-04-30 09:19 UTC, smeyer-ilias requested changes

2020-04-30 09:19 UTC, smeyer-ilias commented on Services/Tree/classes/class.ilMaterializedPathTree.php
> +        if ($this->getTree()->getTreeTable() == 'tree' && $this->getTree()->getTreeId() == 1) {
Please use $this->__isMainTree() $this->getTree()->getTreePk()

2020-04-30 09:40 UTC, smeyer-ilias commented
@mjansenDatabay I've commented a tweak issue. But the main question is: how does this change memory consumption on huge  tree structure with "Trash" enabled? 

Background: getSubtreeInfo() is wrapped by \ilTree::getRbacSubtreeInfo() which is currently used (only) ilObjRole::changeExistingObjects()

"changeExistingObjects()" is triggered in the following cases:

1. Create new objects with autogenerated roles
2. Applying didactic templates (e.g with local role action)
3. Perform "Change Existing objects" in the role administration (local and global roles)

Since the new implementation iterates over all tree entries - including the trashed nodes - the memory consumption might increase extremly on installations with actived trash.
While 1) is not a problem, since new object do not have trashed nodes in their subtree, 2) and 3) might produce out of memory errors without changing the server settings. 

You mentioned that this patch is already enabled since years on minimum two installations. Is the trash enabled on these installations? Did you notice changes in the memory consumption?

2020-04-30 10:08 UTC, mjansenDatabay commented on Services/Tree/classes/class.ilMaterializedPathTree.php
> +        if ($this->getTree()->getTreeTable() == 'tree' && $this->getTree()->getTreeId() == 1) {
I now use `$this->__isMainTree()`, but I don't understand `$this->getTree()->getTreePk()` in this context.

2020-04-30 10:22 UTC, mjansenDatabay commented
Hi @smeyer-ilias 

I pushed the change you requested.

Regarding the trash:
1. AFAIK @fneumann DOES USE the trash (and uses this code since ILIAS 5.0.x). I will ask him regarding the memory consumption.
2. Mark (uzk) does NOT use the trash (and uses this change since several weeks), so of course he does not notice any changes in the memory consumption.
3. The 3rd institution does NOT use the trash (and uses this change since several weeks), so of course they do not notice any changes in the memory consumption.

2021-01-26 11:10 UTC, swiniker commented
@smeyer-ilias : We stumbled over this PR from april last year when we checked for old PRs at the meeting of the Technical Board. Could you please have a look at it and merge or give your reasons for not merging it. Thx!

2021-02-23 12:46 UTC, Amstutz commented
Hi @smeyer-ilias ,

this came up again in our last TB meeting on the 23-02-2021. Is there anything we could do to speed up the process?

Best regards!

2021-03-26 15:25 UTC, merged

2021-03-26 15:40 UTC, smeyer-ilias commented
Thanks. I checked the memory consumption with a profiler. 
Even if many trashed objects are in the path, this shouldn't be a problem. 
100.000 objects consume ~10MB