Fixed implode() argument order to remove PHP 7.4 depreciated warnings
ILIAS-eLearning/ILIAS pull request #2819
Opened 2020-08-01 10:23 UTC by IlRoccOne

implode ( string $glue , array $pieces )

implode() akzeptiert die Parameter aus historischen Gründen in beiden 
Reihenfolgen. Aufgrund der Konsistenz zu explode(), ist die nicht 
dokumentierte Reihenfolge allerdings missbilligt.

Fixed "Array and string offset access syntax with curly braces is 
deprecated", so $string{0} became $string[0]

2020-08-03 05:49 UTC, mjansenDatabay commented
Thank you for your contribution @IlRoccOne . Can you please remove the whitespace changes and only provide the `implode()` fix?

2020-08-03 05:50 UTC, mjansenDatabay requested changes
Thank you for your contribution @IlRoccOne . Can you please remove the whitespace changes and only provide the implode() fix?

2020-08-03 09:02 UTC, chfsx commented
LGTM besides the whitespace changes, thanks a lot @IlRoccOne

2020-08-04 05:01 UTC, IlRoccOne commented
@mjansenDatabay and @chfsx Do the whitespaces serve a purpose? If they are really needed/usefull, I need to figure out how I can restore them whitout starting from scratch. PS: Tailing white space on empty lines got removed by Atom automatically.

2020-08-05 13:41 UTC, mjansenDatabay commented
@IlRoccOne The whitespaces do not serve any purpose (we use `php-cs-fixer` for propert PSR-2 formatting), the changes just distract from the actual changes when reviewing the PR.

2020-09-21 07:32 UTC, mjansenDatabay commented
All implode/join issues have been fixed by #2865

2020-09-21 07:32 UTC, closed without merging