Trunk/refinery/kindly to null
ILIAS-eLearning/ILIAS pull request #2908
Opened 2020-09-21 11:18 UTC by nhaagen

As a successor of https://github.com/ILIAS-eLearning/ILIAS/pull/2899,
this still
 - fixes https://mantis.ilias.de/view.php?id=28861 for trunk
but also
 - adds a kindlyToNull-Transform
 - uses it with the ByTrying-Transform
and moves the ProblemHandler-callable into a trait.

2020-09-21 13:00 UTC, klees requested changes
Hi @nhaagen,

this looks mostly fine, special kudos for factoring out that `ProblemBuilder`-trait. Looks useful.

I think there are some confusions regarding `Transformation` and `Constraint` that show in your code. The relation is like this: every `Constraint` is a `Transformation` but not the other way round. A `Constraint` is a special kind of `Transformation` that does not actually change values (i.e. transforms them) but rather only looks into the values and throws (or creates `Error`s) if the values do not conform to some rule. This allows to have a more specific base class for constraints where we can define more methods than we would want for generic `Transformation`s.

Thanks for working on this so carefully!!!

Best regards!

2020-09-21 13:00 UTC, klees commented on src/Refinery/Factory.php
> +     * @param Transformation[]
```suggestion
     * @param Transformation[] $transformations
```

2020-09-21 13:00 UTC, klees commented on src/Refinery/KindlyTo/Transformation/NullTransformation.php
> +    }
Use `DeriveInvokeFromTransform` instead.

2020-09-21 13:00 UTC, klees commented on src/Refinery/KindlyTo/Transformation/NullTransformation.php
> +    }
We don't need that IMO. This is something only `Constraint`s need but not defined on the `Transformation`-interface.

2020-09-21 13:00 UTC, klees commented on src/Refinery/To/Transformation/StringTransformation.php
> +    }
I don't think we need that. Am I wrong?

2020-09-21 13:00 UTC, klees commented on src/Refinery/ByTrying.php
> +    }
Use `DeriveInvokeFromTransform`.

2020-09-21 13:00 UTC, klees commented on tests/Refinery/ByTrying/ByTryingTransformTest.php
> +        ];
Pleasuse PHPUnits dataproviders here (and also in the other test in this case).

2020-09-21 13:00 UTC, klees commented on src/Refinery/ByTrying.php
> +            if ($transformation->accepts($from)) {
`accepts` is no method on the `Transformation`-interface, so we cannot use it here. I think we could just `applyTo` instead and use the first result that is `ok`.

2020-09-21 13:00 UTC, klees commented on src/Refinery/ProblemBuilder.php
> +    protected $error;
Maybe we should add this as an abstract method here, to force our users to always give an error. Just having a property makes it possible to just forget to set this.

2020-09-21 15:33 UTC, mjansenDatabay commented
@nhaagen LGTM (except the tiny changes @klees already requested). Indeed kudos for the `ProblemBuilder` trait.

2020-09-21 15:34 UTC, mjansenDatabay commented on src/Refinery/ProblemBuilder.php
> +    protected $error;
Something like `abstract protected getError() : string|callable;` or `abstract protected getDefaultError() : string|callable;`  (I know these return types do not work, yet)? I would appreciate this.

2020-09-22 08:48 UTC, nhaagen commented
Thank you both very much for your comments and hints.
I think, I got them all.

Best regards.

2020-09-22 11:28 UTC, merged

2020-09-22 11:28 UTC, klees commented
Thanks @nhaagen!