add total deletion of reservations
ILIAS-eLearning/ILIAS pull request #3001
Opened 2020-11-17 11:38 UTC by iszmais

https://mantis.ilias.de/view.php?id=28973

2020-11-17 11:51 UTC, mjansenDatabay commented on Modules/BookingManager/classes/class.ilObjBookingPoolGUI.php
> +            foreach (explode(',', $DIC->http()->request()->getParsedBody()['rsv_ids']) as $id) {
@iszmais Do we need an additional check, if each `id` does belong to the current object?

2020-11-17 11:54 UTC, iszmais commented on Modules/BookingManager/classes/class.ilObjBookingPoolGUI.php
> +            foreach (explode(',', $DIC->http()->request()->getParsedBody()['rsv_ids']) as $id) {
Hmm... good question. But i would say no since even if they dont belong to the current object the user should be still able to delete them if he has the right permission to do so. So the function can be keeped abstract to provide a higher usability without security isssues.

2020-11-17 12:03 UTC, mjansenDatabay commented on Modules/BookingManager/classes/class.ilObjBookingPoolGUI.php
> +            foreach (explode(',', $DIC->http()->request()->getParsedBody()['rsv_ids']) as $id) {
I am not sure if `rsvDeleteObject` has to fulfill an abstract purpose. It is bound to a very concrete controller/command. If you (as an attacker) are able to inject reservation ids to `$_POST['rsv_ids']`, and these ids belong to another repository object where you did **not** have any higher priviledges, you'll successfully exploited an `Broken Access Control` issue.

2020-11-17 12:13 UTC, iszmais commented on Modules/BookingManager/classes/class.ilObjBookingPoolGUI.php
> +            foreach (explode(',', $DIC->http()->request()->getParsedBody()['rsv_ids']) as $id) {
In this case i will expand the Security check below.

2020-11-17 14:24 UTC, mjansenDatabay requested changes
@iszmais LGTM, except the missing context check for the reservation ids.

2020-11-17 16:06 UTC, iszmais commented on Modules/BookingManager/classes/class.ilObjBookingPoolGUI.php
> +            foreach (explode(',', $DIC->http()->request()->getParsedBody()['rsv_ids']) as $id) {
The new implementation should fullfill all security guidlines.

2020-11-17 17:12 UTC, alex40724 commented on Modules/BookingManager/classes/class.ilObjBookingPoolGUI.php
> +                }
You only need to check
- write permission for the current ref id and
- does the $obj->getPoolId() match the current pool id.

No need to get all the references.

2020-11-18 11:12 UTC, mjansenDatabay approved these changes

2020-11-18 15:21 UTC, merged