Course/Certificate: Fix Mantis issue 29191
ILIAS-eLearning/ILIAS pull request #3064
Opened 2021-01-11 15:24 UTC by mjansenDatabay

If approved, we'll have to add a `ilCtrl` reload to read the `service.xml` changes.

Mantis Issue: https://mantis.ilias.de/view.php?id=29191

Original PR: #3034 3034

2022-02-22 12:51 UTC, klees commented
Hi @smeyer-ilias,

we stumbled upon this PR in our TB meeting. Any updates on this?

Best regards!

2022-03-22 12:17 UTC, swiniker commented
Hi @smeyer-ilias 
As Technical Board, we regularly check for pull requests that have been open for a long time.
Any Updates on this?

Best regards!

2022-04-05 07:49 UTC, Amstutz commented
Hi @smeyer-ilias
As Technical Board, we regularly check for pull requests that have been open for a long time.
Any Updates on this?

Best regards!

2022-05-03 11:42 UTC, Amstutz commented
Hi @smeyer-ilias
As Technical Board, we regularly check for pull requests that have been open for a long time.
Any Updates on this?

Best regards!

2022-05-17 09:16 UTC, Amstutz commented
Hi @smeyer-ilias
As Technical Board, we regularly check for pull requests that have been open for a long time.
Any Updates on this?

Best regards!

2022-06-14 08:43 UTC, Amstutz commented
Hi @smeyer-ilias
As Technical Board, we regularly check for pull requests that have been open for a long time.
Any Updates on this?

Best regards!

2022-08-09 10:18 UTC, Amstutz commented
Hi @smeyer-ilias
As Technical Board, we regularly check for pull requests that have been open for a long time.
Any Updates on this?

Best regards!

2022-08-12 12:06 UTC, smeyer-ilias commented
Sorry, for the delay.
I will check and test this PR after my vacation.

2022-08-23 10:30 UTC, smeyer-ilias requested changes

2022-08-23 10:30 UTC, smeyer-ilias commented on Services/Tracking/classes/status/class.ilLPStatusCollection.php
> +        $ilObjDataCache = $DIC['ilObjDataCache'];
Please use $this->ilObjDataCache

2022-08-23 10:30 UTC, smeyer-ilias commented on Services/Tracking/classes/status/class.ilLPStatusCollection.php
> +        $tree = $DIC['tree'];
Please introduce $tree in the constructor of ilLPCollection.

2022-08-23 10:30 UTC, smeyer-ilias commented on Services/Tracking/classes/status/class.ilLPStatusCollection.php
> +                if ($crsRefId = $tree->checkForParentType($folderRefId, 'crs')) {
Please implement an additional check for group membership here: checkForParentType($foldeRefId, 'grp');

2022-09-20 08:29 UTC, merged