BT-28951: Added aria label for main menu search form input
ILIAS-eLearning/ILIAS pull request #3072
Opened 2021-01-13 14:48 UTC by M-Barz

2021-01-13 16:02 UTC, smeyer-ilias requested changes

2021-01-13 16:02 UTC, smeyer-ilias commented on Services/Search/classes/class.ilMainMenuSearchGUI.php
> +        $this->tpl->setVariable('SEARCH_INPUT_LABEL', mb_strtolower($this->lng->txt('search_field')));
Why strtolower?
If you want to use mb_strtolower in other case please use the wrapper ilStr::strToLower in ./Services/Utilties
The mb_ methods can only be used, if the multibyte extension is loaded, which is not a required module in our installation guide.

2021-01-13 16:02 UTC, smeyer-ilias commented on lang/ilias_de.lang
> +common#:#search_field#:#Sucheingabefeld
Whenever possible avoid the common module. You could can use the search module here.

2021-01-13 16:02 UTC, smeyer-ilias commented on lang/ilias_en.lang
> +common#:#search_field#:#Search input field
Please use uppercase in english (if not a completre sentence): "Search Input Field"

2021-01-13 16:03 UTC, smeyer-ilias commented
Please you add a link the mantis report.

2021-01-14 09:31 UTC, M-Barz commented
Mantis Report:
https://mantis.ilias.de/view.php?id=28951

2021-01-14 09:33 UTC, M-Barz commented
Implemented the requested Changes :)

2021-01-14 11:15 UTC, smeyer-ilias requested changes
Please fix the english language variable.
After this change please commit and merge to changes to 5.4, 6 and trunk

2021-01-14 11:15 UTC, smeyer-ilias commented on lang/ilias_en.lang
> +search#:#search_field#:#Search input field
"Please use uppercase in english (if not a complete sentence): "Search Input Field"

2021-01-14 13:22 UTC, merged