6/sprg/fixes
ILIAS-eLearning/ILIAS pull request #3085
Opened 2021-01-18 12:16 UTC by nhaagen

https://mantis.ilias.de/view.php?id=29358
https://mantis.ilias.de/view.php?id=29522
https://mantis.ilias.de/view.php?id=29529

There were several issues with updating individual plans based on program-settings.

2021-01-19 09:58 UTC, klees requested changes
Hi @nhaagen,

LGTM in general, thanks for improving the general structure here. I noted some minor change requests inline, please adjust accordingly.

Best regards!

2021-01-19 09:58 UTC, klees commented on Modules/StudyProgramme/classes/class.ilObjStudyProgramme.php
> +            $assignment = $ass->getSPAssingnment();
```suggestion
            $assignment = $ass->getSPAssignment();
```

2021-01-19 09:58 UTC, klees commented on Modules/StudyProgramme/classes/class.ilStudyProgrammeUserAssignment.php
> +    public function getSPAssingnment() : ilStudyProgrammeAssignment
```suggestion
    public function getSPAssignment() : ilStudyProgrammeAssignment
```

2021-01-19 09:58 UTC, klees commented on Modules/StudyProgramme/classes/class.ilObjStudyProgramme.php
> +                    $log->write("Adding progress for: " . $id . " " . $node->getId());
Could we use `debug` here instead of `write`?

2021-01-19 09:58 UTC, klees commented on Modules/StudyProgramme/classes/class.ilObjStudyProgramme.php
> +                        );
```suggestion
                        )->setStatus(
                            ilStudyProgrammeProgress::STATUS_NOT_RELEVANT
                        )
                    );
```

2021-01-19 09:58 UTC, klees commented on Modules/StudyProgramme/classes/class.ilObjStudyProgramme.php
> +        return $DIC['ilLog'];
Please do not use the global `ilLog` anymore. Instead use the [`ilLoggerFactory`](https://github.com/ILIAS-eLearning/ILIAS/blob/release_6/Services/Logging/classes/public/class.ilLoggerFactory.php) like this (e.g.) [this](https://github.com/ILIAS-eLearning/ILIAS/blob/2929791b0b24dd1faeaed6ef2c215d700a1c54e5/Modules/Course/classes/class.ilCourseObjective.php#L139).

This is still some dreaded global to be used there, but our users (and we) will get the benefit of configurable log levels per component.

2021-01-19 09:58 UTC, klees commented on Modules/StudyProgramme/classes/model/Progress/class.ilStudyProgrammeProgress.php
> +
```suggestion
```
Sounds plausible indeed.

2021-01-19 10:40 UTC, nhaagen commented
Thanks for cleaning. Changes are in.

2021-01-20 13:47 UTC, klees approved these changes

2021-01-20 15:32 UTC, klees approved these changes

2021-01-25 08:28 UTC, merged