LSO: mark view-mode with ModeInfo
ILIAS-eLearning/ILIAS pull request #3152
Opened 2021-02-05 10:02 UTC by nhaagen

In conjunction with https://github.com/ILIAS-eLearning/ILIAS/pull/3151,
this visualizes the player-mode / learner view of LSO in a way more prominent way, including very strong hints on where to exit ;)

![ScreenshotLSO1](https://user-images.githubusercontent.com/3328364/107018764-24d0ee80-67a1-11eb-94c2-1801a8d2faf6.png)
![ScreenshotLSO2](https://user-images.githubusercontent.com/3328364/107018772-269ab200-67a1-11eb-9368-4f5c85601768.png)

2021-11-30 10:13 UTC, chfsx commented
As Technical Board, we regularly check for pull requests that have been open for a long time.
This PR is marked as Draft, are you still working on it? Thanks for clarifying the state of this PR.

Best regards!

2021-12-16 14:27 UTC, klees requested changes
Hi  @nhaagen,

this looks great and is exactly what the mode info is build for IMO. Two minor changes that I would like you to implement before I merge this:

* The [Mode Info documentation](https://github.com/ILIAS-eLearning/ILIAS/blob/trunk/src/UI/Component/MainControls/Factory.php#L332) says, that the title given to the mode info should describe the mode. Hence "Exit" won't be the way to go here. Please change to `Learning Sequence` or `Bearbeitung der Lernsequenz` in german.
* Please remove the duplicate [X]-Button in the Meta Bar.

Thanks!

2022-03-22 12:19 UTC, swiniker commented
Dear @klees 
As Technical Board, we regularly check for pull requests that have been open for a long time.
This PR is marked as Draft, are you still working on it? Thanks for clarifying the state of this PR.

Thanks and best!

2022-03-22 12:35 UTC, klees commented
@swiniker We are looking to integrate this for ILIAS 8.

2022-03-24 14:58 UTC, merged