Initial php 8 compatibility for WebResource Module
ILIAS-eLearning/ILIAS pull request #3459
Opened 2021-06-22 10:01 UTC by M-Barz

2021-07-06 09:28 UTC, smeyer-ilias requested changes

2021-07-06 09:28 UTC, smeyer-ilias commented on Modules/WebResource/classes/class.ilLinkResourceHandlerGUI.php
> +        if ($ilAccess->checkAccess("read", "", $getParams["ref_id"])) {
Theoretically the index "ref_id" is not defined

2021-07-06 09:28 UTC, smeyer-ilias commented on Modules/WebResource/classes/class.ilLinkResourceHandlerGUI.php
> +                $getParams["ref_id"],
Same here

2021-07-06 09:28 UTC, smeyer-ilias commented on Modules/WebResource/classes/class.ilObjLinkResourceGUI.php
> +        if ($this->getParams["baseClass"] == 'ilLinkResourceHandlerGUI') {
Please check if "baseClass" exists.

2021-07-06 09:28 UTC, smeyer-ilias commented on Modules/WebResource/classes/class.ilObjLinkResourceGUI.php
> +        if (!(int) $this->getParams['link_id']) {
Please check whether "link_id" is set.

2021-07-06 09:28 UTC, smeyer-ilias commented on Modules/WebResource/classes/class.ilObjLinkResourceGUI.php
> +        $this->setValuesFromLink((int) $this->getParams['link_id'] ?? 0);
Precedence (parenthesis)

2021-07-06 09:28 UTC, smeyer-ilias commented on Modules/WebResource/classes/class.ilObjLinkResourceGUI.php
> +        $this->ctrl->setParameter($this, 'link_id', (int) $this->getParams['link_id'] ?? 0);
Precedence (parenthesis)

2021-07-06 09:28 UTC, smeyer-ilias commented on Modules/WebResource/classes/class.ilObjLinkResourceGUI.php
> +        $param->delete((int) $this->getParams['param_id'] ?? 0);
Precedence (parenthesis)

2021-07-06 09:28 UTC, smeyer-ilias commented on Modules/WebResource/classes/class.ilObjLinkResourceGUI.php
> +        $param->delete((int) $this->getParams['param_id'] ?? 0);
Precedence (parenthesis)

2021-07-06 09:28 UTC, smeyer-ilias commented on Modules/WebResource/classes/class.ilObjLinkResourceGUI.php
> +        if (!is_array($this->postParams['ids'])) {
Check  for "ids"

2021-07-06 09:28 UTC, smeyer-ilias commented on Modules/WebResource/classes/class.ilObjLinkResourceGUI.php
> +        foreach ($this->postParams['ids'] as $link_id) {
Check index defined for the following lines.

2021-07-06 09:28 UTC, smeyer-ilias commented on Modules/WebResource/classes/class.ilObjLinkResourceGUI.php
> +            $table->parseSelectedLinks( (array) $this->postParams['ids'] ?? array());
Precedence (parenthesis)

2021-07-06 09:28 UTC, smeyer-ilias commented on Modules/WebResource/classes/class.ilObjLinkResourceGUI.php
> +        $ids = (array) $this->postParams['ids'] ?? array();
Precedence (parenthesis)
And following lines

2021-07-06 09:28 UTC, smeyer-ilias commented on Modules/WebResource/classes/class.ilObjLinkResourceGUI.php
> +                if (count($links = ilParameterAppender::_getParams( (int) $this->getParams['link_id'] ?? 0))) {
Precedence (parenthesis)

2021-07-06 09:28 UTC, smeyer-ilias commented on Modules/WebResource/classes/class.ilObjLinkResourceGUI.php
> +        $_REQUEST['view_mode'] = $this->getParams['view_mode'] = (int) $this->getParams['switch_mode'] ?? self::VIEW_MODE_VIEW;
Precedence (parenthesis)

2021-07-06 09:28 UTC, smeyer-ilias commented on Modules/WebResource/classes/class.ilObjLinkResourceGUI.php
> +        if (strtolower($this->getParams["baseClass"]) == "iladministrationgui") {
Check "baseClass" exists.

2021-07-06 09:28 UTC, smeyer-ilias commented on Modules/WebResource/classes/class.ilObjLinkResourceGUI.php
> +        $sort->savePost((array) $this->postParams['position'] ?? array());
Parenthesis

2021-07-06 09:28 UTC, smeyer-ilias commented on Modules/WebResource/classes/class.ilObjLinkResourceGUI.php
> +        if (is_array($this->postParams['link_ids'])) {
Parenthesis

2021-07-06 09:28 UTC, smeyer-ilias commented on Modules/WebResource/classes/class.ilObjLinkResourceGUI.php
> +        $link_ids = (array) $this->postParams['link_ids'] ?? array();
Parenthesis

2021-07-06 09:28 UTC, smeyer-ilias commented on Modules/WebResource/classes/class.ilObjLinkResourceGUI.php
> +        if (!$this->getParams['link_id']) {
Check "link_id" exists

2021-07-06 09:28 UTC, smeyer-ilias commented on Modules/WebResource/classes/class.ilObjLinkResourceGUI.php
> +        $links->setLinkId((int) $this->getParams['link_id'] ?? 0);
Parenthesis

2021-07-06 09:28 UTC, smeyer-ilias commented on Modules/WebResource/classes/class.ilObjLinkResourceGUI.php
> +        if ($this->postParams['link_check_message']) {
Check link_check_message" exists.

2021-07-06 09:28 UTC, smeyer-ilias commented on Modules/WebResource/classes/class.ilObjLinkResourceListGUI.php
> +        if(isset($request->getQueryParams()['wsp_id'])) {
Please initialize "wsp_id"

2021-07-06 09:28 UTC, smeyer-ilias commented on Modules/WebResource/classes/class.ilObjLinkResourceListGUI.php
> +            (isset($cmd_class) && $cmd_class === "ilpersonalworkspacegui")
Please initialize $cmd_class

2021-07-06 09:28 UTC, smeyer-ilias commented on Modules/WebResource/classes/class.ilParameterAppender.php
> +const LINKS_USER_ID = 1;
Please move to ilParameterAppender as public const

2022-02-08 12:38 UTC, mjansenDatabay commented
Hi @M-Barz 

we stumbled upon this PR in our TB meeting. Any updates on this?

Best regards!

2022-05-17 09:18 UTC, Amstutz commented
Hi @M-Barz

we stumbled upon this PR in our TB meeting. Any updates on this? Can that PR be closed be closed?

Best regards!

2022-07-04 11:20 UTC, closed without merging

2022-07-04 11:20 UTC, smeyer-ilias commented
Already integrated in trunk.