LearningSequence: Refactoring for PHP 8.0
ILIAS-eLearning/ILIAS pull request #3527
Opened 2021-07-27 09:57 UTC by daniwe4

2021-07-29 12:01 UTC, klees requested changes
Hi @daniwe4,

thanks a lot so far. I left various inline comments with change requests. I found two repeating issues, that I want to point out especially:

* For some reason I do not currently understand, you have exchanged `ilObjLearningSequence` for `ilObject` in various places, although we absolutely require a learning sequence object later on.
* `array` type hints are missing an according docstring that informs in more detail about the arrays content in many places.

Please make one more iteration based on my comments.

Special kudos for improving the unit tests!!

2021-07-29 12:01 UTC, klees commented on Modules/LearningSequence/classes/Content/class.ilObjLearningSequenceContentTableGUI.php
> +        /** @var LSItem $set */
Why don't use a type hint in the method signature here?

2021-07-29 12:01 UTC, klees commented on Modules/LearningSequence/classes/Content/class.ilObjLearningSequenceContentTableGUI.php
> +        ilObjLearningSequenceGUI $container_gui,
Why do we need to add this?

2021-07-29 12:01 UTC, klees commented on Modules/LearningSequence/classes/LearnerProgress/class.ilLSLP.php
>  class ilLSLP extends ilObjectLP
We can't add typehints here because of the extended classes, right?

2021-07-29 12:01 UTC, klees commented on Modules/LearningSequence/classes/LearnerProgress/class.ilLSLPEventHandler.php
> +<?php declare(strict_types=1);
It looks as if we could add more type hints in this class.

2021-07-29 12:01 UTC, klees commented on Modules/LearningSequence/classes/Members/class.ilLearningSequenceEditParticipantsTableGUI.php
> +        ilObject $ls_object,
I don't think this can be any arbitrary object, we call a specific method on thet object later on. Change this back to `ilObjLearningSequence` (or convince me otherwise =) ).

2021-07-29 12:01 UTC, klees commented on Modules/LearningSequence/classes/Members/class.ilLearningSequenceEditParticipantsTableGUI.php
> -        $this->ctrl = $ctrl;
Why do you remove these? We need them some lines below...

2021-07-29 12:01 UTC, klees commented on Modules/LearningSequence/classes/Members/class.ilLearningSequenceMembershipGUI.php
> -        $this->access = $access;
Why would we remove these? Are they already set in the parent object via DIC? I would prefer to pull in this dependencies via constructor, even if the parent pulls them per DIC, because this will make this implementation more easily testable. Maybe we should have a look together.

2021-07-29 12:01 UTC, klees commented on Modules/LearningSequence/classes/Members/class.ilLearningSequenceMembershipGUI.php
>  class ilLearningSequenceMembershipGUI extends ilMembershipGUI
This class is missing some typehints.

2021-07-29 12:01 UTC, klees commented on Modules/LearningSequence/classes/Members/class.ilLearningSequenceParticipantsTableGUI.php
> +        ilObject $ls_object,
We can't change the type hint here. We call `getLSParticipants` later on, so a generic `ilObject` won't be enough.

2021-07-29 12:01 UTC, klees commented on Modules/LearningSequence/classes/Members/class.ilLearningSequenceParticipantsTableGUI.php
>      protected function getLastAccess(int $user_id)
There are several methods that look very similar. Make them return `?int` and factor out that part transforming null to "-".

2021-07-29 12:01 UTC, klees commented on Modules/LearningSequence/classes/Members/class.ilLearningSequenceRoles.php
> -    public function leaveLearningSequence() : int
Huh? Isn't this used anywhere?

2021-07-29 12:01 UTC, klees commented on Modules/LearningSequence/classes/Members/class.ilLearningSequenceRoles.php
>      public function getLearningSequenceMemberIds() : array
Document the content of the array in a docstring here.

2021-07-29 12:01 UTC, klees commented on Modules/LearningSequence/classes/Members/class.ilLearningSequenceRoles.php
> -        if (!is_array($roles)) {
Are we 100% sure this can't happen anymore?

2021-07-29 12:01 UTC, klees commented on Modules/LearningSequence/classes/Members/class.ilLearningSequenceRoles.php
> +    public function getLearningSequenceMemberData(array $user_ids, int $active = 1) : array
Document the content of the array in a docstring here.

2021-07-29 12:01 UTC, klees commented on Modules/LearningSequence/classes/Members/class.ilLearningSequenceRoles.php
> +    public function getLearningSequenceAdminIds() : array
Document the content of the array in a docstring here.

2021-07-29 12:01 UTC, klees commented on Modules/LearningSequence/classes/Player/LSTOCBuilder.php
> +    protected array $structure;
Can we add some helpful docstring here?

2021-07-29 12:01 UTC, klees commented on Modules/LearningSequence/classes/Player/class.ilLSLocatorGUI.php
> +    public function __construct(LSUrlBuilder $url_builder, Factory $ui_factory)
Why do we hint on an `LSUrlBuilder` here but only on an `UrlBuilder` for the according property?

2021-07-29 12:01 UTC, klees commented on Modules/LearningSequence/classes/Player/class.ilLSStateDB.php
> +     * @return false|string
Why no typehint on `string`? If `json_encode` fails, I want to know that loud and clear. Maybe wrap a check that throws an exception around it too.

2021-07-29 12:01 UTC, klees commented on Modules/LearningSequence/classes/Player/class.ilLSTOCGUI.php
> +    protected array $nodes = [];
Can we add docstring for these `array`s?

2021-07-29 12:01 UTC, klees commented on Modules/LearningSequence/classes/Player/class.ilObjLearningSequenceLearnerGUI.php
> +        $response = $this->player->play($_GET);
Pull `$_GET` up to the constructor, as requested in the MUST criteria.

2021-07-29 12:01 UTC, klees commented on Modules/LearningSequence/classes/Settings/class.ilLearningSequenceSettings.php
> +    protected array $deletions = [];
Can we add docstrings for these `array`s?

2021-07-29 12:01 UTC, klees commented on Modules/LearningSequence/classes/Xml/class.ilLearningSequenceXMLParser.php
> +    protected array $lp_settings;
Dostrings for the `array`s please.

2021-07-29 12:01 UTC, klees commented on Modules/LearningSequence/classes/Xml/class.ilLearningSequenceXMLWriter.php
> +        ilObject $ls_object,
`ilObject` won't be enough here, we use methods only defined on `ilObjLearningSequence`.

2021-07-29 12:01 UTC, klees commented on Modules/LearningSequence/classes/Xml/class.ilLearningSequenceXMLWriter.php
> +        ilObject $ls_object,
`ilObject` won't be enough here, we use methods only defined on `ilObjLearningSequence`.

2021-07-29 12:01 UTC, klees commented on Modules/LearningSequence/classes/class.ilDashboardLearningSequenceGUI.php
> +    protected function getLsoItem(ilObject $lso_obj) : Item\Standard
`ilObject` is not enough here. Please check every other place where you exchanged an `ilObjLearningSequence` for an `ilObject` as well.

2021-07-29 12:01 UTC, klees commented on Modules/LearningSequence/classes/class.ilLSDI.php
>      public function init(ArrayAccess $dic)
Why don't we add a type hint here?

2021-07-29 12:01 UTC, klees commented on Modules/LearningSequence/classes/class.ilLSLocalDI.php
>      ) {
Why no `: void` here?

2021-07-29 12:01 UTC, klees commented on Modules/LearningSequence/classes/class.ilObjLearningSequence.php
> +    public function getDefaultLearningSequenceRoles(string $a_grp_id = "") : array
Pleae have a look at all `array` type hints you have added and check if we could give extra information in the docstrings about the arrays.

2021-07-29 12:01 UTC, klees commented on Modules/LearningSequence/test/LSItems/LSItemTest.php
> +    protected function setUp() : void
Why would me make this `protected`?

2021-07-29 12:01 UTC, klees commented on Modules/LearningSequence/test/LearnerProgress/Stubs/ilLPStatusWrapperStub.php
> +class ilLPStatusWrapperStub extends ilLPStatusWrapper
Do we really want these classes to have their own files? You could easily define empty classes like these inline, is there any benefit of putting them in their own files?

2021-07-29 12:28 UTC, daniwe4 commented on Modules/LearningSequence/test/LearnerProgress/Stubs/ilLPStatusWrapperStub.php
> +class ilLPStatusWrapperStub extends ilLPStatusWrapper
move classes into test files

2021-07-29 12:29 UTC, daniwe4 commented on Modules/LearningSequence/test/LSItems/LSItemTest.php
> +    protected function setUp() : void
It is protected in the base class. I got a weak warning if we override it to public.

2021-07-29 12:31 UTC, daniwe4 commented on Modules/LearningSequence/classes/class.ilLSLocalDI.php
>      ) {
I didn't see it. Done!

2021-07-29 12:31 UTC, daniwe4 commented on Modules/LearningSequence/classes/class.ilLSDI.php
>      public function init(ArrayAccess $dic)
Done!

2021-07-29 12:34 UTC, daniwe4 commented on Modules/LearningSequence/classes/LearnerProgress/class.ilLSLPEventHandler.php
> +<?php declare(strict_types=1);
Done!

2021-07-29 12:37 UTC, daniwe4 commented on Modules/LearningSequence/classes/LearnerProgress/class.ilLSLP.php
>  class ilLSLP extends ilObjectLP
Thats right. I add inheritdoc strings.

2021-07-29 12:42 UTC, daniwe4 commented on Modules/LearningSequence/classes/Content/class.ilObjLearningSequenceContentTableGUI.php
> +        ilObjLearningSequenceGUI $container_gui,
To avoid this code fragment:
`$lso_gui = $this->parent_gui->parent_gui;
 $item_list_gui->setContainerObject($lso_gui);`

2021-07-29 12:44 UTC, daniwe4 commented on Modules/LearningSequence/classes/Content/class.ilObjLearningSequenceContentTableGUI.php
> +        /** @var LSItem $set */
Because the base class didn't do this.

2021-07-29 12:46 UTC, daniwe4 commented on Modules/LearningSequence/classes/Members/class.ilLearningSequenceEditParticipantsTableGUI.php
> -        $this->ctrl = $ctrl;
They come from the parent class.

2021-07-30 06:01 UTC, daniwe4 commented on Modules/LearningSequence/classes/Members/class.ilLearningSequenceMembershipGUI.php
>  class ilLearningSequenceMembershipGUI extends ilMembershipGUI
Done!

2021-07-30 06:03 UTC, daniwe4 commented on Modules/LearningSequence/classes/Members/class.ilLearningSequenceMembershipGUI.php
> -        $this->access = $access;
Decide to keep the changes after a call.

2021-07-30 06:22 UTC, daniwe4 commented on Modules/LearningSequence/classes/Members/class.ilLearningSequenceParticipantsTableGUI.php
> +        ilObject $ls_object,
Done!

2021-07-30 06:41 UTC, daniwe4 commented on Modules/LearningSequence/classes/Members/class.ilLearningSequenceParticipantsTableGUI.php
>      protected function getLastAccess(int $user_id)
Done!

2021-07-30 06:43 UTC, daniwe4 commented on Modules/LearningSequence/classes/Members/class.ilLearningSequenceRoles.php
> -    public function leaveLearningSequence() : int
I've searched for the string 'leaveLearningSequence' in the whole codebase. Nothing found.

2021-07-30 06:48 UTC, daniwe4 commented on Modules/LearningSequence/classes/Members/class.ilLearningSequenceRoles.php
>      public function getLearningSequenceMemberIds() : array
Delete this method. Is never used in whole ILIAS.

2021-07-30 06:53 UTC, daniwe4 commented on Modules/LearningSequence/classes/Members/class.ilLearningSequenceRoles.php
> -        if (!is_array($roles)) {
`public static function getMemberRoles(int $ref_id) : array
    {
        global $DIC;

        $rbacreview = $DIC->rbac()->review();
        $lrol = $rbacreview->getRolesOfRoleFolder($ref_id, false);

        $roles = array();
        foreach ($lrol as $role) {
            $title = ilObject::_lookupTitle($role);

            switch (substr($title, 0, 8)) {
                case 'il_lso_a':
                case 'il_lso_m':
                    $roles[$role] = $role;
                    // no break
                default:
                    break;
            }
        }

        return $roles;
    }`

Should always be an array.

2021-07-30 07:01 UTC, daniwe4 commented on Modules/LearningSequence/classes/Members/class.ilLearningSequenceRoles.php
> +    public function getLearningSequenceMemberData(array $user_ids, int $active = 1) : array
Remove this method and the calling 'getLearningSequenceMemberData' in ilObjLearningSequence. Its never called in whole ILIAS.

2021-07-30 07:16 UTC, daniwe4 commented on Modules/LearningSequence/classes/Members/class.ilLearningSequenceRoles.php
> +    public function getLearningSequenceAdminIds() : array
Done!

2021-07-30 07:18 UTC, daniwe4 commented on Modules/LearningSequence/classes/Player/LSTOCBuilder.php
> +    protected array $structure;
Done!

2021-07-30 07:20 UTC, daniwe4 commented on Modules/LearningSequence/classes/Player/class.ilLSLocatorGUI.php
> +    public function __construct(LSUrlBuilder $url_builder, Factory $ui_factory)
switch property to LSUrlBuilder

2021-07-30 07:52 UTC, daniwe4 commented on Modules/LearningSequence/classes/Player/class.ilLSStateDB.php
> +     * @return false|string
Done!

2021-07-30 11:23 UTC, daniwe4 commented on Modules/LearningSequence/classes/Player/class.ilLSTOCGUI.php
> +    protected array $nodes = [];
Done!

2021-08-16 05:24 UTC, daniwe4 commented on Modules/LearningSequence/classes/Player/class.ilObjLearningSequenceLearnerGUI.php
> +        $response = $this->player->play($_GET);
Done!

2021-08-16 06:51 UTC, daniwe4 commented on Modules/LearningSequence/classes/Settings/class.ilLearningSequenceSettings.php
> +    protected array $deletions = [];
add docstring for deletions, uploads is to complex to find correct docstring

2021-08-16 07:07 UTC, daniwe4 commented on Modules/LearningSequence/classes/Xml/class.ilLearningSequenceXMLParser.php
> +    protected array $lp_settings;
Done!

2021-08-16 07:13 UTC, daniwe4 commented on Modules/LearningSequence/classes/Xml/class.ilLearningSequenceXMLWriter.php
> +        ilObject $ls_object,
Done!

2021-08-16 07:13 UTC, daniwe4 commented on Modules/LearningSequence/classes/Xml/class.ilLearningSequenceXMLWriter.php
> +        ilObject $ls_object,
Done!

2021-08-16 09:51 UTC, daniwe4 commented on Modules/LearningSequence/classes/class.ilObjLearningSequence.php
> +    public function getDefaultLearningSequenceRoles(string $a_grp_id = "") : array
Done!

2021-08-16 09:52 UTC, daniwe4 commented on Modules/LearningSequence/classes/Members/class.ilLearningSequenceEditParticipantsTableGUI.php
> +        ilObject $ls_object,
Done!

2021-08-16 09:53 UTC, daniwe4 commented on Modules/LearningSequence/classes/class.ilDashboardLearningSequenceGUI.php
> +    protected function getLsoItem(ilObject $lso_obj) : Item\Standard
Done!

2021-08-17 13:21 UTC, merged