Php8 mail migration
ILIAS-eLearning/ILIAS pull request #3543
Opened 2021-08-09 09:06 UTC by fhelfer

PHP 8 Migration: 
* Return-Type-Declarations: function foo() : void
* Type-Hints: function(string $a) : void
* Type Properties: private ilObjUser $user;
* `declare(strict_types=1);`

in:
Services/Mail
Services/Contact/classes

2021-08-09 09:58 UTC, mjansenDatabay requested changes
Hi @fhelfer , thanks for this PR.

Please try to solve the following issues:

1. This PR contains files NOT located in `Services/Mail` or `Services/Contact/classes`. Please remove these files from the change list (`ilCtrl`, `ilTable2GUI`, `php_errors.log`).
2. Please try to `squash` the commits.
3. If you change a file, please try to apply the [`PSR-2 + X` code style](https://github.com/ILIAS-eLearning/ILIAS/blob/trunk/docs/development/coding-style.md).
4. I still find many usages of `$_POST` or `$_GET`. Please try to replace them by using the corresponding methods of `$DIC->http()->request()`. Where applicable, please use our `Refinery` transformations to ensure the user input has the correct type/shape when being processed (example: https://github.com/ILIAS-eLearning/ILIAS/blob/trunk/Modules/Chatroom/classes/gui/class.ilChatroomPrivateRoomGUI.php#L72).
5. Try to replace read/write operations for `$_SESSION` with `ilSession::get` and `ilSession:set` .

Important: Try to execute the code by performing the necessary user interface operations in the mail system (e.g. _Send a mail_, _Add an attachment_, etc.).

If you have any questions or need help, don't hesitate to contact me.

Best regards,
@mjansenDatabay

2021-08-18 17:39 UTC, mjansenDatabay commented
@fhelfer Could you please resolve the conflicts?

2021-08-19 07:28 UTC, fhelfer commented
> @fhelfer Could you please resolve the conflicts?

@mjansenDatabay Done

2021-09-02 06:47 UTC, mjansenDatabay requested changes
- [ ] Please don't use PHP 8 features like `Union Types` or `mixed` (as a return type). ILIAS 8 must be compatible with PHP 7.4 as well.
- [ ] Please used the `static` keyword (if appropriate) and a return type for every function callback (e.g. in `Services/Contact/classes/Provider/ContactMainBarProvider.php`).
- [ ] Please remove obsolete type casts (e.g. `(bool) (ilBuddySystem::getInstance()->isEnabled())`). We don't need them if we already have explicit types.
- [ ] Please replace the expressive array syntax (`array()`) with the short one (`[]`).
- [ ] Please remove all require_once and include_once statements which we do not need anymore. Please keep those in the `tests` folder.
- [ ] Please remove PHPDocs where no added value is provided regarding the PHP types or description.
- [ ] Please add PHPDoc for arrays if they could provide more type related info, e.g. if an array is a list (`int[]`, `string[]`, ...) or a map (`array<int, string>` etc.), or a struct-like array with not more than 4 properties (`array{firstname: string, lastname: string, tite: string, id: int}`). You don't need to apply this for methods derived from base classes of other components (other maintainers).
- [ ] Please use the `<Class>::class` property instead of string, e.g. `ilUsersGalleryGUI::class` instead of `'ilUsersGalleryGUI'`. Class strings are mostly used in `executeCommand` methods, or in method calls like `ilCtrl::getLinkTargetByClass`, `ilCtrl::getFormActionByClass`.

2021-09-02 06:47 UTC, mjansenDatabay commented on Services/Contact/classes/class.ilContactGUI.php
> +    protected ilGlobalPageTemplate $tpl;
Please change this to `ilGlobalTemplateInterface`.

2021-09-02 06:47 UTC, mjansenDatabay commented on Services/Contact/classes/class.ilContactGUI.php
> +    private RequestInterface $httpRequest;
IMO `ServerRequestInterface` is more appropriate here.

2021-09-02 06:47 UTC, mjansenDatabay commented on Services/Contact/classes/class.ilContactGUI.php
> +                if (in_array(strtolower($this->ctrl->getCmdClass()), array_map('strtolower', array('ilUsersGalleryGUI', get_class($this))), true)) {
Please use `ilUsersGalleryGUI::class` instead (here and everywhere class strings are used).

2021-09-02 06:47 UTC, mjansenDatabay commented on Services/Contact/classes/class.ilContactGUI.php
> +    private array|null $postUsrId = null;
ILIAS 8 must be compatible to PHP 7.4 as well. So `Union Types` are not allowed, yet. Here you can use `?array` instead.

2021-09-02 06:47 UTC, mjansenDatabay commented on Services/Contact/classes/class.ilContactGUI.php
> +     * @var int[]
```suggestion
     * @var int[]|null
```

2021-09-02 06:47 UTC, mjansenDatabay commented on Services/Contact/classes/class.ilContactGUI.php
> +            if ($login === '') {
`ilObjUser::_lookupLogin` might also return `false` (at the moment).

2021-09-02 06:47 UTC, mjansenDatabay commented on Services/Contact/classes/class.ilContactGUI.php
> +        global $DIC;
Please move the `global $DIC` to the constructor and initizalize a `$this->refinery` member variable. Don`t use `global` in instance methods.

2021-09-02 06:47 UTC, mjansenDatabay commented on Services/Contact/classes/class.ilMailMemberSearchGUI.php
> +use Psr\Http\Message\RequestInterface;
IMO `ServerRequestInterface` is more appropriate here.

2021-09-02 06:47 UTC, mjansenDatabay commented on Services/Contact/classes/class.ilMailMemberSearchGUI.php
> +    protected mixed $mail_roles;
The `mixed` type ist not allowe in PHP 7.4.

2021-09-02 06:47 UTC, mjansenDatabay commented on Services/Contact/classes/class.ilMailMemberSearchGUI.php
> +    protected mixed $gui;
The `mixed` type ist not allowe in PHP 7.4.

2021-09-02 06:47 UTC, mjansenDatabay commented on Services/Contact/classes/class.ilMailMemberSearchGUI.php
> +    public function __construct(mixed $gui, int $ref_id, ilAbstractMailMemberRoles $objMailMemberRoles)
The `mixed` type ist not allowe in PHP 7.4.

2021-09-02 06:47 UTC, mjansenDatabay commented on Services/Contact/classes/class.ilMailMemberSessionRoles.php
> +            $i = substr($role_title, 0, 12);
Please rename this to `$role_prefix` (or something else)?

2021-09-02 06:47 UTC, mjansenDatabay commented on Services/Contact/classes/class.ilMailSearchCoursesMembersTableGUI.php
> +use Psr\Http\Message\RequestInterface;
IMO `ServerRequestInterface` is more appropriate here (and for the other classes where you introduced it).

2021-09-02 06:47 UTC, mjansenDatabay commented on Services/Contact/classes/class.ilMailSearchCoursesTableGUI.php
> +use Psr\Http\Message\RequestInterface;
IMO `ServerRequestInterface` is more appropriate here (and for the other classes where you introduced it).

2021-09-02 06:47 UTC, mjansenDatabay commented on Services/Contact/classes/class.ilMailSearchGUI.php
> +use JetBrains\PhpStorm\NoReturn;
ILIAS does not have a `JetBrains` dependency. Please remove this (here and everywhere).

2021-09-02 06:47 UTC, mjansenDatabay commented on Services/Contact/classes/class.ilMailSearchGUI.php
> +use Psr\Http\Message\RequestInterface;
IMO `ServerRequestInterface` is more appropriate here (and for the other classes where you introduced it).

2021-09-02 06:47 UTC, mjansenDatabay commented on Services/Mail/classes/class.ilPDMailGUI.php
> +use Psr\Http\Message\RequestInterface;
IMO `ServerRequestInterface` is more appropriate here (and for the other classes where you introduced it).

2021-09-02 06:47 UTC, mjansenDatabay commented on Services/Mail/classes/class.ilPDMailBlockGUI.php
> +use Psr\Http\Message\RequestInterface;
IMO `ServerRequestInterface` is more appropriate here (and for the other classes where you introduced it).

2021-09-02 06:47 UTC, mjansenDatabay commented on Services/Mail/classes/class.ilObjMailGUI.php
> +    private RequestInterface $httpRequest;
IMO `ServerRequestInterface` is more appropriate here (and for the other classes where you introduced it).

2021-09-02 12:35 UTC, mjansenDatabay requested changes

2021-09-02 12:35 UTC, mjansenDatabay commented on Services/Mail/classes/Form/class.ilManualPlaceholderInputGUI.php
> +    protected ilGlobalPageTemplate $tpl;
Should be `ilGlobalTemplateInterface`

2021-09-02 12:35 UTC, mjansenDatabay commented on Services/Mail/classes/Mime/Sender/class.ilMailMimeSenderFactory.php
> +    protected ?int $anonymousUsrId = 0;
`$anonymousUsrId` as a class member should never be `null`, so you can use `int` here.

2021-09-02 12:35 UTC, mjansenDatabay commented on Services/Mail/classes/Mime/Sender/class.ilMailMimeSenderSystem.php
> +        return $this->settings->get('mail_system_sys_reply_to_addr') !== '';
```suggestion
        return ((string) $this->settings->get('mail_system_sys_reply_to_addr', '')) !== '';
```

2021-09-02 12:35 UTC, mjansenDatabay commented on Services/Mail/classes/Mime/Sender/class.ilMailMimeSenderSystem.php
> +        return $this->settings->get('mail_system_sys_env_from_addr') !== '';
```suggestion
        return ((string) $this->settings->get('mail_system_sys_env_from_addr', '')) !== '';
```

2021-09-02 12:35 UTC, mjansenDatabay commented on Services/Mail/classes/Mime/Sender/class.ilMailMimeSenderUser.php
> +            $this->settings->get('global_reply_to_addr', '') !== ''
```suggestion
            ((string) $this->settings->get('global_reply_to_addr', '')) !== ''
```

2021-09-02 12:35 UTC, mjansenDatabay commented on Services/Mail/classes/Mime/Sender/class.ilMailMimeSenderUser.php
> +        return $this->settings->get('mail_system_usr_env_from_addr') !== '';
```suggestion
        return ((string) $this->settings->get('mail_system_usr_env_from_addr', '')) !== '';
```

2021-09-02 12:35 UTC, mjansenDatabay commented on Services/Mail/classes/Mime/Sender/class.ilMailMimeSenderUser.php
>          $from = $this->settings->get('mail_system_usr_from_name', '');
```suggestion
        $from = (string) $this->settings->get('mail_system_usr_from_name', '');
```

2021-09-02 12:35 UTC, mjansenDatabay commented on Services/Mail/classes/Message/class.ilMailBody.php
> +    private mixed $bodyContent;
The `mixed` type is not supported in PHP 7.4, which we'll have to support as well in ILIAS 8.

2021-09-02 12:35 UTC, mjansenDatabay commented on Services/Mail/classes/Mime/Subject/class.ilMailMimeSubjectBuilder.php
> +            if ($prefix !== '') {
If we use this check, we have to ensure that the variable is of type `string`. It might be also `null` here.

2021-09-02 12:35 UTC, mjansenDatabay commented on Services/Mail/classes/Mime/Transport/class.ilMailMimeTransportBase.php
> +                str_contains($message, 'Invalid address') ||
`str_contains` is not supported in PHP 7.4 (https://www.php.net/manual/en/function.str-contains.php), which we'll have to support as well in ILIAS 8.

2021-09-02 12:35 UTC, mjansenDatabay commented on Services/Mail/classes/Mime/Transport/class.ilMailMimeTransportBase.php
> +                str_contains($message, 'Message body empty')
`str_contains` is not supported in PHP 7.4 (https://www.php.net/manual/en/function.str-contains.php), which we'll have to support as well in ILIAS 8.

2021-09-02 12:35 UTC, mjansenDatabay commented on Services/Mail/classes/Mime/Transport/class.ilMailMimeTransportSmtp.php
> +        if ($this->settings->get('mail_smtp_user') !== '') {
```suggestion
        if (((string) $this->settings->get('mail_smtp_user', '')) !== '') {
```

2021-09-02 12:35 UTC, mjansenDatabay commented on Services/Mail/classes/class.ilAccountMail.php
> +                $ilSetting->get("admin_email"), ],
The formatting seems to be not `PSR-2 +x` here.

2021-09-02 12:35 UTC, mjansenDatabay commented on Services/Mail/classes/class.ilMailAutoCompleteSentMailsRecipientsProvider.php
> +                str_contains($this->data['login'], ',') ||
`str_contains` is not supported in PHP 7.4 (https://www.php.net/manual/en/function.str-contains.php), which we'll have to support as well in ILIAS 8.

2021-09-02 12:35 UTC, mjansenDatabay commented on Services/Mail/classes/class.ilMailAutoCompleteSentMailsRecipientsProvider.php
> +                str_contains($this->data['login'], ';')
`str_contains` is not supported in PHP 7.4 (https://www.php.net/manual/en/function.str-contains.php), which we'll have to support as well in ILIAS 8.

2021-09-02 12:35 UTC, mjansenDatabay commented on Services/Mail/classes/class.ilMailAutoCompleteUserProvider.php
> +    protected function getQueryConditionByFieldAndValue(string $field, mixed $a_str) : string
The `mixed` type is not supported in PHP 7.4, which we'll have to support as well in ILIAS 8.

2021-09-02 12:35 UTC, mjansenDatabay commented on Services/Contact/classes/class.ilMailMemberSearchGUI.php
> +    protected mixed $objParticipants;
The `mixed` type is not supported in PHP 7.4, which we'll have to support as well in ILIAS 8.

2021-09-02 12:35 UTC, mjansenDatabay commented on Services/Mail/classes/Form/class.ilIncomingMailInputGUI.php
> +    public function getItemByPostVar($a_post_var) : mixed
The `mixed` type is not supported in PHP 7.4, which we'll have to support as well in ILIAS 8.

2021-09-02 12:35 UTC, mjansenDatabay commented on Services/Mail/classes/Form/class.ilManualPlaceholderInputGUI.php
> +    public function render(bool $ajax = false) : mixed
The `mixed` type is not supported in PHP 7.4, which we'll have to support as well in ILIAS 8.

2021-09-02 12:35 UTC, mjansenDatabay commented on Services/Mail/classes/class.ilFormatMail.php
> +    public function formatReplyMessage() : mixed
The `mixed` type is not supported in PHP 7.4, which we'll have to support as well in ILIAS 8.

2021-09-02 12:35 UTC, mjansenDatabay commented on Services/Mail/classes/class.ilFormatMail.php
> +    public function formatReplySubject() : mixed
The `mixed` type is not supported in PHP 7.4, which we'll have to support as well in ILIAS 8.

2021-09-02 12:35 UTC, mjansenDatabay commented on Services/Mail/classes/class.ilFormatMail.php
> +    public function formatReplyRecipient() : mixed
The `mixed` type is not supported in PHP 7.4, which we'll have to support as well in ILIAS 8.

2021-09-02 12:35 UTC, mjansenDatabay commented on Services/Mail/classes/class.ilFormatMail.php
> +    public function formatForwardSubject() : mixed
The `mixed` type is not supported in PHP 7.4, which we'll have to support as well in ILIAS 8.

2021-09-02 12:45 UTC, mjansenDatabay requested changes

2021-09-02 12:45 UTC, mjansenDatabay commented on Services/Contact/classes/class.ilMailMemberSearchGUI.php
> +    private RequestInterface $httpRequest;
Should be `ServerRequestInterface` IMO

2021-09-02 12:45 UTC, mjansenDatabay commented on Services/Contact/classes/class.ilMailSearchCoursesMembersTableGUI.php
> +    private RequestInterface $httpRequest;
Should be `ServerRequestInterface` IMO

2021-09-02 12:45 UTC, mjansenDatabay commented on Services/Contact/classes/class.ilMailSearchCoursesTableGUI.php
> +    private RequestInterface $httpRequest;
Should be `ServerRequestInterface` IMO

2021-09-02 12:45 UTC, mjansenDatabay commented on Services/Contact/classes/class.ilMailSearchGUI.php
> +    private RequestInterface $httpRequest;
Should be `ServerRequestInterface` IMO

2021-09-02 12:45 UTC, mjansenDatabay commented on Services/Contact/classes/class.ilMailingListsGUI.php
> +    private RequestInterface $httpRequest;
Should be `ServerRequestInterface` IMO

2021-09-02 12:45 UTC, mjansenDatabay commented on Services/Mail/classes/class.ilAccountMail.php
> +    private RequestInterface $httpRequest;
Should be `ServerRequestInterface` IMO

2021-09-02 12:45 UTC, mjansenDatabay commented on Services/Mail/classes/class.ilMailCronNotification.php
> +    private RequestInterface $httpRequest;
Should be `ServerRequestInterface` IMO

2021-09-02 12:45 UTC, mjansenDatabay commented on Services/Contact/classes/class.ilMailSearchGUI.php
> +    private ilGlobalPageTemplate $tpl;
Should be `GlobaTemplateInterface` IMO

2021-09-02 12:45 UTC, mjansenDatabay commented on Services/Contact/classes/class.ilMailingListsGUI.php
> +    protected ilGlobalPageTemplate $tpl;
Should be `GlobaTemplateInterface` IMO

2021-09-02 12:45 UTC, mjansenDatabay commented on Services/Mail/classes/class.ilMailAttachmentGUI.php
> +    private ilGlobalPageTemplate $tpl;
Should be `GlobaTemplateInterface` IMO

2021-09-02 12:45 UTC, mjansenDatabay commented on Services/Contact/classes/class.ilMailMemberSearchGUI.php
> +    protected ilGlobalPageTemplate $tpl;
Should be `GlobaTemplateInterface` IMO

2021-09-18 12:36 UTC, mjansenDatabay commented
@fhelfer I added a commit which finalizes `Services/Contacts`.

Please apply the following changes to `Services/Mail`:

- [ ] Please remove all `require_once` and `include_once` directives.
- [ ] Please apply the `PSR 2 + x` code style to the `Services/Mail` folder. There are at least 10 files which violate our coding style. Use `php-cs-fixer`: `libs/composer/vendor/friendsofphp/php-cs-fixer/php-cs-fixer fix --config=./CI/PHP-CS-Fixer/code-format.php_cs --using-cache=no Services/Mail/classes/`
- [ ] There a still some `PhpDoc` issues. Please have a look at my commens **above**. Remove obsolete `PhpDoc` comments even for `__construct`.
- [ ] In class `ilMail` you declared many properties as `optional`. I am sure they are not. Please check other classes (like `ilMailOptionsGUI`, ...) as well.
- [ ] Please remove leading `\` in front of classes where the `\` is obsolete.
- [ ] `str_starts_with` is not supported in `PHP 7.4`, please use `strpos($haystack, $needle) === 0` instead. I know that there might be a composer polyfill which make it work in `PHP 7.4`, but we should not use it.
- [ ] In some files the recommended line length is exceeded. Try to use multiple lines instead.
- [ ] In the meantime the `Refinery` can be used together with our `HTTP Service`. Try to use `$DIC->http()->wrapper()->query()` and `$DIC->http()->wrapper()->post()` with the `has` and `retrieve` methods for processing the user input. You'll have to pass a `Refinery Transformation` when retrieving a value. Please have a look at `Services/Contacts` for examples (or contact me).
- [ ] Please remove obsolete blank lines in the classes (between methods and property declarations).
- [ ] Please cast values (e.g. integers with `(int)`) in `\ilMail::fetchMailData`. Otherwise there will be some problems in the consumer code when working with this array, e.g. the `sender_id` accessed in `\ilPDMailGUI::getPDMailHTML` (and many other places).

2021-10-04 07:31 UTC, mjansenDatabay approved these changes

2021-10-04 07:34 UTC, merged