Language: add hook to sort entries in language files
ILIAS-eLearning/ILIAS pull request #3575
Opened 2021-08-26 09:54 UTC by nhaagen

Following #3562 and a JF-vote for sorted lang-entries, here is my suggestion on a pre-commit hook.

2021-08-26 10:12 UTC, mjansenDatabay commented
Great @nhaagen !

Does this work on Windows machines? AFAIK @mbecker-databay still uses Windows for development ;-), and if he'd like to use the `Caiptn`, this will probably fail. 

The question is: Do we care about developers using Windows :)?

2021-08-26 10:34 UTC, nhaagen commented
Well, I think we do care, since we are nice people and all ;), and I expect Windows to be of more relevance especially when it comes to translations. I'll find somebody to check into this.

2021-08-26 11:35 UTC, nhaagen commented
I verified with @catkrahl in both git-bash and power shell: it works.

2021-11-30 14:18 UTC, mjansenDatabay requested changes
I suggest to move the script to the `CI` folder. I don't have any other objections.

But I don't know if I am the only person who decides upon changes applied to the `captainhook.json`. So maybe we should put this on a JF agenda and discuss this.

2021-11-30 15:06 UTC, matthiaskunkel commented
Thanks, @mjansenDatabay, for your review and reply. I have added this PR to the agenda of the upcoming JourFixe at Dec 13, 2021.

2021-12-01 10:19 UTC, nhaagen commented
Hey @mjansenDatabay,
I moved the script to CI, langfolder was awkward anyway.
Cheers

2021-12-01 10:34 UTC, mjansenDatabay commented on captainhook.json
> +        "action": "CI/sort_langfile_entries.sh}",
The `}` looks like a typo ;-)

2021-12-01 10:53 UTC, nhaagen commented on captainhook.json
> +        "action": "CI/sort_langfile_entries.sh}",
thank you, sure is :)

2021-12-13 12:33 UTC, matthiaskunkel commented
Jour Fixe, 13 DEC 2021 : We highly appreciate this suggestion and accept the PR for trunk and release 6 and 7.

2022-03-14 22:32 UTC, matthiaskunkel commented
Hi @nhaagen, I am bit too late with reviewing this PR. Now it has conflicts. Sorry. Can you solve them? I really would appreciate to introduce the sorting of language files.
Best, matthias

2022-03-15 08:51 UTC, nhaagen commented
Hi @matthiaskunkel , 
I resetted to trunk and applied sorting. HIt "merge" quickly :)
Cheers, Nils

2022-03-15 09:07 UTC, matthiaskunkel commented
Thanks to @nhaagen for this PR. Accepted and merged to trunk.

2022-03-15 09:07 UTC, merged