SETUP: fix 31311, increase field size for updatesteps start/finished
ILIAS-eLearning/ILIAS pull request #3611
Opened 2021-09-08 10:03 UTC by nhaagen

https://mantis.ilias.de/view.php?id=31311

2021-09-09 13:05 UTC, klees requested changes
Hi @nhaagen,

please move this to a db-update file in the new format and the according component. This should definitely be possible... (right?)

Best regards!

2021-09-10 09:55 UTC, klees approved these changes

2021-09-10 09:56 UTC, klees commented
Hi @chfsx,

this LGTM, but since this is in `Services/Database` i cannot really tell if this matches your idea of a proper organisation and naming of steps, agents, etc. in the service. Please have a look!

Thanks!

2021-09-13 05:39 UTC, merged

2021-09-13 05:39 UTC, chfsx commented
Thanks a lot!