UI: improvements for PHP 8
ILIAS-eLearning/ILIAS pull request #3616
Opened 2021-09-10 09:41 UTC by daniwe4

2021-09-10 13:07 UTC, Amstutz commented
@daniwe4 Nice work. PHP8 is definitely a blessing for ILIAS 8. I did look through it yet, but while browsing through the files I did not find the roadmap, in which probably the following could be removed since done:

### PHP 7 Typehints 

Neat!

2021-09-14 07:12 UTC, daniwe4 commented
Hi @Amstutz , 
thanks for your response. I have remove the block 'PHP 7 Typehints' from the roadmap file.

2021-09-21 13:42 UTC, klees requested changes
Hi @daniwe4,

thanks a lot for this impressive PR. The individual changes look mundane, but the sheer amount is just impressive.

There is one repeated problem (which you did not really cause!) that I want to comment on a little. I refered to it as the "`LoadingAnimation` situation" because this interface is where I first found the problem. The problem is as such: We sometimes have interfaces (such as `LoadingAnimation`) that are used as addition to other interfaces to express commonalities between different types. If these interfaces have mutator-methods `withXY` we want to express that these methods return the exact same type like the thing has that the method was called upon. Just hinting on `LoadingAnimation` as return type wouldn't be enough, because we would lose the information which type we actually used the `withXY` method after the method. This is often expressed as `@return $this` or something similar in the informal docstrings. Sadly, the possibility to express that fact was only [introduced in PHP 8](https://wiki.php.net/rfc/static_return_type), where `static` (meaning: the type of the object that method was called on) can be used as return type. So we can not use this now. In general I would expect that we will want to use `static` as return type almost always when we have mutator methods, since this return type would in fact express what we would want to say: using a mutator won't change the type of object we have. Please revert the changes in the according places and add an according entry to the roadmap that says to hint the mutators return types on `static` once PHP 7.4 is not supported anymore.

Thanks a lot!

2021-09-21 13:42 UTC, klees commented on src/UI/Component/Button/Factory.php
> +<?php declare(strict_types=1);
Could you remove the (now) uninformative `@return` in this file?

2021-09-21 13:42 UTC, klees commented on src/UI/Component/Button/LoadingAnimationOnClick.php
> +    public function withLoadingAnimationOnClick(bool $loading_animation_on_click) : LoadingAnimationOnClick;
I think this is not strong enough. This is supposed to return the same type that this methods was called on. This interface is added on another button and we would loose the information which button this has been if we typehint like this. This was the reason for the informal `@return self`.

2021-09-21 13:42 UTC, klees commented on src/UI/Component/Card/Card.php
>       * Get the image of the card
I think `getImage` is missing a typehint.

2021-09-21 13:42 UTC, klees commented on src/UI/Component/Card/Factory.php
> +<?php declare(strict_types=1);
Various `@return` and `@param` to be removed here.

2021-09-21 13:42 UTC, klees commented on src/UI/Component/Chart/Factory.php
> +<?php declare(strict_types=1);
Various docstrings to be removed here.

2021-09-21 13:42 UTC, klees commented on src/UI/Component/Chart/ProgressMeter/Factory.php
> +<?php declare(strict_types=1);
Various docstrings to be removed here.

2021-09-21 13:42 UTC, klees commented on src/UI/Component/Clickable.php
> +    public function withOnClick(Signal $signal) : Clickable;
There is a similar problem to `LoadingAnimation` here. `Clickable` is too weak, `@return self` would be correct. Same below.

2021-09-21 13:42 UTC, klees commented on src/UI/Component/Counter/Factory.php
> +<?php declare(strict_types=1);
Docstrings to be removed here.

2021-09-21 13:42 UTC, klees commented on src/UI/Component/Deck/Deck.php
> +<?php declare(strict_types=1);
Docstrings to be removed here.

2021-09-21 13:42 UTC, klees commented on src/UI/Component/Divider/Factory.php
> +<?php declare(strict_types=1);
Docstrings to be removed here.

2021-09-21 13:42 UTC, klees commented on src/UI/Component/Dropdown/Factory.php
> +<?php declare(strict_types=1);
Docstrings to be removed here.

2021-09-21 13:42 UTC, klees commented on src/UI/Component/Droppable.php
> +    public function withOnDrop(Signal $signal) : Droppable;
Same thing like "LoadingAnimation" here. This is not specific enough.

2021-09-21 13:42 UTC, klees commented on src/UI/Component/Dropzone/Factory.php
> +<?php declare(strict_types=1);
Docstrings to be removed here.

2021-09-21 13:42 UTC, klees commented on src/UI/Component/Dropzone/File/Factory.php
> +<?php declare(strict_types=1);
Docstrings to be removed here.

2021-09-21 13:42 UTC, klees commented on src/UI/Component/Hoverable.php
> +    public function withOnHover(Signal $signal) : Hoverable;
Same thing as with `LoadingAnimation` here. This is too weak.

2021-09-21 13:42 UTC, klees commented on src/UI/Component/Image/Factory.php
> +<?php declare(strict_types=1);
Various docstrings to be removed here.

2021-09-21 13:42 UTC, klees commented on src/UI/Component/Input/Container/Factory.php
> +/* Copyright (c) 2017 Timon Amstutz <timon.amstutz@ilub.unibe.ch> Extended GPL, see docs/LICENSE */
Docstrings to be removed here.

2021-09-21 13:42 UTC, klees commented on src/UI/Component/Input/Field/Factory.php
> +<?php declare(strict_types=1);
Docstrings to be removed here.

2021-09-21 13:42 UTC, klees commented on src/UI/Component/Input/ViewControl/Factory.php
> +<?php declare(strict_types=1);
Docstrings to be removed here.

2021-09-21 13:42 UTC, klees commented on src/UI/Component/Item/Factory.php
> +<?php declare(strict_types=1);
Docstrings to be removed here.

2021-09-21 13:42 UTC, klees commented on src/UI/Component/Item/Item.php
>      public function getProperties();
Typehint on `array` missing here.

2021-09-21 13:42 UTC, klees commented on src/UI/Component/JavaScriptBindable.php
> +    public function withOnLoadCode(Closure $binder) : JavaScriptBindable;
This is to weak, just like with `LoadingAnimation`.

2021-09-21 13:42 UTC, klees commented on src/UI/Component/Layout/Factory.php
> +<?php declare(strict_types=1);
Docstrings to be removed here.

2021-09-21 13:42 UTC, klees commented on src/UI/Component/Layout/Page/Factory.php
> +<?php declare(strict_types=1);
More docstrings to be removed here.

2021-09-21 13:42 UTC, klees commented on src/UI/Component/Link/Factory.php
> +<?php declare(strict_types=1);
More docstrings to be removed here.

2021-09-21 13:42 UTC, klees commented on src/UI/Component/Listing/Factory.php
> +<?php declare(strict_types=1);
Docstrings to be removed here.

2021-09-21 13:42 UTC, klees commented on src/UI/Component/Listing/Workflow/Factory.php
> +<?php declare(strict_types=1);
Docstrings to be removed here.

2021-09-21 13:42 UTC, klees commented on src/UI/Component/MainControls/Factory.php
> +<?php declare(strict_types=1);
Remove some Docstrings...

2021-09-21 13:42 UTC, klees commented on src/UI/Component/MainControls/Slate/Combined.php
>   */
I think we should be able to hint on `Slate $entry` here and remove the docstring, because a `Combined Slate` is a `Slate` as well.

2021-09-21 13:42 UTC, klees commented on src/UI/Component/Menu/Factory.php
> +use ILIAS\UI\Component\Divider;
Some docstrings to be removed here...

2021-09-21 13:42 UTC, klees commented on src/UI/Component/MessageBox/Factory.php
> +<?php declare(strict_types=1);
Some docstrings to be removed here.

2021-09-21 13:42 UTC, klees commented on src/UI/Component/Modal/Factory.php
> +<?php declare(strict_types=1);
Some docstrings to be removed here...

2021-09-21 13:42 UTC, klees commented on src/UI/Component/Modal/Modal.php
> +    public function withAsyncRenderUrl(string $url) : Modal;
I think this interface is used for other `Modal`s, so there is a similar situation like with `LoadingAnimation` here: This typehint is too weak, in fact it should be something like `static`, but I don't think this is allowed in PHP 7.4.

2021-09-21 13:42 UTC, klees commented on src/UI/Component/Modal/Modal.php
> +    public function withCloseWithKeyboard(bool $state) : Modal;
See above.

2021-09-21 13:42 UTC, klees commented on src/UI/Component/OnUpdateable.php
> +    public function withOnUpdate(Signal $signal) : OnUpdateable;
Same situation like `LoadingAnimation`...

2021-09-21 13:42 UTC, klees commented on src/UI/Component/Onloadable.php
> +    public function withOnLoad(Signal $signal) : Onloadable;
`LoadingAnimation` situation again...

2021-09-21 13:42 UTC, klees commented on src/UI/Component/Panel/Factory.php
> +<?php declare(strict_types=1);
Some docstrings to be removed here...

2021-09-21 13:42 UTC, klees commented on src/UI/Component/Panel/Listing/Factory.php
> +use ILIAS\UI\Component\Item\Group;
Some docstrings to be removed here...

2021-09-21 13:42 UTC, klees commented on src/UI/Component/Panel/Secondary/Factory.php
> +<?php declare(strict_types=1);
Some docstrings to be removed here...

2021-09-21 13:42 UTC, klees commented on src/UI/Component/Popover/Factory.php
> +<?php declare(strict_types=1);
Some docstrings to be removed here...

2021-09-21 13:42 UTC, klees commented on src/UI/Component/Symbol/Avatar/Factory.php
> -
Some docstrings to be removed here...

2021-09-21 13:42 UTC, klees commented on src/UI/Component/Symbol/Factory.php
> -     *
Some docstrings to be removed here ..

2021-09-21 13:42 UTC, klees commented on src/UI/Component/Symbol/Glyph/Factory.php
> +<?php declare(strict_types=1);
Some docstrings to be removed here ....

2021-09-21 13:42 UTC, klees commented on src/UI/Component/Symbol/Icon/Factory.php
> +
Some docstrings to be removed here...

2021-09-21 13:42 UTC, klees commented on src/UI/Component/Table/Column/Factory.php
> -     *
Some docstrings to be removed here...

2021-09-21 13:42 UTC, klees commented on src/UI/Component/Table/Factory.php
> +<?php declare(strict_types=1);
Some docstrings to be removed here...

2021-09-21 13:42 UTC, klees commented on src/UI/Component/Tree/Factory.php
> +     *     Further, levels (sub-Nodes) are indicated by an Expand Glyph
This change doesn't seem to be right. It's "Further levels" that "are indicated...".

2021-09-21 13:42 UTC, klees commented on src/UI/Component/Tree/Factory.php
> +<?php declare(strict_types=1);
Some docstrings to be removed here...

2021-09-21 13:42 UTC, klees commented on src/UI/Component/Tree/Node/Factory.php
> +<?php declare(strict_types=1);
Some docstrings to be removed here...

2021-09-21 13:42 UTC, klees commented on src/UI/Component/Triggerable.php
> +    public function withResetSignals() : Triggerable;
`LoadingAnimation` situation here again...

2021-09-21 13:42 UTC, klees commented on src/UI/Component/Triggerer.php
> +    public function withResetTriggeredSignals() : Triggerer;
`LoadingAnimation` situation again...

2021-09-21 13:42 UTC, klees commented on src/UI/Component/ViewControl/Factory.php
> +<?php declare(strict_types=1);
Some docstrings to be removed here...

2021-09-21 13:42 UTC, klees commented on src/UI/Component/ViewControl/HasViewControls.php
>      public function withViewControls(array $view_controls) : HasViewControls;
`LoadingAnimation` situation here again...

2021-09-21 13:42 UTC, klees commented on src/UI/Factory.php
> +<?php declare(strict_types=1);
Some docstrings to be removed here...

2021-09-21 13:42 UTC, klees commented on src/UI/Implementation/Component/Button/Engageable.php
> +    public function withEngagedState(bool $state) : self
This is the same problem as for `LoadingAnimation`. This is supposed to return the type of the object that this method was called on, not `Engageable` or `EngageableInterface` only.

2021-09-21 13:42 UTC, klees commented on src/UI/Implementation/Component/Button/LoadingAnimationOnClick.php
> +    public function withLoadingAnimationOnClick(bool $loading_animation_on_click = true) : self
`LoadingAnimation` problem again.

2021-09-21 13:42 UTC, klees commented on src/UI/Implementation/Component/ComponentHelper.php
> +<?php declare(strict_types=1);
Please check if we still need this `checkXY` methods after all. They should be superseeded by the typehints on `int` etc. by now. I suppose we should be able to get rid of them.

2021-09-21 13:42 UTC, klees commented on src/UI/Implementation/Component/Input/Field/Checkbox.php
> +//    use Triggerer;
Why is this uncommented?

2021-09-21 13:42 UTC, klees commented on src/UI/Implementation/Component/Input/Field/GroupHelper.php
> +    public function withGroupValues(array $values) : self
`self` is to weak, `LoadingAnimation` situation.

2021-09-21 13:42 UTC, klees commented on src/UI/Implementation/Component/Input/Field/Input.php
> +    public function withOnUpdate(Signal $signal) : C\OnUpdateable
This is to weak, `LoadingAnimation` situation.

2021-09-21 13:42 UTC, klees commented on src/UI/Implementation/Component/Input/Field/InputInternal.php
> +    public function getName() : ?string;
Why only `?string` and not `string`? As far as I remember, the implementation is supposed to return a `string` or throw. The usages of `getName` most likely will rely on that fact.

2021-09-21 13:42 UTC, klees commented on src/UI/Implementation/Component/Input/Field/Numeric.php
> +        return $this->refinery->custom()->constraint(function ($value) {
I think we should be able to just use `$refinery->to()->int()` here now, since [PR 3567](https://github.com/ILIAS-eLearning/ILIAS/pull/3567) is merged already.

2021-09-21 13:42 UTC, klees commented on src/UI/Implementation/Component/JavaScriptBindable.php
> +    public function withOnLoadCode(Closure $binder) : C\JavaScriptBindable
`LoadingAnimation` situation.

2021-09-21 13:42 UTC, klees commented on src/UI/Implementation/Component/Layout/Page/Renderer.php
> +        return "";
Please don't. Throw a `LogicException` if we receive an unkown component here.

2021-09-21 13:42 UTC, klees commented on src/UI/Implementation/Component/Link/Renderer.php
> +        return "";
Please throw a `LogicException` if we have an unknown component.

2021-09-21 13:42 UTC, klees commented on src/UI/Implementation/Component/Listing/Workflow/Renderer.php
> +        return "";
Throw `LogicException` here please.

2021-09-21 13:42 UTC, klees commented on src/UI/Implementation/Component/MainControls/Renderer.php
> +        return "";
`LogicException` here.

2021-09-21 13:42 UTC, klees commented on src/UI/Implementation/Component/Modal/LightboxTextPage.php
> +    protected string $title = '';
Initialisation as empty string is not necessary here, right?

2021-09-21 13:42 UTC, klees commented on src/UI/Implementation/Component/Panel/Secondary/Factory.php
> +    public function listing(string $title, array $item_groups) : C\Panel\Secondary\Listing
Why would this be `$item_groups` here?

2021-09-21 13:42 UTC, klees commented on src/UI/Implementation/Component/Panel/Secondary/Renderer.php
> +        return '';
Please throw `LogicException`.

2021-09-21 13:42 UTC, klees commented on src/UI/Implementation/Component/Table/Renderer.php
> +        return '';
Throw `\LogicException`.

2021-09-21 13:42 UTC, klees commented on src/UI/Implementation/Component/Tree/Node/Node.php
> +    public function withOnClick(Signal $signal) : Clickable
This is too weak. Users should and will get another `Node`.

2021-09-21 13:42 UTC, klees commented on src/UI/Implementation/Component/Triggerer.php
> +    protected function appendTriggeredSignal(C\Signal $signal, string $event) : C\Triggerer
`LoadingAnimation` situation.

2021-09-21 13:42 UTC, klees commented on src/UI/Implementation/Component/ViewControl/Renderer.php
> +        return '';
Throw `LogicException`.

2021-09-21 13:42 UTC, klees commented on src/UI/Implementation/Render/ResourceRegistry.php
> +    public function register(string $name) : void;
Why `void`? Old docstring promised `self`.

2021-09-21 13:42 UTC, klees commented on src/UI/Renderer.php
>       * @param  Component	$context
This can be removed IMO.

2021-10-04 07:22 UTC, daniwe4 commented on src/UI/Component/Button/Factory.php
> +<?php declare(strict_types=1);
At the moment the factories crawler class would quit missing return types with an error.  So before deleting the docstrings we have to adjust the crawler class. I add this to the ROADMAP.

2021-10-04 07:32 UTC, daniwe4 commented on src/UI/Component/Button/LoadingAnimationOnClick.php
> +    public function withLoadingAnimationOnClick(bool $loading_animation_on_click) : LoadingAnimationOnClick;
add self as return type

2021-10-04 07:33 UTC, daniwe4 commented on src/UI/Component/Card/Card.php
>       * Get the image of the card
add ?Image as return type

2021-10-04 07:33 UTC, daniwe4 commented on src/UI/Component/Card/Factory.php
> +<?php declare(strict_types=1);
At the moment the factories crawler class would quit missing return types with an error. So before deleting the docstrings we have to adjust the crawler class. I add this to the ROADMAP.

2021-10-04 07:33 UTC, daniwe4 commented on src/UI/Component/Chart/Factory.php
> +<?php declare(strict_types=1);
At the moment the factories crawler class would quit missing return types with an error. So before deleting the docstrings we have to adjust the crawler class. I add this to the ROADMAP.

2021-10-04 07:34 UTC, daniwe4 commented on src/UI/Component/Chart/ProgressMeter/Factory.php
> +<?php declare(strict_types=1);
At the moment the factories crawler class would quit missing return types with an error. So before deleting the docstrings we have to adjust the crawler class. I add this to the ROADMAP.

2021-10-04 08:45 UTC, daniwe4 commented on src/UI/Component/Clickable.php
> +    public function withOnClick(Signal $signal) : Clickable;
remove return type, add docstring @return static

2021-10-04 08:45 UTC, daniwe4 commented on src/UI/Component/Counter/Factory.php
> +<?php declare(strict_types=1);
At the moment the factories crawler class would quit missing return types with an error. So before deleting the docstrings we have to adjust the crawler class. I add this to the ROADMAP.

2021-10-04 08:45 UTC, daniwe4 commented on src/UI/Component/Deck/Deck.php
> +<?php declare(strict_types=1);
At the moment the factories crawler class would quit missing return types with an error. So before deleting the docstrings we have to adjust the crawler class. I add this to the ROADMAP.

2021-10-04 08:45 UTC, daniwe4 commented on src/UI/Component/Divider/Factory.php
> +<?php declare(strict_types=1);
At the moment the factories crawler class would quit missing return types with an error. So before deleting the docstrings we have to adjust the crawler class. I add this to the ROADMAP.

2021-10-04 08:46 UTC, daniwe4 commented on src/UI/Component/Dropdown/Factory.php
> +<?php declare(strict_types=1);
At the moment the factories crawler class would quit missing return types with an error. So before deleting the docstrings we have to adjust the crawler class. I add this to the ROADMAP.

2021-10-04 08:46 UTC, daniwe4 commented on src/UI/Component/Droppable.php
> +    public function withOnDrop(Signal $signal) : Droppable;
remove return type, add docstring @return static

2021-10-04 08:47 UTC, daniwe4 commented on src/UI/Component/Hoverable.php
> +    public function withOnHover(Signal $signal) : Hoverable;
remove return type, add docstring @return static

2021-10-04 08:48 UTC, daniwe4 commented on src/UI/Component/JavaScriptBindable.php
> +    public function withOnLoadCode(Closure $binder) : JavaScriptBindable;
remove return type, add docstring @return static

2021-10-04 08:48 UTC, daniwe4 commented on src/UI/Component/Dropzone/Factory.php
> +<?php declare(strict_types=1);
At the moment the factories crawler class would quit missing return types with an error. So before deleting the docstrings we have to adjust the crawler class. I add this to the ROADMAP.

2021-10-04 08:48 UTC, daniwe4 commented on src/UI/Component/Dropzone/File/Factory.php
> +<?php declare(strict_types=1);
At the moment the factories crawler class would quit missing return types with an error. So before deleting the docstrings we have to adjust the crawler class. I add this to the ROADMAP.

2021-10-04 08:49 UTC, daniwe4 commented on src/UI/Component/Image/Factory.php
> +<?php declare(strict_types=1);
At the moment the factories crawler class would quit missing return types with an error. So before deleting the docstrings we have to adjust the crawler class. I add this to the ROADMAP.

2021-10-04 08:49 UTC, daniwe4 commented on src/UI/Component/Input/Container/Factory.php
> +/* Copyright (c) 2017 Timon Amstutz <timon.amstutz@ilub.unibe.ch> Extended GPL, see docs/LICENSE */
At the moment the factories crawler class would quit missing return types with an error. So before deleting the docstrings we have to adjust the crawler class. I add this to the ROADMAP.

2021-10-04 08:49 UTC, daniwe4 commented on src/UI/Component/Input/Field/Factory.php
> +<?php declare(strict_types=1);
At the moment the factories crawler class would quit missing return types with an error. So before deleting the docstrings we have to adjust the crawler class. I add this to the ROADMAP.

2021-10-04 08:49 UTC, daniwe4 commented on src/UI/Component/Input/ViewControl/Factory.php
> +<?php declare(strict_types=1);
At the moment the factories crawler class would quit missing return types with an error. So before deleting the docstrings we have to adjust the crawler class. I add this to the ROADMAP.

2021-10-04 08:49 UTC, daniwe4 commented on src/UI/Component/Item/Factory.php
> +<?php declare(strict_types=1);
At the moment the factories crawler class would quit missing return types with an error. So before deleting the docstrings we have to adjust the crawler class. I add this to the ROADMAP.

2021-10-04 08:51 UTC, daniwe4 commented on src/UI/Component/Item/Item.php
>      public function getProperties();
add return type array

2021-10-04 08:57 UTC, daniwe4 commented on src/UI/Implementation/Component/ViewControl/Renderer.php
> +        return '';
replace return by throw statement

2021-10-04 09:02 UTC, daniwe4 commented on src/UI/Implementation/Render/ResourceRegistry.php
> +    public function register(string $name) : void;
The implementation of this method didn't return anything.

2021-10-04 10:53 UTC, daniwe4 commented on src/UI/Renderer.php
>       * @param  Component	$context
remove @param

2021-10-06 06:37 UTC, daniwe4 commented on src/UI/Component/MainControls/Slate/Combined.php
>   */
done!

2021-10-06 06:38 UTC, daniwe4 commented on src/UI/Component/Modal/Modal.php
> +    public function withAsyncRenderUrl(string $url) : Modal;
remove return type, add docstring @return static

2021-10-06 06:39 UTC, daniwe4 commented on src/UI/Component/Modal/Modal.php
> +    public function withCloseWithKeyboard(bool $state) : Modal;
remove return type, add docstring @return static

2021-10-06 06:39 UTC, daniwe4 commented on src/UI/Component/OnUpdateable.php
> +    public function withOnUpdate(Signal $signal) : OnUpdateable;
remove return type, add docstring @return static

2021-10-06 06:40 UTC, daniwe4 commented on src/UI/Component/Onloadable.php
> +    public function withOnLoad(Signal $signal) : Onloadable;
remove return type, add docstring @return static

2021-10-06 06:41 UTC, daniwe4 commented on src/UI/Component/Triggerable.php
> +    public function withResetSignals() : Triggerable;
remove return type, add docstring @return static

2021-10-06 06:41 UTC, daniwe4 commented on src/UI/Component/Triggerer.php
> +    public function withResetTriggeredSignals() : Triggerer;
remove return type, add docstring @return static

2021-10-06 06:42 UTC, daniwe4 commented on src/UI/Component/ViewControl/HasViewControls.php
>      public function withViewControls(array $view_controls) : HasViewControls;
remove return type, add docstring @return static

2021-10-06 06:43 UTC, daniwe4 commented on src/UI/Implementation/Component/Button/Engageable.php
> +    public function withEngagedState(bool $state) : self
remove return type, add docstring @return static

2021-10-06 06:44 UTC, daniwe4 commented on src/UI/Implementation/Component/Button/LoadingAnimationOnClick.php
> +    public function withLoadingAnimationOnClick(bool $loading_animation_on_click = true) : self
remove return type, add docstring @return static

2021-10-06 06:56 UTC, daniwe4 commented on src/UI/Implementation/Component/ComponentHelper.php
> +<?php declare(strict_types=1);
remove check for float and int

2021-10-06 06:57 UTC, daniwe4 commented on src/UI/Implementation/Component/Input/Field/Checkbox.php
> +//    use Triggerer;
removed it!

2021-10-06 06:59 UTC, daniwe4 commented on src/UI/Implementation/Component/Input/Field/GroupHelper.php
> +    public function withGroupValues(array $values) : self
remove return type, add docstring @return static

2021-10-06 09:06 UTC, daniwe4 commented on src/UI/Implementation/Component/Input/Field/Input.php
> +    public function withOnUpdate(Signal $signal) : C\OnUpdateable
remove return type, add docstring @return static

2021-10-06 09:13 UTC, daniwe4 commented on src/UI/Implementation/Component/Input/Field/InputInternal.php
> +    public function getName() : ?string;
My decision to append the ? depends on the class Inpu.php. See https://github.com/ILIAS-eLearning/ILIAS/blob/1836410bfa2bb66b19803cf71188c7486ae4a75a/src/UI/Implementation/Component/Input/Field/Input.php#L68

2021-10-06 09:16 UTC, daniwe4 commented on src/UI/Implementation/Component/Input/Field/Numeric.php
> +        return $this->refinery->custom()->constraint(function ($value) {
protected function getConstraintForRequirement() : ?Constraint
    {
        return $this->refinery->to()->int();
    }

2021-10-06 09:19 UTC, daniwe4 commented on src/UI/Implementation/Component/Layout/Page/Renderer.php
> +        return "";
throw new LogicException("Cannot render: " . get_class($component));

2021-10-06 09:20 UTC, daniwe4 commented on src/UI/Implementation/Component/Link/Renderer.php
> +        return "";
throw new LogicException("Cannot render: " . get_class($component));

2021-10-06 09:20 UTC, daniwe4 commented on src/UI/Implementation/Component/Listing/Workflow/Renderer.php
> +        return "";
throw new LogicException("Cannot render: " . get_class($component));

2021-10-06 09:21 UTC, daniwe4 commented on src/UI/Implementation/Component/MainControls/Renderer.php
> +        return "";
throw new LogicException("Cannot render: " . get_class($component));

2021-10-06 09:23 UTC, daniwe4 commented on src/UI/Implementation/Component/Panel/Secondary/Renderer.php
> +        return '';
throw new LogicException("Cannot render: " . get_class($component));

2021-10-06 09:23 UTC, daniwe4 commented on src/UI/Implementation/Component/Table/Renderer.php
> +        return '';
throw new LogicException("Cannot render: " . get_class($component));

2021-10-06 09:25 UTC, daniwe4 commented on src/UI/Implementation/Component/Modal/LightboxTextPage.php
> +    protected string $title = '';
remove the initialisation

2021-10-18 11:22 UTC, klees approved these changes

2021-10-18 11:24 UTC, klees commented
@daniwe4 Please rebase again. Thx!

2021-10-18 11:25 UTC, klees commented
Hi @Amstutz,

I did it, I manage to look through this, mostly. LGTM after @daniwe4's improvements. Please have another look, if possible, and maybe hit the merge button afterwards.

Best regards

2021-11-02 14:40 UTC, Amstutz commented
Thx a lot @daniwe4 for this huge contribution. LGTM. I found some minor issues in the examples, that have not been caught by the test, since they have to do with globals such as $_GET. We need to $_GET completely out of the examples. However, this should not delay this merge here any further. This merge is important since, it will level up an important part of ILIAS on which many other parts really. Ill provide a quick fix for the few cases right after the merge.

2021-11-02 14:40 UTC, merged