UI/ViewControl: add possibility of return value null to Pagination::getRange
ILIAS-eLearning/ILIAS pull request #3663
Opened 2021-09-28 12:52 UTC by lukastocker

Now Pagination::getRange can return null as value. Thus a user can react appropriate if the list is empty.

2021-10-04 14:29 UTC, Amstutz requested changes
Hi @lukastocker 

Makes sense, thx for the proposal. 

- [ ] One small addition, can you provide a small unit test, making sure, that getRange returns null and not causes any errors in case getPageLength < 1?

Thx.

2021-10-04 14:46 UTC, lukastocker commented
> Hi @lukastocker
> 
> Makes sense, thx for the proposal.
> 
>     * [ ]  One small addition, can you provide a small unit test, making sure, that getRange returns null and not causes any errors in case getPageLength < 1?
> 
> 
> Thx.

Hi @Amstutz,

glad to hear that. 
Sure, I can do that and will update this PR as soon as possible.

2021-10-19 07:06 UTC, lukastocker commented
Hi @Amstutz ,
I just pushed the test to this PR. 

Kind regards
Luka Stocker

2021-11-02 10:41 UTC, Amstutz commented
Thx a lot! Sry for the merge delay!

2021-11-02 10:41 UTC, merged