D&D Fileupload
ILIAS-eLearning/ILIAS pull request #3712
Opened 2021-10-18 22:40 UTC by thibsy

This pull request introduces a new sort of Kitchensink inputs, described by the interface `AdditionalInputsAware`.

An `AdditionalInputsAware`-input is able to be provided with any other sort of `Input`, which serves as a template for subordinate inputs generated by this input. Subordinate in this context means, that the template is used to generate additional-inputs when `AdditionalInputsAware::withValue()` or `AdditionalInputsAware::withInput()` is called. Sort of like the `Group`-input, the input holds a list of subordinate Inputs - with the difference, that they can also be generated from client-side as well. For this reason a new `SubordinateNameSource` was introduced, that generates inputs stacked to an already existing one. So for example, an input name could look like `form_input_1[{INDEX}][sub_input_1]`, whereas `{INDEX}` stands for a placeholder that needs to be set when rendering subordinate Inputs on both, client- and server-side. This leads to POST results structured like this: 
```
array(
    'form_input_1 => [
        0 => [
            'sub_input_1' => value,
             ...
        ],
    ],
);
```
Now this means that subordinate inputs can be generated on client-side and they are stacked on the parent Input.

The use-case of client-side generated Inputs came along with the feature-request of refactoring the D&D dropzones and Module/File classes, where `File`-inputs must be able to hold further information about a file that has been uploaded from the computer, for example new title and additional description or whether it should be extracted or not etc. 

When implementing this I stumbled across several points where Kitchensink would be very limited to allow that sort of use-case, so I had to "patch things up a bit". I have commented below what code-snippets I mean with that.

2021-10-19 10:47 UTC, chfsx commented
@thibsy if possible I would suggest to separate the changes in UI Inputs from the needed changes in the fileupload/fileobject to have a sleeker overview of the changes needed in UI-Inputs

2021-10-19 12:14 UTC, thibsy commented on src/UI/Implementation/Component/Input/Field/File.php
>      public function __construct(
Instead of providing an input-template by `withTemplateForAdditionalInputs()`, it should be passed in the constructor, otherwise `withValue()` depends on whether the method is called or not. That was the same reason for creating the file-inputs zip-options already in the constructor, so if both, template and zip-options are enabled the options can be merged with the template. Passing the template to the constructor would solve that problematic agreed?

2021-10-19 12:23 UTC, thibsy commented on src/UI/Implementation/Component/Input/Field/File.php
> +                $values[$file_id][] = $file_info;
`File::getValue()` consists of a mixture of integer and string array-key-indexes, because if a `Group` input was provided as a template, the input's array might be associative. The `File`-inputs zip-options can certainly not be, because then they might collide with other keys when merging them into the template-group (`File::mergeInputWithZipOptions()`). Therefore the actual file-info is now appended with the `[]` operator.

2021-10-19 13:00 UTC, thibsy commented on src/UI/Implementation/Component/Input/Field/File.php
> +                $template = $template->withInput(new ArrayInputData($data));
I needed to introduce a new sort of `InputData`, because the client-side generated input names are now split up into an array mapped to the parent input. Therefore I had to "rebuild" their original name and map their values to it in a separate array, which I then passed along the newly introduced `ArrayInputData`-object. This way it was possible to delegate the handling of operations and validation to the inputs themselves.

2021-11-05 15:30 UTC, klees requested changes
Hi @thibsy,

thanks for improving the implementation of the file input capabilities of the ILIAS UI framework. Please note that this is only a review from me, not from @Amstutz and me as we mostly do for PRs to the UI framework.

I am a little sorry that it took me so long, but this is a lot to digest. Maybe we could make faster progress if we would concentrate on the `AdditionalFormInputAware`-part first and move it to a single PR.

Feel free to contact me for another discussion, as always. I hope this helps.

Please answer the following questions:
- [ ] FileDropzone::getData: What is it that we will return on this method? Could we hint on (or at least document) something better than just `array`?
- [ ] FileDropzone::withUploadButton: Are we sure we can remove this? As far as I remember, this was introduced to customize the appearance and title of the button. Did we get rid of the use cases?
- [ ] SubordinateNameSource: Why do we need this [const](https://github.com/ILIAS-eLearning/ILIAS/pull/3712/files#diff-8fa5adc903b33bfeb00464fa82427a909c114077aac9a3ba4f1a41ddcd3de9f2R17) if it is always the same? Couldn't we just drop this level in the nested array?
- [ ] Selectors: Do we really need that much selectors in the JS? This will make the connection between the template and the js code brittle. Could we use selectors that are distinct from the selectors that we use for styling to introduce some separation of concerns here?
- [ ] JavaScript 1: Would this JS work for multiple inputs on the same page?
- [ ] A11y: Did you do any accessibilitiy assessment with the new implementation? If so: What was the outcome?
- [ ] FormInput: Why did you remove the `extends FormInput` on `Input\Field\File`?
- [ ] UploadHandler::getInfoResults: Why do we need that new method?
- [ ] Required: Will it really be correct to assume, that sub inputs are required if the parent is required (see [here](https://github.com/ILIAS-eLearning/ILIAS/pull/3712/files#diff-ecc5cce787348f8b383528c542fba119f75a5fca27d9b3ba14495f1de4a819deR74)). This feels wrong. This seems to be correct for disabled inputs, though.
- [ ] Sub Content 1: Nothing seems to happen if sub content of a `AdditionalFormInputAwareInput` [is not ok](https://github.com/ILIAS-eLearning/ILIAS/pull/3712/files#diff-ecc5cce787348f8b383528c542fba119f75a5fca27d9b3ba14495f1de4a819deR136). Is this correct?
- [ ] Sub Content 2: [This](https://github.com/ILIAS-eLearning/ILIAS/pull/3712/files#diff-ecc5cce787348f8b383528c542fba119f75a5fca27d9b3ba14495f1de4a819deR138) looks as if you unwrap sub content in an array. Why would we want to do this? Can't we keep it wrapped in that array? This feels like a surprising special case for fields that return an array.
- [ ] Sub Content 3: Do we really need to allow `null` for [`AdditionalFormInputAwareInput::$additional_inputs`](https://github.com/ILIAS-eLearning/ILIAS/pull/3712/files#diff-ecc5cce787348f8b383528c542fba119f75a5fca27d9b3ba14495f1de4a819deR35)? Using an empty array instead would make the code simpler [here](https://github.com/ILIAS-eLearning/ILIAS/pull/3712/files#diff-ecc5cce787348f8b383528c542fba119f75a5fca27d9b3ba14495f1de4a819deR188). 


Please consider the following suggestions. You do not need to follow those, but but please indicate shortly why you prefer to do otherwise:
- [ ] File(Dropzone): Why did you rename `Dropzone/File/File` to `Dropzone/File/FileDropzone` (hence, repeating the Dropzone)? Stick to the existing name...
- [ ] Removed Constructors: Why did you remove `Field\Factory::url` and `::link` from the factory of the input fields? Just an oversight, I guess?
- [ ] Checkbox::withValue: I think the change there is problematic. The `$value` should strictly be `bool` there, not anything else. Why did you remove this?
- [ ] WTF: is [this](https://github.com/ILIAS-eLearning/ILIAS/pull/3712/files#diff-11283614eb1a80aab33a9d2c520f66aa468f09f15caa5ee7518123e2091df16fR18)?!? =D
- [ ] Static: Please don't use [`static`](https://github.com/ILIAS-eLearning/ILIAS/pull/3712/files#diff-f8dba1dd818b533395780a15f6d1243674aaac83caa54a7bdd826b3b4b39ae70R15). Inject dependencies instead (see "DI" below).
- [ ] Rendering 0: Please try to modularize the rendering code a little by introducing methods. The code is extremely hard to read like this...
- [ ] Rendering 1: I think the file input won't show a disabled version. At least I don't understand how this would actually happen =)
- [ ] Rendering 2: There is HTML in the `Renderer` which should be moved to the respective template. I would expect that the code will look cleaner afterwards as well.
- [ ] Javascript 2: It looks as if we could get rid of jquery and just use standard browser APIs. Please have a look into this.
- [ ] Responsiveness/Bootstrap: Only judging from the code it looks as if the responsiveness of the new implementation is worse than before, because the Bootstrap grid classes are used and we will likely see grid in grid effects somewhere. Also, we are looking to get rid of Bootstraps. So I would rather like you to remove the grid and Bootstrap classes and move to another HTML structure. Feel free to ask for support again (if you need any) for appropriate style code.
- [ ] Template: Why do we need that doubly wrapped div in `tpl.wrapper.html`? Could we get away with one div to get a little more semantic html?
- [ ] Naming: Would `HasDynamicSubFields` be a name that would be also correct for `AdditionalFormInputAware`? I deem this to be understandable more easily.
- [ ] Inheritance: Could we use something else then a base class to implement `AdditionalFormInputAware(Input)`? Preferably a standalone object that could be used by an Input Field that `HasDynamicSubFields`. If that feels odd, maybe a trait would do. Only if these two are not feasible we should use the current subclassing approach. The `use composition over inheritance` rule of thumb is especially strong in PHP, where we only can have one base class. The Input Fields (and the UI components in general) are things where we very likely will have various properties like `HasDynamicSubFields` on one component and we will not be able to implement them all via inheritance. Hence `interface`s for declaring the properties (we can have multiple there) and composition for implementing them.
- [ ] Null Object: Maybe the problem you mention in your comment ("Instead of providing an input-template by withTemplateForAdditionalInputs(), [...]") could be solved by introducing a [null object](https://www.tutorialspoint.com/design_pattern/null_object_pattern.htm) for an Input Field. This should make your code in [`AdditionalFormInputAwareInput::withInput`](https://github.com/ILIAS-eLearning/ILIAS/pull/3712/files#diff-ecc5cce787348f8b383528c542fba119f75a5fca27d9b3ba14495f1de4a819deR115) simpler and would come in handy in various other cases as well (not related to this PR).
- [ ] Merge Inputs: [`File::mergeInputWithZipOptions`](https://github.com/ILIAS-eLearning/ILIAS/pull/3712/files#diff-11283614eb1a80aab33a9d2c520f66aa468f09f15caa5ee7518123e2091df16fR428) seems to be overly complicated. Can't we just wrap the two inputs in a group and use that? If you would just pass this new group on to `parent::withTemplateForAdditionalInputs` in `File::withTemplateForAdditionalInputs`, the code in `File::withValue` should become considerably simpler.
- [ ] Data Structures: It looks as if some more datastrucutures could make your code simple. E.g.: Introduce a `ZipOption` class that bundles your zip options. You won't confuse them with other fields from the additional inputs anymore. Or: Build a structure `FileResult` that has the fields `$file_info`, `$zip_options` and `$additional_info`. You won't be confusing array keys anymore. This is mostly a reaction to [this comment](https://github.com/ILIAS-eLearning/ILIAS/pull/3712/files#r731807157), but also an idea for some intricate array-merging code snippets. 


Please implement the following changes:
- [ ] Docstrings: Remove `@package` and  [...]

2021-11-05 15:40 UTC, Amstutz commented
Just a minor additon: 

- [ ] Unit Tests: I am somewhat skeptical that the 27 lines changed in the tests really reflect the changes of the implementation. Please try to cover all changes. 

Just a note, as  of today, we do not strictly require js tests. But this might change soon, see: https://github.com/ILIAS-eLearning/ILIAS/pull/3685 . You do not have to, but some js tests would be nice as well.

2021-12-21 16:31 UTC, closed without merging