19929 use plugin lang if local role is created by plugin
ILIAS-eLearning/ILIAS pull request #373
Opened 2016-12-05 12:46 UTC by shecken

2016-12-05 13:12 UTC, lechimp-p requested changes
LGTM in general, minor renaming, thx for refactoring.

2016-12-05 13:12 UTC, lechimp-p commented on Services/AccessControl/classes/class.ilObjRole.php
> +	public static function _removeObjectId($a_role_title) {
`private` plz.

2016-12-05 13:12 UTC, lechimp-p commented on Services/AccessControl/classes/class.ilObjRole.php
> +		$test_str = explode('_',$a_role_title);
Why `$test_str`? To me this name is misleading. Nice refactoring, though.

2016-12-05 13:14 UTC, shecken commented on Services/AccessControl/classes/class.ilObjRole.php
> +	public static function _removeObjectId($a_role_title) {
I need this public because of use in ilObjectRolePermissionTableGUI.php line 685.

2017-05-10 12:17 UTC, chfsx commented
@smeyer-ilias could you please have a look at this PR? Thanks

2017-06-28 06:17 UTC, klees commented
Hi @smeyer-ilias,
any chance that this will be merged some time?
Regards!

2017-09-26 12:14 UTC, chfsx commented
TB: We will discuss this PR during next JF

2017-10-06 11:37 UTC, merged

2017-10-06 11:38 UTC, smeyer-ilias commented
Thanks, for providing a bugfix.