Refinery: add new method for 'less than or equal' integer inputs. Add…
ILIAS-eLearning/ILIAS pull request #3823
Opened 2021-12-08 09:19 UTC by lukastocker

… a new test and language variable for error message.

2021-12-08 09:53 UTC, klees approved these changes
LGTM in general, 2 minor change requests.

@mjansenDatabay Would you please review as well and, in case, press the button? Thx!

2021-12-08 09:53 UTC, klees commented on src/Refinery/Integer/Group.php
> +     * @return LessThanOrEqual
Docstrings can be removed if the typehint give as much information.

2021-12-08 09:53 UTC, klees commented on src/Refinery/Integer/LessThanOrEqual.php
> +    protected $max;
```suggestion
    protected int $max;
```
... and remove docstrings. Yay, PHP 7.4.

2021-12-08 11:04 UTC, mjansenDatabay requested changes
Thx @lukastocker again for a new `Refinery` transformation.

I don't have anything to add. Please change the findings @klees mentioned. IMO this is ready to merge afterwards.

2021-12-08 11:15 UTC, lukastocker commented
Hi @mjansenDatabay and @klees ,

thanks for your quick reviews. I just implemented and pushed the changes.
As for the redundant docstrings in the Group.php file: I also removed the docstring for "isGreaterThan", "isLessThan" and "isGreaterThanOrEqual" to standardize the coding style.

Kind regards
Luka

2021-12-08 11:25 UTC, mjansenDatabay commented
Thanks a lot @lukastocker , I just started a "Streamlining Removal of PHPDocs Feature Branch" ;).

2021-12-08 11:42 UTC, mjansenDatabay requested changes
@lukastocker Could you please add the return types/type hints for the functions (where appropriate) in THIS contraint impl.? I'll merge this PR aftwards.

2021-12-08 11:42 UTC, mjansenDatabay commented on src/Refinery/Integer/LessThanOrEqual.php
> +            function ($value) {
Maybe we could add a return type declaration here. I guess this could also be streamlined for other constraints.

2021-12-08 11:42 UTC, mjansenDatabay commented on src/Refinery/Integer/LessThanOrEqual.php
> +            function ($txt, $value) {
Maybe we could add a return type declaration here (and a type hint for $txt). I guess this could also be streamlined for other constraints.

2021-12-15 08:05 UTC, lukastocker commented
Hi @mjansenDatabay,

the typehints are implemented. 
For the other constraints I will open a new PR with a appropriate title/description.

Kind regards,
Luka Stocker

2021-12-15 08:34 UTC, mjansenDatabay commented
> For the other constraints I will open a new PR with a appropriate title/description.

Wow, thanks a lot @lukastocker !

2021-12-15 08:34 UTC, mjansenDatabay approved these changes

2021-12-15 08:34 UTC, merged