fix contraint for numeric inputs
ILIAS-eLearning/ILIAS pull request #3850
Opened 2021-12-16 16:01 UTC by iszmais

The constraint to check the given request value from numeric input checks falsefully if those are int.
It should check if those are numerics (including numeric strings).

2021-12-17 07:15 UTC, klees requested changes
Hi @iszmais,

thanks a lot for taking care. There currently is no test covering this, right? Would you be so kind and add a regression test for the problem?

Best regards!

2021-12-17 10:47 UTC, iszmais commented
Hi @klees thx for the feedback.

Unfortunatly I wont be able to provide test for that this year.

2022-01-24 14:54 UTC, Amstutz commented
would be highly appreciated, still need the test though. Can we assist in some way with this?

2022-01-24 15:24 UTC, iszmais commented
Hi @Amstutz ,

with not more or less than time :D
I guess i will be able to look into it mid february. feel free to take my solution attempt for an own PR if you want that ASAP.

Greetings,
@iszmais

2022-01-29 09:29 UTC, closed without merging

2022-01-29 09:32 UTC, Amstutz commented
Hi @iszmais 

Thx again. I just pushed your change along with a test, see: https://github.com/ILIAS-eLearning/ILIAS/commit/daa3963e1d78b1561db615f199a6b702c7eb4c8c

Note to however might be interested: We implicitly did cast float to int if no "required" was set. When required, this failed in the required constraint. Now it passes, so its more inline with the default behavior.