Setup: move dbupdate_3560 to objectives
ILIAS-eLearning/ILIAS pull request #3925
Opened 2022-01-20 13:50 UTC by daniwe4

2022-01-25 15:02 UTC, klees requested changes
Hi @daniwe4,

I have various suggestions for improvements:

* [x] Label: Tell the admin, which operations have been added, modified, etc. in various `getLabel`-methods. [Here](https://github.com/ILIAS-eLearning/ILIAS/pull/3925/files#diff-58b2b389267d257daf6c10cfbf37bd0ca64d651f1b868b59606acc5fbf9df659R35), [here](https://github.com/ILIAS-eLearning/ILIAS/pull/3925/files#diff-f0d914afffc66fe78817adacb0bb9474801fba82ebea3d2ec986ac778b375a2fR46), [here](https://github.com/ILIAS-eLearning/ILIAS/pull/3925/files#diff-b2625c8f730ba310db766b65534ff3b88609d84dcab12303bf0a1f3dc2a0f22bR30), [here](https://github.com/ILIAS-eLearning/ILIAS/pull/3925/files#diff-78b38727a3687cca7ef6a469dfa58681daab53522d80769bd4328d8eeda5fa8fR32), [here](https://github.com/ILIAS-eLearning/ILIAS/pull/3925/files#diff-5e1717e0a6f15e8fb746ef9e22f23813322975a2017fa71e10188e33bb2354d6R38).
* [ ] Migration: Please remove the migration file. Everything is in a new place now, right?
* [x] Naming: [ilObject::_getObjectIdByTitle](https://github.com/ILIAS-eLearning/ILIAS/pull/3925/files#diff-ff9d6240be485dd464c16fdaab28206db2450556800ef6c171c04631675836b9R2305) deserves a better naming. This should be `_getObjectTypeIdByTitle` AFAIC.
* [ ] Description: Please add one in the PR. What is changed by this and why?

Please change, I'll pass this on to @smeyer-ilias afterwards.

Best regards!

2022-01-28 08:50 UTC, daniwe4 commented
Hi @klees,
thanks for your suggestions. I think we can tick everything except that the migration files cannot be deleted yet. The functions contained are still used in DB update steps that are not yet recorded by the template.

2022-01-28 08:56 UTC, klees commented
Hi @smeyer-ilias,

as maintainer of RBAC I ask you to include this code into your component. Feel free to ask me here or via any other channel about the specifics.

Best regards!

2022-03-02 10:09 UTC, oliversamoila commented
Hi @smeyer-ilias and @klees .
Anything new here ?

2022-03-02 11:27 UTC, klees commented
@smeyer-ilias: Is there anything I may or should do here atm? Anything I can help you with?

2022-04-08 13:26 UTC, oliversamoila commented
Hey @smeyer-ilias 
das Abschließen des Refactorings der Komponente services_Migration hängt nach meinem Wissen nur noch hinter diesem PR. Damit hängt auch das Review hinten an. 
Bitte melde dich dazu.
Viele Grüße
Oliver

2022-04-08 16:58 UTC, mjansenDatabay commented
@daniwe4 In the meantime there is a new database update step in our code base using the deprecated method: `\ilTreeAdminNodeAddedObjective::step_1`

Option 1) Rebase on `trunk` and change the method call
Option 2) Merge and contact @iszmais afterwards, pointing to this PR

2022-04-12 08:01 UTC, smeyer-ilias requested changes
Thanks for working on this. 
There are some PHP 8 related issues.

2022-04-12 08:01 UTC, smeyer-ilias commented on Services/AccessControl/classes/Setup/class.ilAccessCustomRBACOperationAddedObjective.php
> +                    'create_date' => ['timestamp', ilUtil::now()],
Please remove this dependency to ilUtil.

2022-04-12 08:01 UTC, smeyer-ilias commented on Services/AccessControl/classes/Setup/class.ilAccessInitialPermissionGuidelineAppliedObjective.php
> +    const RBAC_OP_COPY = 99;
Please add access modifiers.

2022-04-12 08:01 UTC, smeyer-ilias commented on Services/AccessControl/classes/Setup/class.ilAccessRBACOperationClonedObjective.php
> +            ."JOIN object_data od ON (od.obj_id = ref.obj_id AND od.type = " . $db->quote($this->type) . ")" . PHP_EOL
The second parameter for quote is missing

2022-04-12 08:01 UTC, smeyer-ilias commented on Services/AccessControl/classes/Setup/class.ilAccessRBACOperationClonedObjective.php
> +            ."OR ops_id = " . $db->quote($this->dest_id) . ")" . PHP_EOL
Missing quote parameter

2022-04-12 08:01 UTC, smeyer-ilias commented on Services/AccessControl/classes/Setup/class.ilAccessRBACOperationsAddedObjective.php
> +    const RBAC_OP_COPY = 99;
Please add access modifiers.

2022-04-12 08:01 UTC, smeyer-ilias commented on Services/AccessControl/classes/Setup/class.ilAccessRolePermissionSetObjective.php
> +    const RBAC_OP_COPY = 99;
Please add access modifier

2022-04-12 08:01 UTC, smeyer-ilias commented on Services/AccessControl/classes/class.ilRbacReview.php
> +        return (int) $row["ops_id"] ?? null;
This creates a warning if $row['ops_id'] is not set

2022-04-12 08:01 UTC, smeyer-ilias commented on Services/Object/classes/class.ilObject.php
> +        return (int) $row['obj_id'] ?? null;
This creates a warning if $row['obj_id'] is not set

2022-04-12 08:01 UTC, smeyer-ilias commented on Services/Tree/classes/Setup/class.ilTreeAdminNodeAddedObjective.php
> +    const RBAC_OP_WRITE = 4;
Please add access modifiers.

2022-04-12 10:12 UTC, daniwe4 commented on Services/AccessControl/classes/Setup/class.ilAccessCustomRBACOperationAddedObjective.php
> +                    'create_date' => ['timestamp', ilUtil::now()],
done

2022-04-12 10:14 UTC, daniwe4 commented on Services/AccessControl/classes/Setup/class.ilAccessInitialPermissionGuidelineAppliedObjective.php
> +    const RBAC_OP_COPY = 99;
done

2022-04-12 10:27 UTC, daniwe4 commented on Services/AccessControl/classes/Setup/class.ilAccessRBACOperationClonedObjective.php
> +            ."JOIN object_data od ON (od.obj_id = ref.obj_id AND od.type = " . $db->quote($this->type) . ")" . PHP_EOL
done

2022-04-12 10:27 UTC, daniwe4 commented on Services/AccessControl/classes/Setup/class.ilAccessRBACOperationClonedObjective.php
> +            ."OR ops_id = " . $db->quote($this->dest_id) . ")" . PHP_EOL
done

2022-04-12 10:28 UTC, daniwe4 commented on Services/AccessControl/classes/Setup/class.ilAccessRBACOperationsAddedObjective.php
> +    const RBAC_OP_COPY = 99;
done

2022-04-12 10:29 UTC, daniwe4 commented on Services/AccessControl/classes/Setup/class.ilAccessRolePermissionSetObjective.php
> +    const RBAC_OP_COPY = 99;
done

2022-04-12 10:36 UTC, daniwe4 commented on Services/AccessControl/classes/class.ilRbacReview.php
> +        return (int) $row["ops_id"] ?? null;
done

2022-04-12 10:37 UTC, daniwe4 commented on Services/Object/classes/class.ilObject.php
> +        return (int) $row['obj_id'] ?? null;
done

2022-04-12 10:38 UTC, daniwe4 commented on Services/Tree/classes/Setup/class.ilTreeAdminNodeAddedObjective.php
> +    const RBAC_OP_WRITE = 4;
done

2022-04-12 10:44 UTC, daniwe4 commented
Hi @smeyer-ilias ,
thank you for your valuable hints. I hopefully fixed them all.

2022-04-13 12:11 UTC, smeyer-ilias requested changes
Thanks for fixing.

2022-04-13 12:11 UTC, smeyer-ilias commented on Services/AccessControl/classes/class.ilRbacReview.php
> +        return (int) $row["ops_id"] ?? null;
Hm, I don't see any changes:
return isset($row["ops_id"]) ? (int) $row['ops_id'] : null;

should fix the php8 warning.

2022-04-13 12:11 UTC, smeyer-ilias commented on Services/Object/classes/class.ilObject.php
> +        return (int) $row['obj_id'] ?? null;
return isset($row["obj_id"]) ? (int) $row['obj_id'] : null;

should fix the php8 warning.

2022-04-13 12:47 UTC, daniwe4 commented on Services/AccessControl/classes/class.ilRbacReview.php
> +        return (int) $row["ops_id"] ?? null;
Hi @smeyer-ilias ,
the fix is a few lines up:
`$res = $ilDB->query($sql);
        if ($ilDB->numRows($res) == 0) {
            return null;
        }`

2022-04-13 12:48 UTC, daniwe4 commented on Services/Object/classes/class.ilObject.php
> +        return (int) $row['obj_id'] ?? null;
Hi @smeyer-ilias ,
the fix is a few lines up:
`$res = $ilDB->query($sql);
        if ($ilDB->numRows($res) == 0) {
            return null;
        }`

2022-04-13 12:56 UTC, smeyer-ilias approved these changes
Ok, thanks for the explanation.

2022-04-13 12:56 UTC, merged

2022-04-14 17:58 UTC, mjansenDatabay commented
I created a new PR which makes already use of the new 'ilTreeAdminNodeAddedObjective' objective: #4366

2022-04-21 08:55 UTC, thibsy commented on Services/Migration/DBUpdate_3560/classes/class.ilDBUpdateNewObjectType.php
> -    public static function addRBACTemplate($a_obj_type, $a_id, $a_description, $a_op_ids)
This leads to several errors in dbupdate_04.php, see https://mantis.ilias.de/view.php?id=32461