5 2 report panel headings
ILIAS-eLearning/ILIAS pull request #397
Opened 2016-12-28 16:05 UTC by alex40724

2016-12-28 16:11 UTC, alex40724 commented
I am unsure how we want to provide a consistent heading structure in the new UI framework. The current panel > sub panel > card structure resulted in a h3 > h3 > h2 hierarchy which is clearly a bug to me. I changed it to h3 > h4 > h5. I think for the panels this is ok in general. The cards now use a h5, which might result in missing heading levels in other contexts, e.g. h3 > h5. But I think this is less problematic than using the same or even higher heading numbers for substructures.

2016-12-28 16:16 UTC, alex40724 commented
See also http://www.ilias.de/mantis/view.php?id=19420

2016-12-28 16:25 UTC, Amstutz approved these changes
I checked the Deck of Cards that I have in use with the proposed changes. Looks good to me.

Regarding headings: Do we have a strict rule, not to leave out headings? If not, would you recommend to introduce one? If so, we might think of not using hX in components like cards, that could be used in potentially different levels of hierarchy. Wie could e.g. just use il-card-title or similar.

2016-12-28 16:25 UTC, Amstutz commented on src/UI/templates/default/Panel/tpl.report.html
> +<div class="panel panel-primary il-panel-report">
Thanks for adding il-panel-report. IMHO, this is exactly how we should use CSS classes. il-[name-of-family]-[name-of-component] on top level and all CSS followed from there. Nice.

2016-12-29 08:16 UTC, Amstutz requested changes
Attention the Unit tests are currently failing due to the DOM changes made. Please fix.

I fixed them locally, but can not push it to you repo due to permission restrictions. You can merge them from here: https://github.com/Amstutz/ILIAS/tree/5_2_report_panel_headings

2017-01-07 17:49 UTC, merged

2017-01-07 17:53 UTC, alex40724 commented
@Amstutz Thanks for the test fixes.