Certificate: Add PRIVACY.md
ILIAS-eLearning/ILIAS pull request #3984
Opened 2022-02-01 08:44 UTC by mjansenDatabay

2022-02-08 10:22 UTC, atoedt commented on Services/Certificate/PRIVACY.md
> +- The `Certificate Service` can be enabled in the global administration. If enabled, certificate templates can be
An account with "Edit Settings" permissions Administration > Achiervements > Certificates > Settings can enable the Certificate Service globally.

2022-02-24 11:08 UTC, atoedt requested changes

2022-02-24 11:08 UTC, atoedt commented on Services/Certificate/PRIVACY.md
> +  for the particular object in the repository.
- If the Certifcate Service globally activated then the object types 
      - Course
      - StudyProgramme
      - Exercise
      - Test
      - ScormAicc
      - CmiXapi
      - LTIConsumer
feature an additional subtab "Certificate" in the "Settings-Tab. 
- Account with the permission "Edit Settings" for these particular objects can configure and activate Certifcates.

2022-02-24 11:08 UTC, atoedt commented on Services/Certificate/PRIVACY.md
> +  for the particular object in the repository.
löschen

2022-02-24 11:08 UTC, atoedt commented on Services/Certificate/PRIVACY.md
> +- For each issued persisting user certificate the ID of the user account is stored
For each issued persisting user certificate, the User ID of the user account is stored. The purpose of this ID being stored is the identification of the certificate to presented to or exported by the respective owner of certificate. 
- In addition, certificate template may contain placeholders. 
- All placeholders defined in a certificate template will be replaced by the corresponding user data and contextual data i.e., course title or issuing date. 
- The issuing of certificate and thus replacing place holder with user data is triggered by User completes object. 
- The actual replacing of place holders is down by processing a queue. The queue holds User ID along with the object related data and a datetime information. Once a queue item has been processed, the record will be deleted.
- The issued certificates are immutable: They contain the user data that replaced the place holders at the moment of issuing. It will not change with time.

2022-02-24 11:08 UTC, atoedt commented on Services/Certificate/PRIVACY.md
> +  string.
Löschen von For Each ... a JSON  string.

2022-02-24 11:08 UTC, atoedt commented on Services/Certificate/PRIVACY.md
> +      - User Defined Fields (if avaiable and enabled for `Certificate` in field definition)
for "Certificate"

2022-02-24 11:08 UTC, atoedt commented on Services/Certificate/PRIVACY.md
> +      - User Defined Fields (if avaiable and enabled for `Certificate` in field definition)
Link to Advanced Metadata Service once the respective md. is available

2022-02-24 11:08 UTC, atoedt commented on Services/Certificate/PRIVACY.md
> +- There might be other user related data stored depending on specific placeholders of the respective consumer. Consumers
Löschen There might be othe .... datetime information.

2022-02-24 11:08 UTC, atoedt commented on Services/Certificate/PRIVACY.md
> +  when the PDF documents are requested depend on the specific consumer. Please check the privacy documentation
löschen von The certificate service ...depend on the specific consumer.

2022-02-24 11:08 UTC, atoedt commented on Services/Certificate/PRIVACY.md
> +- The certificate service itself provides a `Deck of Card` user interface listing all achieved certificates for the acting
- The Certificate Service presents the certificate and the respective personal data only to the owner of the issued certificates at Achievements > Certificates. Owners can download a PDF of their certificate. 
- Certificates are also presented to their owner in Achievements > Learning History, if activated.

2022-02-24 11:08 UTC, atoedt commented on Services/Certificate/PRIVACY.md
> +  when the PDF documents are requested depend on the specific consumer. Please check the privacy documentation
Certificates may be presented to other accounts in the object types listed above. Please refer to the respective privacy.md of those object types to see presentation of certificate data in that very object type. For expample the course object presents Certificate Download links in the Member tab to accounts with "Manage Member" permission.

2022-02-24 11:08 UTC, atoedt commented on Services/Certificate/PRIVACY.md
> +- If a user account is removed from system, all it's user certificates will be completely deleted from
If a user account is deleted, all it's certificates will be completely deleted from the database. There is no trash for users.

2022-02-24 11:08 UTC, atoedt commented on Services/Certificate/PRIVACY.md
> +  consuming component (e.g. a course) is copied or a manual export of the certificate is triggered.
Certificate owners can export PDFs of their Certificates at Achievements > Certificates. 
No other exports of user related data is provided by the Certificate Service itself. Exports may be possible in the object types listed above. Please refer to the respective Privacy.mds.

2022-07-12 11:20 UTC, mjansenDatabay commented
@atoedt / @erikreidt I would like to merge this into `trunk`. Do you have any objections?

2022-07-20 11:55 UTC, mjansenDatabay commented
OK, no objections, I'll merge this later this day.

2022-07-21 13:14 UTC, merged