UI Components, fix of responsive Logo Issue, see: #32016
ILIAS-eLearning/ILIAS pull request #4029
Opened 2022-02-11 17:48 UTC by Amstutz

Currently, the responsive Header Logo is not displayed on small screen sizes, the standard one is. See: https://mantis.ilias.de/view.php?id=32016

2022-03-07 11:33 UTC, Amstutz commented
This is the location that need JF approval: https://github.com/ILIAS-eLearning/ILIAS/pull/4029/files#diff-6a41b430974074e3a2f9b2241e68588cdc0199013306c77e6dfc7cf6481d58b6

2022-03-07 13:41 UTC, matthiaskunkel commented
Jour Fixe, 07 MAR 2022 : We highly appreciate this PR and accept it for 7 and trunk.

2022-03-11 15:11 UTC, chfsx requested changes
@Amstutz there are two missing TypeHints. @thibsy will contact you next week to discuss the further steps concerning this PR, thanks a lot!

2022-03-11 15:11 UTC, chfsx commented on src/UI/Component/Layout/Page/Standard.php
> +    public function getResponsiveLogo();
missing `: ?Image`

2022-03-11 15:11 UTC, chfsx commented on src/UI/Implementation/Component/Layout/Page/Standard.php
> +    public function getResponsiveLogo()
missing `:?Image`

2022-03-14 10:40 UTC, Amstutz commented
@thibsy discussed with me some implication of this change for 6 and 7. He correctly pointed out, that this will affect skins already in production, since the responsive icon of the core will be used in many cases. To prevent undesired results, @thibsy will propose a small change in the update script, making sure, that the core responsive icon will be overridden in case no custom responsive icon is used by the skin.


@thibsy and @chfsx : thx a lot for the kind support and feedback with this PR / Issue. Highly appreciated.

2022-03-14 10:40 UTC, Amstutz commented
@thibsy discussed with me some implication of this change for 6 and 7. He correctly pointed out, that this will affect skins already in production, since the responsive icon of the core will be used in many cases. To prevent undesired results, @thibsy will propose a small change in the update script, making sure, that the core responsive icon will be overridden in case no custom responsive icon is used by the skin.


@thibsy and @chfsx : thx a lot for the kind support and feedback with this PR / Issue. Highly appreciated.

2022-03-14 10:40 UTC, closed without merging