Make Chaining of `Renderer`s possible
ILIAS-eLearning/ILIAS pull request #4137
Opened 2022-03-16 11:54 UTC by klees

As pitched by @iszmais in #4118, this makes it possible to write decorators for `Renderer` in the UI-framework, by passing the root of a chain of decoratred `Renderer`s through the `render`-function.

The change is non-breaking from the perspective of the core, since existing usages of `Renderer::render` will continue to work as expected. This is breaking from the perspective of plugins, however, since the interface changed and implementing classes will need to change accordingly.

We might want to take this to the JF for this reason or even decide to only make the change in the trunk. I would be happy if @Amstutz takes an according decision as I'm the one who proposes this.

2022-03-16 13:05 UTC, iszmais commented
Thx for the contribution @klees ,

LGTM for me codewise, but i agree that this should go to the JF.

Greetings,
@iszmais

2022-03-16 13:06 UTC, iszmais approved these changes

2022-03-17 11:03 UTC, iszmais commented
Just a proposal:
Maybe i usefull for all stages below trunk to provide this changes without the interface changes. This would make them non-breaking for already existing plugins but still provides the option to use the chaining feature since addition dont violate the origin interface.

2022-03-17 11:07 UTC, klees commented
@iszmais You mean: making the change in the `DefaultRenderer` but not the `Renderer`-interface? Sounds plausible...

2022-03-17 12:27 UTC, Amstutz requested changes
Hi @klees 

I am fine with the changes on the interface and agree that we should get the opinion of the JF here.

Concerning the implementation, a two questions:
- [x] Arrays of Components: IMO, [this line](https://github.com/ILIAS-eLearning/ILIAS/pull/4137/files#diff-c56a548132be9f8c8ccf6cde8287558f810c7a7fc0c8c97f18d4d67e4049b3f7R42) is wrong, right? It should be the same logic as if rendering a single component, `$renderer = $this->getRendererFor($component); $out = $renderer->render($component, $root)`. Maybe factor out does two duplicate line of code.
- [ ] Async Rendering: IMO, this does not work for Async Rendering atm. The $root parameter needs to be passed in the function for sync rendering as well, right?

Please Change:
- [x] Add Tests: Maybe I am wrong with the above. If so, prove it by adding tests for passing arrays, passing arrays on async and rendering single async components. If not, make sure those issues will not hunt us in the future. 

Thx!

2022-03-17 12:46 UTC, klees commented
Hi @Amstutz,

thanks for looking into this:

* Arrays of Components: If we would not include this line we would need every decorator for `Renderer` to deal with arrays of components as well. If we include this line, they would only need to deal with single components because the `DefaultRenderer` would start the chain again for the case of an array of components. Both would be valid, but I expect the current version to cause less surprises.
* Async Rendering: I simplied missed this. Will add...

Best regards!

2022-03-17 13:35 UTC, klees commented
@Amstutz Done.

2022-03-21 08:07 UTC, Amstutz approved these changes
Hi @klees 

Thx for adding the answer and the tests. This is good to be merged, if accepted by JF.

Thx.

2022-03-21 11:36 UTC, iszmais commented
Hi @klees ,

This may be a little late, but the problem occured to me just now. I tried some testing with this an dchaining renderers together and came to some difficulties. E.g. this is still bound to some kinde of order or deep level in its rendering. Like when i have to make some wrapping modifications inside other renderers (e.g. Render A manipulates a section and Render B manipulates the page outside the section and a button inside the section).
I came to the conclusion that this is cause conceptionally by the fact the the added parameter "root" i required to serve 2 purposes here, as a fallback (wich should always be the complete UI-Renderer) and an chaining (wich should only be the next chain node) wich it cant solve both. (I may be wrong here, pls correct me if needed)
To clsoe the circle: I think to solve this problem we neverless need a addition to the getRendererFor function, but much smaller as my first approach.
This may still be a good improvement, just not the one solving the mentioned problem.

Greetings,
@iszmais

2022-03-21 13:44 UTC, matthiaskunkel commented
Jour Fixe, 21 MAR 2022 : Timon pointed to this PR that will be discussed in more detail on the next JF and that is a pre-requisite for a following PR for a plugin rendererer.
In addition, please don't forget to add information about changes and implications of a PR to the readme files to make it easier for others to understand the PR and its aim.

2022-04-04 12:08 UTC, matthiaskunkel commented
Jour Fixe, 04 APR 2022: We highly appreciate this suggestion and accept the PR for all maintained versions and trunk.

2022-04-11 13:39 UTC, merged

2022-04-11 13:39 UTC, Amstutz commented
Thx a lot!