PHP 8: Code Review `WebServices`
ILIAS-eLearning/ILIAS pull request #4144
Opened 2022-03-17 07:08 UTC by mjansenDatabay

Hi @smeyer-ilias,

I completed the review of the `Services/Metadata` component. In general the code looked very good in regards of the PHP types.

Results:
- [ ] The code style is `PSR-2 + X` compliant
- [ ] No usage of `$_GET` / `$_POST` / `$_REQUEST` / `$_SESSION`
- [x] There is a `Unit Test Suite` with at least one unit test
- [x] The unit tests pass
- [x] External libraries are compatible with PHP 8 (if relevant)
- [x] There are no serious `PhpStorm Code Inspection` issues left
- [ ] The types are fully documented (PhpDoc) or explict PHP types are used (type hints, return types, typed properties)

I found multiple usages of `$_REQUEST` and `$_REQUEST`:

- `$_GET`: 19 usages
- `$_REQUEST`: 72 Usages
- `$_POST`: 38 Usages
- `$_SESSION`: 4 Usages

Our goal was to eliminate the usage of super global variables.

--

Furthermore the `PHP-CS-FIXER` "touched" some files because the code was not `PSR-2 + X` compliant.

I also fixed some trivial issues reported by my inspection profile.

Best regards,
@mjansenDatabay

2022-03-17 12:05 UTC, smeyer-ilias requested changes
Thanks for reviewing.
There is one issue regarding a wrong return type.

2022-03-17 12:05 UTC, smeyer-ilias commented on Services/WebServices/SOAP/classes/class.ilAbstractSoapMethod.php
> +    protected function __raiseError(string $a_message, $a_code) : void
The parent method returns string|int
Therefore no return type here.

2022-03-17 12:05 UTC, smeyer-ilias commented on Services/WebServices/Rest/classes/class.ilRestFileStorage.php
> +        if (!$fp = fopen($a_absolute_path, 'wb+')) {
For interest: I thought binary mode is default and therefore not required. Is this assumption wrong?

2022-03-17 13:12 UTC, mjansenDatabay commented on Services/WebServices/SOAP/classes/class.ilAbstractSoapMethod.php
> +    protected function __raiseError(string $a_message, $a_code) : void
Okay, the parent method returns ` soap_fault|SoapFault|null`. I'll fix this.

2022-03-18 11:54 UTC, smeyer-ilias approved these changes
Thank for reviewing ant the improvements.

2022-03-18 11:55 UTC, merged