General Refactoring of `Services/Notifications`
ILIAS-eLearning/ILIAS pull request #4429
Opened 2022-04-27 14:32 UTC by iszmais

Resolves issues mentioned in https://github.com/ILIAS-eLearning/ILIAS/pull/4357#pullrequestreview-942138173 :

- Add repository Pattern
- Get Rid of singelton
- Add Service
- Ad ilCtrlInterface usage

The last open point is dicussed separatly [here](https://github.com/ILIAS-eLearning/ILIAS/pull/4407)

2022-04-27 17:17 UTC, mjansenDatabay commented
@iszmais Please fix the tests (it should be sufficient to rebase your branch).

2022-04-28 07:23 UTC, mjansenDatabay requested changes
The tests fail, please rebase your branch on a working `trunk`.

2022-04-28 12:21 UTC, iszmais commented
@mjansenDatabay Thx for the feedback!

I fixed the test (the ones that fail seem like others uncorrelated to this pr) and did some minor fixed inside the repository itsself.

Greetings,
@iszmais

2022-04-29 12:59 UTC, mjansenDatabay approved these changes

2022-04-29 12:59 UTC, merged