Fix issues with access to uninitialized variables
ILIAS-eLearning/ILIAS pull request #4539
Opened 2022-05-16 09:27 UTC by swiniker

Hi @smeyer-ilias 
Found a few issues with access to variables in your components.

Thanks,
@swiniker

2022-05-23 13:00 UTC, smeyer-ilias requested changes
Thanks for fixing these issues. 
I added @pascalseeland for the review of LDAP and ECS issues.

2022-05-23 13:00 UTC, smeyer-ilias commented on Services/User/classes/class.ilObjUserFolderGUI.php
> +            $obj = $obj_factory->getInstanceByObjId($id);
Please can you replace it with ilObjectFactory::getInstanceByObjId()

2022-05-23 13:00 UTC, smeyer-ilias commented on Services/User/classes/class.ilObjUser.php
> +    public static function _lookupEmail(int $a_user_id) : ?string
Changing the return type of this methods means that all calls of this method must also be checked/adapated.

2022-05-23 13:00 UTC, smeyer-ilias commented on Services/User/classes/class.ilObjUser.php
> +    public static function _lookupGender(int $a_user_id) : ?string
Changing the return type of this methods means that all calls of this method must also be checked/adapated.

2022-05-23 13:00 UTC, smeyer-ilias commented on Services/User/classes/class.ilObjUser.php
> +    public static function _lookupClientIP(int $a_user_id) : ?string
Changing the return type of this methods means that all calls of this method must also be checked/adapted.

2022-05-23 13:00 UTC, smeyer-ilias commented on Services/User/classes/class.ilObjUser.php
> +    public static function _lookupLogin(int $a_user_id) : ?string
Changing the return type of this methods means that all calls of this method must also be checked/adapted.

2022-05-23 13:00 UTC, smeyer-ilias commented on Services/User/classes/class.ilObjUser.php
> +    public static function _lookupExternalAccount(int $a_user_id) : ?string
Changing the return type of this methods means that all calls of this method must also be checked/adapted.

2022-05-23 13:00 UTC, smeyer-ilias commented on Services/User/classes/class.ilObjUser.php
> +    public static function _lookupLastLogin(int $a_user_id) : ?string
Changing the return type of this methods means that all calls of this method must also be checked/adapted.

2022-05-23 13:00 UTC, smeyer-ilias commented on Services/User/classes/class.ilObjUser.php
> +    public static function _lookupFirstLogin(int $a_user_id) : ?string
Changing the return type of this methods means that all calls of this method must also be checked/adapted.

2022-05-23 13:00 UTC, smeyer-ilias commented on Services/Logging/classes/class.ilLog.php
> +        $this->current_log_level = $this->setLogLevel($a_log_level ?? $this->WARNING);
Please can you replace it with $this->setLogLevel($a_log_level ?? $this->default_log_level)

2022-05-23 13:00 UTC, smeyer-ilias commented on Services/AccessControl/classes/class.ilAccess.php
> +                            serialize($condition)
Are you sure, that serialization is correct here? I cannot find a unserialize.

2022-05-24 18:08 UTC, swiniker commented on Services/AccessControl/classes/class.ilAccess.php
> +                            serialize($condition)
No, I'm not, but you are throwing an array at a function that wants a string, so serialization was the poor man's choice, but you can decide whatever you want to pass here.

2022-05-24 18:19 UTC, swiniker commented on Services/User/classes/class.ilObjUser.php
> +    public static function _lookupEmail(int $a_user_id) : ?string
Yes, I know (and this goes for all your following comments). But:
* You are calling _lookup($a_user_id) from all these functions and there the return type is ?string. So it seems to me that the problem we have right now, ie. that a field can also be empty, is possible in all these cases. So we should either provide for this case by catching null and always returning a value or by allowing null. Which one it should be is not a decision I can make for you. I just chose one. We could alternatively add a null coalescing operator in all these functions.

2022-05-24 19:27 UTC, swiniker commented on Services/Logging/classes/class.ilLog.php
> +        $this->current_log_level = $this->setLogLevel($a_log_level ?? $this->WARNING);
Done.

2022-05-24 19:27 UTC, swiniker commented on Services/User/classes/class.ilObjUserFolderGUI.php
> +            $obj = $obj_factory->getInstanceByObjId($id);
Done

2022-05-24 19:54 UTC, swiniker commented
You can find an alternative PR with Null-Coalescing in #4596

2022-05-25 13:51 UTC, smeyer-ilias requested changes

2022-05-25 13:51 UTC, smeyer-ilias commented on Services/User/classes/class.ilObjUser.php
> +    public static function _lookupEmail(int $a_user_id) : ?string
I do not agree. If you change the return type of a method, you have to check all callers of this method, since it is a breaking change. One example: 
lookupEmail() is used in ilBadgeHandler.php which uses the return value as first parameter in ilMail->enqueue() which expects a string. 

I would prefer a type cast to string, since distinguishing between null and empty strings is not necessary here, imo.

Can you please revert the return type changes and add type casts to the return statements? Otherwise i will fix this in the trunk.

2022-05-25 13:56 UTC, kergomard commented on Services/User/classes/class.ilObjUser.php
> +    public static function _lookupEmail(int $a_user_id) : ?string
You have seen that there is another option for this PR below, right? There I use null coalescing. For your convenience, here is the link: https://github.com/ILIAS-eLearning/ILIAS/pull/4596

2022-05-25 13:59 UTC, smeyer-ilias commented on Services/User/classes/class.ilObjUser.php
> +    public static function _lookupEmail(int $a_user_id) : ?string
No, sorry, haven't seen it. 
Perfect! So I can close this one?

2022-05-25 14:04 UTC, swiniker commented on Services/User/classes/class.ilObjUser.php
> +    public static function _lookupEmail(int $a_user_id) : ?string
Yes, please do.

2022-05-25 14:04 UTC, smeyer-ilias commented
see https://github.com/ILIAS-eLearning/ILIAS/pull/4596

2022-05-25 14:04 UTC, closed without merging