Proposal for the implementation of Popovers in UI-Service
ILIAS-eLearning/ILIAS pull request #454
Opened 2017-03-14 09:28 UTC by wanze

The implementation uses the same pattern (Triggerer/Signals/Triggerable) as introduced with the modals. Here's a short example how a component acting as triggerer can display a popover on hover:

```php
$popover = $factory->popover('Title', 'Hello World');
$button = $factory->button()->standard('Show Popover', '#')
    ->withOnHover($popover->getShowSignal());
```
Cheers

2017-03-14 10:00 UTC, klees reviewed
LGTM, thx!

2017-03-14 10:00 UTC, klees commented on src/UI/Component/Popover/Popover.php
> +	public function getPosition();
Is this really something the dev should decide? Or could we derive this from other information, maybe even client side?

2017-03-14 10:00 UTC, klees commented on src/UI/Implementation/Component/Popover/Renderer.php
> +	protected function esacpe($str) {
`esacpe` -> `escape`

2017-03-14 10:08 UTC, wanze commented on src/UI/Implementation/Component/Popover/Renderer.php
> +	protected function esacpe($str) {
omg thanks

2017-03-14 10:18 UTC, wanze commented on src/UI/Component/Popover/Popover.php
> +	public function getPosition();
The default position is set to `auto`, meaning that bootstrap is deciding where to display the popover based on the available space.

2017-03-14 12:48 UTC, klees commented on src/UI/Component/Popover/Popover.php
> +	public function getPosition();
Unless someone has a use case where its definitely necessary that the Dev decides, I would just drop this position property and always set it to auto. I currently can't see that use case.

2017-03-15 08:08 UTC, Amstutz requested changes
Popovers seem to be not so much a technical challenge (except for the placement) as much more a semantical. What types of popovers are needed? What rules restrictions will apply to them? Here much more work is still needed. We will discuss much of it in the scheduled meeting, today 10:15. As always, everybody is invited to join.

2017-03-15 08:08 UTC, Amstutz commented on src/UI/Component/Popover/Popover.php
> +	public function getPosition();
The Dev. should decide as little as possible. We could talk about giving different popover instances and let the dev choose one (e.g. Top Navigation Popover, which always displays on the bottom of the item). I am not sure if this is needed. Needs to be discussed. The placement option of bootstrap is probably to limited for us. We should think about extending that a little. Similar to: [http://sandywalker.github.io/webui-popover/demo/](http://sandywalker.github.io/webui-popover/demo/)

2017-03-15 08:08 UTC, Amstutz commented on src/UI/Component/Popover/Popover.php
> +	public function getText();
We might have a type of popover only accepting text. However there are certainly others as well. Not sure if this is placed at the correctly here.

2017-03-15 08:08 UTC, Amstutz commented on src/UI/Factory.php
> +	 *     Popovers are used to display secondary information to a component.
Not only. They might also contain interaction. Please specifiy further. See: [https://docs.google.com/document/d/1JoInU0-tkRHDOMjMTNziV-hJb6ypDCI1zT9OGtAThZk/edit#heading=h.um0atzynczok](https://docs.google.com/document/d/1JoInU0-tkRHDOMjMTNziV-hJb6ypDCI1zT9OGtAThZk/edit#heading=h.um0atzynczok)
However, note that the current description given in the pipeline document was rejected by the JF and therefore needs some revision.

2017-03-15 08:08 UTC, Amstutz commented on src/UI/Factory.php
> +	public function popover($title, $text, $position = 'auto');
There will be certainly more than one popover type. Position should be moved out of the constructor. The constructor should be as small as possible.

2017-03-15 08:08 UTC, Amstutz commented on src/UI/Factory.php
> +	 *     Popovers consist of a short title and text.
Incomplete

2017-03-15 08:08 UTC, Amstutz commented on src/UI/Factory.php
> +	 *     2: The text MUST be plain text (no HTML) and no longer than a paragraph.
Very incomplete. Accessability is a huge topic in the case of popovers. Please checkout the rules proposed at: [https://docs.google.com/document/d/1JoInU0-tkRHDOMjMTNziV-hJb6ypDCI1zT9OGtAThZk/edit#heading=h.um0atzynczok](https://docs.google.com/document/d/1JoInU0-tkRHDOMjMTNziV-hJb6ypDCI1zT9OGtAThZk/edit#heading=h.um0atzynczok)

2017-03-15 08:08 UTC, Amstutz commented on src/UI/Implementation/Component/Popover/Popover.php
> +	const POS_AUTO = 'auto';
We probably need to extend that with something like bottom-corner (think about our top navigation).

2017-03-15 08:08 UTC, Amstutz commented on src/UI/templates/js/Popover/popover.js
> +
Think about adding further placement options here.

2017-05-04 07:32 UTC, closed without merging

2017-05-04 07:32 UTC, wanze commented
Please see the follow-up pull request: https://github.com/ILIAS-eLearning/ILIAS/pull/513