Pass over rendered HTML to use in an uihook plugin for replacements
ILIAS-eLearning/ILIAS pull request #4541
Opened 2022-05-16 10:06 UTC by PurHur

Hello,

i added the html to the $a_pars array so this UIHook call behaves like the other `UIHook->getHtml` calls in `ilTemplate`.

The problem is when you make an UIHookPlugin that wants to replace something in the rendered html the whole page will be blank, because there is no way you can not completely replace the dashboard html. 

The impact of this PR will be quite low. The UIHooks are always called, it justs adds a `new` parameter. As an uihook plugin developer i would assume this parameter is always filled with the rendered html in the first place, like its done here in the general ilTemplate hook: https://github.com/ILIAS-eLearning/ILIAS/blob/release_7/Services/UICore/classes/class.ilTemplate.php#L180

Greetings
Purhur

2022-05-16 10:07 UTC, PurHur commented
@iszmais ping because i think you are the maintainer here.

2022-05-16 10:56 UTC, PurHur commented
The question here is if the getHtml method of UIHook plugins is really deprecated or not. Is there a link to this information in the wiki? I cant find it.

2022-05-18 09:09 UTC, iszmais approved these changes
@amichelsdatabay As far as i can see this isnt a bug since this UI Call should provide the HTML (there is a later one that does).
But since this whole stucture got a little messy over time i will merge this as an improvement so you can access the rendered HTML on both ways.
Just be aware that this can produce conflict with other plugins which may cause the changes made in your plugin to not be rendered.

**I strongly recommend to use the function exchangeUIRendererAfterInitialization() inside your plugin object to prevent those kinds of conflicts!**

2022-05-18 09:12 UTC, iszmais requested changes
1 Minor Change request:
Please squash your commits and set a commit message wich also hint onto changes inside the dashboard so its easier to differ these commit from the others in future

2022-05-18 09:22 UTC, iszmais commented
@amichelsdatabay

2022-05-18 15:30 UTC, PurHur commented
See https://github.com/ILIAS-eLearning/ILIAS/pull/4544#issuecomment-1130164999

Thanks for your documentation for the new system so plugin devs have a change to know where to migrate.

2022-05-18 15:30 UTC, closed without merging