Revert condition switch in language translation of notifications
ILIAS-eLearning/ILIAS pull request #4557
Opened 2022-05-17 09:48 UTC by iszmais

fixes the initial refactoring made in  https://github.com/ILIAS-eLearning/ILIAS/commit/93460397884602f72074df5ddc7a92cb932a34dd

2022-05-17 18:06 UTC, mjansenDatabay requested changes
@iszmais Can you please squash the commits and rebase the branch on `trunk`. Thanks a lot.

2022-05-18 08:14 UTC, iszmais commented
@mjansenDatabay resolved

2022-05-18 08:40 UTC, mjansenDatabay reviewed
Thx @iszmais

2022-05-18 08:40 UTC, mjansenDatabay approved these changes

2022-05-18 08:40 UTC, merged