Object: move fallback to _SESSION to another place (#32831)
ILIAS-eLearning/ILIAS pull request #4640
Opened 2022-06-07 14:29 UTC by klees

Hello everyone,

since `Services\Object` currently has no maintainer, neither implicit nor explicit, I kindly ask everyone to look into this change.

This is supposed to fix [#32831](https://mantis.ilias.de/view.php?id=32831). Instead of overwriting `$_POST`, the value in question `tit` is pulled from `$_SESSION` in the only consuming location that I could find.

Best regards!

2022-06-07 21:27 UTC, alex40724 commented
@smeyer-ilias Could you have a look at this, please?

2022-06-08 08:32 UTC, smeyer-ilias requested changes
Thanks for fixing this. 
Please remove the superglobal access.

2022-06-08 08:32 UTC, smeyer-ilias commented on Services/Object/classes/class.ilObjectCopyGUI.php
> +            $tit = $_SESSION['source_query']; // TODO PHP8 Review: Remove/Replace SuperGlobals
Please use ilSession::get('source_query', '') here.

2022-06-10 10:36 UTC, klees commented on Services/Object/classes/class.ilObjectCopyGUI.php
> +            $tit = $_SESSION['source_query']; // TODO PHP8 Review: Remove/Replace SuperGlobals
Done!

2022-06-10 10:37 UTC, klees commented
Thx @smeyer-ilias, I introduced ilSession.

2022-07-04 11:18 UTC, merged

2022-07-04 11:18 UTC, smeyer-ilias commented
Thanks for fixing this.