Fix user id is zero
ILIAS-eLearning/ILIAS pull request #4673
Opened 2022-06-20 14:24 UTC by lscharmer

This PR fixes that the user id is zero under certain circumstances. The user id will be the anonymous user in these cases.

2022-07-20 10:16 UTC, chfsx commented
sorry, wrong PR, will post this comment in #4169

2022-08-11 16:30 UTC, alex40724 requested changes

2022-08-11 16:30 UTC, alex40724 commented on Services/User/classes/class.ilObjUser.php
> +            $this->setId(ANONYMOUS_USER_ID);
Please note that @pascalseeland takes care of the authentication service, but not of the user server, which is still maintained by @smeyer-ilias.

This should not be fixed in the user class. The ID is usually set to 0 when new objects (here new users) are created. It is wrong to set the anonymous ID in these processes automatically. New user objects should not get the anonymous user ID. Whatever code calls the constructor here during initialisation should already pass the anonymous user ID.

2023-04-20 12:41 UTC, alex40724 commented
Since @kergomard now took over this component, we left it to him to decide how to move forward here.

2023-05-24 08:18 UTC, kergomard commented
Thank you @lscharmer for this PR that has been around for so long.
I agree with @alex40724 , that this is most probably not the right solution and thus close this PR. I agree though, that the handling of users that are not authenticated is a mess even after the improvement and should be streamlined and improved.
Thanks again and best,
@kergomard

2023-05-24 08:18 UTC, closed without merging