fixed resolution of some language variables in permissions
ILIAS-eLearning/ILIAS pull request #4676
Opened 2022-06-21 11:08 UTC by schmitz-ilias

Fixed the resolution of language variables in the permissions, see [https://mantis.ilias.de/view.php?id=32909](url). This includes the name of custom roles from plugins, the name of all roles in the log, and the name of custom operations from plugins in the permissions table.

2022-06-21 12:18 UTC, smeyer-ilias requested changes
Thanks @schmitz-ilias for fixing this.
Please have a look at the comments, there are only two minor issues.

2022-06-21 12:18 UTC, smeyer-ilias commented on Services/AccessControl/classes/class.ilObjRoleGUI.php
> +        $data['title'] = $role->_getTranslation($role->getTitle());
Please change this to a static call, since the method is static: ilObjRole::_getTranslation(...)

2022-06-21 12:18 UTC, smeyer-ilias commented on Services/AccessControl/classes/class.ilObjRoleTemplate.php
> +     * @return string
Please remove the phpdoc-comment (\return string), since it does not provide additional information.

2022-06-21 13:19 UTC, smeyer-ilias approved these changes
Thanks

2022-06-22 08:52 UTC, merged

2022-07-21 07:01 UTC, iljalukin commented
This PR causes a change in the display of the title in the "Edit Properties" dialog of the role.
Previously, the role title was displayed there in the form il_crs_admin_12345 and could be used in further workflows such as assigning the local role when creating registration codes.
Currently, the translated title "Course Administrator" is displayed there and you have no way to get to the role title. 
Is the change of displaying the title really intended and necessary at this point?

2022-07-21 11:13 UTC, schmitz-ilias commented
Hi @iljalukin, I talked to @smeyer-ilias about the issue you brought up. We propose to not revert to the previous behavior, but instead to add the role title in the form il_crs_admin_12345 in brackets to the end of the title in the header of the role GUI. 
I will implement this in the next few days and link the PR here.