UI Rating Input
ILIAS-eLearning/ILIAS pull request #468
Opened 2017-03-27 09:19 UTC by nlzh

Proposal to add a new input for rating things.
Uses, but not introduces input-facory (which is in PR #360).
The implementation is incomplete, mainly backing the proposal's examples.

2017-03-27 12:20 UTC, klees requested changes
Some points for discussion and some change requests added. I like your description!

2017-03-27 12:20 UTC, klees commented on src/UI/Component/Input/Rating/Rating.php
> +interface Rating extends Component{
Please add getters for the available properties.

2017-03-27 12:20 UTC, klees commented on src/UI/Component/Input/Factory.php
> +	public function rating($topic, $byline='');
As I `SHOULD` add captions I would like to `$caption` as an argument. I would drop `$byline` as this seems to be truely optional.

2017-03-27 12:20 UTC, klees commented on src/UI/Component/Input/Rating/Rating.php
> +	public function withTopic($topic);
I currently do not see a usecase for changing the topic after the fact. Please remove this or give an example, where one would change the topic and not just create a new rating object.

2017-03-27 12:20 UTC, klees commented on src/UI/Component/Input/Rating/Rating.php
> +	public function withCaptions(array $scale_captions);
See `withTopic`, same issue here.

2017-03-27 12:20 UTC, klees commented on src/UI/Component/Input/Rating/Rating.php
> +	public function withHiddenTopic($hidden=true);
I am not sure we want/need this. I see that there are/might be usecases where we want or do not want the topic to be displayed (e.g. one rating besides the title vs. multiple ratings in a form). But I think we should at least try to make this happen via CSS. Exposing this as an interface to the consuming dev gives her the choice and we try to minimize these in general.

2017-03-27 12:20 UTC, klees commented on src/UI/Implementation/Component/Input/Rating/Rating.php
> +	public function withCaptions(array $scale_captions) {
Please check array shape and content here. There should be an according helper in ComponentHelper.

2017-03-27 12:20 UTC, klees commented on src/UI/Implementation/Component/Input/Rating/Rating.php
> +	public function withTopic($topic) {
Check arg here, there should be an according method in ComponentHelper.

2017-03-27 12:20 UTC, klees commented on src/UI/Implementation/Component/Input/Rating/Rating.php
> +	public function withByline($byline) {
Check arg here, there should be an according method in ComponentHelper.

2017-03-27 12:20 UTC, klees commented on src/UI/Implementation/Component/Input/Rating/Rating.php
> +	public function withHiddenTopic($hidden=true){
Check arg here, there should be an according method in ComponentHelper.

2017-03-27 12:20 UTC, klees commented on src/UI/Implementation/Component/Input/Rating/Rating.php
> +	public function __construct($topic, $byline='') {
Check args here, there should be an according method in ComponentHelper.

2017-03-27 12:20 UTC, klees commented on tests/UI/Component/Input/Rating/RatingTest.php
> +*/
No uncommented code, please.

2017-03-27 12:20 UTC, klees commented on src/UI/templates/default/Input/Rating/rating.less
> +		*/
I do not understand this comment. What is disabled mode? What would I need to do here?

2017-03-27 12:20 UTC, klees commented on src/UI/templates/default/Input/Rating/rating.less
> +		*/
I do not understand this comment. What is disabled mode?

2017-03-27 12:20 UTC, klees commented on src/UI/templates/default/Input/Rating/tpl.rating.html
> +	<span class="il-input-rating-topic">{TOPIC} </span>
Despite my general concern with the hideTopic thingy, with this template there is "topic"-clutter in the html even if there is no `{TOPIC}`.

2017-03-27 12:35 UTC, klees commented
Hi @Amstutz,

please have a look as well. There are some small issues, but I would be happy to get your feedback, especially on the description.

Regards!

2017-03-27 14:56 UTC, nlzh commented on src/UI/templates/default/Input/Rating/rating.less
> +		*/
Inputs should have a disabled-status, i.e. readonly, but showing values. 
This is not implemented; I just pinned a note for the colors I thought to be the ones to use.

2017-03-27 14:57 UTC, nlzh commented
Thanks for the review, you totally have valid points. I corrected the issues.

2017-04-03 12:28 UTC, Amstutz requested changes
Thank you a lot for this PR. I like the generic approach of handling the rating as regular input. However this needs some more thought. Most importantly:
- How do we handle/display (average) ratings from other users. Amazon e.g. has a nice popover solution? Do we even want this double-functionality (entering and displaying ratings in the same input)?
- How do we clearly distinct own ratings from other user (average ratings). Currently a little blue dot is used in some implementations.
- How can a user completely remove a given rating?
- If we display average ratings from other users we might need further glyphs such as half-filled stars etc..

Further it might be a good idea to handle the star as regular glyph that is used in the ratings. I am not really sure about this last proposals, what do you think?

2017-04-03 12:28 UTC, Amstutz commented on src/UI/Component/Input/Factory.php
> +	 *     the numerical value into a colloquial term.
Good!

2017-04-03 12:28 UTC, Amstutz commented on src/UI/Component/Input/Factory.php
> +	 *     and a string that is displayed dependent on the selected item.
Currently the string displayed also changes if an element is focused (hovered).

2017-04-03 12:28 UTC, Amstutz commented on src/UI/Component/Input/Factory.php
> +	 *     Additionally, a title plus a short phrase is shown explaining the topic to be rated.
Maybe schange to "Additionally, a title plus an optional by-line phrase is/can be shown explaining the topic to be rated." Stressing, that the by-line is optional.

2017-04-03 12:28 UTC, Amstutz commented on src/UI/Component/Input/Factory.php
> +	 *     The probably most famous rating input is the amazon five-star rating.
Attention: Currently in ILIAS, this rating is not limited to making a rating (performing an input) but also showing the current average of a rating. See: [Pipeline Document](https://docs.google.com/document/d/1JoInU0-tkRHDOMjMTNziV-hJb6ypDCI1zT9OGtAThZk/edit#heading=h.rww0pri4fw8u) for a summary of existing ratings.

The composition should allow the following core functionality:

- Performing a rating (check)
- Showing your current rating (check)
- Removing the own rating, setting the status to not set (not checked)
- Showing the current average ratings of all users that may have performed a rating (not checked)

2017-04-03 12:28 UTC, Amstutz commented on src/UI/Component/Input/Factory.php
> +	 *          Ratings MUST have a topic
Please add a period. This is not of type usage but composition (see [README](https://github.com/ILIAS-eLearning/ILIAS/blob/trunk/src/UI/README.md#how-to-implement-a-component), for some reason, this type was missing in the docu, this has been updated).

2017-04-03 12:28 UTC, Amstutz commented on src/UI/Component/Input/Factory.php
> +	 *          Ratings SHOULD use captions for the scale
Same as above.

2017-04-03 12:28 UTC, Amstutz commented on src/UI/Component/Input/Factory.php
> +	 *          Ratings MAY be used in forms.
This is good, but also makes it slightly more complex. How should the average of other users be displayed there? Not at all?

2017-04-03 12:28 UTC, Amstutz commented on src/UI/Component/Input/Factory.php
> +	 *          Ratings SHOULD appear close to the thing that is rated.
Good!

2017-04-03 12:28 UTC, Amstutz commented on src/UI/Component/Input/Factory.php
> +	 *          Ratings SHOULD appear close to the thing that is rated.
I would also like to see some accessability rule here. E.g. "There MUST be a way to add and remove ratings by only using the keyboard.". Currently adding ratings by only using the keyboard is possible. However, it is quite hard to accomplish. E.g. there is no visual indication, that the ratings are currently focused.

2017-04-03 12:28 UTC, Amstutz commented on src/UI/Component/Input/Factory.php
> +	public function rating($topic, $captions='');
In my opinion we should not crowd to constructor with optional arguments. This could make future refactorings hard/nasty.

2017-04-03 12:28 UTC, Amstutz commented on src/UI/templates/default/Input/Rating/rating.less
> +		color: @il-glyph-color;
Good!

2017-04-03 12:28 UTC, Amstutz commented on src/UI/templates/default/Input/Rating/rating.less
> +		color: @il-glyph-highlighted-color;
Good!

2017-04-06 09:07 UTC, nlzh commented
Thanks for the reviews - I incorporated your suggestions.
However, I think that displaying the average before or simultaneously to a user input will influence the user's response, plus, the data will have to be retrieved prior to using the input. 
For visualization of rating results I imagine a different approach alltogether, separated from any input, but I understand there are other opinions and use cases.

The usage of glyphs is imaginable; a glyph will be rendered as "a"-tag, though,  while the rating uses "label"-tags with the "for" atrribute to accomplish the magic. I opted for the latter in favor of not adding JavaScript.

2017-06-08 15:36 UTC, Amstutz commented
@nhaagen : Thanks again for this PR. However, at the current stage I think this needs to be embed in a more general suggestion for the framework concerning inputs. @klees and myself already started working on this. I close this for the moment, but your work is not lost. I am sure we will be able to reuse parts of it, as soon as the more general suggestion is here.

2017-06-08 15:36 UTC, closed without merging