Forum: Feature 0029875: Course/Group title in subject of forum mail notifications
ILIAS-eLearning/ILIAS pull request #4721
Opened 2022-07-05 08:22 UTC by fhelfer

This fixes: https://mantis.ilias.de/view.php?id=29875
(language have to be reloaded)

2022-07-05 10:06 UTC, mjansenDatabay requested changes

2022-07-05 10:06 UTC, mjansenDatabay commented on Modules/Forum/classes/class.ilObjForumNotificationDataProvider.php
> +        $forum = ilObjectFactory::getInstanceByObjId($this->getObjId());
We should extract this code to a separate base class/or a trait/or even better: some type injected as dependency.

Is it ensured that these (expensive) calls are not executed multiple times during a bulk processing of forum notifications? If not, a cache should be introduced (See: `ilForumNotificationCache`).

2022-07-05 10:06 UTC, mjansenDatabay commented on Modules/Forum/classes/Notification/class.ilForumMailEventNotificationSender.php
> +        $body .= $this->getLanguageText($this->provider->getTopItemType()) . ": " . $this->provider->getTopItemTitle();
We should not append the body if we could not find a relevant parent object. This is valid for all similar usages (budy/subject) and also effects the design of the language variables.

2022-07-05 10:22 UTC, smeyer-ilias commented on Modules/Forum/classes/class.ilForumCronNotification.php
> +            $top_item_ref_id = $this->tree->getParentId($ref_id);
Have you considered to use $tree->checkForParentType(..., 'crs|grp') here or should only direct child elements be supported?

2022-07-08 08:48 UTC, fhelfer commented on Modules/Forum/classes/class.ilObjForumNotificationDataProvider.php
> +        $forum = ilObjectFactory::getInstanceByObjId($this->getObjId());
Added top_item to notificationCache

2022-07-11 08:13 UTC, mjansenDatabay commented on Modules/Forum/classes/class.ilObjForumNotificationDataProvider.php
> +            $top_item_crs_ref = $this->tree->checkForParentType($this->getRefId(), 'crs');
We should not execute both operations here. We should check for a `crs` parent first. If a `crs` could **not** be found, we should check for a `grp`.

I suggest to extract this caching into a new class or a trait, nesting `if` statements should be avoided. We should work with early returns here.

2022-07-11 08:13 UTC, mjansenDatabay commented on Modules/Forum/classes/class.ilForumCronNotification.php
> +            $top_item_crs_ref = $this->tree->checkForParentType($ref_id, 'crs');
We should not execute both operations here. We should check for a `crs` parent first. If a `crs` could **not** be found, we should check for a `grp`.

IMO we still need caching here. I suggest to extract this into a new method, nesting `if` statements should be avoided. We should work with early returns here.

2022-07-18 19:05 UTC, mjansenDatabay commented
@fhelfer Please check my latest changes in https://github.com/ILIAS-eLearning/ILIAS/pull/4721/commits/35126e816001aee42ae149024169ed71e33cb204 and test this thoroughly

2022-07-19 06:26 UTC, fhelfer commented
> @fhelfer Please check my latest changes in https://github.com/ILIAS-eLearning/ILIAS/pull/4721/commits/b1948473a38c4b64501c9f930e6a3c13410871b14 and test this thoroughly

works

2022-07-20 12:36 UTC, mjansenDatabay approved these changes

2022-07-20 12:39 UTC, merged