Forum: Feature 0029875: Course/Group title in subject of forum mail notifications (release_7)
ILIAS-eLearning/ILIAS pull request #4726
Opened 2022-07-05 09:56 UTC by fhelfer

This fixes: https://mantis.ilias.de/view.php?id=29875
(language have to be reloaded)

2022-07-12 09:22 UTC, mjansenDatabay requested changes
Same as #4721

2022-07-18 19:04 UTC, mjansenDatabay commented
@fhelfer Please check my changes in https://github.com/ILIAS-eLearning/ILIAS/pull/4721/commits/35126e816001aee42ae149024169ed71e33cb204 and adopt the changes (please test this thoroughly)

2022-07-20 14:08 UTC, fhelfer commented
tested, works

2022-07-21 06:32 UTC, mjansenDatabay approved these changes

2022-07-21 06:32 UTC, merged