Docs Guideline Proposal
ILIAS-eLearning/ILIAS pull request #473
Opened 2017-03-30 14:02 UTC by Amstutz

Proposal for naming, structuring and placing doc files (such as readmes) in ILIAS. I do not have a strong opinion on those proposals, so feel free to ask for, or even better push changes.

2017-03-30 14:16 UTC, chfsx requested changes
How about adding a link or a section which described how changes should be proposed? (PR agains trunk and label JourFixe).

Thankss a lot for your work!

2017-03-30 14:16 UTC, chfsx commented on docs/README.md
> +and configuring ilias ([configuration](configuration)) and for understanding the code
ILIAS always in capitals! And pray to god Matthias does not see this :-)

2017-03-30 14:16 UTC, chfsx commented on docs/documentation/docs-guidelines.md
> +* Markdown SHOULD be used for providing information such as described above.
I'd like a MUST here...

2017-03-30 14:21 UTC, gpkvt commented on docs/documentation/docs-guidelines.md
> +* Markdown SHOULD be used for providing information such as described above.
I second that. Markdown is easy readable as plain text, integrates well with Github and can be transformed into other formats without hassle.

2017-03-30 15:34 UTC, Amstutz commented
@chfsx the requested section which describes how changes should be proposed has been added.

2017-03-30 15:52 UTC, chfsx approved these changes

2017-03-31 08:58 UTC, gpkvt commented
How do we handle links to other docs which are available inside the ILIAS repo? In INSTALL.md I used relative paths, whichs works fine on github. When you read the document on you local machine after you checked out the repo it might be a bit unconvienient, but at least you know that the document is also part of the repository and available locally. 

Also there is no need to change the path for each release, as it would be if we use full URLs.

Any opinion on this?

2017-03-31 09:19 UTC, Amstutz commented
@gpkvt Thank you for your for this remark. I agree, internal links seem to do fit best for this. I added a respective rule.

2017-04-10 11:48 UTC, matthiaskunkel commented on docs/documentation/docs-guidelines.md
> +* Markdown SHOULD be used for providing information such as described above.
Jour Fixe, April 10, 2017: Thank you for this PR. It can be merged.

2017-04-10 14:49 UTC, merged