Fix maximum levenshtein distance
ILIAS-eLearning/ILIAS pull request #4793
Opened 2022-07-18 11:58 UTC by kunzeus

Mantis: https://mantis.ilias.de/view.php?id=17861
Used the recommended code from the comment area.
I added the requested performance improvements:
Not running the Levenshtein distance when string sizes differ too much and leave the code execution when the maximum allowed distance is reached

However, I didn't want to start with integrating the Levenshtein distance as a library since I currently don't want to mess around  with the composer. 
Therefore, I integrated the Levenshtein distance in the class.assQuestion class since it's the same baseclass for all three classes it is used inside the test module.

Since this is my first pull request in ILIAS, I know I still have a lot to learn. Therefore, please let me know if additional things need to be taken into consideration or changes have to be done.

2022-07-19 07:04 UTC, mbecker-databay commented
Hi and thank you very much for your PR!

I have reviewed the code and I would ask you for one change prior to accepting it.

The current efforts in general are to try to free the base classes - assQuestion and assQuestionGUI - from any extra weight. 
I would like to have the Levenshtein implementation extracted to an own class. 
That would also keep the source code license clean: The MIT licensed part would live in its own file.

Cheers!

Max

2022-07-19 09:16 UTC, mbecker-databay commented
After sending my above remark, when discussing this with other T&A developers, I was told that the ideal place/way to handle this is by means of the Refinery / Transformation library.

While I personally do not find the naming/labelling intuitive (because we do not strictly "transform" here but "analyze"), it's the designated place for such functionality in ILIAS.

2022-07-20 05:48 UTC, dsstrassner commented
I would say, we talk about this PR in the next TechSquad Meeting tomorrow. Do you join us @kunzeus?

2022-07-20 08:58 UTC, kunzeus commented
i should be there, there should be no more all day events on a thursday for now.

2022-07-27 15:28 UTC, kunzeus commented
I added the code of the Levenshtein function into the refiner.
Please, let me know if I got something wrong or more adjustments are needed.

2022-08-02 11:31 UTC, mbecker-databay commented
As discussed in the TechSquad meeting, be so kind and provide tests for the transformation. @klees & @mjansenDatabay will be so kind and review that part in here.

2022-08-02 16:53 UTC, mjansenDatabay requested changes
Hi @kunzeus,

thank you a lot for contributing to ILIAS and the `Refinery`. We highly apreciate your efforts.

In addition to the inline comments please implement the following changes:
- [x] Instead of having two methods in the factory, `levenshtein(...)` and `levenshteinCustom(...)`, please create a new sub-group `levenshtein(...)` with `standard(...)` and `custom(...)` as methods. Using `camelCase` in these factories could be an indicator for a "smell" where a new sub-group could be more appropriate.
- [ ] Please use `snake_case` variable names, whish will be our variable naming convention in the future (see: #4533).
- [ ] Please rename variables like `$str2Array` or `$str2Length`. Instead of `str1` and `str2` you could use words like `main`/`base` and `other`, `left` and `right` or similar pairs ...
- [ ] There are two PSR-2 (our current code style) violations. Please add a blank line to the refinery related classes.
- [ ] Please add our license header where missing (see: https://github.com/ILIAS-eLearning/ILIAS/blob/trunk/CI/Rector/ChangeLicenseHeader.php#L32).
- [ ] Please use `declare(strict_types=1);` in the test class.

A separate PR for ILIAS >= 8 with `Typed Properties` would be highly appreciated as well.

Kindly,
@mjansenDatabay and @klees

2022-08-02 16:53 UTC, mjansenDatabay commented on src/Refinery/String/Levenshtein.php
> +    private function StringToArray(string $str): array
```suggestion
    private function stringToArray(string $str): array
```

Maybe `stringToChars` or `stringToCharCollection` would be a better name.

2022-08-02 16:53 UTC, mjansenDatabay commented on src/Refinery/String/Group.php
> +    public function levenshteinDefault(string $str, int $maximumDistance) : Levenshtein
```suggestion
    public function levenshteinDefault(string $str, int $maximumDistance) : Transformation
```

2022-08-02 16:53 UTC, mjansenDatabay commented on src/Refinery/String/Group.php
> +    ) : Levenshtein {
```suggestion
    public function levenshteinCustom(
        string $str,
        int $maximumDistance,
        float $costIns,
        float $costRep,
        float $costDel
    ) : Transformation {
```

2022-08-02 16:53 UTC, mjansenDatabay commented on src/Refinery/String/Group.php
> +     * @return Levenshtein
```suggestion
     * @return Transformation
```

2022-08-02 16:53 UTC, mjansenDatabay commented on src/Refinery/String/Group.php
> +     * @return Levenshtein
```suggestion
     * @return Transformation
```

2022-08-02 16:53 UTC, mjansenDatabay commented on src/Refinery/String/Levenshtein.php
> +        $length = strlen($str);
AFAIK the used string methods are not multibyte safe. `ilStr` could be used to handle multibyte strings in ILIAS. Appropriate unit tests for such strings would be great.

2022-08-02 16:53 UTC, mjansenDatabay commented on tests/Refinery/String/LevenshteinTest.php
> +        $language = $this->getMockBuilder('\ilLanguage')
```suggestion
        $language = $this->getMockBuilder(ilLanguage::class)
```

2022-08-08 08:59 UTC, mjansenDatabay requested changes

2022-08-08 08:59 UTC, mjansenDatabay commented on src/Refinery/String/Transformation/LevenshteinTransformation.php
> +        $length = ilstr::strLen($string_to_convert);
```suggestion
        $length = ilStr::strLen($string_to_convert);
```

2022-08-08 08:59 UTC, mjansenDatabay commented on src/Refinery/String/Group.php
> +
Can we please remove these empy lines :)?

2022-08-08 08:59 UTC, mjansenDatabay commented on src/Refinery/String/Levenshtein.php
> +}
We stillt need a line break here. Please use the `PHP-CS-FIXER`.

2022-08-09 06:21 UTC, mjansenDatabay requested changes
Hi @kunzeus,

I am fine with these changes except for the description of the `levensthein()` (group) method.

After this has been changed, @maxbecker and @dsstrassner can merge this whenever they like.

Please keep in mind that (at least) the `Refinery` code has to be slightly changed for `release_8` and `trunk`.

Best regards,
@mjansenDatabay

2022-08-09 06:21 UTC, mjansenDatabay commented on src/Refinery/String/Group.php
> +     * Creates a between class.
Please add a more detailed description here.

2022-08-11 08:46 UTC, merged