Mail: Refactor 0030825: Replace Mail Mandaten
ILIAS-eLearning/ILIAS pull request #4812
Opened 2022-07-19 12:30 UTC by fhelfer

This fixes: https://mantis.ilias.de/view.php?id=30825

2022-07-20 12:35 UTC, mjansenDatabay requested changes
Thx @fhelfer , LGTM in general. I only have some minor remarks.

We don't need this code anymore: https://github.com/ILIAS-eLearning/ILIAS/pull/4812/files#diff-6347dce422a6e5cf515d769bee07abc81edca22ff56a565019e9bd058f4f86c8L1427

2022-07-20 12:35 UTC, mjansenDatabay commented on Services/Mail/README.md
> +* \[INSTALLATION_NAME\]: Client Name
```suggestion
* \[INSTALLATION_NAME\]: Installation Name
```

2022-07-20 12:35 UTC, mjansenDatabay commented on lang/ilias_de.lang
> +mail#:#mail_nacc_installation_name#:#Name des Mandanten
```suggestion
mail#:#mail_nacc_installation_desc#:#Beschreibung der Installation
mail#:#mail_nacc_installation_name#:#Name der Installation
```

2022-07-20 12:35 UTC, mjansenDatabay commented on lang/ilias_en.lang
> +mail#:#mail_nacc_installation_name#:#Client Name
```suggestion
mail#:#mail_nacc_installation_desc#:#Installation Description
mail#:#mail_nacc_installation_name#:#Installation Name
```

2022-07-20 12:35 UTC, mjansenDatabay commented on Services/Mail/classes/Setup/class.ilMailDatabaseUpdateSteps.php
> +    }
IMO we need a further step to replace the content in the `body` field of table `mail_template`.

2022-07-21 08:58 UTC, mjansenDatabay commented on Services/Mail/classes/Setup/class.ilMailDatabaseUpdateSteps.php
> +                $this->db->replace(
Please don't use `REPLACE`.

> Values for all columns are taken from the values specified in the [REPLACE](https://dev.mysql.com/doc/refman/8.0/en/replace.html) statement. Any missing columns are set to their **default** values, just as happens for [INSERT](https://dev.mysql.com/doc/refman/8.0/en/insert.html). You cannot refer to values from the current row and use them in the new row.

2022-07-21 08:58 UTC, mjansenDatabay commented on Services/Mail/classes/Setup/class.ilMailDatabaseUpdateSteps.php
> +                $this->db->replace(
Please don't use `REPLACE`.

> Values for all columns are taken from the values specified in the [REPLACE](https://dev.mysql.com/doc/refman/8.0/en/replace.html) statement. Any missing columns are set to their **default** values, just as happens for [INSERT](https://dev.mysql.com/doc/refman/8.0/en/insert.html). You cannot refer to values from the current row and use them in the new row.

2022-07-21 08:59 UTC, mjansenDatabay commented on Services/Mail/classes/Setup/class.ilMailDatabaseUpdateSteps.php
> +            $this->db->replace(
Please don't use `REPLACE`.

> Values for all columns are taken from the values specified in the [REPLACE](https://dev.mysql.com/doc/refman/8.0/en/replace.html) statement. Any missing columns are set to their **default** values, just as happens for [INSERT](https://dev.mysql.com/doc/refman/8.0/en/insert.html). You cannot refer to values from the current row and use them in the new row.

2022-07-21 09:56 UTC, mjansenDatabay commented on Services/Mail/classes/Setup/class.ilMailDatabaseUpdateSteps.php
> +        if (isset($row['value']) && $row['value'] !== null) {
```suggestion
        if (isset($row['value'])) {
```

If `isset($row['value'])` evaluates to `true`, the value cannot be `null`, so the 2nd check is obsolete.

2022-07-21 09:56 UTC, mjansenDatabay commented on Services/Mail/classes/Setup/class.ilMailDatabaseUpdateSteps.php
> +            if (isset($row['m_message'], $row['tpl_id']) && $row['m_message'] !== null && $row['tpl_id'] !== null) {
```suggestion
            if (isset($row['m_message'], $row['tpl_id'])) {
```

If `isset($row['m_message'], $row['tpl_id'])'` evaluates to `true`, the values cannot be `null`, so the further checks are obsolete.

2022-07-21 09:56 UTC, mjansenDatabay commented on Services/Mail/classes/Setup/class.ilMailDatabaseUpdateSteps.php
> +            if (isset($row['lang'], $row['type'], $row['body']) && $row['body'] !== null) {
```suggestion
            if (isset($row['lang'], $row['type'], $row['body'])) {
```

If `isset($row['lang'], $row['type'], $row['body'])` evaluates to `true`, the values cannot be `null`, so the further check is obsolete.

2022-07-21 12:55 UTC, mjansenDatabay approved these changes

2022-08-01 09:38 UTC, mjansenDatabay commented
@fhelfer Please rebase this branch based on `trunk`.

2022-08-01 09:45 UTC, fhelfer commented
> @fhelfer Please rebase this branch based on `trunk`.

Done

2022-08-01 10:00 UTC, mjansenDatabay commented
Sorry @fhelfer . Since we created the `release_8` branch on Friday, we'll have to rebase this on `release_8` (only this PR, not the other open PRs).

2022-08-01 17:46 UTC, merged