Trunk validation
ILIAS-eLearning/ILIAS pull request #485
Opened 2017-04-10 07:11 UTC by klees

Proposal for a interface to be used for restrictions that are checked during validation.

I'm not sure if `Restriction` should be replaced by `Constraint`.

This aims at being used in the input handling of the UI framework to enable type hinting and moving validation related problems out of the UI framework. Timon and I had the feeling that this should be usefull for a lot of other purposes as well, so we propose this as a global interface. A global library also makes it possible to introduce an share some common restrictions in the system.

Have a look [here](https://github.com/klees/ILIAS/blob/trunk_validation/src/Validation/README.md) for examples.

I kindly ask all developers to comment this PR to request changes or provide feedback. After two weeks I will propose to merge this request during JourFixe if more than 2/3 of the commenting core-developers, but at least two, support it. Thx!

2017-04-10 07:38 UTC, chfsx requested changes
Hi @klees ans thanks a lot for this PR. I also thinks it's the right way to go for forms and event better to provide this interface for other code.

see my comments, I thinks only small things or questions to discuss...

2017-04-10 07:38 UTC, chfsx commented on src/Validation/README.md
> +catch (\InvalidArgumentException $e) {
Why this throws a InvalidArgumentException? These exceptions are usually thrown if an argument is not of the expected type.

http://php.net/manual/de/class.invalidargumentexception.php 

Maybe a UnexpectedValueException is better, or an own exception.

2017-04-10 07:38 UTC, chfsx commented on src/Validation/README.md
> +This service abstract validations of values and provides some basic validations
typo abstract*s*

2017-04-10 07:38 UTC, chfsx commented on src/Validation/Factory.php
> +	public function custom($is_ok, $error);
Why not typehinting on callable for $is_ok? And I'm not sure if it's a good idea to accept both types string|callable for a parameter. Something like that leads to switchs or ifs in the implementaion.

Additionally the possibility to use custom() may lead to hundreds of those custom() usages, maybe it's better to create PR for new types of restrictions.

2017-04-10 08:13 UTC, Amstutz approved these changes
Thank you for this Request. I like and approve it. Some minor feedbacks, mostly matter of personal preference.

2017-04-10 08:13 UTC, Amstutz commented on src/Validation/Factory.php
> +	public function seq(array $others);
Matter of personal taste: I hate those 3 letter Abbreviation. It is not immediately clear to me, what seq is supposed to be: sequence? sequent? sequently? I think naming can (should) be more precise than that. However, I see also the benefit of having, short readable lines. Up to you.

2017-04-10 08:13 UTC, Amstutz commented on src/Validation/Factory.php
> +	public function par(array $others);
Matter of personal taste: I hate those 3 letter Abbreviation. Here the problem is bigger than above. par to me those not immediatly hint for parellel. Could also be parity or similar.

2017-04-10 08:13 UTC, Amstutz commented on src/Validation/Factory.php
> +	public function custom($is_ok, $error);
I do not have a strong opinion versus allowing string and callable or not. Both have benefits. I slightly prefer accepting both for pure convenience on the consumer side.

I think it is necessary to allow custom validation for very specific scenarios. It is a thought one though. The need for a PR for each new validation could lead to not properly validated code though to the fear of the need to discuss a PR in the JF. However, we should always encourage to add reusable validations here. Other than UI stuff, the use of validations are not immediately visible and therefore easier to just leave out if the overhead gets too big.

2017-04-10 08:13 UTC, Amstutz commented on src/Validation/Restriction.php
> +     *
Indentation issue.

2017-04-10 08:13 UTC, Amstutz commented on src/Validation/README.md
> +```
A further example with problem builder would be nice.

2017-04-10 08:40 UTC, wanze commented on src/Validation/Factory.php
> +	public function seq(array $others);
I have the same opinion as Timon, I think it is better to be explicit when naming methods than using abbreviations.

2017-04-10 09:43 UTC, chfsx commented on src/Validation/Factory.php
> +	public function seq(array $others);
+1

2017-04-10 09:46 UTC, klees commented on src/Validation/Factory.php
> +	public function custom($is_ok, $error);
Accepting `string|callable` won't lead to switches if the implementor just uses `function($_) use ($error) { return $error; }` to normalize the string to a callable.

I see your point with the custom validations, we should at least somehow encourage to add validations in the lib.

2017-04-10 11:36 UTC, klees commented
Thanks for your feedback. Any opinions about Restriction vs. Constraint?

2017-04-10 13:07 UTC, Amstutz commented
@klees: about Restriction vs. Constraint:

> "Restriction, constraint, restraint, or limitation?
> These are all things that limit what you can do. A restriction is a rule or law that is made by someone in authority. A constraint is something that exists rather than something that is made, although it may exist as a result of someone's decision. A restraint is also something that exists: it can exist outside yourself, as the result of someone else's decision; but it can also exist inside you, as a fear of what other people may think or as your own feeling about what is acceptable:moral/social/cultural restraints. A limitation is more general and can be a rule that someone makes or a fact or condition that exists."

Source: [http://english.stackexchange.com/questions/92696/constraint-vs-restriction](http://english.stackexchange.com/questions/92696/constraint-vs-restriction)

Going from this, I would chose constraint. But I think the two are very similar.

2017-04-10 13:10 UTC, klees commented
@Amstutz: Very nice, thx. That supports my feeling that it should be `Constraint`.

2017-04-13 11:38 UTC, klees commented
Hi @chfsx, are there any other changes you would suggest?

2017-04-13 11:45 UTC, chfsx commented
currently it has conflicts but beside this everything's fine and thank you very much!

2017-04-13 11:46 UTC, chfsx approved these changes

2017-05-04 12:27 UTC, Amstutz commented
@klees Are you still working on this? If not I guess this can be merged.

2017-05-04 14:21 UTC, klees commented
Definitely not sick, @shecken is working on the implementation: https://github.com/klees/ILIAS/pull/28

2017-05-08 12:09 UTC, matthiaskunkel commented
Jour Fixe, May 08, 2017: We give another 14 days to comment and think about this suggestion. Postponed to Jour Fixe at May 22, 2017.

2017-05-22 12:23 UTC, matthiaskunkel commented
Jour Fixe, May 22, 2017: No objections were made since the last Jour Fixe. We ask Richard to merge this pull request.

2017-05-26 12:02 UTC, merged