Implemented PSR12 according to PR #4533
ILIAS-eLearning/ILIAS pull request #4877
Opened 2022-07-29 05:09 UTC by lauraherzog

Pull Request #4533 stated to update the Coding Standard to PSR12. I implemented it within the PHP CS Fixer. If anything needs to be changed, let me know.

2022-07-29 10:55 UTC, klees requested changes
@lauraherzog Thanks a lot, I left two remarks.

2022-07-29 10:55 UTC, klees commented on CI/PHP-CS-Fixer/code-format.php_cs
> +        'strict_param' => true,
Why did you change that?

2022-07-29 10:55 UTC, klees commented on CI/PHP-CS-Fixer/code-format.php_cs
> +        'return_type_declaration' => ['space_before' => 'none'],
I think we can drop this, it is already included in @PSR12 AFAIK.

2022-08-02 08:00 UTC, mjansenDatabay commented
Hi @lauraherzog and @klees,

thx a lot for this PR. IMO we need some further changes for the PSR-12 "migration".

---------

- [ ] The `PSR-2 and additions` chapter in `docs/development/coding-style.md` has to be modfied:

>
> https://github.com/ILIAS-eLearning/ILIAS/blob/2488641ea826ae8001feae5a7459b3e9cfe65a0b/docs/development/coding-style.md?plain=1#L5
>

---------

- [ ] The `Server Side (PHP)` chapter in `docs/development/README.md` has to be modified:

>
> https://github.com/ILIAS-eLearning/ILIAS/blob/2488641ea826ae8001feae5a7459b3e9cfe65a0b/docs/development/README.md#L27
>

---------

- [ ] The `PHP-CS-FIXER` examples have to be modified:

>
> https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/CI/PHP-CS-Fixer/example
>

---------

- [ ] Our `PhpStorm` inspection profile in `docs/development/inspection-configs/php-storm-php-inspections.xml` has to be modified:

>
> https://github.com/ILIAS-eLearning/ILIAS/blob/2488641ea826ae8001feae5a7459b3e9cfe65a0b/docs/development/code-style-configs/php-storm.xml#L1
>

---------

- [ ] The `PhpStorm` code style config in `docs/development/code-style-configs/php-storm.xml` has to be modified:

>
> https://github.com/ILIAS-eLearning/ILIAS/blob/2488641ea826ae8001feae5a7459b3e9cfe65a0b/docs/development/inspection-configs/php-storm-php-inspections.xml#L1
>

---------

If you need any assistance, don't hesitate to contact me.

Best regards,
@mjansenDatabay

2022-08-02 09:39 UTC, klees commented
@mjansenDatabay

* For the docu (first item in your list) we'll just have to merge #4533 before. No need to change that here, IMO.
* Could you be a bit more specific regarding the required change in the PHPStorm inspection config?

2022-08-02 10:03 UTC, mjansenDatabay commented
> Could you be a bit more specific regarding the required change in the PHPStorm inspection config?

We'll have to import the current config/profiles files into `PhpStorm` and then change the internal coding style to `PSR-12`. Then we'll have to export these modified files again.

2022-08-24 12:07 UTC, klees commented
Superseeded by #4960

2022-08-24 12:07 UTC, closed without merging