Fix for creating repository objects with long titles or descriptions
ILIAS-eLearning/ILIAS pull request #4952
Opened 2022-08-19 08:35 UTC by schmitz-ilias

This PR fixes the creation of repository objects with titles and/or descriptions longer than object_data allows, see [33865](https://mantis.ilias.de/view.php?id=33865).

2022-08-23 14:44 UTC, klees commented
Hi @schmitz-ilias and everyone,

we discussed this PR in the TB today. Currently we cannot see anyone assuming responsibility for `Service/Utilities` as maintainer or coordinator, only implicit maintainers. On the other hand, almost every ILIAS developer seems to dependent on this somehow. This is why we decided to take this to the JF to find someone to look into this PR.

In general we are looking to get rid of `Service/Utilities` completely. There is valuable code in there, but there also seems to be stuff that is not (much) used anymore. The code that is still in use should migrate to newer facilities, such as `src\Data`, the Refinery or the UI-Framework. We ask every developer to participate in this endeavour so we won't need to ask the question "who is responsible for `Services/Utilities` again some times soon.

Best regards!

2022-08-31 15:42 UTC, alex40724 requested changes
Just my 2cents as an implicit maintainer. I think the length correction is ok. However I would not introduce strict type declaration during beta phase, since this might trigger additional errors in consumer code, which might have already been tested.

2022-09-07 06:11 UTC, schmitz-ilias commented
> Just my 2cents as an implicit maintainer. I think the length correction is ok. However I would not introduce strict type declaration during beta phase, since this might trigger additional errors in consumer code, which might have already been tested.

Done, thanks!

2022-09-19 09:08 UTC, alex40724 approved these changes
Thanks!

2022-09-19 14:10 UTC, matthiaskunkel commented
Jour Fixe, 19 SEP 2022 : We highly appreciate this PR and accept it for 8 and trunk.

2022-11-01 13:58 UTC, merged