Bugfix 31495 FileInfo Error with no file
ILIAS-eLearning/ILIAS pull request #5007
Opened 2022-09-14 03:53 UTC by elopezmo

#bugfix
Target: release_7
Mantis issue: 31495
https://mantis.ilias.de/view.php?id=31495

The error was triggered every time the assessment form for a user in an individual assessment was loaded without a file having been added to it. The parent class calls the abstract function getInfoResult (which should return file information) and the current implementation in the ilIndividualAssessmentMemberGUI class could not handle an empty identifier.

This fix leans on the implementation as in the ilMMUploadHandlerGUI class which inherits from the same parent class.

An alternative solution would be to avoid calling the function in the first place by modifying the parent class AbstractCtrlAwareUploadHandler:100. I chose this safer approach to avoid unforeseen effects in other parts of the code, but I am of course open for discussion on that point :).

2022-09-19 10:59 UTC, klees requested changes
Hi @elopezmo ,

as discussed in our mentoring session: This does not seem to fix the root cause of the issue. Instead we would need to take care that we do not set a value on the form field for the file if we do not actually have a file. This would need to be done in `ilIndividualAssessmentUserGrading::toFormInput`.

Thanks for looking into this!

2022-09-29 08:43 UTC, elopezmo commented
Hi @klees,
I modified the pull request as discussed :).

2022-10-13 13:22 UTC, klees approved these changes

2022-10-13 13:22 UTC, merged

2022-10-13 13:28 UTC, klees commented
Picked changes to release_8 and trunk.