[FIX] 0034523: Failed test: Datei hochladen
ILIAS-eLearning/ILIAS pull request #5049
Opened 2022-09-21 15:46 UTC by chfsx

@Amstutz / @klees as mentioned in https://mantis.ilias.de/view.php?id=34523

But I misunderstood the Close-Signal, therefore I implemented an additional Closed-Signal (which naming is not good, i know, better Ideas appreciated...).

You therefore can listen to a triggered Signal on closing a Modal, the Dropzone\File\Wrapper uses this to clean the filelist (as mentioned in the initial bug ticket).

2022-09-22 06:25 UTC, chfsx commented
We could name it `onClosedSignal` instead of `ClosedSignal`

2022-09-22 07:26 UTC, klees requested changes
Hi @chfsx,

the current nomenclature for the client side actions is actually really bad and I get confused all the time, but:

* A `Signal` is something I can connect to, that can cause what its name says. The `CloseSignal` is supposed to close the modal.
* The things that I connect to `Signal`s are called `Triggerer`s. If they trigger, the connected `Signal`s actually do the things they are supposed to 

AFAIK you are looking to build a Triggerer. Please have a look into `src/UI/Implementation/Component/Dropdown/Dropdown.php` for an example.

@Amstutz We need to devise a plan to change that wording some time...

Best regards!

2022-09-22 07:48 UTC, chfsx commented
ah of course, I knew I missed something. I will propose an Interface `Closable` (or `Dismissable`?) like other (`Hoverable` etc.) and remake the implementation of the whole PR...

2022-09-22 08:32 UTC, chfsx commented
@klees / @Amstutz I updated the PR accordingly:
- New Interface `Closable` which is implemented by Modals (we could rename it to `Dismissable` if needed
- Wrapper-Dropzones are now Triggarable and has a Clear-Signal
- Closing a Modal now triggers the Clear-Signal

2022-09-22 08:36 UTC, chfsx commented
Sorry, just wait a minute, there is some code wrong due to amending last commit, I'll update and force-push soon with running tests

2022-09-22 08:43 UTC, chfsx commented
There you go

2022-09-26 16:28 UTC, klees reviewed
Hi @chfsx,

thanks for looking into this. The code looks fine, just two little things came to mind.

Please answer the following questions:
- [x] Trigger: I'm most sure that I'm missing something, but: Where is the closed-triggerer of the modal actually invoked? Or is this done by Bootstrap himself?

Please consider the following suggestions. You do not need to follow those, but but please indicate shortly why you prefer to do otherwise:
- [ ] Debug: [These](https://github.com/ILIAS-eLearning/ILIAS/pull/5049/files#diff-2d9abcacf08b7e7e7a931e40d78ee734af912ab8af6659fa4b7a570dd349f632R494) are for debugging purpose, right? Can we remove them?

In general I find it really interesting, how boilerplatish most of the code looks. Although current naming is bad, this at least speaks to the fact that the abstractions behind it seem to be fine.

Best regards!

2022-09-27 07:46 UTC, Amstutz commented
> Trigger: I'm most sure that I'm missing something, but: Where is the closed-triggerer of the modal actually invoked? Or is this done by Bootstrap himself?

As far as I understand, by the hidden.bs.modal event thrown by bootstrap:
![image](https://user-images.githubusercontent.com/1866896/192465130-1055684e-357d-4dc3-be6b-d69fadfce84f.png)

Which is again cause by closing the modal in il.UI.Modal.closeModal
![image](https://user-images.githubusercontent.com/1866896/192465286-5f72553f-aff2-4f23-8ff0-7df9e2603bef.png)

Which again is registered in the renderer:
![image](https://user-images.githubusercontent.com/1866896/192465388-139dc829-a6ad-473f-996c-b4a6a424289f.png)

hidden.bs.modal then generates the new signal according to the proposal of @chfsx 
![image](https://user-images.githubusercontent.com/1866896/192465537-cffb1dde-ce50-4090-802a-b4ea142ed397.png)

2022-09-28 06:51 UTC, chfsx commented
Thanks @Amstutz for the explanations, nothing to add :-) and I removed the two console.logs in my last commit as well.

2022-09-28 07:03 UTC, klees approved these changes

2022-09-28 07:28 UTC, merged

2022-09-28 07:29 UTC, klees commented
Picked to trunk.

2022-09-28 07:30 UTC, klees commented
Thanks a lot!