fix js error on initial toast load
ILIAS-eLearning/ILIAS pull request #5121
Opened 2022-10-13 15:27 UTC by iszmais

This PR mostly reverts changes made in https://github.com/ILIAS-eLearning/ILIAS/pull/5012 and add all toasts that are preexisting to the toast container withing the pagebuilder to prevent an additional request.

2022-10-13 15:34 UTC, iszmais commented
@lscharmer @Amstutz @klees Pls leave your opinion on this.
I wouldnt see the need to take that to a JF until the is no major discussion point.
Feel free to open such.

Greeting,
@iszmais

2022-10-14 06:34 UTC, klees commented
Hi @alex40724,

you are listed as implicit maintainer for Services/Notification, hence I assigned you. Please reassign if there is a person you deem more suitable.

Thanks!

2022-10-14 06:36 UTC, klees approved these changes
I'm not much into the whole feature and problem, but this looks plausible indeed.

2022-10-14 06:37 UTC, mjansenDatabay commented
It is `Services/Notifications`, so I deassigned @alex40724 and assigned @mjansenDatabay

2022-10-14 06:38 UTC, klees commented
Oh, that's an intricate distinction =)

2022-10-14 06:40 UTC, mjansenDatabay commented
The changes LGTM in general.

@chfsx There is one change in `src/GlobalScreen` (https://github.com/ILIAS-eLearning/ILIAS/pull/5121/files#diff-5769142c345fc3a6bc2301605fe73f7876384f4504e108611a562c99fff70f2b). Do you have any objections?

2022-10-24 12:11 UTC, lscharmer requested changes

2022-10-24 12:11 UTC, lscharmer commented on src/GlobalScreen/Scope/Layout/Builder/StandardPageBuilder.php
> +        foreach (
This is just a minor thing but I would suggest to extract something into a variable for clarity.
Something like this:
```php
$toasts = (new ToastsOfNotifications($this->ui->factory(), new ilSetting('notifications'))
    ->transformNotificationsForToasts(
        (new ilNotificationOSDHandler())->getNotificationsForUser($this->user->getId())
    );
foreach ($toasts as $toast) {
    $toast_container = $toast_container->withAdditionalToast($toast);
}
```

2022-10-24 13:16 UTC, lscharmer requested changes
Please squash the commits.

2022-10-24 13:19 UTC, lscharmer approved these changes
Thank you :)

2022-11-02 15:59 UTC, chfsx requested changes

2022-11-02 15:59 UTC, chfsx commented on src/GlobalScreen/Scope/Layout/Builder/StandardPageBuilder.php
> +        $transformer = new ToastsOfNotifications($this->ui->factory(), new ilSetting('notifications'));
IMO notifications should be collected the same was as other types of notifications are collected (e.g. see SystemInfos, which has an own Collector and is called here src/GlobalScreen/Scope/Layout/Provider/PagePart/StandardPagePartProvider.php:225). we already have the whole `MainNotificationCollector` thing to collect notifications, would be great we could use this pattern for other types of notifications as well.

2022-12-02 10:16 UTC, iszmais commented
@chfsx Is there still something missing your requirements?
If yes feel free to leave a comment or otherwise i would appreciate your approval.

Greetings,
@iszmais

2022-12-02 12:38 UTC, chfsx commented
Hi @iszmais 

Yes actually my comment from last time is still relevant, but I that you have pushed something to this. We should look at this together. The `StandardPageBuilder` should not get too much dependencies, but especially no new ones. You have addressed this by allowing the `PagePartProvider` to supply the TostContainer. But also in `StandardPagePartProvider` we should keep the dependencies small. For certain things this is not possible (e.g. breadcrumb with ilLocator). In the case of the toasts it would be a good idea to collect the single toasts by ToastProviders and a ToastCollector. Or you can use (maybe better) the existing `NotificationCollector`, like it is done for the `AdministrativeNotifications` (see for example `\ILIAS\GlobalScreen\Scope\Layout\Provider\PagePart\StandardPagePartProvider::getSystemInfos`). Otherwise the toasts will have some kind of special status and it will be difficult to keep track of them in the future.

would you like to have a chat on discord next week?

2022-12-12 13:30 UTC, iszmais commented
Hello @chfsx ,

I abstracted the toast provider into an own scope within the global screen. Imo it should not be combined or integrated inside the already exsiting notification scope since the intention of creating the toast was do separete the over the years tangled chat and notfication therefore i think we should start that tangeling again.

Maybe you already can take a look into this i will also fix the tests to it.
I would prefer to present the changes of the existing providers (ChatInvitation, Badge, WhoIsOnline, ...) in seperate PRs wich are depending on this just to make it easier for the target maintainers.

Greetings,
@iszmais

2022-12-13 15:17 UTC, iszmais commented
Correlation to https://github.com/iszmais/ILIAS/pull/7

2023-02-01 07:28 UTC, chfsx commented
Hi @iszmais 

Thank you for your comments and the discussion in https://github.com/iszmais/ILIAS/pull/7. I pushed you two more commits there that we should still include (one is not directly related to your change, but I noticed it because it didn't have any data on the ToastProviders in the artefact yet). 
Your explanation of the distinction between toasts and notifications convinced me, so we can merge it like that!

2023-02-01 10:55 UTC, chfsx approved these changes
Thanks a lot @iszmais !

2023-02-01 10:55 UTC, merged