UI Notification Center
ILIAS-eLearning/ILIAS pull request #525
Opened 2017-05-19 14:06 UTC by nhaagen

Proposal for the NotificationCenter,  as described in http://www.ilias.de/docu/goto.php?target=wiki_1357_Page_Layout_Revision.

2017-05-19 14:22 UTC, klees commented
Hi @Amstutz,

we started to build PRs for the Page Layout to have a place to explain the Notification Center and the Cockpit (as we have called it now).

Best regards!

2017-05-29 15:27 UTC, Amstutz requested changes
This PR seems incomplete. Please add the complete interface. Also, add the mockups for a quick overview for other developers.

Further how will entries in the list of notifications be devised? Do they get their own entries, similar to the "Cockpit entries" or are they just generic items? What about the content of the popover, if one such entry is clicked upon? Please look at the mockups provided in the FR.

2017-05-29 15:27 UTC, Amstutz commented on src/UI/Component/Layout/Factory.php
> +	public function page();
See feedback of cockpit PR.

2017-05-29 15:27 UTC, Amstutz commented on src/UI/Factory.php
> +	 *   purpose: Layout elements
See feedback of Cockpit PR.

2017-05-29 15:27 UTC, Amstutz commented on src/UI/Component/Layout/Page/Factory.php
> +     *     location for further extensions.
I once heard the nice definition of "The notification center" offers possible "reactions" to notifications of the system for the user (e.g. new Mail) while the Cockpit offers action (e.g. open a course). Can we add that here somehow?

2017-05-29 15:27 UTC, Amstutz commented on src/UI/Component/Layout/Page/Factory.php
> +     *      and title.
Pleace move this to the respective entry of this list if one will exist. If not, move to composition.

2017-05-29 15:27 UTC, Amstutz commented on src/UI/Component/Layout/Page/Factory.php
> +     *      view of the service.
Or change the popovers content to some content offering direct interaction (e.g. see background tasks).

2017-05-29 15:27 UTC, Amstutz commented on src/UI/Component/Layout/Page/Factory.php
> +     *   composition:
remove if empty.

2017-05-29 15:27 UTC, Amstutz commented on src/UI/Component/Layout/Page/Factory.php
> +     *   composition:
Add rules about accessibility here.

2018-01-09 13:14 UTC, klees commented
We will open new PRs once our components are ready. Thx for Feedback!

2018-01-09 13:14 UTC, closed without merging