Data type "color"
ILIAS-eLearning/ILIAS pull request #542
Opened 2017-05-29 14:25 UTC by nhaagen

Introduces the data-type "color". 
Color can be constucted using a regular or short hex-value as well as RGB-values.
Same for value retrieval.

2017-06-01 09:42 UTC, klees requested changes
Change storage and creation please. Documentation is thorough. Thx.

2017-06-01 09:42 UTC, klees commented on src/Data/Color/Color.php
> +	 * @return <int>
`int[]` or `array<int>` for an array of integer.

2017-06-01 09:42 UTC, klees commented on src/Data/Color/Color.php
> +	protected $value;
Store as `$r`, `$g` and `$b` and `__construct` accordingly.

2017-06-01 09:42 UTC, klees commented on src/Data/Color/Color.php
> +	public function value() {
This will e.g. return `#03a417`? Maybe this should be named `asHex`?

2017-06-01 09:42 UTC, klees commented on src/Data/Color/Color.php
> +	}
Maybe add individual `r`, `g` and `b` getter? Maybe use `as*`for all other formats (rgb-string, hex, array)?

2017-06-01 09:42 UTC, klees commented on src/Data/Color/Color.php
> +	/**
Short description missing. `@return` missing.

2017-06-01 09:42 UTC, klees commented on src/Data/Color/Color.php
> +					new D\Factory()
This is is wrong here.

2017-06-01 09:42 UTC, klees commented on src/Data/Color/Color.php
> +	private function normalize($value) {
Move all this specific cases of how a value could be inputted to a new `ColorFactory`. Give them names (like "fromHex", "fromRGB", ...) and split them apart. Make central `build`-method, that decides which `from`-method to use. I.e.: refactor this =)

2017-06-08 16:02 UTC, Amstutz commented
@klees is this ready to be merged? Do we need a JF discussion for this?

2017-06-09 10:06 UTC, klees commented
@Amstutz I have to rereview, but it should be mostly fine. I don't see the necessity to JF this, do you see?

2017-06-09 10:14 UTC, klees requested changes
Minor naming, the rest is good. Thx!

2017-06-09 10:14 UTC, klees commented on src/Data/Color/ColorFactory.php
> +			$this->validateRGB($value);
Please change names from "validate*" to "check*". This is a convention we also use in the UI-framework and I try to use in general.

2017-06-09 11:28 UTC, klees approved these changes

2017-06-09 11:37 UTC, merged

2017-06-09 11:39 UTC, Amstutz commented
Nope and looks good, thanks a lot @nhaagen and @klees

2017-06-09 11:41 UTC, Amstutz reviewed
If you find the time, you could enhance the readme with a brand new color example. This is not a requirement however.