UI Link
ILIAS-eLearning/ILIAS pull request #552
Opened 2017-06-12 21:10 UTC by alex40724

2017-06-13 08:53 UTC, klees requested changes
Hi @alex40724,
I'm not happy with this. My reasons are threefold:

* I'm not sure, we really need this component in this form. As far as I understand, atm you need this for the dropdown. Why don't you just use a button? Is it just a matter of presentation?
* The naming to me is wrong. A [link](https://de.wikipedia.org/wiki/Hyperlink) references another resource in hypertext content. As the description states, this will not always be the case with this "link". I would prefer another name, if we really need a concept separate from a button.
* The rendering to me is wrong. An `<a>` is a hyperlink, which this concept is not. By attaching an js-action to the `<a>` you in fact will cause confusion for every machine trying to semantically interpret the resulting html. AFAIK the new button tag was exactly introduced to solve this issue.

In general it seems to me as if this suggestion was build bottom up from the desired rendering result and not top down from the semantics we want to encode in the UI. It seem to confuse "renders as" and "is a".

Best regards!

2017-06-13 09:39 UTC, alex40724 commented
I am fine with passing Buttons to the Dropdowns. I hope Timon can agree on this, otherwise I have no idea how to proceed, since he rejected DropdownItems and suggested Links.

I think we still need something that

> Links trigger interactions that change the view.

and

> Links MAY be used inline in a Textual Paragraph.

Would "Changing the view" (or screen?) be something that would fit the "references another resource in hypertext content" character?

And Buttons are clearly not allowed inline in Textual Paragraphs, right?

> It seem to confuse "renders as" and "is a".

I based the rendering part on your Button definition:

> Button is a clickable, graphically obtrusive control element.

Beside the inline use in text paragraphs this was the main differentiator to me. I think visual representation and "being something" should go hand in hand. Otherwise users might not learn what they get. And I barely think that they will identify the single items in a Dropdown as Buttons.

But as I said for me it is ok to shrink the link concept down to something that "changes views" and is allowed to be used inline in text paragraphs. Would this be ok?

And would open a modal be ok for a link (since it is some kind of other view/screen/resource)? Otherwise I do not know how to implement features like this: http://www.ilias.de/docu/goto.php?target=wiki_1357_Usability_Improvements_Marginal_List_Calendar

2017-06-13 11:20 UTC, Amstutz commented
Hello @alex40724 @klees ,

I think we need the concept you are proposing here @alex40724. Thanks for this PR! 

I just had a talk with Richard and I think the issue he has boils down to the naming of this component. I somewhat feel responsible for this issue, since it was me initially proposed to name this "Link". However, Richards point that this is not really a proper Hyperlink if just a JS event is fired is valid. Alexandra and I somehow also stumbled over this while researching different button types last year. We stumbled upon this "Shy Button" or "btn-link" which is a button that mymics a link. 

Therefore I propose the following and hope that everybody can agree to that (if I understood @klees correctly in the previous talk, he seems fine with that):

- We implement this as Button -> Shy (Reads as "Shy Button")
- This is a button the mimics a link (including the a tag)

I think lots of the description/rules that you provided alex (big thanks for that) can be reused. There are some slight adjustements to be made.  If you want I can provide them.

2017-06-13 11:31 UTC, alex40724 commented
So we implement a Shy Button extending the buttons and I can pass an array of Shy Buttons and Dividers to the Dropdown constructor, right?

2017-06-13 12:05 UTC, Amstutz commented
@alex40724:

> So we implement a Shy Button extending the Button and I can pass an array of Shy Buttons and Dividers to the Dropdown constructor, right?

Yes to the Shy Buttons, yes to the dividers from my point of view. I did not talk the dividers through with @klees. See my comment in: https://github.com/ILIAS-eLearning/ILIAS/pull/550

> And: If I want a "real hyperlink" in running text, I would not use a Shy Button, right?

Regarding the description of "Buttons" no, it would be better to implement the Hyperlink for that. However, that is for another day.

2017-06-13 12:23 UTC, klees commented
I'm very happy with the shy-button.

2017-06-13 21:20 UTC, alex40724 commented
Here we go https://github.com/ILIAS-eLearning/ILIAS/pull/556

2017-06-13 21:21 UTC, alex40724 commented
@klees @Amstutz 

I have reduced to Link proposal here now to reflect the idea of a hypertext link.

Feel free to suggest changes for description/rules and more in the comments.

2017-06-14 04:07 UTC, Amstutz commented on src/UI/Factory.php
> +	 *      presented.
Maybe add: "Links are not used to trigger JS-Events" or similar.

2017-06-14 04:17 UTC, Amstutz reviewed
Thanks a lot for updating this. This is definitely JF ready. I have some suggestions on the description. Use them as you like.

Some comments:
- Depending on the outcome of the Data Type Link discussion, we should use this data type here. Since this is yet ongoing, string is fine with me for the moment.
- Add tests for the final merge.

2017-06-14 04:17 UTC, Amstutz commented on src/UI/Factory.php
> +	 *      bear text or other content.
Maybe add: Links always contain a valid href tag (which should not just contain a hash tag).

2017-06-14 04:17 UTC, Amstutz commented on src/UI/Factory.php
> +	 *      presented.
Maybe add: "Links are not used to trigger JS-Events" or similar.

2017-06-14 04:17 UTC, Amstutz commented on src/UI/Factory.php
> +	 *          status. Buttons are much more obtrusive than links.
Maybe add: Buttons might fire JS-Events, links not.

2017-06-14 04:17 UTC, Amstutz commented on src/UI/Factory.php
> +	 *           Hovering an active link should indicate a possible interaction.
Links MUST not be used to fire JS Event. Use a Shy Button instead.

2017-06-14 04:17 UTC, Amstutz commented on src/UI/Implementation/Component/Link/Link.php
> + * This implements commonalities between standard and primary buttons.
Change this to link

2017-06-14 07:32 UTC, klees approved these changes

2017-06-14 07:34 UTC, klees commented
Thanks a lot for your patience. If we came to an agreement about the "link"-type, I would add it here, but atm I do not think we still need it. @nhaagen will be able to reuse this in the meantime.

2017-06-19 16:25 UTC, matthiaskunkel commented
Jour Fixe, June 19, 2017: Pull request accepted. Please consider Timon's suggestions in the discussion part.

2017-06-21 07:33 UTC, alex40724 commented
@Amstutz I modified the rules according to your suggestions and added tests. Can you approve this for the trunk?

2017-06-21 14:59 UTC, Amstutz approved these changes

2017-06-21 15:30 UTC, merged