UI Shy Button
ILIAS-eLearning/ILIAS pull request #556
Opened 2017-06-13 20:57 UTC by alex40724

2017-06-13 21:01 UTC, alex40724 commented
@Amstutz Feel free to add alternative description/rules in the comments.

2017-06-14 04:32 UTC, Amstutz reviewed
Thanks a lot. Looks good to me and is JF ready. For the final merge we need tests. Consider renaming the corresponding css class to btn-shy. I will take care of the final version of the less as soon as this is merged, since I am working on some less improvements for buttons anyways, see: https://github.com/ILIAS-eLearning/ILIAS/pull/554

2017-06-14 04:32 UTC, Amstutz commented on src/UI/templates/default/Button/tpl.shy.html
> +<a class="btn btn-link<!-- BEGIN disabled --> ilSubmitInactive<!-- END disabled -->"<!-- BEGIN with_href --> href="{HREF}"<!-- END with_href --> data-action="{ACTION}"<!-- BEGIN with_id --> id="{ID}"
why not naming this class btn-shy? I think this would be easier to comprehend.

2017-06-14 04:32 UTC, Amstutz commented on src/UI/templates/default/Button/button.less
> +}
Note, we have some relations here to: https://github.com/ILIAS-eLearning/ILIAS/pull/554. I will adapt this accordingly as soon as accepted/merged.

2017-06-14 04:32 UTC, Amstutz commented on src/UI/Component/Button/Factory.php
> +	 *           standard button presentation.
Good!

2017-06-14 07:02 UTC, klees approved these changes
This to me feels a lot more correct than link. Thanks a lot for your patience. This also solves a discussion @Amstutz and me had some time ago, i.e. "what are these links in the footer?".

2017-06-14 07:32 UTC, Amstutz commented
@klees Thank you for your vigor in striving for the best possible quality of this service!

2017-06-14 08:20 UTC, alex40724 commented on src/UI/templates/default/Button/tpl.shy.html
> +<a class="btn btn-link<!-- BEGIN disabled --> ilSubmitInactive<!-- END disabled -->"<!-- BEGIN with_href --> href="{HREF}"<!-- END with_href --> data-action="{ACTION}"<!-- BEGIN with_id --> id="{ID}"
btn-link is an existing bootstrap class for this purpose, btn-shy is not:
http://getbootstrap.com/css/#buttons-options

2017-06-19 13:42 UTC, matthiaskunkel commented
Jour Fixe, June 19, 2017: Pull request accepted. Please merge to trunk.

2017-06-21 09:21 UTC, alex40724 commented
@Amstutz @klees 
I have added the tests for the Shy Button. I am not sure if my interpretation of the button test setup is correct. So please let me know, if I missed something or anything needs to be added before merging this to the trunk.

2017-06-21 14:31 UTC, Amstutz commented on src/UI/templates/default/Button/tpl.shy.html
> +<a class="btn btn-link<!-- BEGIN disabled --> ilSubmitInactive<!-- END disabled -->"<!-- BEGIN with_href --> href="{HREF}"<!-- END with_href --> data-action="{ACTION}"<!-- BEGIN with_id --> id="{ID}"
accepted.

2017-06-21 14:38 UTC, Amstutz requested changes
Everything looks ready to be merged except one detail:
- Please add a further test to check for the correct html output. See test_render_close_button() as an example.

2017-06-21 14:53 UTC, alex40724 commented
@Amstutz But this is already done by all the methods like 
test_button_with_label($factory_method)
test_button_action($factory_method)
test_button_activated_on_default($factory_method)
...

2017-06-21 14:56 UTC, merged