trunk setup/import/export: implement an import/export mechanism
ILIAS-eLearning/ILIAS pull request #5561
Opened 2023-02-13 13:55 UTC by daniwe4

2023-02-24 15:09 UTC, klees commented
Hi @daniwe4,

please implement this with https://github.com/ifsnop/mysqldump-php instead of mysqldump.

Thanks!

2023-05-05 12:27 UTC, chfsx commented
Thank you for this suggestion and also that it has already been switched to the library so that additional exec calls do not have to be introduced.

With the help of this implementation, we can finally integrate large parts of our build process into ILIAS, as until now we had to work with a bash script to generate the database template for new ILIAS versions: https://github.com/ILIAS-eLearning/ilias-build-release/blob/master/ilias-build-release#L60

In order to be able to replace this part of the process, the PR still needs the following extensions:

1. when generating a dump, we need to be able to export certain tables empty, for example. For example, the table il_plugin should not have any content, even if the instance used to create the template has installed some. For this we need a general hook to export such tables empty. some tables we don't want to export completely empty, but for example only individual entries. An example would be the user_data, where we only want to export the entries of root and anonymous, ignoring all others.
2. some data has to be modified when building the template, for example the md5-hash of "homer" has to be exported for root in the usr_data together with the enc_type md5, so that people can log in on a newly installed ILIAS.

@fwolf-ilias  could give more examples if necessary. For the two cases, however, we could certainly use the following hooks of the library:

- https://github.com/ifsnop/mysqldump-php#changing-values-when-exporting
- https://github.com/ifsnop/mysqldump-php#table-specific-export-conditions

However, both work with anonymous functions, which I would like to wrap in an interface or in small DTOs so that the use is clearer and the connection to the library is smaller.

Do you want to work out a proposal for this or do we want to get together to look at this in more detail? especially how consumers could then use the API and we can cover the core-build case.

2023-05-05 13:14 UTC, chfsx requested changes
see comment above

2023-06-07 13:46 UTC, daniwe4 commented
Hello @chfsx , I have tried to implement your above requirements and have recorded this in the setup/README.md. I hope it corresponds to what you imagined.
Greetings Daniel

2023-10-03 04:49 UTC, chfsx requested changes
@daniwe4 thanks for the updated PR! there is just onbe small change requested now, since the class doesn't use exec anymore it should be renamed to something else, maybe `PHPMysqlDumper`

2023-10-03 04:49 UTC, chfsx commented on Services/Database/classes/Setup/MysqlExecDumper.php
> +class MysqlExecDumper implements MysqlDumper
The class should be renamed since this doesn't user `exec` anymore, right?

2023-10-09 06:13 UTC, daniwe4 commented on Services/Database/classes/Setup/MysqlExecDumper.php
> +class MysqlExecDumper implements MysqlDumper
Done!

2023-10-09 06:37 UTC, merged

2023-10-16 13:16 UTC, matthiaskunkel commented
I set the Jour Fixe tag to this PR to notify us about the added library 'mysqldump-php' that was already committed to trunk in February 2023.

2023-10-30 09:39 UTC, klees commented
Description of the change [here](https://docu.ilias.de/goto_docu_wiki_wpage_8047_1357.html).

2023-10-30 12:50 UTC, nicoroeser commented on setup/README.md
> +* There are also named objectives for **import** and **export**. <plugin name>` will exclude the named plugin from the command
Line broken at wrong offset, I think. `--skip` and ` <plugin name>` probably should be kept together.

2023-10-30 13:00 UTC, nicoroeser commented on Services/FileSystem/classes/Setup/class.ilFileSystemDirectoryCopiedRecursivelyObjective.php
> +     * $target_folder should always be the path wehre to copy into.
Typo: “wehre”.

2023-10-30 13:00 UTC, matthiaskunkel commented
Jour Fixe, 30 OCT 2023: Fabian notified us about the library that has already been merged to trunk. We highly appreciate this suggestion and accept the PR for Trunk.