LSO: add column 'LPSettings' to content-table
ILIAS-eLearning/ILIAS pull request #5564
Opened 2023-02-14 15:56 UTC by nhaagen

https://docu.ilias.de/goto_docu_wiki_wpage_7722_1357.html

2023-04-25 05:42 UTC, kergomard requested changes
Thank you very much for the PR @nhaagen !

To be honest: I'm completely unhappy with this class and it got a little worse with your changes, ...but this is not your fault! And right now I won't have the resources to get this to the point where you can make your changes in a more solid way.

So, I have a question/request:

- Do we really need to have [this function](https://github.com/ILIAS-eLearning/ILIAS/pull/5564/files#diff-6539c073d041b3cdae18a3da02ee6f716826ddef66ccd84d0ea96396157e2043R3411) `public`? I don't think we are using it outside the class itself, right? I would thus, if in any shape way or form possible, like to set it to `private`. If there is something preventing us from doing that: Could you please declare it `final` and `deprecate` it right away? We really need to find a better way.

Thanks again and best,
@kergomard

2023-04-25 06:35 UTC, klees commented
Thx @kergomard. I agree wholeheartedly.

2023-04-25 15:06 UTC, kergomard approved these changes

2023-04-26 12:36 UTC, klees commented
I have worked with the commits a little, so now this implements:

* [Learning Sequence: Improve Handling of Learning Progress Settings of Sub-Objects](https://docu.ilias.de/goto_docu_wiki_wpage_7722_1357.html)
* [Learning Sequence: Improve Usability of Objects without Kiosk-Mode (slightly)](https://docu.ilias.de/goto_docu_wiki_wpage_7707_1357.html)

2023-04-26 12:37 UTC, merged