UI Dropdown (Rebased #544)
ILIAS-eLearning/ILIAS pull request #560
Opened 2017-06-21 19:52 UTC by alex40724

2017-06-22 13:48 UTC, alex40724 commented
Sorry that this is another PR, but I rebased my branch which completely confused the existing PR. I have no idea why two pull requests with the same source and target branches look so differently now.

@Amstutz: I made small changes related to the JF comments and the implementation is now using divider->horizontal and button->shy. I also added unit tests. Can you approve this for the trunk, please.

2017-06-23 09:29 UTC, Amstutz commented on src/UI/Factory.php
> +	 *           Dropdown Items are being implemented as "ul" list with a set of "li" elements and
MUST be implemented

2017-06-23 09:30 UTC, Amstutz commented on src/UI/Implementation/Component/Dropdown/Renderer.php
> +			$tpl->parseCurrentBlock();*/
Please remove unused code.

2017-06-23 09:32 UTC, Amstutz commented on src/UI/Factory.php
> +	 * @return  \ILIAS\UI\Component\DropDown\Factory
Dropdown, not DropDown. This will lead to a failing test case in MainFactoryTest (from AbstractFactoryTest).

2017-06-23 09:35 UTC, Amstutz commented on src/UI/templates/default/Dropdown/dropdown.less
> +	margin: 9px 0;
Either use padding-large-vertical (defaults to 6px) here or introduce a new variable.

2017-06-23 09:36 UTC, Amstutz commented on src/UI/templates/default/Dropdown/dropdown.less
> +	margin: 3px 0;
Use padding-base-vertical here.

2017-06-23 09:37 UTC, Amstutz requested changes
Looks good to me. There are some slight adjustments I ask to make, then this can be merged.

2017-06-23 12:01 UTC, merged