UI Breadcrumbs
ILIAS-eLearning/ILIAS pull request #561
Opened 2017-06-22 07:59 UTC by nhaagen

This is a Breadcrumbs-implementation for UI making use of UILinks.

2017-06-22 13:59 UTC, alex40724 commented
Looks good to me.

2017-06-29 15:10 UTC, Amstutz commented
LGTM in general. 

However, please move the content of https://github.com/ILIAS-eLearning/ILIAS/blob/release_5-2/templates/default/less/Services/Locator/delos.less next to the template. Also refactor it slightly:
```
/* Services/Locator */

ol.breadcrumb {
	margin: 0;
	font-weight: 600; <-- introduce a new breadcrum variable for this.
	padding-left: 15px; <-- use @padding-large-horizontal
	font-size: .8em; <-- use @font-size-base or a variation of is.
}

[dir="rtl"] ol.breadcrumb {
	padding-right: 15px; <-- use @padding-large-horizontal
}

.breadcrumb a {
/*	color: #a0a0a0; */ <-- Maybe delete this block?
}

.breadcrumb > li + li:before {
/*	 color: #a0a0a0; */ <-- Maybe delete this block?
 }
```

2017-06-29 15:10 UTC, Amstutz requested changes
Please fix conflicts, run tests again and slightly refactor less.

2017-06-30 08:54 UTC, Amstutz approved these changes
Thank you very much.

2017-06-30 11:09 UTC, nhaagen commented
You're most welcome. Will you hit the merge-button?

2017-06-30 12:08 UTC, Amstutz commented
Normally you could as soon as this is accepted. However in this particular case, I just realised we also need the JF approval for this (thx @klees). This is already done for Icons und Tags... So we discuss this on monday and you can merge that on monday evening if accepted by JF.

2017-06-30 12:13 UTC, nhaagen commented
Thanks; however, I cannot merge (also Icons/Tags), since I have no write access to ILIAS...

2017-07-03 11:34 UTC, klees reviewed
LGTM in general, minor wording issue.

2017-07-03 11:34 UTC, klees commented on src/UI/Factory.php
> +	public function breadcrumbs($crumbs);
Hint `array` here.

2017-07-03 11:34 UTC, klees commented on src/UI/Factory.php
> +	 *     1: Crumbs MUST trigger navigation.
navigation = page change?

2017-07-03 11:34 UTC, klees commented on src/UI/Component/Breadcrumbs/Breadcrumbs.php
> +	public function getCrumbs();
`getEntries` please.

2017-07-03 12:08 UTC, atoedt commented on src/UI/Factory.php
> +	 *     Breadcrumbs is a type of secondary navigation scheme. It eases the
Breadcrumbs is a supplemental navigation scheme.

2017-07-03 12:08 UTC, atoedt commented on src/UI/Factory.php
> +	 *     user's navigation back to higher items in hierarchical (or prior items
Users user's can backtrack the path they have taken in the tree. The backtracking is supported for hierarchical and temporal structures.

2017-07-03 12:08 UTC, atoedt commented on src/UI/Factory.php
> +	 *     Breadcrumbs also serve as an effective visual aid indicating the
This sentence must go if the Beardcrums is conceptualized to encompass the "prior items". They are no way an effective visual aide to locate anything. They offer the opportuntiy to backtrack but they do not help locating anything.

2017-07-03 12:08 UTC, atoedt commented on src/UI/Factory.php
> +	 *     The term is based on the story of Hansel and Gretel and is well established,
The Adriadne and Grimms sentence does not add specificity. Please remove.

2017-07-03 12:08 UTC, atoedt commented on src/UI/Factory.php
> +	 *     user's navigation back to higher items in hierarchical (or prior items
Please think long and hard whether to include "prior items" or not

2017-07-03 12:08 UTC, atoedt commented on src/UI/Factory.php
> +	 *     Breadcrumbs-entries are rendered as horizontally arranged UI Links
does not apply to prior items 
consider dropping the horizontally or adding a vertically

2017-07-03 12:08 UTC, atoedt commented on src/UI/Factory.php
> +	 * ---
Breadcrums MUST NOT entail objects users have no Visible permission for.

2017-07-03 12:08 UTC, atoedt commented on src/UI/Factory.php
> +	 *     1: Crumbs MUST trigger navigation.
what is a page? 
Change from object to object, from reporitory to PD or Administration
Minimally from one sub-item of an Objects to another or from one sub-tab to another

2017-07-03 12:16 UTC, matthiaskunkel commented on src/UI/Factory.php
> +	 *     user's navigation back to higher items in hierarchical (or prior items
Jour Fixe: please remove "(or prior items in chronological)"

2017-07-03 12:23 UTC, matthiaskunkel commented on src/UI/Factory.php
> +	 *     user's navigation back to higher items in hierarchical (or prior items
Please remove "back" from the description.

2017-07-03 12:24 UTC, matthiaskunkel commented on src/UI/Factory.php
> +	 *     Breadcrumbs also serve as an effective visual aid indicating the
Rejected

2017-07-03 12:25 UTC, matthiaskunkel commented on src/UI/Factory.php
> +	 *     Breadcrumbs-entries are rendered as horizontally arranged UI Links
rejected

2017-07-03 12:28 UTC, matthiaskunkel commented on src/UI/Factory.php
> +	 * context: >
Please add the following contextes:
- search results
- info page
- the no-name space under the main menu

2017-07-03 12:32 UTC, matthiaskunkel commented on src/UI/Factory.php
> +	 *     1: Crumbs MUST trigger navigation.
Jour Fixe: "Crumbs must trigger navigation to other resources of the system." (similar to Link definition)

2017-07-03 12:33 UTC, klees commented on src/UI/Factory.php
> +	 * ---
"Breadcrumbs MUST only entail resources that are visible to the user."

2017-07-03 12:36 UTC, klees commented on src/UI/Component/Breadcrumbs/Breadcrumbs.php
> +	public function getCrumbs();
Please rename the entries to `items` completely, as we use this wording in the rules.

2017-07-03 12:36 UTC, matthiaskunkel commented on src/UI/Factory.php
> +	 * ---
Jour Fixe: We skip this as it is only related to repository object.

2017-07-03 12:38 UTC, matthiaskunkel commented on src/UI/Component/Breadcrumbs/Breadcrumbs.php
> +	public function withAppendedEntry($crumb);
Jour Fixe: Rename to 'withAppendedItem'

2017-07-03 12:44 UTC, matthiaskunkel commented
Jour Fixe, July 03, 2017: Thank you for this pull request. We have added a few wording improvements. PR is appreciated and can be merged to trunk.

2017-07-07 14:20 UTC, klees commented
Hi @nhaagen, please add the context mentioned in the open comment from @matthiaskunkel, solve conflicts and then contact me immediately, so I can push the "Merge"-button.

2017-07-07 14:30 UTC, merged