UI Viewcontrol (formerly 549 and #548)
ILIAS-eLearning/ILIAS pull request #564
Opened 2017-06-25 18:16 UTC by xus

2017-06-28 07:42 UTC, Amstutz commented
Is this ready for a final review?

2017-06-29 07:26 UTC, xus commented
@Amstutz yes, it is.

2017-06-29 07:49 UTC, xus commented on src/UI/Component/ViewControl/Factory.php
> +	 *      4: The currently active Button must be labeled by setting aria-checked to "true".
I've created a PR adding this aria tags in the button. #567

2017-06-29 07:58 UTC, xus commented on src/UI/Implementation/Component/ViewControl/Renderer.php
> +				$tpl->setVariable("BUTTON", $default_renderer->render($f->button()->standard($label, $action)->WithUnavailableAction()));
If the PR #567 is approved, then the standard button will get also: withAriaLabel("button definition")->withAriaChecked()));

2017-06-29 07:58 UTC, xus commented on src/UI/Implementation/Component/ViewControl/Renderer.php
> +				$tpl->setVariable("BUTTON", $default_renderer->render($f->button()->standard($label, $action)->withUnavailableAction()));
If the PR #567 is approved, then the standard button will get also: withAriaLabel("button definition")->withAriaChecked()));

2017-06-29 07:59 UTC, xus commented on src/UI/Implementation/Component/ViewControl/Renderer.php
> +				$tpl->setVariable("BUTTON", $default_renderer->render($f->button()->standard($label, $action)));
Same as commented before but without withAriaChecked()

2017-06-29 13:49 UTC, Amstutz requested changes
In general this looks good. However the less needs some further work. Please adjust.

2017-06-29 13:49 UTC, Amstutz commented on src/UI/Component/ViewControl/Factory.php
> +	 *      4: The currently active Button must be labeled by setting aria-checked to "true".
Thx.

2017-06-29 13:49 UTC, Amstutz commented on src/UI/Component/ViewControl/Section.php
> +	 * @return \ILIAS\UI\Component\Component the Default- or Split-Button placed in the middle of the control
Why not returning Button here? Month Button (not Split anymore)

2017-06-29 13:49 UTC, Amstutz commented on src/UI/Implementation/Component/ViewControl/Renderer.php
> +				$tpl->setVariable("BUTTON", $default_renderer->render($f->button()->standard($label, $action)->WithUnavailableAction()));
+1

2017-06-29 13:49 UTC, Amstutz commented on src/UI/Implementation/Component/ViewControl/Renderer.php
> +	const MODE_ARIA = "Mode View Controler";
This should be managed by language and chose a better text. E.g. "Change the currently displayed mode".

2017-06-29 13:49 UTC, Amstutz commented on src/UI/Implementation/Component/ViewControl/Renderer.php
> +				$tpl->setVariable("BUTTON", $default_renderer->render($f->button()->standard($label, $action)->withUnavailableAction()));
+1

2017-06-29 13:49 UTC, Amstutz commented on src/UI/examples/ViewControl/Mode/base.php
> +}
Please add a further example in which you mark an other button as active.

2017-06-29 13:49 UTC, Amstutz commented on src/UI/examples/ViewControl/Section/base.php
> +	$back = $f->button()->standard("a", "http://www.ilias.de");
Chose previous as label in the example here. Previous is a better choice, since it tells something about the role of the button.

2017-06-29 13:49 UTC, Amstutz commented on src/UI/examples/ViewControl/Section/base.php
> +	$next = $f->button()->standard("b", "http://www.github.com");
Chose next as label in the example here. Previous is a better choice, since it tells something about the role of the button.

2017-06-29 13:49 UTC, Amstutz commented on src/UI/templates/default/ViewControl/viewcontrol.less
> +  background-color: lighten(@brand-primary, 15%);
lighten(@brand-primary, 15%) must move into a less variable. see: https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/templates#colors. However, you might just use the bootstrap button-mixin for this: https://github.com/ILIAS-eLearning/ILIAS/blob/release_5-2/Services/UICore/lib/bootstrap-3.2.0/less/mixins/buttons.less. Probably use the same variables as are used for the default button:

```
.btn-default {
  .button-variant(@il-btn-standard-color; @il-btn-standard-bg; @il-btn-standard-border);
}
```

2017-06-29 13:49 UTC, Amstutz commented on src/UI/templates/default/ViewControl/viewcontrol.less
> +  border: 1px solid transparent;
See comment above.

2017-06-29 13:49 UTC, Amstutz commented on src/UI/templates/default/ViewControl/viewcontrol.less
> +  padding: 3px 8px;
Use: padding-base-vertical and padding-base-horizontal here.

2017-06-29 13:49 UTC, Amstutz commented on src/UI/templates/default/ViewControl/viewcontrol.less
> +  top: 2px;
There is still something a little off in the positioning. The button in the middle is a little further down than the others.

2017-06-29 13:49 UTC, Amstutz commented on src/UI/templates/default/ViewControl/viewcontrol.less
> +  color:@component-active-color;
See comment above.

2017-06-29 13:49 UTC, Amstutz commented on src/UI/templates/default/ViewControl/viewcontrol.less
> +  background-color:@brand-primary; //todo search the proper color.
See comment above.

2017-06-29 16:18 UTC, alex40724 commented on src/UI/Implementation/Component/ViewControl/Renderer.php
> +	const MODE_ARIA = "Mode View Controler";
@xus see, e.g. 
$tpl->setVariable("LABEL", $this->txt($component->getAriaLabel()));
in src/UI/Implementation/Component/Glyph/Renderer.php

2017-07-06 15:24 UTC, xus commented
Hi @Amstutz @alex40724 I have to merge this manually. I've already fixed the conflicts in my local trunk branch + adapted the unit tests. Can I merge this?

2017-07-06 15:31 UTC, alex40724 commented
@xus Please add this to the trunk. I will discuss the less with Timon as soon as he is back from vacation.

2017-07-07 07:47 UTC, xus commented
Merged manually into the trunk.

2017-07-07 07:47 UTC, closed without merging