Object: Refactor AutoRating
ILIAS-eLearning/ILIAS pull request #5665
Opened 2023-03-08 14:52 UTC by kergomard

Couldn't we move the whole auto-rating stuff to `ilObject::putInTree()`? This to me looks far more logical. It changes the behavior slightly, as this would also set the notifications, when an object with auto-rating is linked.

See: https://mantis.ilias.de/view.php?id=34112

2023-03-08 14:58 UTC, kergomard commented on Modules/LTIConsumer/classes/class.ilObjLTIConsumerGUI.php
> -            $gui->handleAutoRating($newObj);
@Uwe-Kohnle : I'm unsure why you are doing this manually here. Would the putInTree()-Approach cover your cases?

2023-03-09 08:48 UTC, alex40724 requested changes
First of all, I think we agree that this is not well de-coupled code. But this change would not work:

"It changes the behavior slightly, as this would also set the notifications, when an object with auto-rating is linked."

Which would be simply wrong behaviour = bug. This is intended to be set for new objects, not for existing ones being linked. This might lead to great confusion if existing objects are suddenly changed due to linking in the background.

2023-03-09 10:07 UTC, alex40724 commented
The rating service could set this listening to an object event that is fired on creation, but including the ref id. This would remove the rating code from the object service.

The event 'Services/Object'/'create' does not include the ref id. 
The event 'Services/Object' / 'putObjectInTree' is not only creation related.

In my opinion the main problem is, that ilObjectGUI->saveObject contains the interesting business logic, which is wronly placed in a GUI class. The BL here is the process "create > putintree > apply didactic templates > handle auto rating".

These steps should be performed in a method in ilObject instead. And I think this method then should be called, e.g. in createFileObj of ilObjFileAbstractProcessor, which currently does putintree (but not applying didactic templates or handle auto rating) itself.

If this method would exist in ilObject, it could raise an event at the end. The rating service could listen to this event, so the rating code would disappear from the Object service.

2023-03-10 09:04 UTC, kergomard commented
@alex40724 : I think the behavior can actually be changed more easily. This is not the most elegant of all solutions, but it is a step in the right direction, from where I stand.

2023-03-10 09:09 UTC, kergomard commented on Modules/File/classes/Processors/class.ilObjFileAbstractProcessor.php
> +        $file_obj->processAutoRating();
@chfsx : FYI.

2023-03-10 09:31 UTC, chfsx commented on Modules/File/classes/Processors/class.ilObjFileAbstractProcessor.php
> +        $file_obj->processAutoRating();
@kergomard Thanks a lot!

2023-03-14 10:57 UTC, kergomard commented
@alex40724 and @Uwe-Kohnle : Could you maybe have a look at the changes in your part of the code until the end of the week? This way, we could merge this and get rid of one more issue in ILIAS 8. Thank you very much!

2023-03-20 06:55 UTC, kergomard commented
Hi @alex40724 and @Uwe-Kohnle 
This is a notice in case you see this differently: I will merge this on Wednesday 2023-03-22. I think the changes in your components are trivial enough and we should get rid of this error, before the release of ILIAS8.
Thank you very much and best,
@kergomard

2023-03-30 05:51 UTC, kergomard commented
Hi @alex40724 and @Uwe-Kohnle 
After contacting you through multiple channels I didn't get any feedback on this PR. This is the last call. I will merge this tomorrow Friday 31 of March in the morning.
Best,
@kergomard

2023-03-31 08:53 UTC, merged