Notifications: Upgrade to PHP 8.1
ILIAS-eLearning/ILIAS pull request #5669
Opened 2023-03-10 14:07 UTC by mjansenDatabay

2023-03-10 15:12 UTC, iszmais requested changes
LGTM Just 2 minor missing unions types

2023-03-10 15:12 UTC, iszmais commented on Services/Notifications/classes/Model/ilNotificationLink.php
> +    public function __construct(private $title, private string $url)
I recommend using Union type inside the constructor paramter instead of docu

2023-03-10 15:12 UTC, iszmais commented on Services/Notifications/classes/class.ilObjNotificationAdminGUI.php
>      protected function getForm(array $values = null): Form
I recommend Union Type here (array|null)

2023-03-13 07:25 UTC, mjansenDatabay commented on Services/Notifications/classes/Model/ilNotificationLink.php
> +    public function __construct(private $title, private string $url)
We still should avoid union types in productive code in ILIAS (except for rare cases where native PHP classes/interfaces required to explicitly set a union type).

2023-03-13 09:43 UTC, iszmais commented on Services/Notifications/classes/Model/ilNotificationLink.php
> +    public function __construct(private $title, private string $url)
I agree that we should the usage, but if its used it should be typed as such.

Or did i understand you wrong here?

2023-03-13 09:44 UTC, iszmais commented on Services/Notifications/classes/Model/ilNotificationLink.php
> +    public function __construct(private $title, private string $url)
An alternative might be to stricten the paramter itsself to make the usage of a unions time unneccessary

2023-03-13 10:46 UTC, iszmais approved these changes

2023-03-13 11:05 UTC, merged