Use refactored notification provider functions
ILIAS-eLearning/ILIAS pull request #5702
Opened 2023-03-16 18:13 UTC by iszmais

**DEPENDS ON https://github.com/ILIAS-eLearning/ILIAS/pull/5698**

With the merge of the depending PR the usage of OSDNotifcation obliges the Service to handle the cleanup of its own notifications. Therefore the refactored Notification System provider a new feature trough the NotifcationProvider from wich this service heritages, to delete your own Notifcation with a safe named key.

You can set that key within your Notification config with the function `setProviderKey()`

If an event causes the Notification to be irelevant it can be deleted by that key with a new function in your NotificationProvider Inehitance `removeOSDNotificationsByProviderKey()` wich optional recieves a user ID to remove this OSD for on user. Otherwise its removed for all users.

Further you can cleanup all old notifications with the function `deleteStaleNotifications()`. I encourage you to do so if your service produces a lot of notifications.

2023-03-16 18:16 UTC, iszmais commented
@alex40724  This PR already covers the obvious parts wich can be handler by the provider and already sets a provider key.
Since im not familiar with the component i would appreciate if you could add the removal/cleanup calls on the required cases.
(Or Feel free to present your own approach on that).

2023-03-17 07:45 UTC, mjansenDatabay requested changes

2023-03-17 07:45 UTC, mjansenDatabay commented on Services/Badge/classes/class.ilBadgeHandler.php
> +                    $notification = $provider->getNotificationConfig();
What is unclear to me is the coupling to the notification provider here. Conceptually we know, that some (**not**all) of the `Toast` elements collected and handled by the `GS` are based on the `OSD` notification channel. So depending on the concrete `Toast Provider`, there might (**not** must) be a dependency to the `OSD` notifications from the direction of the `Toast` provider. But IMO there should be no coupling to the `GS Notifications` here.

2023-03-17 07:45 UTC, mjansenDatabay commented on Services/Badge/classes/class.ilBadgeHandler.php
> +                    $notification->setProviderKey(self::BADGES);
IMO this does not help. The notification emitted through `Services/Notifications` here must be provided with a **unique** `Identification`. Instead, you pass a static `badges` as key. How should the `Services/Badges` in turn emit a signal to `Services/Notifications`, that the notification sent in the past is not longer valid and should be removed?

2023-03-17 12:04 UTC, closed without merging