ECS: Allow to Add ECS to Kitchensink-Forms
ILIAS-eLearning/ILIAS pull request #5799
Opened 2023-04-13 07:43 UTC by kergomard

Hi @pascalseeland 
This PR adds an Option to add ECS-Settings as a KS-Input-Section to Settings-Forms. I did this, to enable the move of the general settings of the Test to KS-Forms.

The changes in `ECSSettingsGUI` are just a fix for an issue with types of POST-Values that came to be a problem because of the use of strict types.
The naming in `ilECSObjectSettings` is a little funky for my taste, I tried to find a workable naming, but let me know, if you would like it otherwise.

I tested the functionality with some spoofed data and everything works as far as I can see, but sadly, I don't have an ECS-Server at my disposal.

Thank you very much and best,
@kergomard

2023-05-12 14:48 UTC, kergomard commented
@pascalseeland : Any chance of a feedback on this?

Thank you very much and best!

2023-06-01 07:45 UTC, kergomard commented
Hi @pascalseeland 

I would be very grateful if you could have a look at this.

Thanks and best,
@kergomard

2023-07-03 03:43 UTC, pascalseeland requested changes
Please fix the missing renaming of variables in lines 145, 160 and 180 as it breaks the code.

2023-07-03 03:43 UTC, pascalseeland commented on Services/WebServices/ECS/classes/class.ilECSObjectSettings.php
> +        $exportable_participants = (new ilECSParticipantSettingsRepository())->getExportableParticipants($a_type);
This renames the used variables from exportManager to export_manager, which causes issues in the rest of this method. Same issue exists with exportableParticipants.

2023-07-03 03:43 UTC, pascalseeland commented on Services/WebServices/ECS/classes/class.ilECSObjectSettings.php
> -        $obj_id = $this->content_obj->getId();
This variable is used in the rest of this method. If it is removed here, the rest of the usages need to be changed as well.

2023-07-03 06:43 UTC, kergomard commented
Hi @pascalseeland 
Thank you very much for your review! you are right and I fixed the issues. I also renamed a function I introduced from `ecsIsActivatableForObject` to `ecsCanBeActivatedforObject`.

Thanks and best,
Stephan

2023-07-03 12:10 UTC, merged