Dashboard (ILIAS 9): Feature: Global Sorting for Dashboard Sections
ILIAS-eLearning/ILIAS pull request #5801
Opened 2023-04-13 08:32 UTC by fhelfer

Feature Wiki: https://docu.ilias.de/goto_docu_wiki_wpage_7526_1357.html
Depends on: #4941

2023-07-24 09:16 UTC, fhelfer commented
@iszmais , @lscharmer, since https://github.com/ILIAS-eLearning/ILIAS/pull/4941 has been merged, this PR is no longer blocked. Can you leave a review?

2023-08-01 10:54 UTC, iszmais requested changes
Thank you for your effort @fhelfer !

I have 3 minor request i would reqeust you to change:
- Please Rename the language war of `topitem_title` to `topitem_block` to match its new translation. If this var is also used somewhere else, add an addtional var instead of replacing it.
- Pls shorten the length of the **Position** column. You may align it to the view of `Administration >> Layout and Navigation >> Main Menu`. I assume the proposal was made based on an old UI.
- Pls change the Input Type to numbers. We dont need to verifiy that in the backend, this is just to prevent a misusage of the UI.

2023-08-01 10:54 UTC, iszmais commented on Services/Dashboard/Administration/classes/class.ilDashboardSortationTableGUI.php
> +    private \ILIAS\UI\Factory $uiFactory;
Pls use use statements instead of inline pathing.

2023-08-01 10:54 UTC, iszmais commented on Services/Dashboard/ItemsBlock/classes/class.ilPDSelectedItemsBlockViewSettings.php
> +                throw new \InvalidArgumentException("Unknown view: $view");
Pls use use statements instead of inline pathing.

2023-08-01 10:54 UTC, iszmais commented on Services/Dashboard/Administration/classes/class.ilDashboardSortationTableGUI.php
> +            "tpl.dashboard_sortation_row.html",
The quotation through the whole PR seems inconsistent.
Please use singel quotes `'` if able.

2023-08-01 10:54 UTC, iszmais commented on Services/Dashboard/Administration/classes/class.ilDashboardSortationTableGUI.php
> +                ];
```suggestion
            ];
```

You **CAN** prevent such indentation errors by removing the last `,` in your formatted array.
This helps most IDEs to detect your end of array and therefore automatically fix the indentation.

2023-08-02 11:34 UTC, iszmais requested changes

2023-08-02 11:34 UTC, iszmais commented on Services/Dashboard/Administration/classes/class.ilDashboardSortationTableGUI.php
> +    private ilAccessHandler $access;
Is this used anywhere?
Else pls remove.

2023-08-02 12:46 UTC, lscharmer requested changes

2023-08-02 12:46 UTC, lscharmer commented on Services/Block/classes/class.ilColumnGUI.php
> +                    if ($this->getColType() === 'pd' && in_array(substr($type, 2), $this->dash_side_panel_settings->getValidModules())) {
Please use `in_array` only with  `strict = true` as such:
```suggestion
                    if ($this->getColType() === 'pd' && in_array(substr($type, 2), $this->dash_side_panel_settings->getValidModules(), true)) {
```

2023-08-02 12:46 UTC, lscharmer commented on Services/Dashboard/Administration/classes/class.ilObjDashboardSettingsGUI.php
> +                if (isset($form_data['side_panel']['enable'][$mod])) {
If block can be shortened:
```suggestion
                $this->side_panel_settings->enable($mod, (bool) ($form_data['side_panel']['enable'][$mod] ?? false));
```

2023-08-02 12:46 UTC, lscharmer commented on Services/Dashboard/ItemsBlock/classes/class.ilPDSelectedItemsBlockViewSettings.php
> +    public function getViewPositions(): array
Please add doc block for return type.

2023-08-02 12:46 UTC, lscharmer commented on Services/Dashboard/ItemsBlock/classes/class.ilDashboardSidePanelSettingsRepository.php
> +    public function getPositions(): array
Please add doc block for return type.

2023-08-07 09:20 UTC, lscharmer requested changes

2023-08-07 09:20 UTC, lscharmer commented on Services/Dashboard/ItemsBlock/classes/class.ilPDSelectedItemsBlockViewSettings.php
> +    public function setViewPositions(array $positions): void
Please add the doc type for the `$position` parameter. In general: If it is not specified in a parent class or interface, the type of an array parameter or return value should be written in the doc block.
If there are other instances where the doc block is missing, please add them accordingly.

2023-08-07 11:46 UTC, lscharmer approved these changes

2023-08-30 09:58 UTC, fhelfer commented
TestCases have been created & tested, PR ready for merge

2023-08-30 10:09 UTC, iszmais approved these changes

2023-08-30 11:20 UTC, iszmais commented
@fhelfer This looks great!
Thank you a lot for your effort and patience within the QA!

2023-08-30 11:21 UTC, merged