Dashboard (ILIAS 9): Feature: KS-ViewControls for Dashboard Sections
ILIAS-eLearning/ILIAS pull request #5804
Opened 2023-04-13 12:03 UTC by fhelfer

Feature Wiki: https://docu.ilias.de/goto_docu_wiki_wpage_7503_1357.html
Depends on #4941

2023-07-24 09:16 UTC, fhelfer commented
@iszmais , @lscharmer, since https://github.com/ILIAS-eLearning/ILIAS/pull/4941 has been merged, this PR is no longer blocked. Can you leave a review?

2023-08-02 13:22 UTC, lscharmer requested changes

2023-08-02 13:22 UTC, lscharmer commented on Services/Block/classes/class.ilBlockGUI.php
> +        if (in_array($this->getPresentation(), [self::PRES_SEC_LIST, self::PRES_MAIN_LIST]) &&
Please add parameter `strict = true` for `in_array`

2023-08-02 13:22 UTC, lscharmer commented on Services/Block/classes/class.ilBlockGUI.php
> +            (count($panel->getItemGroups()) == 0 || (count($panel->getItemGroups()) == 1 && count($panel->getItemGroups()[0]->getItems()) == 0))) {
Please change all `count(...) == 0` to `... === []`

2023-08-02 13:22 UTC, lscharmer commented on Services/Block/classes/class.ilBlockGUI.php
> +            if ($this->getPresentation() == self::PRES_SEC_LIST) {
```suggestion
            if ($this->getPresentation() === self::PRES_SEC_LIST) {
```

2023-08-02 13:22 UTC, lscharmer commented on Services/Block/classes/class.ilBlockGUI.php
> +        if (count($this->sort_options)) {
```suggestion
        if ($this->sort_options !== []) {
```

2023-08-02 13:22 UTC, lscharmer commented on Services/Block/classes/class.ilBlockGUI.php
> +            if (!is_null($pg_view_control)) {
```suggestion
            if ($pg_view_control !== null) {
```

2023-08-03 13:26 UTC, iszmais requested changes
LGTM :+1: 

Just some minor style change requests

2023-08-03 13:26 UTC, iszmais commented on Services/Block/classes/class.ilBlockGUI.php
> +        global $DIC;
This seems to be doubled.
Pls Remove.

2023-08-03 13:26 UTC, iszmais commented on Services/Block/classes/class.ilBlockGUI.php
> +    protected \ILIAS\UI\Factory $factory;
Pls use a `use` instead of inline pathing.

2023-08-03 13:26 UTC, iszmais commented on Services/Block/classes/class.ilBlockGUI.php
> +                $panel instanceof \ILIAS\UI\Component\Panel\Listing\Standard
Please use `use`

2023-08-07 09:24 UTC, lscharmer approved these changes

2023-08-30 09:58 UTC, fhelfer commented
TestCases have been created & tested, PR ready for merge

2023-08-30 10:07 UTC, iszmais approved these changes

2023-08-30 12:23 UTC, iszmais commented
@fhelfer Thank you again for your continuing effort for the ILIAS Project and be ensured of our appreciation!

2023-08-30 12:24 UTC, merged