MarkdownFormattingToHTML
ILIAS-eLearning/ILIAS pull request #5840
Opened 2023-04-24 14:39 UTC by chfsx

@klees this adds a new Transformation `MarkdownFormattingToHTML` which uses the library we decided to use to convert Markdown to HTML. This case is certainly an excellent example that can be converted within the framework of https://github.com/ILIAS-eLearning/ILIAS/blob/trunk/docs/development/text-handling.md. For the moment, however, it is important to offer this function centrally in order to be able to find all of its places.

2023-04-26 13:26 UTC, mjansenDatabay requested changes
Hi @chfsx ,

thank you a lot for contributing to the `Refinery`.

Please answer the following questions:
- [x] What do you mean by `a 'ä' isn't a 'ä' but a 'ä' ;-)`?

Please implement the following changes:
- [ ] Fix the access modifier of the overwritten `setUp` modifier in the unit test.

You already addressed the other topic I would have raised, namely the correlation to Richard's document.

Best regards,
@mjansenDatabay

2023-04-26 13:26 UTC, mjansenDatabay commented on tests/Refinery/String/MarkdownFormattingToHTMLTest.php
> +        // Never ever try to change something on this array :-) e.g. a 'ä' isn't a 'ä' but a 'ä' ;-)
Could you please provide more details here? I don't get it :-).

2023-04-26 13:26 UTC, mjansenDatabay commented on tests/Refinery/String/MarkdownFormattingToHTMLTest.php
> +    public function setUp(): void
```suggestion
    protected function setUp(): void
```

2023-05-01 07:24 UTC, chfsx commented
Hi @mjansenDatabay, thanks for the feedback!
> a 'ä' isn't a 'ä' but a 'ä' ;-)
this was a copy/paste mistake from https://github.com/ILIAS-eLearning/ILIAS/blob/trunk/tests/Refinery/String/UTFNormalTest.php :-) I removed the line
and changed the access modifier of `setUp`

2023-05-01 11:52 UTC, mjansenDatabay approved these changes

2023-05-01 11:53 UTC, merged