Trunk forum irss
ILIAS-eLearning/ILIAS pull request #5873
Opened 2023-05-04 08:24 UTC by nmatuschek

IRSS integration of forum drafts attachments

2023-06-19 10:06 UTC, mjansenDatabay requested changes
Thx a lot @nmatuschek .

Please fix the code style with:

```bash
php8.1 libs/composer/vendor/bin/php-cs-fixer fix --config=./CI/PHP-CS-Fixer/code-format.php_cs --using-cache=no  -vvv Modules/Forum/classes
```

2023-06-19 10:06 UTC, mjansenDatabay commented on Modules/Forum/classes/class.ilObjForum.php
> +            $draft_ids[] = (int)$row->draft_id;
```suggestion
            $draft_ids[] = (int) $row->draft_id;
```

2023-06-20 06:55 UTC, nmatuschek commented on Modules/Forum/classes/class.ilObjForum.php
> +            $draft_ids[] = (int)$row->draft_id;
ok. done. :-)

2023-06-20 07:17 UTC, mjansenDatabay approved these changes

2023-06-20 07:18 UTC, merged