[FIX] UI: fixed access before initialization error in Table\Presentation
ILIAS-eLearning/ILIAS pull request #5897
Opened 2023-05-09 12:41 UTC by thibsy

Hi all,

I noticed that rendering a `Table\Presentation` component without calling `::withData()` on it, an error is thrown because the `$records` property is accessed before initialization.

I've fixed this by initializing the value by default, so `::withData()` stays an optional method call and supplied an according unit-test for this. This should be picked for release_8 as well if accepted.

Kind regards,
@thibsy

2023-06-01 11:29 UTC, klees requested changes
Hi @thibsy,

as briefly discussed via Discord: We agree that simply showing a headline without anything below it will be confusing for users. We instead want to adapt the solution of `ilTable2GUI` and show some "There is no data here..."-message instead of the rows.

Thanks for taking care of this!

2023-07-10 07:08 UTC, thibsy commented
Hi @klees 

I have implemented empty table rows for the `Table\Presentation` and `Table\Data` table _in addition_ to the initial fix, which makes `Table\Presentation::withData()` optional again.

This PR introduces:
- a new language variable `ui_table_no_records`, which currently translates to `No records` and is used by both tables as a default message/content to indicate there's no data available.
- a new unit test for both renderings, which uses `str_contains()` to check only for the important aspects. Note the `PresentationTest:: testBareTableRendering()` case was not valid anymore, because this rendering test will now result in rendering the empty entry. I have replace the test accordingly.
- a new example for both tables, which demonstrate the default behaviour if no data has been provided. I think we might even provide some `Table::withNoRecordsMessage()` method in the future to provide more flexibility, or even add this to `DataRetrieval` because there might be different reasons for having no data (like permissions).
- unfortunately, some code-style changes, because #5970 got merged in the meantime, fixing arrow-function whitespaces.

I am open for better suggestions for the `ui_table_no_records` translations and the design for the new empty row for `Table\Presentation` tables =).

Kind regards,
@thibsy

2023-09-25 14:36 UTC, klees approved these changes
LGTM. Do we need @catenglaender or is this already styled nicely?

2023-09-25 14:50 UTC, thibsy commented
Hi @klees 

Here are the screenshots of how the empty tables look like right now:

![Screenshot 2023-09-25 at 16 44 39](https://github.com/ILIAS-eLearning/ILIAS/assets/30862472/6110711f-966d-4366-b139-5566d4a95e59)
![Screenshot 2023-09-25 at 16 44 00](https://github.com/ILIAS-eLearning/ILIAS/assets/30862472/94a84052-1ffd-4fb3-9234-5570c7b9a14b)

I think it looks okay-ish. Unless you or @catenglaender disagree?

Kind regards,
@thibsy

2023-09-25 15:24 UTC, klees commented
Looks fine for the moment IMO. Would merge now if conflicts are resolved.

2023-09-25 17:04 UTC, thibsy commented
@klees I've rebased onto trunk, this should be ready for merge then =).

2023-09-25 17:29 UTC, merged