Test: Fix form handling
ILIAS-eLearning/ILIAS pull request #5937
Opened 2023-05-25 07:13 UTC by mjansenDatabay

See: https://mantis.ilias.de/view.php?id=37383

2023-06-14 12:13 UTC, fneumann requested changes

2023-06-14 12:13 UTC, fneumann commented on Modules/Test/classes/class.ilObjTestSettingsGeneralGUI.php
> +                (new ilDateTime($starting_time, IL_CAL_DATETIME))->get(IL_CAL_UNIX) < (int) $this->testOBJ->getStartingTime()
must be $ending time in this comparison - otherwise it is not longer possible to change the starting time to a value prior to the saved one

2023-06-14 18:24 UTC, mjansenDatabay commented on Modules/Test/classes/class.ilObjTestSettingsGeneralGUI.php
> +                (new ilDateTime($starting_time, IL_CAL_DATETIME))->get(IL_CAL_UNIX) < (int) $this->testOBJ->getStartingTime()
Good catch @fneumann

2023-06-14 23:10 UTC, fneumann approved these changes

2023-06-21 09:10 UTC, kergomard commented
Ok, I merge this. I will see if we need parts of this in later versions. The basic should not occur there though, as far as I can see.

2023-06-21 09:10 UTC, merged