Individual Assessment get new permission amend finalized record
ILIAS-eLearning/ILIAS pull request #605
Opened 2017-08-11 13:59 UTC by shecken

With this PR the feature [Amend Finalized Records](https://www.ilias.de/docu/goto.php?target=wiki_1357_New_Permission%3A_Amend_Finalized_Records) will be implemented.

2017-08-18 08:17 UTC, klees requested changes
LGTM in general, thx for boyscouting. Please solve the naming issues.

2017-08-18 08:17 UTC, klees commented on Modules/IndividualAssessment/classes/class.ilIndividualAssessmentMembersGUI.php
> +		$this->iass_access = $this->object->accessHandler();
Why did you rename this?

2017-08-18 08:17 UTC, klees commented on Modules/IndividualAssessment/classes/AccessControl/class.ilIndividualAssessmentAccessHandler.php
> +		if (!isset($this->mass_global_permissions_cache[$iass_id][$user_id][$operation])) {
Please declare `mass_global_permissions_cache`.

2017-08-18 08:17 UTC, klees commented on Modules/IndividualAssessment/classes/AccessControl/class.ilIndividualAssessmentAccessHandler.php
> +	public function mayViewIass($use_cache = true)
Remove that `Iass`-suffix please. If you feel it is necessary to distinguish that method from `mayViewUser` by a suffix, use `Object`.

2017-08-18 08:17 UTC, klees commented on Modules/IndividualAssessment/classes/class.ilIndividualAssessmentMemberGUI.php
> +	protected function userCanGrade()
Why do you use `may` sometimes and `can` some other times?

2017-08-22 06:54 UTC, shecken commented on Modules/IndividualAssessment/classes/class.ilIndividualAssessmentMembersGUI.php
> +		$this->iass_access = $this->object->accessHandler();
iass has his own access handler class. Rename makes clear this is not the global ilias access handler.

2017-08-23 10:05 UTC, klees commented
@shecken Gna, please update once again.

2017-08-23 15:11 UTC, merged