Mt 32014 release 8
ILIAS-eLearning/ILIAS pull request #6061
Opened 2023-06-26 07:34 UTC by chlulei

Addresses mantis ticket 32014: https://mantis.ilias.de/view.php?id=32014

2023-06-29 14:20 UTC, smeyer-ilias requested changes
Thanks @chlulei, please fix the default value

2023-06-29 14:20 UTC, smeyer-ilias commented on Modules/Course/classes/class.ilObjCourseAdministrationGUI.php
> +        $checkBox->setChecked((bool) $this->settings->get(self::SETTING_COURSES_AND_GROUPS_ENABLED, 0));
Please set the default to "1"

2023-07-05 09:02 UTC, merged

2023-07-05 09:12 UTC, smeyer-ilias commented
Thanks @chlulei!

2023-07-05 10:44 UTC, iszmais commented
@chlulei Within the procession of the ticket i stumbled upon 1 criteria:
```Default status for both new settings is enabled.```
And since a default should be enforced by the providing source and not the the demanding i would appreciate if you could also add an update step to set such default, just like @alex40724 did in the similar setting: https://github.com/ILIAS-eLearning/ILIAS/commit/28962f2945712d231c94cb322f0e39e3ec9b6e13