Implemented HelpId as Attributes
ILIAS-eLearning/ILIAS pull request #6092
Opened 2023-06-30 13:17 UTC by chfsx

This PR brings the functionality of persisting Help-IDs as described in https://docu.ilias.de/goto_docu_wiki_wpage_6926_1357.html

As requested by the JF, the rector is now no longer part of the PR, but you can view it [here](https://github.com/srsolutionsag/ILIAS/commit/897c4f7a2838badba812145ddd7d54b001665415). @alex40724 you may want to use it to automatically switch or remove the old method calls from ilHelp. please get in touch if i can be of any help.

2023-09-19 09:51 UTC, alex40724 commented
@chfsx Thanks for the PR and sorry for the delay. I am currently waiting for https://mantis.ilias.de/view.php?id=37753 being fixed to try out the full scenario in a branch. This might become an ILIAS 10 refactoring. I will provide more feedback once I setup a technical prototype.

2023-10-31 15:21 UTC, alex40724 requested changes
Thanks again for this PR. This is now definitely an ILIAS 10 development. I will take care of the changes, once funding is settled. I will take care of the necessary changes and merge.

2024-05-14 10:56 UTC, klees commented
Hi @alex40724 ,

we are checking older PRs without activity in the Technical Board regularly. So this PR popped up. Is there anything that needs to or can be done here? Can we do anything to help?

Kind regards!

2024-07-29 14:01 UTC, alex40724 commented
Plan is still to integrate this into ILIAS 10. There is a follow up now here:
https://github.com/ILIAS-eLearning/ILIAS/pull/7869

2024-08-05 11:53 UTC, closed without merging