Port of #4125(samesite cookies) to ILIAS8.
ILIAS-eLearning/ILIAS pull request #6119
Opened 2023-07-09 10:38 UTC by pascalseeland

This PR a port of #4125 to ILIAS8. It contains two changes compared to the PR for ILIAS 7:
- An upgrade of the dfleydev/fig-cookies for allowing the access to the samesite attribute using the Cookie API instead of direct access to $_COOKIE
- An implementation of a transformation to use to HTTP interface provided by ILIAS. The Refinery is not initialized yet and cannot be initialized early enough during init

2023-07-10 08:03 UTC, mjansenDatabay requested changes

2023-07-10 08:03 UTC, mjansenDatabay commented on Services/Http/classes/class.ilHTTPS.php
> +                ) && $_SERVER['HTTPS'] == 'on';
```suggestion
                ) && $_SERVER['HTTPS'] === 'on';
```

2023-07-10 08:03 UTC, mjansenDatabay commented on Services/Http/classes/class.ilHTTPS.php
> +                ) && $_SERVER['HTTPS'] != 'on';
```suggestion
                ) && $_SERVER['HTTPS'] !== 'on';
```

2023-07-10 08:03 UTC, mjansenDatabay commented on Services/Init/classes/class.ilInitialisation.php
> +            $client_id_from_cookie = $DIC->http()->cookieJar()->get('ilClientId')->getValue();
Is it possible to use `$DIC->http()->wrapper()->cookie()->retrieve(...)` instead? Maybe you could re-use the anonymous class transformation from above.

2023-07-10 08:03 UTC, mjansenDatabay commented on Services/Init/classes/class.ilInitialisation.php
> +        //        $c->globalScreen()->tool()->context()->current()->addAdditionalData('DEVMODE', (bool) DEVMODE);
We should delete this line, we don't need comments, we have the Git history :-).

2023-07-11 06:22 UTC, mjansenDatabay commented on Services/Http/classes/class.ilHTTPS.php
> +                'httponly' => true,
```suggestion
                'secure' => true,
                'httponly' => IL_COOKIE_HTTPONLY,
```

2023-07-11 11:01 UTC, mjansenDatabay commented on Services/Http/classes/class.ilHTTPS.php
> +                'samesite' => (strtolower(session_get_cookie_params()['samesite'] ?? '')) === 'strict' ? session_get_cookie_params()['samesite'] : 'Lax'
```suggestion
```

See: https://github.com/ILIAS-eLearning/ILIAS/pull/6133

2024-02-20 11:46 UTC, kergomard commented
Hi @pascalseeland and @chfsx  

As Technical Board, we regularly check for pull requests that have been open for a long time.
Any Updates on this? Note, that you can also close this, if you are not able or if you not have the resources to look into it in detail.

Best regards!
@kergomard

2024-09-12 10:29 UTC, closed without merging

2024-09-12 10:29 UTC, chfsx commented
Since there were several conflicts, I resolved them locally and merged this. Thanks a lot!

2024-09-12 11:52 UTC, mjansenDatabay commented
@chfsx / @pascalseeland Do we need this for ILIAS >= 9.x as well?

2024-09-13 05:27 UTC, chfsx commented
@mjansenDatabay I also think that we need to put this in all releases. unfortunately, cherry-picking is not an option :-) i'll try to adapt the changes

2024-09-13 05:52 UTC, mjansenDatabay commented
> @mjansenDatabay I also think that we need to put this in all releases. unfortunately, cherry-picking is not an option :-) i'll try to adapt the changes

Thank you Fabian. I would have done the same, but I wasn't sure if you both had already agreed on what to do for 9.x and trunk.

2024-09-13 06:04 UTC, chfsx commented
This PR should adapt the changes for ILIAS 9 and 10: https://github.com/ILIAS-eLearning/ILIAS/pull/8065