UI: DataTable, port from trunk; include URLBuilder, ViewControls, restructured Inputs
ILIAS-eLearning/ILIAS pull request #6261
Opened 2023-08-23 07:08 UTC by nhaagen

This adds the DataTable and InputViewControls to v8.

2023-09-21 08:55 UTC, klees commented
@nhaagen Do we understand why the tests don't run? @mjansenDatabay plz halp.

2023-09-21 09:36 UTC, mjansenDatabay commented
> @nhaagen Do we understand why the tests don't run? @mjansenDatabay plz halp.

Here I am.

```
        _____________________________________________
      //:::::::::::::::::::::::::::::::::::::::::::::\\
    //:::_______:::::::::________::::::::::_____:::::::\\
  //:::_/   _-"":::_--"""        """--_::::\_  ):::::::::\\
 //:::/    /:::::_"                    "-_:::\/:::::|^\:::\\
//:::/   /~::::::I__                      \:::::::::|  \:::\\
\\:::\   (::::::::::""""---___________     "--------"  /::://
 \\:::\  |::::::::::::::::::::::::::::""""==____      /::://
  \\:::"\/::::::::::::::::::::::::::::::::::::::\   /~::://
    \\:::::::::::::::::::::::::::::::::::::::::::)/~::://
      \\::::\""""""------_____::::::::::::::::::::::://
        \\:::"\               """""-----_____:::::://
          \\:::"\    __----__                )::://
            \\:::"\/~::::::::~\_         __/~:://
              \\::::::::::::::::""----""":::://
                \\::::::::::::::::::::::::://
                  \\:::\^""--._.--""^/::://
                    \\::"\         /":://
                      \\::"\     /":://
                        \\::"\_/":://
                          \\::::://
                            \\_//
                              "
```

What's the problem :-)?

2023-09-21 11:15 UTC, nhaagen commented
@klees dunno, force-pushed and apparently the tests are back

2023-09-21 11:21 UTC, klees commented
Thx both =)

2023-09-21 13:47 UTC, mjansenDatabay commented
You called me, and you didn't need me :(. I am feeling so useless^^.

2023-09-21 14:04 UTC, klees commented
@mjansenDatabay I'm sorry. I thought that we would need your bright mind to solve this =)

2024-03-11 14:30 UTC, nhaagen commented
picked https://github.com/ILIAS-eLearning/ILIAS/pull/6702

2024-03-21 09:45 UTC, klees commented
Hi @Amstutz/@thibsy,

we started to incorporate this into our updated [cate](https://cate-tms.de) and could not find problems with the code until now. There are two PRs missing in here, but imho they contain marginal changes. So, from my perspective this is good to go for 8.

Would you be so kind and have a look into this now?

Kind regards!

2024-03-27 13:35 UTC, thibsy requested changes
Hi @nhaagen and @klees,

Thanks a lot for testing this with your (productive?) environment, and bundling all related changes together.

Since we have already reviewed the actual changes for ILIAS 9 and/or 10, we will only look at changes which might affect the back-porting to ILIAS 8 and PHP 7.4.

- [ ] Breaking changes: there are several breaking changes in there, what is your strategy to deal with them? To name some:
	- some input interface namespaces changed
	- the field selection view control interface and factory method changed
	- the view control interface was renamed and lost a method
	- the data table factory method changed
	- the data retrieval interface changed
	- the column interface changed
- [ ] Inline comments: I have added some inline comments which need to be addressed. But maybe wait until we have discussed the first point at the next JF.

Kind regards,
@Amstutz and @thibsy

2024-03-27 13:35 UTC, thibsy commented on src/UI/URLBuilder.php
> +        assert(ist_string($value) || is_array($value));
I think this line has been added for backwards compatibility, right? Please don't use `assert()` though, and throw an `InvalidArgumentException` yourself instead. Also note the typo in `ist_string()`.

2024-03-27 13:35 UTC, thibsy commented on src/UI/Implementation/Render/AbstractComponentRenderer.php
>          $registry->register('./src/UI/templates/js/Core/ui.js');
We don't need this file anymore, all functionality should be contained in `Core/dist/core.js` now. Please remove this line and delete the corresponding file as well.

2024-04-15 08:51 UTC, matthiaskunkel commented
Jour Fixe, 15 APR 2024: We still prefer to allow plugin developers to use UIDataTable in ILIAS8-plugins and therefore suggest to implement a solution for ILIAS 8 that allows input interfaces to stay in there previous namespaces. We accept breaking changes in interface to the data table and related components as they could not used in ILIAS 8 until now.

2024-04-18 12:40 UTC, nhaagen commented
We added legacy interfaces for 

- ILIAS\UI\Component\Input\Field\Input
- ILIAS\UI\Component\Input\Field\FilterInput
- ILIAS\UI\Component\Input\ViewControl\ViewControl

and marked them as deprecated for 9.
That should strongly hint to necessary adjustments without breaking too much.

2024-04-29 11:32 UTC, merged