Dashboard Bugfix: Favourites Action in all Dashboard Blocks
ILIAS-eLearning/ILIAS pull request #6286
Opened 2023-08-30 13:09 UTC by fhelfer

addToFavourites() was not in action menu for Blocks in Tile View also entirely missing for Learning Sequences
Only trunk

2023-09-04 08:28 UTC, dsstrassner commented
Is there already mantis issue?

2023-09-04 08:29 UTC, fhelfer commented
there is not, but i can create one

2023-09-04 08:40 UTC, fhelfer commented
https://mantis.ilias.de/view.php?id=37869

2023-09-04 11:48 UTC, iszmais requested changes
@fhelfer Thank you again for you contious effort.

This seems to work, but is missing a differentation when the item is already within the favourites (than an action to remove the item should be shown).
This is also still broken in the list view, therefore i would appreciate a fix for both views in one PR.

Thank you in advance!

2023-09-05 09:15 UTC, lscharmer requested changes

2023-09-05 09:15 UTC, lscharmer commented on Services/Dashboard/Block/classes/class.ilDashboardBlockGUI.php
> + * @ilCtrl_Calls      ilDashboardBlockGUI: ilCommonActionDispatcherGUI
Please remove the superfluous whitespace.

2023-09-07 09:22 UTC, lscharmer approved these changes

2023-09-07 10:04 UTC, iszmais approved these changes

2023-09-07 10:05 UTC, iszmais commented
@fhelfer Thank you again for the fast fix.

sincerely,
@iszmais

2023-09-07 10:06 UTC, merged