fix: poll when delete voting period.
ILIAS-eLearning/ILIAS pull request #630
Opened 2017-08-29 12:15 UTC by xus

@suittenpointner reported in a comment  [here](https://www.ilias.de/mantis/view.php?id=20594)

2017-08-31 14:43 UTC, smeyer-ilias requested changes

2017-08-31 14:43 UTC, smeyer-ilias commented on Modules/Poll/classes/class.ilObjPollGUI.php
> +			$this->object->setVotingPeriodBegin(0);
I think setVotingPeriodBegin/End(null) is more precise here. 
The values are store in table il_poll as unix timestamp. 
null means no date
0 means 1970-01-01 00:00:00

2017-09-04 10:22 UTC, xus commented
@smeyer-ilias Can I merge this?

2017-09-04 14:28 UTC, smeyer-ilias commented
Yes, please. Thanks.

2017-11-23 15:48 UTC, merged