Refinery:
ILIAS-eLearning/ILIAS pull request #6326
Opened 2023-09-15 14:26 UTC by lscharmer

This PR introduces new transformations for the refinery, mostly designed to be usable for the ILIAS Setup:

## `$refinery->to()->memberOf()`
Enum validation: Checks if a value is in a specified set.

Example use case in the config would be: `chatroom.log_level` which must be one of `emerg`, `alert`, `crit`, `error`, `warning`, `notice`, `info`, `debug` or `silly`

## `$refinery->to()->defaultToNull()->recordOf()`
This is the same as `$refinery->to()->recordOf()` except that missing keys will be supplied as `null` to the corresponding transformation instead of thrown an error.

Example use case for this transformation can be found in: `ilChatroomSetupAgent::getArrayToConfigTransformation()`. It is useful when one wants to provide a default value for the config.

## `$refinery->executable()`
Checks if the given string specifies an executable path.

I could not find a suitable place for this transformation so I placed it on the top level of the refinery.

An example use case would be for config paths like: `mediaobject.path_to_ffmpeg`, `style.path_to_scss`, `virusscanner.path_to_scan` etc.

## `$refinery->int()->isBetween()`
This is just a convenience transformation but IMO very nice to have.
There is no actual class for this constraint as it can be composed from other transformations and constraints.

Example use case would be in the config would be: `chatroom.deletion_interval.deletion_value` which have both min and max values.

## Other changes

### `DeriveTransformWithProblem`
This trait is implemented to prevent boilerplate when implementing new transformations, as some methods are always implemented the same.

### ProblemBuilder
No behavior is changed, just some simplifications (with one exception (pun intended): the InvalidArgumentExcpetion is now a ArgumentCountError)

Just FYI: Another PR will follow which will introduce deeper changes to the refinery and the relation between Transformations and Constraints but that PR will be independent of the changes made in this PR.

2023-09-21 13:51 UTC, mjansenDatabay requested changes
Thx a lot for this PR @lscharmer . After a first glimpse I only have some minor remarks, most of them are "documentation".

2023-09-21 13:51 UTC, mjansenDatabay commented on src/Refinery/To/DefaultToNull/Group.php
> +class Group
Could you try to describe (with PhpDocs) the purpose of this group? Maybe it is also worth to add some lines to the `README.md` of the `Refinery`.

2023-09-21 13:51 UTC, mjansenDatabay commented on src/Refinery/To/DefaultToNull/Group.php
> +    public function recordOf(array $transformations): Transformation
Could you try to describe (with PhpDocs) the purpose of this transformation (here or/and in the respective class)? Maybe it is also worth to add some lines to the `README.md` of the `Refinery`.

2023-09-21 13:51 UTC, mjansenDatabay commented on src/Refinery/Factory.php
> +    public function executable(): Transformation
Although the name is already descriptive: Could you try to describe (with PhpDocs) the purpose of this transformation (here or/and in the respective class)? Maybe it is also worth to add some lines to the `README.md` of the `Refinery`.

2023-09-21 13:51 UTC, mjansenDatabay commented on src/Refinery/To/Group.php
> +        return new MemberOfTransformation($valid_members, $this->language);
Could you try to describe (with PhpDocs) the purpose of this transformation (here or/and in the respective class)? Maybe it is also worth to add some lines to the `README.md` of the `Refinery`.

2023-09-21 13:51 UTC, mjansenDatabay commented on src/Refinery/To/Group.php
> +        return new DefaultToNull($this->language);
Although the name is already descriptive: Could you try to describe (with PhpDocs) the purpose of this transformation (here or/and in the respective class)? Maybe it is also worth to add some lines to the `README.md` of the `Refinery`.

2023-09-21 13:51 UTC, mjansenDatabay commented on src/Refinery/DeriveTransformWithProblem.php
> +    public function check($value)
Could we use `: void` here as return type?

2023-09-21 14:01 UTC, lscharmer commented on src/Refinery/DeriveTransformWithProblem.php
> +    public function check($value)
Even though the method in `Constraint::check()` has none?

2023-09-25 11:17 UTC, mjansenDatabay approved these changes

2024-01-10 14:57 UTC, klees requested changes
Hi @lschamer,

the [request for minimal PRs from the other PR](https://github.com/ILIAS-eLearning/ILIAS/pull/6314#pullrequestreview-1813234053) applies here as well. 

Thanks a lot for adding these transformations, they seem to be quite useful and currently missing.

Please consider the following suggestions. You do not need to follow those, but but please indicate shortly why you prefer to do otherwise:
- [ ] ProblemBuilder: You seem to be fixing some problem with the `ProblemBuilder`, but do not really understand what it is. Or is it just a refactoring? Please split that change into a single commit. If it is a problem: please add unit test, that fail without the changes.
- [ ] DefaultToNull: I also came accross this problem several times. I'm not convinced that "all fields might be null" is the thing that really needs to be expressed. Instead we would want to say: this and that field could be null (and it is fine). Also, we would not only want to say it for the strict `to` variant, but also for the less `kindlyTo` variant. Hence I propose the following implementation: On toplevel, we add a transformation `withDefault($transformation, $default)` that replaces a `null` value with `$default` and passes non-null values to the `$transformation`. We could derive `optional($transformation)` from there. We could then introcude special cases for `WithDefault` in the `recordOf`-transformations for the `to` and `kindlyTo` variant. We could the write `recordOf(["key" => $f->optional(...)]);` or something similar for `withDefault`. Maybe we should discuss this, but I would at least suggest to split this topic from the PR at hand.
- [ ] MemberOf: Although I would personally also prefer `memberOf`, I think we should name this transformation `inArray`. This is something most PHP developers will recognize immediately, while "member of" comes from a more mathy background imo.

Please implement the following changes:
- [ ] Executable: Please rename to `IsExecutable`. We use this `has`/`is` naming scheme for constraints consistently, mostly.

Best wishes!

2024-02-06 12:20 UTC, klees commented
Hi @lscharmer,

as with #6314, please assign back if back if this is ready for the next iteration.

Kind regards!

2024-02-08 14:56 UTC, lscharmer commented
Hi @klees,

this PR is updated an can be reviewed again. Below are my answers to your review:

> - [x] ProblemBuilder: You seem to be fixing some problem with the `ProblemBuilder`, but do not really understand what it is. Or is it just a refactoring? Please split that change into a single commit. If it is a problem: please add unit test, that fail without the changes.

Yes, it is just refactoring. It is now placed in it's own commit.

> - [x] DefaultToNull: I also came accross this problem several times. I'm not convinced that "all fields might be null" is the thing that really needs to be expressed. Instead we would want to say: this and that field could be null (and it is fine). Also, we would not only want to say it for the strict `to` variant, but also for the less `kindlyTo` variant. Hence I propose the following implementation: On toplevel, we add a transformation `withDefault($transformation, $default)` that replaces a `null` value with `$default` and passes non-null values to the `$transformation`. We could derive `optional($transformation)` from there. We could then introcude special cases for `WithDefault` in the `recordOf`-transformations for the `to` and `kindlyTo` variant. We could the write `recordOf(["key" => $f->optional(...)]);` or something similar for `withDefault`. Maybe we should discuss this, but I would at least suggest to split this topic from the PR at hand.

I will extract the `DefaultToNull` stuff into it's own PR (it is removed from this one). The Transformation was not ment to address the `default` / `optional` problem, but I see how this is relevant when one chooses a specific approach on how one wants to pursue to implement such a concept.

We can further discuss the details in that PR (coming soon).

> - [x] MemberOf: Although I would personally also prefer `memberOf`, I think we should name this transformation `inArray`. This is something most PHP developers will recognize immediately, while "member of" comes from a more mathy background imo.

Done

> - [x] Executable: Please rename to `IsExecutable`. We use this `has`/`is` naming scheme for constraints consistently, mostly.

Done



Best regards
@lscharmer

2024-04-23 14:22 UTC, klees commented
Hi @lscharmer,

thanks again and sorry that it took me so long to rereview this. I just merged this manually with two rather minor changes.

Kind regards!

2024-04-23 14:22 UTC, closed without merging

2024-04-23 16:17 UTC, mjansenDatabay commented
Thx @klees for your efforts