Taxonomy Settings: Remove Legacy Table, use Panels, Move Activation to Additional Feature Section
ILIAS-eLearning/ILIAS pull request #6392
Opened 2023-10-08 10:44 UTC by alex40724

Feature Wiki
https://docu.ilias.de/goto_docu_wiki_wpage_7694_1357.html
and
https://docu.ilias.de/goto_docu_wiki_wpage_7696_1357.html

2023-10-09 05:50 UTC, kergomard requested changes
Hi @alex40724 
Thank you for this PR. I only looked at the parts for the test and I would kindly ask you to to change the following tings:
- [ ] Please use short array syntax.
- [ ] Please move all name spaces to a use-statement and don't address them inline.
- [ ] Please move [this access of the `$DIC`](https://github.com/ILIAS-eLearning/ILIAS/pull/6392/files#diff-79341fc60c03ba53809fb097ae04d5d5a3e597a46a47406f01dd0fed78e926c2R88) together with all other accesses a few lines further up.

Thanks and best,
@kergomard

2023-10-09 10:16 UTC, alex40724 commented
I took care of the first three issues in the T&A code changes.

With this PR I provide the integration of the taxonomy settings screen into the question pool settings, but I will not take care of the legacy setting / the integration of the object service fully here. This would require a) a migration of the setting (if wanted), b) taking care of copy/import/export processes and c) replace the calls to the old legacy settings methods. I also noticed that the skill management setting is legacy too (not using ilObjectServiceSettingsGUI), so I think d) moving this to ilObjectServiceSettingsGUI would be appropriate, too. However this would include a lot of code changes with different possible alternatives depending on the maintainers preference, especially c). This is beyond what I can currently offer.

2023-10-09 10:46 UTC, alex40724 commented
Btw. that last commit triggered breaking unit tests in unrelated T&A tables:
1) ilTestPassOverviewTableGUITest::testActiveId
Pimple\Exception\UnknownIdentifierException: Identifier "ui.factory" is not defined.

/home/runner/work/ILIAS/ILIAS/libs/composer/vendor/pimple/pimple/src/Pimple/Container.php:105
/home/runner/work/ILIAS/ILIAS/src/DI/UIServices.php:37
/home/runner/work/ILIAS/ILIAS/Modules/Test/classes/tables/class.ilTestPassOverviewTableGUI.php:53
/home/runner/work/ILIAS/ILIAS/Modules/Test/test/tables/ilTestPassOverviewTableGUITest.php:53

Running the tests locally does not trigger these errors, so this seems to depend on the unit test execution sequence.

2023-10-09 12:22 UTC, kergomard commented
Hi @alex40724 
There is still [one inline Namespace left](https://github.com/ILIAS-eLearning/ILIAS/pull/6392/files#diff-79341fc60c03ba53809fb097ae04d5d5a3e597a46a47406f01dd0fed78e926c2R51).
Max fixed the Tests, if I'm getting this right.

So, there is the last issue:
Why don't we just move the current setting for filtering by taxonomy to the "Additional Features" section and make the subtab "Taxonomy" depend on that?

Best,
@kergomard

2023-10-09 14:31 UTC, alex40724 commented
> Hi @alex40724 There is still [one inline Namespace left](https://github.com/ILIAS-eLearning/ILIAS/pull/6392/files#diff-79341fc60c03ba53809fb097ae04d5d5a3e597a46a47406f01dd0fed78e926c2R51). Max fixed the Tests, if I'm getting this right.

The namespace issue is fixed.
 
> So, there is the last issue: Why don't we just move the current setting for filtering by taxonomy to the "Additional Features" section and make the subtab "Taxonomy" depend on that?

I removed the original setting. It is already under "Additional Features" due to the use of ilObjectServiceSettingsGUI. The subtab is already aware of the setting, as documented. It will not appear, if the taxonomy service is deactivated.

2023-10-09 14:56 UTC, kergomard commented
Hi @alex40724 
Thank you very much for moving the last namespace import!

Now, I don't think we can simply remove the Checkbox for the setting. Right now we save a field 'show_taxonomies' in the table `qpl_questionpool`. All preexisting settings would be lost. And then we also use `ilTestQuestionPool::getShowTaxonomies()` to define if we would like to show the filter on the list of questions.

As far as I can see, we need another solution.

Thanks and best,
@kergomard

2023-10-09 18:43 UTC, alex40724 commented
This is basically what I wrote in my comment https://github.com/ILIAS-eLearning/ILIAS/pull/6392#issuecomment-1752732560 above.

2023-10-10 05:30 UTC, kergomard commented
Hi @alex40724 
I rephrase my question from [above](https://github.com/ILIAS-eLearning/ILIAS/pull/6392#issuecomment-1752908566): Do the taxonomies in the test question pool continue working as they do today without any of your changes under `Modules\TestQuestionPool`?

Best,
@kergomard

2023-10-10 05:59 UTC, alex40724 commented
No, the old integration using the legacy table via ilObjTaxonomyGUI directly will not work.

2023-10-10 13:16 UTC, kergomard commented
Hi @alex40724 
I don't think the legacy table has anything to do with it. We cannot implement this in the `TestQuestionPool` with your current proposal, so I'm actively searching for good options to allow the improvement to go through with minimal fuzz for everybody.

If I understand this correctly, the whole problem is [this `if`-statement here](https://github.com/ILIAS-eLearning/ILIAS/pull/6392/files#diff-01b4767940262e6f90d648b13b2a9f4d5eab80e8c29a713fdeca4a7955167841R60). If you would remove the activation checks from the `addSubTab()`-function things would work (alternatively, but I personally don't like this option, you could also provide a `skip_checks` or `always` or `force` parameter). We could then simply check the need for the sub tab on our side and things would work. Am I missing something?

Thank you very much and best,
@kergomard

2023-10-10 13:55 UTC, alex40724 commented
@kergomard  So you do not want to integrate ilObjectServiceSettingsGUI, but keep the legacy setting? I can re-add these old lines, remove the ilObjectServiceSettingsGUI part and add the tab in the pool code directly (as it was similar before).

2023-10-10 14:31 UTC, kergomard commented
If I'm understanding you right: Yes, this would be what we would want. I would then take care of moving the setting down to the section "Additional Features" and making the sub-tab dependent on our setting and we have a working solution.

2023-10-12 08:27 UTC, kergomard approved these changes
Thank you very much @alex40724 !

Now this looks and works right for the TestQuestionPool. Thank you very much!

On a side note: 
- The Taxonomies do not work on PHP8.2 as there is a missing property, declaration in `UsageManager`. `UsageManager::db_repo` is set without declaring it first. This happens in quite a few of the Components you have changed lately, e.g. the `MediaTypeManager`. I kindly ask you to test on PHP8.2.

Thanks and best,
@kergomard

2023-10-12 09:27 UTC, mbecker-databay approved these changes
I am fine with this!

2023-10-12 09:41 UTC, alex40724 commented
Merged manually due to conflict.

2023-10-12 09:41 UTC, closed without merging