[9] Revamp Thread-Tab of Forum
ILIAS-eLearning/ILIAS pull request #6476
Opened 2023-10-26 07:49 UTC by gvollbach

https://docu.ilias.de/goto_docu_wiki_wpage_7529_1357.html

2023-10-26 07:53 UTC, mjansenDatabay commented on Modules/Forum/classes/class.ilForumThreadObject.php
> +class ilForumThreadObject extends ilTable2GUI
Please rename this by using a `TableGUI` suffix.

2023-10-26 08:37 UTC, mjansenDatabay commented on Modules/Forum/classes/class.ilForumExportGUI.php
> +        } else if($this->ref_id > 0) {
`elseif` :-)

2023-10-26 08:39 UTC, mjansenDatabay commented
@gvollbach Please squash the commits to 1 single commit. Thx.

2023-10-26 08:49 UTC, mjansenDatabay requested changes

2023-10-26 08:49 UTC, mjansenDatabay commented on Modules/Forum/classes/class.ilObjForumGUI.php
> +    private function addDraftButtonIfDraftsExists($cmd)
Missing types

2023-10-26 08:49 UTC, mjansenDatabay commented on Modules/Forum/classes/class.ilForumThreadObjectTableGUI.php
> +class ilForumThreadObjectTableGUI extends ilTable2GUI
Please add a blank line

2023-10-26 08:49 UTC, mjansenDatabay commented on Modules/Forum/classes/class.ilForumThreadObjectTableGUI.php
> +    public function fetchDataAnReturnObject(): array
Please add a blank line

2023-10-26 08:49 UTC, mjansenDatabay commented on Modules/Forum/classes/class.ilObjForumGUI.php
> +     * @throws ilCtrlException
Please remove obsolete information

2023-10-26 08:49 UTC, mjansenDatabay commented on Modules/Forum/classes/class.ilObjForumGUI.php
> +     * @return void
Please remove obsolete information

2023-10-26 08:49 UTC, mjansenDatabay commented on Modules/Forum/classes/class.ilObjForumGUI.php
> +     * @return void
Please remove obsolete information

2023-10-26 08:49 UTC, mjansenDatabay commented on Modules/Forum/classes/class.ilObjForumGUI.php
> +     * @throws ilCtrlException
Please try to specify the shape of the array

2023-10-26 08:49 UTC, mjansenDatabay commented on Modules/Forum/classes/class.ilObjForumGUI.php
> +     * @param ilForumTopic $forum_topic
Please remove obsolete information

2023-10-26 08:49 UTC, mjansenDatabay commented on Modules/Forum/classes/class.ilObjForumGUI.php
> +     * @return Standard
Please remove obsolete information

2023-10-26 08:49 UTC, mjansenDatabay commented on Modules/Forum/classes/class.ilObjForumGUI.php
> +    private function getEditTitleModal(ilForumTopic $topic)
The return type is missing here

2023-10-26 08:49 UTC, mjansenDatabay commented on Modules/Forum/classes/class.ilObjForumGUI.php
> +     * @return Shy
Please remove obsolete information

2023-10-26 08:49 UTC, mjansenDatabay commented on Modules/Forum/classes/class.ilObjForumGUI.php
> +     * @throws ilCtrlException
Please remove obsolete information

2023-10-26 08:49 UTC, mjansenDatabay commented on Modules/Forum/classes/class.ilObjForumGUI.php
> +        $threadIdToMerge = (int) ($this->http->wrapper()->query()->retrieve('thr_pk', $this->refinery->kindlyTo()->int()) ?? 0);
This makes not sense. The transformation either returns an integer, or raises an exception. NULL is not possible.

Please try this.

```php
$threadIdToMerge = $this->http->wrapper()->query()->retrieve(
    'thr_pk',
    $this->refinery->byTrying([
        $this->refinery->kindlyTo()->int(),
        $this->refinery->always(0)
    ])
);
```

2023-10-26 08:49 UTC, mjansenDatabay commented on Modules/Forum/classes/class.ilObjForumGUI.php
> +     * @return Item
Please remove obsolete information

2023-10-26 08:49 UTC, mjansenDatabay commented on Modules/Forum/classes/class.ilObjForumGUI.php
> +     * @return Item
Please remove obsolete information

2023-10-26 09:12 UTC, gvollbach commented
> @gvollbach Please squash the commits to 1 single commit. Thx.

Done.

2023-10-26 09:13 UTC, mjansenDatabay commented on Modules/Forum/classes/class.ilForumExportGUI.php
> +        } elseif($this->ref_id > 0) {
Whitespace, again ^^. I again suggest to use the `Captain` to run the PHP-CS-FIXER on every commit :-).

2023-10-26 20:38 UTC, oliversamoila commented on lang/ilias_de.lang
>  forum#:#merged_threads_successfully#:#Die selektierten Themen wurden erfolgreich zusammengeführt
Die Themen wurden erfolgreich zusammengeführt.

2023-10-27 05:58 UTC, mjansenDatabay commented on Modules/Forum/classes/class.ilForumThreadObjectTableGUI.php
> +class ilForumThreadObjectTableGUI extends ilTable2GUI
No, this is not solved.

2023-10-27 05:58 UTC, mjansenDatabay commented on Modules/Forum/classes/class.ilForumThreadObjectTableGUI.php
> +    public function fetchDataAnReturnObject(): array
No, this is not solved.

2023-10-27 06:00 UTC, mjansenDatabay commented on Modules/Forum/classes/class.ilObjForumGUI.php
> +     * @return Standard
No, this is not solved.

2023-10-27 06:01 UTC, mjansenDatabay requested changes
Please check my new inline comments.

2023-10-27 06:31 UTC, mjansenDatabay approved these changes

2023-10-27 06:32 UTC, merged