UI DataTable: Add LinkList Column
ILIAS-eLearning/ILIAS pull request #6482
Opened 2023-10-26 15:34 UTC by tfamula

![Bildschirmfoto vom 2023-10-26 17-32-16](https://github.com/ILIAS-eLearning/ILIAS/assets/35489053/f81ea540-a60a-4aee-be77-b0a3711a646e)

2023-10-26 15:37 UTC, tfamula commented
It would be great if we could fasttrack this before Coding Completed tomorrow, like https://github.com/ILIAS-eLearning/ILIAS/pull/6459.

2023-10-26 15:38 UTC, tfamula commented on src/UI/examples/Table/Column/Link/base.php
> +        ->withRequest($DIC->http()->request());
This PR also includes a little fix for the the example of the Link Column

2023-10-27 08:09 UTC, thibsy requested changes
Hi @tfamula

Thanks a lot for your contribution to the UI components!

It is possible to fast-track this as well, like we did with #6459. So if you can provide the requested changes today, I will gladly merge this afterwards.

Please consider the following suggestions. You do not need to follow them, but please indicate shortly why you prefer to do otherwise:

- [x] `Column\LinkList::format()`: this method currently compares the given `$value` against the `Listing\Listing` interface. IMO this is too broad and would allow any kind of listing in the future (even though they might fail `Link\Standard` check like `Listing\Property` currently does). I believe we should stick with only `Listing\Ordered` and `Listing\Unordered` for the moment.

Please implement the following changes:

- [x] `LinkList`: please rename this interface to `LinkListing`, indicating its association with `Listing\*` components. Also rename the factory method accordingly.
- [x] `ColumnTest`: please also add a unit-test for invalid values passed into `LinkList::format()`. One where another component is passed, and, one where a listing with non-link values is passed.

Kind regards,
@Amstutz, @klees and @thibsy

2023-10-27 10:19 UTC, tfamula commented
Hi @thibsy 
Thanks for the quick feedback! All done!

2023-10-27 11:03 UTC, thibsy approved these changes
Thx @tfamula, this LGTM now. I added the JF label so we can announce this as well.

2023-10-27 11:05 UTC, merged

2023-10-30 13:32 UTC, matthiaskunkel commented
Jour Fixe, 30 OCT 2023: We highly appreciate this suggestion and accept the PR for Trunk.