Fix WAC authentification of anonymous user
ILIAS-eLearning/ILIAS pull request #661
Opened 2017-09-21 16:05 UTC by d3r1w

This PR provides a fix for the reported bug [0021071](https://www.ilias.de/mantis/view.php?id=21071)

**Solution**
The WebAccessChecker service authenticated the anonymous user if no user was found to deliver public available pictures. ILIAS in return allows each authenticated user to access the public section of the repository. If the setting is enabled or not is not relevant at all.

We discovered that a user can be stored in the session without being authenticated. Therefore we set the anonymous user without being authenticated which prevents arbitrary users from accessing the public section of the repository.

2017-09-22 06:34 UTC, chfsx requested changes

2017-09-22 06:34 UTC, chfsx commented on Services/Init/classes/class.ilInitialisation.php
> +			throw new ilException('Can not redirect anonymous user to landing page');
@smeyer-ilias is that ok for you, since this is a fallback which should never happen

2017-09-22 06:34 UTC, chfsx commented on Services/Init/classes/class.ilStartUpGUI.php
> +			require_once './Services/Init/classes/class.ilInitialisation.php';
@d3r1w requires can be abandoned since we have autoloading

2017-09-22 06:34 UTC, chfsx commented on Services/WebAccessChecker/classes/class.ilWebAccessChecker.php
> +				require_once './Services/Context/classes/class.ilContext.php';
@d3r1w same here with the require, you can delete it I think

2017-09-22 06:34 UTC, chfsx commented on Services/WebAccessChecker/classes/class.ilWebAccessChecker.php
> +				$GLOBALS['DIC']['ilAuthSession']->setAuthenticated(false, ANONYMOUS_USER_ID);
@smeyer-ilias this seemed to be a bit strange to us, how should we read this? a session is available in both true and false

2017-09-22 08:42 UTC, smeyer-ilias commented on Services/Init/classes/class.ilInitialisation.php
> +			throw new ilException('Can not redirect anonymous user to landing page');
Unfortunately this fallback is in use. 
ilStartUpGUI::showLoginPageOrStartupPage() -> redirectToStartingPage()

Steps to reproduce: 
1) Enable pub section
2) logout
3) call public section
4) call login.php

2017-09-22 08:43 UTC, smeyer-ilias commented on Services/Init/classes/class.ilStartUpGUI.php
> +			require_once './Services/Init/classes/class.ilInitialisation.php';
But this is a pull request against 5.2

2017-09-22 08:44 UTC, chfsx commented on Services/Init/classes/class.ilStartUpGUI.php
> +			require_once './Services/Init/classes/class.ilInitialisation.php';
My bad, sorry!

2017-09-22 08:44 UTC, chfsx commented on Services/WebAccessChecker/classes/class.ilWebAccessChecker.php
> +				require_once './Services/Context/classes/class.ilContext.php';
No change required since this is against 5.2

2017-09-22 08:58 UTC, smeyer-ilias commented on Services/WebAccessChecker/classes/class.ilWebAccessChecker.php
> +				require_once './Services/Context/classes/class.ilContext.php';
Same here for 5.2

2017-09-22 09:00 UTC, smeyer-ilias commented on Services/WebAccessChecker/classes/class.ilWebAccessChecker.php
> +				$GLOBALS['DIC']['ilAuthSession']->setAuthenticated(false, ANONYMOUS_USER_ID);
The idea was, to allow unauthenticated sessions (e.g before login) which could be used to store session data for the login process.

2017-09-22 09:02 UTC, smeyer-ilias commented on Services/Init/classes/class.ilInitialisation.php
> +			throw new ilException('Can not redirect anonymous user to landing page');
I will change the mentioned redirectToStartingPage. 
But have no time to do this before Tuesday.

2017-09-22 09:02 UTC, chfsx commented on Services/Init/classes/class.ilInitialisation.php
> +			throw new ilException('Can not redirect anonymous user to landing page');
Thanks and no hurry!

2017-09-22 09:45 UTC, chfsx approved these changes

2017-09-22 09:47 UTC, chfsx commented on Services/Init/classes/class.ilInitialisation.php
> +			throw new ilException('Can not redirect anonymous user to landing page');
This still works with the changes:

1. Enable pub section
2. logout
3. call public section
4. call login.php

2017-09-27 18:54 UTC, chfsx commented
@smeyer-ilias can we help in some wa to change the stuff you mentioned above?

2018-01-15 15:00 UTC, chfsx commented
@smeyer-ilias I assign this one to you since there are only improvements in ilInitialisation and ilStartupGUI in it

2018-06-19 12:15 UTC, closed without merging