Refinery/MarkdownToHtml: Don't accept HTML and unsafe links
ILIAS-eLearning/ILIAS pull request #7012
Opened 2024-02-05 11:57 UTC by mjansenDatabay

See: https://mantis.ilias.de/view.php?id=40204

2024-02-05 12:04 UTC, corro commented
Maybe consider setting `max_nesting_level` too in order to avoid excessively long rendering times and possible DoS.

2024-02-08 10:38 UTC, klees requested changes
LGTM, please make the two changes. Feel free proceed afterwards. Thanks!

2024-02-08 10:38 UTC, klees commented on tests/Refinery/String/MarkdownFormattingToHTMLTest.php
> +        $this->markdown_wihtout_html = $group->markdown(true)->toHTML();
```suggestion
        $this->markdown_without_html = $group->markdown(true)->toHTML();
```

2024-02-08 10:38 UTC, klees commented on src/Refinery/String/MarkdownFormattingToHTML.php
> +    public function __construct(bool $strip_html = false)
Lets default this to `true` so people would need to allow HTML willingly.

2024-02-09 07:32 UTC, mjansenDatabay commented
@klees I applied the requested changes.

Furthermore, I added the `max_nesting_level` configuration option (it is not configurable by our users), this was also a recommendation. I did not find a meaningful value for that (so I chose `42`), the documentation suggests a value between 10 and 50.

According to the suggestion of @chfsx I changed the HTML handling to `escape` instead of `strip`.

2024-02-13 07:49 UTC, klees approved these changes

2024-02-13 08:25 UTC, merged