[FIX] 0040540: Unzip behaviour changed in ILIAS 9
ILIAS-eLearning/ILIAS pull request #7089
Opened 2024-02-21 16:30 UTC by chfsx

Hello @alex40724 , hello everyone else (see below)

thanks for the feedback! i have taken this as an opportunity to replace all existing calls of `ilFileUtils::unzip` with `\ILIAS\Filesystem\Util\Archive\Archives` or `\ILIAS\Filesystem\Util\Archive\LegacyArchives`, because this was only a wrapper anyway. it also allows consumers to make finer settings in the future as to how unzip should behave if it needs adjustments. i have restored the default that NO top-directory is created but the structure is kept. the behavior with ZIP is also relevant, which i have also restored. i have tried to test as many of the locations as possible, so far i have not noticed any errors.

@alex40724  here a hint: in `ilFileUtils` (formerly in `ilUtil`) there was also a method `processZipFile`. this was used exclusively in `ilExSubmission`. i have therefore moved the method there, but i think you can simply replace it later.

here are the affected components:
- Modules/CmiXapi: @Uwe-Kohnle 
- Modules/Exercise: @alex40724 
- Modules/ScormAicc: @Uwe-Kohnle 
- Modules/Survey: @alex40724 
- Services/Certificate: @mjansenDatabay 
- Services/Export: @smeyer-ilias 
- Services/FileServices: @chfsx 
- Services/FileSystem: @chfsx 
- Services/MediaObjects: @alex40724 
- Services/Style/Content: @alex40724 
- Services/Style/System: @Amstutz 
- Services/User: @kergomard 

I would merge this PR next thursday if there is no objection.

Info: Failing tests are due to License-Header, but the header seems correct in the file mentioned
----

Former text of PR:
@alex40724 this should fix the issues in exercise concerning unzip, https://mantis.ilias.de/view.php?id=40540

2024-02-22 14:49 UTC, alex40724 requested changes
@chfsx Thanks for the PR.

I added a comment to the ticket. The main problem is, that this is not exercise specific, but a genera issue of the unzip method in ilFileUtils. I added a test case, see https://mantis.ilias.de/view.php?id=40540#c101844

2024-02-23 09:27 UTC, chfsx commented
@alex40724 thanks for the feedback, see updated initial text in this PR

2024-02-23 09:29 UTC, chfsx commented
@alex40724 I see you made already changes, I will update the PR asap

2024-02-23 09:32 UTC, chfsx commented
@alex40724 PR updated

2024-02-23 09:38 UTC, mjansenDatabay approved these changes
Thx @chfsx , this looks good for `Services/Certificate`.

2024-02-23 10:05 UTC, kergomard approved these changes
Thank you very much @chfsx !
I think I can approve this for the Test and the User.

2024-02-26 08:12 UTC, alex40724 commented
@chfsx Thanks. I removed all ilFileUtils::unzip calls in my code, so these parts should be obsolete.

2024-02-26 08:46 UTC, chfsx commented
@alex40724 thanks, I updated the PR and made a change in your ZipAdapter to match the new situation https://github.com/ILIAS-eLearning/ILIAS/pull/7089/commits/f44887f11ef082771ff9aa93e449d0322b45b5f6

2024-02-27 10:29 UTC, alex40724 approved these changes

2024-02-27 10:33 UTC, alex40724 commented
Thanks. It's ok to remove processZipFile from the Util class. I will hope to find the time to properly refactor this after the merge. Worst case is, I will keep it as it is internally.

2024-02-27 10:42 UTC, alex40724 commented
Btw. I will collect some requirements for the Archives interface for use cases I could (if I did not overlook anything) not implement yet. E.g. adding empty direcotories in "in memory"/temporary zip archives. But this I would address in ILIAS 10.

2024-03-05 06:18 UTC, chfsx commented
Friendly reminder to give feedback to this PR until tomorrow’s evening. I‘ll merge this thursday

2024-03-07 15:58 UTC, merged