LSO: 39159, parent type for LSOPages (Intro/Extro), Migration and WAC
ILIAS-eLearning/ILIAS pull request #7140
Opened 2024-03-06 10:16 UTC by nhaagen

- DB Update inserting type into copg_pobj_def
- Migration to update IDs of PageObjects 
(php setup/setup.php migrate --run ilLearningSequenceMigrationAgent.LSOMigratePageIdsExtro)

https://mantis.ilias.de/view.php?id=39159

2024-03-18 13:48 UTC, klees commented
Hi @alex40724,

would you be so kind and have a look into this? There are two new migrations in the LSO, but these basically will write into tables that belong to COPage, which is why I think you should have a look.

The state of the art is as such:

* For the LSO we have been reusing the standard container page for the intro and extro pages. To be able to have to these pages (instead of one...) we have synthesized page ids via the id of the parent object (-1 * parent_id, -2 * parent_id).
* This seems to have been creating issues with the WAC, as described in the linked ticket.
* We would like to solve this by introducing a new page type for the LSO, which would require us to relabel the existing pages of the LSO. Luckily, we can identify these by our odd id-scheme.

I will will ask @nhaagen to have another look into [your COPage docu](https://github.com/ILIAS-eLearning/ILIAS/blob/release_9/Services/COPage/README-technical.md).

I would still ask you if you would be ok with us writing in the table of COPage via migration. Also, other input or feedback would be appreciated.

Kind regards!

2024-03-18 15:35 UTC, nhaagen commented
I'll revise this to separate Intro/Extro by type rather than (negative) id; until then, I set the PR to "draft".

2024-03-19 10:15 UTC, alex40724 commented
@nhaagen Please have a look at https://github.com/ILIAS-eLearning/ILIAS/commit/7c55ed13b7a226592168ed842d0b2f5685e5177d

I added some docu on setting the parent ID of pages. Setting this to the repo object ID of the context enables a default behaviour for WAC checking in ilObjMediaObject. As far as I can see, LSO already sets this ID correctly, so I assume no additional change is needed here and we can omit the ilObjMediaObject part of this PR.

EDIT: I also added docu on import/export, since this was definitely missing.

2024-03-19 10:23 UTC, alex40724 requested changes

2024-03-19 10:23 UTC, alex40724 commented on Modules/LearningSequence/classes/Setup/class.LSOMigratePageIdsExtro.php
> +            . "AND parent_id = " . $row['parent_id'];
Please always add the current parent type to the WHERE clause, since this is the important part of the primary key "... AND parent_type='...'".

2024-03-19 10:23 UTC, alex40724 commented on Modules/LearningSequence/classes/Setup/class.LSOMigratePageIdsIntro.php
> +        $this->db->manipulate($query);
Please always add the current parent type to the WHERE clause, since this is the important part of the primary key "... AND parent_type='...'".

2024-03-19 14:01 UTC, nhaagen commented
Hi @alex40724 , thank you for the hints. 
I incorporated them and rebased to catch up with ilObjMediaObject.

2024-03-21 11:14 UTC, alex40724 approved these changes

2024-03-25 10:14 UTC, merged

2024-03-25 10:22 UTC, klees commented
Picked to trunk.