[Docu] DevTutorial: Text Proposal Persistence
ILIAS-eLearning/ILIAS pull request #7185
Opened 2024-03-14 16:40 UTC by fneumann

Proposal for the tutorial on persistence in ILIAS. Reworked and translated the initial German text to English.

2024-04-24 14:10 UTC, acgruber commented
Hi @chfsx,
would you be so kind to review this sometime soon so I can merge? :)
Thanks a lot!
Ann-Christin

2024-05-03 13:53 UTC, chfsx requested changes
Thanks a lot for the proposal, I made several inline comments and suggestion. 

One general request:

Please use namespaces for the example files and rename the `classes` to `src`. I think we are more state of the art then since we are committing this tutorial for trunk with the ongoing component revision.

namespace would be `ILIAS\components\Todo then.

2024-05-03 13:53 UTC, chfsx commented on docs/development/devguide/tutorial/04-coding/08-persistence-data.md
> +## Why do I Need This in ILIAS?
```suggestion
## Why do I need This in ILIAS?
```

2024-05-03 13:53 UTC, chfsx commented on docs/development/devguide/tutorial/04-coding/08-persistence-data.md
> +## How to Proceed?
```suggestion
## How to proceed?
```

2024-05-03 13:53 UTC, chfsx commented on docs/development/devguide/tutorial/04-coding/08-persistence-data.md
> +## What is This About?
```suggestion
## What is this about?
```

2024-05-03 13:53 UTC, chfsx commented on docs/development/devguide/tutorial/04-coding/08-persistence-data.md
> +# Database Usage In ILIAS
```suggestion
# Database usage in ILIAS
```

2024-05-03 13:53 UTC, chfsx commented on docs/development/devguide/tutorial/04-coding/08-persistence-data.md
> +ILIAS is designed for the use of MysQL or MariaDB as database systems, but also supported Oracle and PostgreSQL in former versions. To keep this flexibility, database calls must use the interface [il
```suggestion
ILIAS is designed for the use of MySQL or MariaDB as database systems, but also supported Oracle and PostgreSQL in former versions. To keep this flexibility, database calls must use the interface [ilDBInterface](../../../../../components/ILIAS/Database/interfaces/interface.ilDBInterface.php), whose functions largely abstract the peculiarities of certain SQL dialects.
```

2024-05-03 13:53 UTC, chfsx commented on docs/development/devguide/tutorial/04-coding/08-persistence-data.md
> +To access the ILIAS database, the classes of your component also require an instance of the global database class. If it cannot be passed as a parameter of the constructor, it should be taken from th
```suggestion
To access the ILIAS database, the classes of your component also requires an instance of the global database class. If it cannot be passed as a parameter of the constructor, it should be taken from the dependency injection container of ILIAS, which is available as a global variable `$DIC`.
```

2024-05-03 13:53 UTC, chfsx commented on docs/development/devguide/tutorial/04-coding/08-persistence-data.md
> +1. a new sequence value for the primary key field todo_id is generated with `nextId()`.
maybe you could explain that `nextId` is only possible if the tables has been created with `createSequence`

2024-05-03 13:53 UTC, chfsx commented on docs/development/devguide/tutorial/04-coding/08-persistence-data.md
> +## What do I Need to Watch Out For? (Dos & Dont's)
```suggestion
## What do I need to watch out for? (Dos & Dont's)
```

2024-05-03 13:53 UTC, chfsx commented on docs/development/devguide/tutorial/04-coding/TodoExample/classes/class.ilTodoItem.php
> +    private ?string $deadline;
Those lines can be removed, see below

2024-05-03 13:53 UTC, chfsx commented on docs/development/devguide/tutorial/04-coding/TodoExample/classes/class.ilTodoItem.php
> +        ?string $deadline
```suggestion
        private int $todo_id,
        private int $user_id,
        private string $title,
        private ?string $description,
        private ?string $deadline
```

2024-05-03 13:53 UTC, chfsx commented on docs/development/devguide/tutorial/04-coding/TodoExample/classes/class.ilTodoItem.php
> +        $this->deadline = $deadline;
this lines can be removed with the suggestion above

2024-05-23 13:33 UTC, acgruber commented
Thanks a lot for you review and suggestions, @chfsx!

@fneumann, would be great if you found the time to look at this sometime soon :)

2024-06-12 17:05 UTC, fneumann commented
Sorry for the delay. No I worked in all suggestions.

2024-06-20 19:20 UTC, acgruber commented
Thank you, @fneumann!

@chfsx, I will merge as soon as you approve the changes!

2024-08-15 12:50 UTC, acgruber commented
Hello @fneumann and @chfsx,
Could you kindly give me an update on this PR? Can this be merged?
Thanks!

2024-08-15 15:21 UTC, fneumann commented
Missed one little wording issue. Now everything should be resolved. @chfsx would you approve this?

2024-08-16 04:41 UTC, chfsx commented
Many thanks @fneumann  for your great work! every documentation brings ILIAS forward and is very valuable. thank you also for your patience in this matter, I am sorry that the PR remained open for so long.

2024-08-16 04:41 UTC, merged