Feature/10/container resource gui
ILIAS-eLearning/ILIAS pull request #7214
Opened 2024-03-19 14:30 UTC by chfsx

![image](https://github.com/ILIAS-eLearning/ILIAS/assets/6661332/116ce911-2279-4d51-aeba-d52db119af4f)

This PR contains the implementation of the Container Resource GUI as decided yesterday: [IRSS: Container-Resource User-interface](https://docu.ilias.de/goto_docu_wiki_wpage_8127_1357.html)

The changes to the IRSS are in the following commit for your info, which I will cherry-pick in the next few days: https://github.com/ILIAS-eLearning/ILIAS/commit/62a506cdb2db156d66872ccd49f94351bd8a3644

The following commit also contains a readme on how to use the container GUI in your component: https://github.com/ILIAS-eLearning/ILIAS/commit/24198ba5bed6851b68cb53f20edadb054fa93f27

as a first use I have already rebuilt the HTML learning module, incl. migration. after I have merged the other two commits, I would give you Alex the PR regarding the changes in the learning module: https://github.com/ILIAS-eLearning/ILIAS/commit/2012677b0390167fbbc86675d1e1e1c8f57a141d

The adjustments to the breadcrumb will follow separately as PR

2024-04-15 09:39 UTC, matthiaskunkel commented
Jour Fixe, 15 APR 2024: @chfsx notified us about the extension of the IRSS to handle multiple files and the first use of it in for the HTML LM. PR will be handled by @alex40724. Please check how Lucene can write an index of the HTML pages in the new structure.

2024-05-07 10:52 UTC, alex40724 commented
@chfsx Thanks for the PR! I just tried to test the basics. I was able to

- create an HTML learning module
- add files to the main directory
- declare an HTML file as start file (note: in current releases other file types may be start file, too)

But I was not able to open the HTML LM in presentation mode. I tried two objects and always get:

Diese localhost-Seite wurde nicht gefundenFür folgende Webadresse wurde keine Webseite gefunden: http://localhost/trunk/ilias/public/deliver.php/JY3LCsIwEAD_JWdx89ikiZR-yV6SdKPF2pY2PkD8dyseB4aZt1jESRDMSyXoY40Edb1P14mfBMM4xI1gq_Maz0xQtocmUMkReGl3vyBBYxldQm90n3M0ujivnA279w-Kg5j2xTD1_Dpe6m0Un7btOtUoqyR6KX-EqfgoGYsLWRv2rAM3ycmSFKJMNmMK2oT8BQ/-/index.html.

I am not sure if this is related to the component revision. Could you rebase your branch and check, if presentation is ok? Thanks.

2024-06-05 07:32 UTC, alex40724 requested changes
@chfsx  Any chance of getting a rebased version that fixes the presentation of the learning modules? I would love to merge this.

2024-06-05 07:32 UTC, alex40724 commented on components/ILIAS/HTMLLearningModule/classes/class.ilObjFileBasedLM.php
> +        );
I understand the technical reason. But is this something consumer code needs "to know" and take care of?

2024-06-05 10:20 UTC, chfsx commented
@alex40724 the PR has now been rebased. If you still face issues aka "Diese localhost-Seite wurde nicht gefundenFür folgende Webadresse wurde keine Webseite gefunden:" we should meet using Discord/Skype/Whatever since I cannot reproduce this. but i remember that you sometimes have very low limits in the OS for your development machines, i know of one case where this also led to problems with the signed URLs. but we could look into that, basically there is also a solution for that. 

Concerning the "empty" zip: I changed that to internal and adapted the code in `ilObjFileBasedLM`

2024-07-08 07:08 UTC, alex40724 commented
Are you able to run composer du in this branch?

I tried the first time I ran into the missing dependency issues.

I out-commented the the missing dependencies (lots of them), but still I am not able to test this, since I cannot add new objects in this branch.

@chfsx Does this work for you?

2024-07-16 04:52 UTC, chfsx commented
of course I can't solve the general issues in trunk with this PR, I have an installation with existing HTML learning modules, which I update to test this. the creation of new objects is generally broken in trunk FMPOV.

2024-09-13 17:49 UTC, alex40724 commented
@chfsx The modals in the trunk are working again. I created a local branch with your commit. For reasons I do not understand the DB Update does not run, so I added the rid field manually.

I then ran into the same issue getting a "Für folgende Webadresse wurde keine Webseite gefunden..." error.

I tracked this down to this line
```
169            $file_inside_zip_uri = "zip://$requested_zip#$sub_request";
```
in StreamDelivery.

After adding an additional "/" after the "#" it works.
```
-->            $file_inside_zip_uri = "zip://$requested_zip#/$sub_request";
```

Does this work for you, too? No idea, if this is related to the zip lib version.

2024-09-13 17:57 UTC, alex40724 commented
Since this is not related to the files included here, I merged this manually to the trunk now.

For the delivery issue I added a mantis report. https://mantis.ilias.de/view.php?id=42062

Thanks!

2024-09-13 17:57 UTC, closed without merging