Update visibilities properties and constructor in Dashboard
ILIAS-eLearning/ILIAS pull request #7316
Opened 2024-04-04 14:43 UTC by iszmais

A partial approach on refactoring the Dashboard (see https://github.com/ILIAS-eLearning/ILIAS/pull/6539):
-  add `final` and `readonly`
-  update constructors
- removed trivial local variables

2024-04-04 14:47 UTC, iszmais commented
@alex40724 @klees The refactoring also contains some minor changes within the depending classes in `RecommendedContent`, `StudyProgramme` and `LearningSequence`. This is just cosmetic/conventional nature and does not interefere with any process. Pls have a short look.

Greetings,
@iszmais

2024-04-04 15:03 UTC, lscharmer requested changes

2024-04-04 15:03 UTC, lscharmer commented on Services/Dashboard/Achievements/classes/class.ilAchievements.php
> +        switch (self::SERVICES) {
This seems wrong. I don't think you want to match upon the `self::SERVICES` array but on the `$service` integer.

2024-04-04 15:03 UTC, lscharmer commented on Services/Dashboard/Achievements/classes/class.ilAchievements.php
> +        return array_filter(self::SERVICES, function ($s) {
```suggestion
        return array_filter(self::SERVICES, $this->isActive(...));
```

2024-04-16 13:24 UTC, iszmais commented
@alex40724 @klees 
Just a ping i case this here was overlooked.

The taken changes in your components are quite small:
- changes property from `viewSettings` to `view_settings`
- changed function name from `getCurrentView` to `getView` (since there is only 1 view)
- applied 2 final states to function

Therefore i assume there is not much to review at all, but i would reluctantly merge this without your confirmation in respect to your maintainance/authority.

Greetings,
@iszmais

2024-04-16 13:48 UTC, lscharmer approved these changes

2024-07-08 15:27 UTC, iszmais commented
:bell:

2025-01-02 12:00 UTC, iszmais commented
@klees @alex40724 :bell:

2025-01-07 11:46 UTC, klees reviewed
Hi @iszmais,

I'd rather not use `final`, at least in my components. The feature feels like a good idea at the beginning, but from my experience quickly is in the way of automated testing.

This is more of a preference here, so I leave the decision up to you. If you decide to stay with the current code, I would kindly ask for a small explanation, why these methods should be final.

Feel free to merge.

Kind regards!

2025-01-07 16:32 UTC, iszmais commented
@klees Thank you for your feedback.

I used the `final` keyword to "guide" future progress on these providers by promoting a singular (or dual?) structure in this provider system. This should prevent the creation of inheritance clusters and intransparent structures as well as component internal duplication, especially on "critical" functionality like management operations or general identification.
This should further not impede the testing, but, on the contrary, help it by structuring the conceptional requirements on this provider system within the code basis. This way we could prevent numb testing and make sure the test themself doesn't encourage behavior that contradicts the general concept.

However, I'm aware that the `final` keyword only tackles this issue partially and works very one-sided.
Due to that, it's no requirement to me either, just a suggestion.

Therefore, I removed it from your supervised components.

Greetings,
@iszmais

2025-02-04 15:41 UTC, klees approved these changes

2025-02-05 09:12 UTC, iszmais commented
> Hi @iszmais,
>
> the Technical Board looks into oldish PRs regularly, this is when this PR came up. Is there anything that we can do here to > move this to some definite state, be it a merge or close?
>
> Kind regards!

@alex40724 / @smeyer-ilias All eyes on you. As soon as you can give your approval to the changes in `Repository` (Recommended Content), this will be ready to merge.

Greetings,
@iszmais

2025-07-14 11:38 UTC, iszmais commented
@alex40724 / @smeyer-ilias :bell:

2025-11-26 09:55 UTC, iszmais commented
@alex40724 / @smeyer-ilias :bell:

2026-02-22 09:33 UTC, alex40724 approved these changes

2026-02-25 09:33 UTC, iszmais commented
Thank you all for approval!

Unfortunately, this PRs origin target release went out of support over the review process.

Therefore, I will merge this for ILIAS 10+ and close this PR.

Greetings,
@iszmais

2026-02-25 09:33 UTC, closed without merging