Escape all properties of symbols that are publicly accessible
ILIAS-eLearning/ILIAS pull request #7350
Opened 2024-04-11 12:52 UTC by iszmais

https://mantis.ilias.de/view.php?id=40220

This escapes all properties inside the Symbols that:
- can be changed by the consumer via the UI-Factory
- are raw part of the rendered HTML
- not restricted object wise (e.g. size)

2024-04-29 12:12 UTC, matthiaskunkel commented
Jour Fixe, 29 APR 2024: Related to this PR, Richard points out that there is a need to change our templating system in the near future, as our current template engine does not recognise the context in which statements are made by the system. A new template engine needs to offer escaping functions to prevent XSS and make ILIAS more secure. Alexander supports the idea to add a second and modern template engine to the core - even before finishing the Legacy UI project. Otherwise we would loose important time. Skin developers can be expected to familiarise themselves with the syntax of the new template engine. Nico requests to add (harmless) information about the background of such fixes to the commit.

2024-05-06 07:59 UTC, thibsy requested changes
Hi @iszmais

Thx for looking into this. Before we can merge this, please

- [x] wrap the `htmlspecialchars()` calls in a new method inside our `AbstractComponentRenderer` along with some information about when to use it and what to expect from the result.
- [ ] implement a unit test which covers the new escaping of properties (paths, labels, names, abbreviations).
- [ ] amend the commit message as requested by @nicoroeser about the nature of this fix.

Kind regards,
@Amstutz, @klees and @thibsy

2024-05-06 16:01 UTC, iszmais commented
Hi @thibsy ,
I applied all requested changes.
Feel free to leave me a feedback or to merge!

Greetings,
@iszmais

2024-05-15 09:03 UTC, thibsy requested changes
Hi @iszmais

Thx a lot for implementing the requested changes! I have noticed an issue and some unnecessary variables in the unit tests which need to be addressed before we can merge this. I have left some inline comments where this is the case.

Kind regards,
@thibsy

2024-05-15 09:03 UTC, thibsy commented on tests/UI/Component/Symbol/Avatar/AvatarTest.php
> +        $str = '/path/to/picture.jpg';
This variable is never used, please remove it.

2024-05-15 09:03 UTC, thibsy commented on tests/UI/Component/Symbol/Avatar/AvatarTest.php
> +        $f = $this->getAvatarFactory();
You already initialised this variable above, please remove this line.

2024-05-15 09:03 UTC, thibsy commented on tests/UI/Component/Symbol/Avatar/AvatarTest.php
> +        $f = $this->getAvatarFactory();
You already initialised this variable above, please remove this line.

2024-05-15 09:03 UTC, thibsy commented on tests/UI/Component/Symbol/Icon/IconTest.php
> +        $expected = '<img class="icon name small" src="data:image/svg+xml;base64,PHN2ZyB2ZXJzaW9uPSIxLjEiIGlkPSJMYXllcl8xIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3
I think this couples the unit test to the actual image we use for rendering. Please try to implement this test case without the actual source, so changes to the image won't break the unit tests.

2024-05-15 11:18 UTC, iszmais commented
@thibsy my apologies. Seems i didnt psuh my revent state.
This should be fixed now.

The image source, however seems to be an enforces transformation within the rendering with Abbreviation. Therefore i see no other way than to test that sufficent without the base64 encoded image, just like in the `testRenderingStandardAbbreviation` testcase.

Greetings,
@iszmais

2024-05-16 06:29 UTC, thibsy approved these changes
Thx @iszmais for cleaning up the unit tests! You're right, we have already coupled some test cases to the image source, which makes this a general problem and not your concern anymore :). This otherwise LGTM, so I will merge this now and pick for trunk.

2024-05-16 06:30 UTC, merged

2024-05-16 08:24 UTC, mjansenDatabay commented
@iszmais / @thibsy IMO we also need this for 8.x, right?