User: Add goto link for the login page
ILIAS-eLearning/ILIAS pull request #7371
Opened 2024-04-16 08:24 UTC by lscharmer

Add goto link (`/go/usr/login` & `goto.php/usr/login`) which redirects to the login page.

2024-04-16 08:30 UTC, mjansenDatabay requested changes
Hi @lscharmer ,

thx for this PR. In my opinion, we need to display the link in the ILIAS footer. Please have a look at `ilPasswordAssitanceGUI`, you can adapt the code.

Best regards,
Michael

2024-04-16 08:33 UTC, mjansenDatabay commented on components/ILIAS/User/classes/class.ilObjUserGUI.php
> +            $ilCtrl->redirectToURL('/login.php?' . http_build_query([
Do we need a `cmd=foce_login` query parameter here? IMO there are a few occurrences in our code base, where this parameter is appended to ensure the display of the login page, even it the user/initialisation state is "undefined".

2024-04-29 17:46 UTC, mjansenDatabay approved these changes

2024-05-10 07:52 UTC, mjansenDatabay approved these changes

2024-05-14 06:48 UTC, mjansenDatabay requested changes

2024-05-14 06:48 UTC, mjansenDatabay commented on components/ILIAS/Authentication/classes/StaticUrlHandler.php
> +        $additional_params = join('/', $request->getAdditionalParameters() ?? []);
Why do we need this?

2024-05-14 11:22 UTC, lscharmer commented on components/ILIAS/Authentication/classes/StaticUrlHandler.php
> +        $additional_params = join('/', $request->getAdditionalParameters() ?? []);
Duplicated line is removed

2024-05-14 11:39 UTC, mjansenDatabay approved these changes

2024-05-14 11:40 UTC, merged