fixed 37158: A11Y/LoginPage: The A11Y info page cannot be requested o…
ILIAS-eLearning/ILIAS pull request #7415
Opened 2024-04-23 12:00 UTC by alex40724

…n the login page

See
https://mantis.ilias.de/view.php?id=37158

2024-04-23 13:14 UTC, mjansenDatabay requested changes
Hi @alex40724 ,

thx for the PR.

I suggest to use class-strings to avoid problems when the classes are renamed in future. If classes are renamed (e.g. in PhpStorm) such class-strings are automatically renamed as well. This is maybe more "robust" than using "Search & Replace".

Best regards,
Michael

2024-04-23 13:14 UTC, mjansenDatabay commented on Services/Init/classes/class.ilStartUpGUI.php
> +            case "ilaccessibilitycontrolconceptgui":
```suggestion
            case strtolower(ilAccessibilityControlConceptGUI::class):
```

2024-04-23 13:14 UTC, mjansenDatabay commented on Services/Init/classes/class.ilInitialisation.php
> +            (strtolower($requestCmdClass ?? "") === "ilaccessibilitycontrolconceptgui")
```suggestion
            (strtolower($requestCmdClass ?? "") === strtolower(ilAccessibilityControlConceptGUI::class))
```

2024-04-23 15:03 UTC, alex40724 commented
@mjansenDatabay Yes, of course. I added your changes.

2024-04-29 09:03 UTC, mjansenDatabay approved these changes

2024-04-29 09:04 UTC, mjansenDatabay commented
@pascalseeland I'll merge and pick this to all relevant branches.

2024-04-29 09:05 UTC, merged

2024-04-29 09:30 UTC, alex40724 commented
@mjansenDatabay Thanks!