Remove mailing lists on user deletion
ILIAS-eLearning/ILIAS pull request #7437
Opened 2024-04-26 11:11 UTC by iszmais

https://mantis.ilias.de/view.php?id=41275

- Delete all of users mailing lists when deleting a user.
- Delete all mailing lists of users for wich he was the last contact when deleting a user.

2024-04-26 11:19 UTC, mjansenDatabay requested changes

2024-04-26 11:19 UTC, mjansenDatabay commented on Services/Contact/classes/class.ilMailingLists.php
> +            $entries[] = new ilMailingList(new ilObjUser((int) $row->user_id), $row->ml_id);
```suggestion
            $entries[] = new ilMailingList(new ilObjUser((int) $row->user_id), (int) $row->ml_id);
```

2024-04-26 11:19 UTC, mjansenDatabay commented on Services/Contact/classes/class.ilMailingLists.php
> +        while ($row = $res->fetchRow(ilDBConstants::FETCHMODE_OBJECT)) {
```suggestion
        while ($row = $ilDB->fetchObject($res)) {
```

2024-04-26 11:19 UTC, mjansenDatabay commented on Services/Contact/classes/class.ilMailingLists.php
> +            $entries[] = new ilMailingList(new ilObjUser((int) $row->user_id), $row->ml_id);
Creating user instances here is very expensive in terms of performance. We should avoid this in scenarios where dozens of user accounts can potentially be deleted at once.

Please use simple SQL statements within `ilMailingLists`.

2024-04-26 11:19 UTC, mjansenDatabay commented on Services/Contact/classes/class.ilContactAppEventListener.php
> +                    $related = new ilMailingLists(new ilObjUser($ass->getUserId()));
Creating user instances is very expensive, we should avoid this in scenarios where dozens of user accounts can potentially be deleted at once.

Please use simple SQL statements within `ilMailingLists`.

2024-04-26 14:07 UTC, iszmais commented
@mjansenDatabay I separated both problems in 2 different mantis issues.

Therefore this now only fix the missing deletion and all concerned scoped are deleted.
I will make a separate PR for the [other](https://mantis.ilias.de/view.php?id=41278)

2024-04-29 06:38 UTC, mjansenDatabay requested changes

2024-04-29 06:38 UTC, mjansenDatabay commented on Services/Contact/classes/class.ilContactAppEventListener.php
> +            }
Please introduce a new method `deleteAll` which deletes all these lists with one single SQL statement.

2024-05-02 06:20 UTC, mjansenDatabay approved these changes

2024-05-02 06:20 UTC, merged