Session/Object(List)/Info: Ensure proper input/output handling
ILIAS-eLearning/ILIAS pull request #7563
Opened 2024-05-24 09:03 UTC by mjansenDatabay

See: https://mantis.ilias.de/view.php?id=41228

If approved, this MUST be picked to `release_9` and `trunk`.

2024-05-24 09:13 UTC, kergomard approved these changes
Thank you very much @mjansenDatabay ! Changes in `ilObjectListGUI` are fine with me. I remove myself from the list of assignees.

2024-06-04 06:33 UTC, mjansenDatabay commented
Hi @smeyer-ilias and @alex40724  , do you have any objections here? I highly recommend merging this (or providing another solution).

2024-06-07 08:58 UTC, smeyer-ilias approved these changes
Thanks @mjansenDatabay

2024-06-21 09:45 UTC, mjansenDatabay commented
Hi @alex40724 ,

do you have any objections regarding `ilInfoScreenGUI`? I recommend addressing this Mantis issue before the release of 8.13 ;-).

Best regards
Michael

2024-06-26 15:38 UTC, alex40724 commented
@mjansen Thanks for the PR. We had this topic on one of the recent Jour Fixes. The info screen currently accepts HTML. Various components are using this.

See https://docu.ilias.de/goto_docu_wiki_wpage_7928_1357.html

Not rendering HTML is currently scheduled as breaking change for ILIAS 10.

We cannot introduce this with a bug fix, since it will break several views.

E.g. apply your fix and open the starting screen of a test.

It will look similar to the screenshot below and breaks several test features, e.g. "Verwendung vorheriger Lösungen":

<img width="989" alt="Bildschirmfoto 2024-06-26 um 17 28 49" src="https://github.com/ILIAS-eLearning/ILIAS/assets/1221841/f20421c7-e335-4e76-8710-2706f8c93e9a">

The consumers need to output escape exploitable keys/values here instead.

2024-06-26 15:38 UTC, alex40724 requested changes
See last comment.

2024-06-26 15:51 UTC, alex40724 commented
Here is a screenshot of the ListGUI patch part, which is broken, too:

<img width="989" alt="Bildschirmfoto 2024-06-26 um 17 49 52" src="https://github.com/ILIAS-eLearning/ILIAS/assets/1221841/d40723a7-f045-4bca-b53f-6f94be7b97d1">

2024-06-26 16:07 UTC, alex40724 commented
I close this since it breaks too much stuff. This needs a very different approach imo.

2024-06-26 16:07 UTC, closed without merging