User Bugfix: Initial Password set for new Users bugs out because of error in PasswordSettings
ILIAS-eLearning/ILIAS pull request #7611
Opened 2024-06-05 09:54 UTC by fhelfer

This PR fixes a looping redirect because the initial Password set for users throws an error, but the error page always redirects to password change. 

The Bug occurs because of the changes I did in https://github.com/ILIAS-eLearning/ILIAS/pull/7370 Whoops :)
thx @nmatuschek for finding this.

Best, @fhelfer

2024-06-05 10:35 UTC, mjansenDatabay requested changes

2024-06-05 10:35 UTC, mjansenDatabay commented on components/ILIAS/User/classes/class.ilForcedUserPasswordChangeStartUpStep.php
> +            ['ildashboardgui', 'ilpersonalsettingsgui', \ILIAS\Authentication\Password\LocalUserPasswordSettingsGUI::class],
```suggestion
            [ilDashboardGUI::class', ilPersonalSettingsGUI::class'', \ILIAS\Authentication\Password\LocalUserPasswordSettingsGUI::class],
```

2024-06-05 10:35 UTC, mjansenDatabay commented on components/ILIAS/User/classes/class.ilForcedUserPasswordChangeStartUpStep.php
> +        return;
Hmmm, can we just remove the `return;` and the code below?

2024-06-05 10:57 UTC, mjansenDatabay commented
@kergomard Should be move the user-related class to the `Auth` component?

2024-06-05 10:58 UTC, mjansenDatabay approved these changes

2024-06-05 12:39 UTC, kergomard approved these changes
Thank you very much  @fhelfer . The changes LGTM.

@mjansenDatabay : I would think this class should be in `Auth`, yes. ...unless you see a reason for it not to.

Best,
@kergomard

2024-06-11 09:26 UTC, mjansenDatabay requested changes
Hi @fhelfer , thx for the PR. Let's rename class `LocalUserPasswordSettingsGUI` to `ilLocalUserPasswordSettingsGUI` (without namespace) as long ist #[7624](https://github.com/ILIAS-eLearning/ILIAS/pull/7624)  is not merged.

2024-06-14 13:44 UTC, mjansenDatabay approved these changes

2024-06-14 13:44 UTC, merged