WIP IRSS Certificates
ILIAS-eLearning/ILIAS pull request #7658
Opened 2024-06-14 10:42 UTC by fhelfer

2024-07-09 11:20 UTC, klees commented
Hi @fhelfer,

I assigned you since this is WIP. If this PR leaves that stage: please remove the assignment.

Kind regards!

2024-08-16 10:31 UTC, mjansenDatabay commented on components/ILIAS/Tree/classes/class.ilTree.php
> +    public function buildJoin(string $alias = null): string
Please revert these changes in `ilTree`. IMO we don't need them.

2024-10-23 18:07 UTC, mjansenDatabay requested changes

2024-10-23 18:07 UTC, mjansenDatabay commented on components/ILIAS/Certificate/classes/Setup/class.ilCertificateDatabaseUpdateSteps.php
> +        $res = $this->db->query("SELECT value FROM settings WHERE keyword = 'defaultImageFileName'");
Please use `ilDbInterface::quote` here, and also query the "module" to ensure you get the correct value (e.g. in case plugins use the same keyword for other modules).

2024-10-23 18:07 UTC, mjansenDatabay commented on components/ILIAS/Certificate/classes/Setup/class.ilCertificateDatabaseUpdateSteps.php
> +        $this->db->manipulate("DELETE FROM settings WHERE keyword = 'defaultImageFileName'");
Please use `ilDbInterface::quote` here, and also query the "module" to ensure you get the correct value (e.g. in case plugins use the same keyword for other modules).

2024-10-23 18:07 UTC, mjansenDatabay commented on components/ILIAS/Certificate/classes/Setup/Migration/CertificateIRSSMigration.php
> +            return 0;
```suggestion
            return 0;
```

2024-10-23 18:07 UTC, mjansenDatabay commented on components/ILIAS/Certificate/classes/Setup/Migration/CertificateIRSSMigration.php
> +        }
Why not:

```suggestion
        $rid = '-';
        if ($rid instanceof ResourceIdentification) {
            $rid = $rid->serialize();
        }
```

2024-10-23 18:07 UTC, mjansenDatabay commented on components/ILIAS/Certificate/classes/Setup/class.ilCertificateDatabaseUpdateSteps.php
> +                    'type' => 'text',
Can we use `ilDBConstants` for all `type` attributes?

2024-10-23 18:07 UTC, mjansenDatabay commented on components/ILIAS/Certificate/classes/Setup/Migration/CertificateIRSSMigration.php
> +            ['text', 'text'],
Can we use `ilDBConstants` for all `type` attributes in this file?

2024-10-23 18:07 UTC, mjansenDatabay commented on components/ILIAS/Certificate/classes/Setup/Migration/CertificateIRSSMigration.php
> +        global $DIC;
```suggestion
```

2024-10-23 18:07 UTC, mjansenDatabay commented on components/ILIAS/Certificate/classes/Form/Repository/class.ilCertificateSettingsFormRepository.php
> +                    ILIAS_HTTP_PATH . '/public/' . ILIAS_WEB_DIR . '/' . CLIENT_ID . $old_thumbnail_image_path
IMO this is not correct. The `public` folder will not be part of the HTTP path if ILIAS is configured correctly.

2024-10-23 18:07 UTC, mjansenDatabay commented on components/ILIAS/Certificate/classes/Form/Repository/class.ilCertificateSettingsFormRepository.php
> +                ilWACSignedPath::signFile(
`public` will IMO not be part of the HTTP path, if ILIAS is configured correctly.

2024-10-23 18:07 UTC, mjansenDatabay commented on components/ILIAS/Certificate/classes/class.ilObjCertificateSettings.php
> +            return ilWACSignedPath::signFile(ILIAS_HTTP_PATH . '/public/' . ILIAS_WEB_DIR . '/' . CLIENT_ID . $id);
`public` will IMO not be part of the HTTP path, if ILIAS is configured correctly.

2024-10-24 16:48 UTC, mjansenDatabay approved these changes

2024-10-24 16:50 UTC, merged