T&A #41600: Change byline of Test Setting "Introductory message"
ILIAS-eLearning/ILIAS pull request #7727
Opened 2024-06-28 13:26 UTC by dsstrassner

for ilias_de & ilias_en.lang. Please cherry pick also to Trunk.

2024-06-28 13:40 UTC, dsstrassner commented
The feature request states as the second part of the Byline: "The message can be edited in the sub-tab "Introductory Message" of these settings and is accessible already before the test can be started." - The sub-tab part is missing, but the JourFixe decision has no information whether this byline part is okay or not. So, I changed only the "info" to "test"-tab. Maybe @matthiaskunkel could state, if we should add the "sub-tab" info also ;-)

2024-07-08 07:34 UTC, matthiaskunkel requested changes

2024-07-08 07:34 UTC, matthiaskunkel commented on lang/ilias_de.lang
> +assessment#:#tst_introduction_desc#:#Zeigt einen Einleitungstext auf dem 'Test'-Reiter an. Der Text ist bereits vor Beginn des Tests zugänglich.
Please use German Anführungszeichen: „Test“-Reiter.

2024-07-08 07:35 UTC, matthiaskunkel commented
And adding an additional information about where the introductory message is created would be fine for me.

2024-07-08 10:33 UTC, dsstrassner commented
Done ;-)

2024-07-15 12:33 UTC, merged

2024-07-15 12:35 UTC, thojou commented
Hey @dsstrassner,

i took your PR and integrated the changes into trunk.

Thank you.