41874: Cron.php does not work when account has IP restriction.
ILIAS-eLearning/ILIAS pull request #7910
Opened 2024-08-08 09:43 UTC by Hufschmidt

Siehe https://mantis.ilias.de/view.php?id=41874

Sollte eigentlich die sauberste Lösung sein. Damit wird der IP-Check für Accounts über die Konsole deaktiviert und es funktioniert wieder wie mit ILIAS 7.x und bevor. Für Login-Versuche über das Web-UI von ILIAS sollte die IP-Sperre weiterhin gelten

2024-08-08 09:55 UTC, mjansenDatabay requested changes
Thx @Hufschmidt , there is only one tiny code style violation.

2024-08-08 09:55 UTC, mjansenDatabay commented on Services/Authentication/classes/Frontend/class.ilAuthFrontendCLI.php
> +  }
```suggestion
  protected function checkIp(ilObjUser $user): bool
  {
    return true;
  }
```

2024-08-08 10:13 UTC, Hufschmidt commented on Services/Authentication/classes/Frontend/class.ilAuthFrontendCLI.php
> +  }
Ah, nicht dran gedacht. Sollte nun gefixed sein. (Habe auch noch spaces durch tabs ersetzt)

2024-08-08 10:17 UTC, mjansenDatabay commented on Services/Authentication/classes/Frontend/class.ilAuthFrontendCLI.php
> +  }
Mittlerweile ist es anders, Spaces sind korrekt, Tabs seit ein paar Jahre nicht mehr :-).

2024-08-08 10:21 UTC, Hufschmidt commented on Services/Authentication/classes/Frontend/class.ilAuthFrontendCLI.php
> +  }
Huch, hab wohl schon lange nichts mehr commited, jetzt auch wieder mit spaces. :D
Aller guten Dinge sind ~~drei~~ vier... :)

2024-08-08 10:59 UTC, merged

2024-08-21 10:53 UTC, mjansenDatabay commented
This PR may affect the SOAP authentication: https://mantis.ilias.de/view.php?id=41941