Implement ability to use styles for login & logout page editor
ILIAS-eLearning/ILIAS pull request #7987
Opened 2024-08-23 11:56 UTC by mBeym

2024-08-23 12:05 UTC, mjansenDatabay requested changes

2024-08-23 12:05 UTC, mjansenDatabay commented on components/ILIAS/Init/classes/class.ilStartUpGUI.php
>          // get page object
```suggestion

```

2024-08-23 12:05 UTC, mjansenDatabay commented on components/ILIAS/Authentication/classes/class.ilObjAuthSettingsGUI.php
> +                break;
```suggestion
                break;

```

2024-08-23 12:05 UTC, mjansenDatabay commented on components/ILIAS/Authentication/classes/class.ilObjAuthSettingsGUI.php
> +                    $this->ctrl->getLinkTargetByClass(ilObjectContentStyleSettingsGUI::class, "")
```suggestion
                    $this->ctrl->getLinkTargetByClass(ilObjectContentStyleSettingsGUI::class)
```

2024-08-23 12:05 UTC, mjansenDatabay commented on components/ILIAS/Authentication/classes/class.ilObjAuthSettingsGUI.php
> +            case strtolower(ilObjectContentStyleSettingsGUI::class):
```suggestion

            case strtolower(ilObjectContentStyleSettingsGUI::class):
```

2024-08-23 12:05 UTC, mjansenDatabay commented on components/ILIAS/Authentication/classes/class.ilObjAuthSettingsGUI.php
> +                $this->checkPermission("write");
```suggestion
                $this->checkPermission('write');
```

2024-08-23 12:05 UTC, mjansenDatabay commented on components/ILIAS/Authentication/classes/class.ilObjAuthSettingsGUI.php
> +                $this->tabs_gui->activateSubTab("style");
```suggestion
                $this->setSubTabs('authSettings');
                $this->tabs_gui->activateTab('authentication_settings');
                $this->tabs_gui->activateSubTab('style');
```

2024-08-23 12:05 UTC, mjansenDatabay commented on components/ILIAS/Authentication/classes/class.ilAuthLoginPageEditorGUI.php
> +            ->styleForRefId($a_ref_id);
Why do we use a different "ref_id" compared to `ilStartupGUI`.

2024-08-23 12:05 UTC, mjansenDatabay commented on components/ILIAS/Authentication/classes/class.ilAuthLogoutPageEditorGUI.php
> +            ->styleForRefId($a_ref_id);
Why do we use a different "ref_id" compared to `ilStartupGUI`.

2024-08-23 12:05 UTC, mjansenDatabay commented on components/ILIAS/Authentication/classes/class.ilAuthLogoutPageEditorGUI.php
> +        $this->content_style_gui->addCss($this->tpl,  $this->ref_id);
Why do we use a different "ref_id" compared to `ilStartupGUI`.

2024-08-23 12:27 UTC, mBeym commented on components/ILIAS/Authentication/classes/class.ilAuthLoginPageEditorGUI.php
> +            ->styleForRefId($a_ref_id);
why should I load the ref_id from the database when it's already supplied as a parameter?

2024-08-23 13:25 UTC, mjansenDatabay commented on components/ILIAS/Authentication/classes/class.ilAuthLoginPageEditorGUI.php
> +            ->styleForRefId($a_ref_id);
If it is the identical `$ref_id` we could leave this as it is.

2024-08-23 13:26 UTC, mjansenDatabay requested changes

2024-08-23 13:26 UTC, mjansenDatabay commented on components/ILIAS/Init/classes/class.ilStartUpGUI.php
> +    }
This method must not be part of a GUI class.

2024-08-26 06:43 UTC, mjansenDatabay requested changes

2024-08-26 06:43 UTC, mjansenDatabay commented on components/ILIAS/Init/classes/class.ilStartUpGUI.php
> +        )['ref_id'];
We MUST NOT put any database operations in the GUI-layer.

2024-08-26 06:43 UTC, mjansenDatabay commented on components/ILIAS/Init/classes/class.ilStartUpGUI.php
> +        )['ref_id'];
We MUST NOT put any database operations in the GUI-layer.

2024-08-26 08:04 UTC, mjansenDatabay requested changes

2024-08-26 08:04 UTC, mjansenDatabay commented on components/ILIAS/Init/classes/class.ilStartUpGUI.php
> +        $auth_settings_ref_id = (int) reset($auth_settings_ref_ids);
This looks like duplicate code, please provide a centralized method for this.

2024-09-16 13:21 UTC, mjansenDatabay commented on components/ILIAS/Authentication/classes/class.ilObjAuthSettings.php
> +        return (int) reset($auth_settings_ref_ids);
```suggestion

        return (int) reset($auth_settings_ref_ids);
```

2024-09-17 10:32 UTC, mjansenDatabay commented on components/ILIAS/Authentication/classes/class.ilObjAuthSettingsGUI.php
> +class ilObjAuthSettingsGUI extends ilObjectGUI implements ilContentPageObjectConstants
```suggestion
class ilObjAuthSettingsGUI extends ilObjectGUI
```
```suggestion
class ilObjAuthSettingsGUI extends ilObjectGUI implements ilContentPageObjectConstants
```
```suggestion
class ilObjAuthSettingsGUI extends ilObjectGUI implements ilContentPageObjectConstants
```

2024-09-17 10:33 UTC, mjansenDatabay commented on components/ILIAS/Authentication/classes/class.ilObjAuthSettingsGUI.php
> +                    self::UI_TAB_ID_STYLE,
```suggestion
                    'style',
```

2024-09-18 05:54 UTC, merged