[FEATURE] UI: introduce new `Progress\Bar` component.
ILIAS-eLearning/ILIAS pull request #8003
Opened 2024-08-28 15:14 UTC by thibsy

Hi folks,

I have picked up @chfsx's work from #7597 and want to introduce a new `Progress\Bar` component with this PR.
This PR is not yet finalised, I will update this description and convert to "normal" PR once its ready.

kind regards,
@thibsy

2024-10-09 19:43 UTC, klees requested changes
Just some minor wording and typo stuff.

2024-10-09 19:43 UTC, klees commented on components/ILIAS/UI/src/Component/Progress/Factory.php
> +     *     components, and instructs them to perform a desierd change. We have been referring to
```suggestion
     *     components, and instructs them to perform a desired change. We have been referring to
```

2024-10-09 19:43 UTC, klees commented on components/ILIAS/UI/src/Component/Progress/Instruction/Bar/Factory.php
> +     *     Factors a Progress Bar Instruction which orders the clientside Progress Bar
```suggestion
     *     Creates a Progress Bar Instruction which orders the clientside Progress Bar
```

"to factor" means something else =)

2024-10-09 19:43 UTC, klees commented on components/ILIAS/UI/src/examples/Progress/Bar/client.php
> + *   Stadnard Button is clicked, the Progress Bar value us increased by 10% each time.
```suggestion
 *   Standard Button is clicked, the Progress Bar value us increased by 10% each time.
```

2024-10-10 07:51 UTC, Amstutz commented
Hi Thibeau,

thanks a lot for this PR. Nicely worked out. However, there are some questions and suggestions, as usual!

Please change:
- [ ] Minor Corrections: Please change typos and spelling according to @klees' review 

Please change or indicate why not:
- [ ] A11y: Add some A11y rules for the Progress Bar, enforcing it the be usable and understandable without any graphical UI.
- [ ] Progress: In the naming there is a high overlap. with Progress Meter (as also noted in details). Could the Progress Bar also be a Chart? Not sure, if we like the Progress as a family on top level, although there definitly is some semantic overlap with the workflow listing. Can people understand what to find in "Progress"? Also, the bar mostly is a visualisation (a simple text "7%" or something would do the same...), hence `Chart seems to be a good match. `Bar` and `Progress` could then become siblings in a `Progress` family?
- [ ] Float: Try not to use them (in general =)), they are full of surprises and ill behaviour. Try to use rationals ifpossible, either with fixed or variable denominator. For this usecase here: Wo we really want to know sub-percent process? If not: a simple `int` between 0 and 100 would do just fine. If we want sub-percent process, maybe 0...1000 gives enough room? If we want to have other scales (see last question below), we could allow users to pick the denominator.
- [ ] Text-Smithing: The [`in a single step`](https://github.com/ILIAS-eLearning/ILIAS/pull/8003/files#diff-57376164217c293595cf037a163a2f612d0c9a8265233c02746b4a1e90b447ecR32), would benefit from a `in a single step **without further user interaction**`, if that is really meant here. Something similar goes for the description of the `Workflow` rival. 

Please answer the following question:
- [ ] Instruction: Is it a UI Component? From the description, this all looks much more like technical detail to keep internal.
- [ ] Percent scale: How sure are you that we really only want to have a progress bar showing percents? There are use cases like "copy object" where "x of y subobjects" seems to be a semantic (instead of "X% of copy process") where users would understand the actual scale of the whole process better. Could we easily incorporate this now? How would we incorporate it later?

thx a lot 
@amstutz and @klees

2024-10-10 14:43 UTC, thibsy commented
Hi @Amstutz and @klees,

Thx for your feedback! Let me answer your questions right away:

- `Progress` (family): I was doing some research, and I found out "the meter element should not be used to indicate progress (as in a progress bar)" (https://html.spec.whatwg.org/#the-meter-element). Therefore I suggest to rename the `ProgressMeter` to `Meter`, so we can get rid of this overlap. With this in mind it also makes more sense that `Meter` is a `Chart`. The progress bar does IMO not fit into this category for one reason: It knows an indeterminate state, which does not represent any raw data on purpose, and is simply used to indicate _progress_. Since this component has actually some overlap with the `Listing\Workflow` component, it made sense to me to introduce their own family (`Workflow` still needs to be moved). I think consumers can expect these kind of components to be simple indicators of progress within a process or task, be that a percentage, timeline, steps or simple text. This task could e.g. also be **loading**, where we could introduce components to improve [user waiting experience](https://uxdesign.cc/loading-progress-indicators-ui-components-series-f4b1fc35339a) (which actually becomes important with more asynchronous rendering). I also believe that this entire component family should be strictly internal someday.
- Percent scale: You are right. There will probably be the need for more flexibility in regards of scales. However, the `Progress\Bar` is represented as a percentage by design, so I think the different scales would only ever affect the wording around it. This could also lead to very basic representations like `1 out of 9` in certain contexts, but maybe these should not be considered `Progress\Bar`s anymore. IMO, the allowance of different scales would only be sugar for our consumers at this point, because the component ultimately breaks it down to a percentage. Nonetheless, maybe in the next round this component or component family can benefit from some `ILIAS\Data` type, which can be used to configure your own scale. But maybe these should also be other components altogether.
- Instruction(s): You are right again :). These "components" are definitely meant to be kept internal and should not be exposed on the factory like they are right now. However, we are limited by the technology of our time, so we need to expose these components for the time being. Otherwise consumers will not be able to use them properly inside their endpoints. Our goal is to ultimately shift the request handling closer to the UI framework, which is made possible by the new component revision. This will allow us to only ever expose this factory to some kind of `InstructionRetrieval`, which will be managed by the UI framework during asynchronous requests. @klees and I have already discussed the concept of "HTML over the wire" for some time now, and this (and the proposed prompts) are the first implementation(s) of it. "HTML over the wire" refers to the asynchronous rendering of components, where a client-side component requests HTML from an endpoint, which will be used to update the current HTML in some way. The idea is that instructions are shaped into sections, each of which conveys specific HTML for specific parts of the existing HTML structure. While talking about this in a short meeting with @klees today, we have realised that we were focusing too much on "ordering the client to do something", while we should have rather focused on the thing at hand. This is why we have decided to rename this (again) to `State`. Now it should be more visible as to why this thing is a component. 

The rest of your review is incorporated. I especially agree with your remarks about the floating point numbers. I also renamed to argument to a more appropriate `$visual_progress_value`, and phrased the factory description accordingly.

Let me know if this is ready for JF then.

Kind regards,
@thibsy

2024-10-14 13:30 UTC, matthiaskunkel commented
Jour Fixe, 14 OCT 2024: We highly appreciate this suggestion and accept the PR for ILIAS 10.

2024-10-25 16:41 UTC, merged