Revise Content-Tab »Folder« in User Mail System
ILIAS-eLearning/ILIAS pull request #8020
Opened 2024-09-09 07:00 UTC by fneumann

See feature request:
https://docu.ilias.de/goto_docu_wiki_wpage_8177_1357.html

2024-09-10 08:07 UTC, mjansenDatabay requested changes
Hi @fneumann ,

thx for your excellent work. I only found a few minor issues and added some code style remarks (because of personal preference).

Please apply the following changes:
- [x] Replace usages of `isset` on member variables of classes with a `$this->variable !== null` check, or `!isset` with `$this->variable === null`.

And one question:
- What was the personal indicator for you to introduce `Enum` for some use cases and constants for other use cases? I am just curious, I don't see any necessity to change this..

Best regards
Michael

2024-09-10 08:07 UTC, mjansenDatabay commented on components/ILIAS/Mail/classes/Folder/MailFolderSearch.php
> +    private ?array $filtered_ids = null;
Please try to provide the shape of the array by using PHPDoc Types: https://phpstan.org/writing-php-code/phpdoc-types

2024-09-10 08:07 UTC, mjansenDatabay commented on components/ILIAS/Mail/classes/Folder/MailFolderTableUI.php
> +     * @return TableColumn[]
```suggestion
     * @return array<string, TableColumn>
```

2024-09-10 08:07 UTC, mjansenDatabay commented on components/ILIAS/Mail/classes/Folder/MailFolderSearch.php
> +     * @return self
```suggestion
```

2024-09-10 08:07 UTC, mjansenDatabay commented on components/ILIAS/Mail/classes/Folder/MailFolderTableUI.php
> +        return trim(($record->getImportName() ?? '') . ' (' . $this->lng->txt('user_deleted') . ')');
```suggestion

        return trim(($record->getImportName() ?? '') . ' (' . $this->lng->txt('user_deleted') . ')');
```

2024-09-10 08:07 UTC, mjansenDatabay commented on components/ILIAS/Mail/classes/Folder/MailFolderTableUI.php
> +            return $user->getPublicName();
```suggestion

            return $user->getPublicName();
```

2024-09-10 08:07 UTC, mjansenDatabay commented on components/ILIAS/Mail/classes/Folder/MailFolderTableUI.php
> +        if (!empty($user = ilMailUserCache::getUserObjectById($record->getSenderId()))) {
```suggestion

        if (!empty($user = ilMailUserCache::getUserObjectById($record->getSenderId()))) {
```

2024-09-10 08:07 UTC, mjansenDatabay commented on components/ILIAS/Mail/classes/Folder/MailFolderTableUI.php
> +        }
You can avoid the `else` branch here, just return the string.

2024-09-10 08:07 UTC, mjansenDatabay commented on components/ILIAS/Mail/classes/Folder/MailFolderTableUI.php
> +            // todo: probably check further moving restrictions (e.g. to/from drafts)
This seems like a forgotten TODO statement.

2024-09-10 08:07 UTC, mjansenDatabay commented on components/ILIAS/Mail/classes/Folder/MailFolderTableUI.php
> +        return $columns;
```suggestion

        return $columns;
```

2024-09-10 08:07 UTC, mjansenDatabay commented on components/ILIAS/Mail/classes/Message/MailBoxOrderColumn.php
> +
```suggestion
```

2024-09-10 08:07 UTC, mjansenDatabay commented on components/ILIAS/Mail/classes/Message/MailBoxQuery.php
> +    private ?array $filtered_ids = null;
Please try to provide the shape of the array by using PHPDoc Types: https://phpstan.org/writing-php-code/phpdoc-types

2024-09-10 08:07 UTC, mjansenDatabay commented on components/ILIAS/Mail/classes/Message/MailBoxQuery.php
> +
```suggestion
```

2024-09-10 08:07 UTC, mjansenDatabay commented on components/ILIAS/Mail/classes/Message/MailBoxQuery.php
> +        return $clone;
```suggestion

        return $clone;
```

2024-09-10 08:07 UTC, mjansenDatabay commented on components/ILIAS/Mail/classes/Message/MailBoxQuery.php
> +        return $clone;
```suggestion

        return $clone;
```

2024-09-10 08:07 UTC, mjansenDatabay commented on components/ILIAS/Mail/classes/Message/MailBoxQuery.php
> +
```suggestion
```

2024-09-10 08:07 UTC, mjansenDatabay commented on components/ILIAS/Mail/classes/Message/MailBoxQuery.php
> +        return 0;
```suggestion

        return 0;
```

2024-09-10 08:07 UTC, mjansenDatabay commented on components/ILIAS/Mail/classes/Message/MailBoxQuery.php
> +        if (!empty($this->period_end)) {
```suggestion

        if (!empty($this->period_end)) {
```

2024-09-10 08:07 UTC, mjansenDatabay commented on components/ILIAS/Mail/classes/Message/MailBoxQuery.php
> +        return '';
```suggestion

        return '';
```

2024-09-10 08:07 UTC, mjansenDatabay commented on components/ILIAS/Mail/classes/class.ilMailFolderGUI.php
> +
```suggestion
```

2024-09-10 08:07 UTC, mjansenDatabay commented on components/ILIAS/Mail/classes/Folder/MailFolderData.php
> +
```suggestion
```

2024-09-10 08:07 UTC, mjansenDatabay commented on components/ILIAS/Mail/classes/Folder/MailFolderSearch.php
> +        return $this->count;
```suggestion

        return $this->count;
```

2024-09-10 08:07 UTC, mjansenDatabay commented on components/ILIAS/Mail/classes/Folder/MailFolderSearch.php
> +        return $this->unread;
```suggestion

        return $this->unread;
```

2024-09-10 08:07 UTC, mjansenDatabay commented on components/ILIAS/Mail/classes/Folder/MailFolderSearch.php
> +        return $this->filtered_ids;
```suggestion

        return $this->filtered_ids;
```

2024-09-10 08:07 UTC, mjansenDatabay commented on components/ILIAS/Mail/classes/Folder/MailFolderTableUI.php
> +        return $this->avatars[$record->getSenderId()];
```suggestion

        return $this->avatars[$record->getSenderId()];
```

2024-09-10 08:07 UTC, mjansenDatabay commented on components/ILIAS/Mail/classes/Message/MailBoxQuery.php
> +        return $ids;
```suggestion

        return $ids;
```

2024-09-10 08:07 UTC, mjansenDatabay commented on components/ILIAS/Mail/classes/Message/MailBoxQuery.php
> +        return $set;
```suggestion

        return $set;
```

2024-09-10 08:07 UTC, mjansenDatabay commented on components/ILIAS/Mail/classes/class.ilMailFolderGUI.php
> +        return [];
```suggestion

        return [];
```

2024-09-10 08:07 UTC, mjansenDatabay commented on components/ILIAS/Mail/classes/class.ilMailFolderGUI.php
> +        echo $this->ui_renderer->renderAsync($modal);
Please use the HTTP service for "echo/exit" use cases. Don't hesitate to contact me if you have any questions.

2024-09-10 08:07 UTC, mjansenDatabay commented on components/ILIAS/Mail/classes/class.ilMailFolderGUI.php
> +                exit;
Please use the HTTP service for "echo/exit" use cases.

2024-09-10 08:07 UTC, mjansenDatabay commented on components/ILIAS/Mail/classes/Message/MailBoxQuery.php
> +        return $clone;
```suggestion

        return $clone;
```

2024-09-10 08:07 UTC, mjansenDatabay commented on components/ILIAS/Mail/classes/Message/MailBoxQuery.php
> +        return $clone;
```suggestion

        return $clone;
```

2024-09-10 08:07 UTC, mjansenDatabay commented on components/ILIAS/Mail/classes/Message/MailBoxQuery.php
> +        return $clone;
```suggestion

        return $clone;
```

2024-09-10 08:07 UTC, mjansenDatabay commented on components/ILIAS/Mail/classes/Message/MailBoxQuery.php
> +        return $clone;
```suggestion

        return $clone;
```

2024-09-10 08:07 UTC, mjansenDatabay commented on components/ILIAS/Mail/classes/Message/MailBoxQuery.php
> +        return $clone;
```suggestion

        return $clone;
```

2024-09-10 08:07 UTC, mjansenDatabay commented on components/ILIAS/Mail/classes/Message/MailBoxQuery.php
> +        return $clone;
```suggestion

        return $clone;
```

2024-09-10 08:07 UTC, mjansenDatabay commented on components/ILIAS/Mail/classes/Message/MailBoxQuery.php
> +        return $clone;
```suggestion

        return $clone;
```

2024-09-10 08:07 UTC, mjansenDatabay commented on components/ILIAS/Mail/classes/Message/MailBoxQuery.php
> +        return $clone;
```suggestion

        return $clone;
```

2024-09-10 08:07 UTC, mjansenDatabay commented on components/ILIAS/Mail/classes/Message/MailBoxQuery.php
> +        return $clone;
```suggestion

        return $clone;
```

2024-09-10 08:07 UTC, mjansenDatabay commented on components/ILIAS/Mail/classes/Message/MailBoxQuery.php
> +        return $clone;
```suggestion

        return $clone;
```

2024-09-10 08:07 UTC, mjansenDatabay commented on components/ILIAS/Mail/classes/Message/MailBoxQuery.php
> +        return $clone;
```suggestion

        return $clone;
```

2024-09-10 08:07 UTC, mjansenDatabay commented on components/ILIAS/Mail/classes/Message/MailBoxQuery.php
> +        return $clone;
```suggestion

        return $clone;
```

2024-09-10 08:07 UTC, mjansenDatabay commented on components/ILIAS/Mail/classes/Message/MailBoxQuery.php
> +        return $clone;
```suggestion

        return $clone;
```

2024-09-10 08:07 UTC, mjansenDatabay commented on components/ILIAS/Mail/classes/class.ilMailFolderGUI.php
> +        ] = (new URLBuilder($this->data_factory->uri(
```suggestion
        [
            $url_builder,
            $action_token,
            $row_id_token,
            $target_token,
        ] = (new URLBuilder($this->data_factory->uri(
```

2024-09-10 08:07 UTC, mjansenDatabay commented on components/ILIAS/Mail/classes/Folder/MailFolderSearch.php
> +        ) {
```suggestion
        if (!isset($this->filtered_ids) &&
            isset($this->lucene_result) &&
            isset($this->lucene_searcher)) {
```

2024-09-11 11:26 UTC, fneumann commented
Resolved all threads. 
Fixed an issue with unrecognized '0' as a filter condition. 

Regarding Enums and class constant:
I created Enums to use them as typed function parameters or return values. The actions of MailFolderTableUI are never passed this way but only used internally as array keys and externally as query parameters. Having them as class constants seemed enough.

2024-09-12 11:54 UTC, merged