UI: Testsuite for UI components - adding missing descriptions and …
ILIAS-eLearning/ILIAS pull request #8252
Opened 2024-10-23 13:18 UTC by lukastocker

…expected output to examples from Testrail (ILIAS core > Test Suites & Cases > UI-Service).

This PR is build on PR No. [6885](https://github.com/ILIAS-eLearning/ILIAS/pull/6885). 
Therefore its commits are also included in this PR. Please ignore them and just concentrate on [my commit](https://github.com/ILIAS-eLearning/ILIAS/commit/fa561b98795753372cec75b7fd3eff98f53f3888). 
This PR should be merged **after** PR 6885 is merged - not before.

2024-10-23 13:20 UTC, lukastocker commented
**Please note:**
Following Testrail Tests are not up-to-date:
- Menu > Sub
- ViewControl > Pagination no_pages

Following directories/files are missing a specific testcase in Testrail:
- Button > Minimize
- Card > Sdt > with_sections & with_title_action
- Card > RepositoryObject > (alle examples)
- Chart > Bar (horizontal and vertical)
- Dropzone > File > Standard > bulky
- Entity > (all examples)
- Help > (all examples)
- Image > Standard > with_additional_on_load_code, with_signal_action, with_string_action
- Image > Responsive > with_additional_high_resolution_source
- Input > Container > Form > Std > with_required_input
- Input > Field > ColorPicker
- Input > Field > Markdown
- Input > ViewControll > (all examples)
- Layout > Alignment (all examples)
- Listing > Entity
- Listing > Property
- MainControls > (all examples)
- Modal > LightboxCardPage > show_modal_on_button_click
- Panel > Sub > with_secondary_panel
- Table > Action (all examles)
- Table > Column (all examles)
- Table > Data (all examles)
- Table > Presentation > without_data
- Symbol > Glyph > Bold
- Symbol > Glyph > Header
- Symbol > Glyph > Italic
- Symbol > Glyph > Launch
- Symbol > Glyph > Link
- Symbol > Glyph > Sortation

2024-10-23 14:06 UTC, lukastocker commented
**Additional Note:**

I am unsure why the checks (8.1, 8.2) are failing. We looked into the issue but couldn't find a reason why the process exits with code 8. Locally it runs fine. The PR is up-to-date with the latest release_9 branch.

2024-10-25 12:35 UTC, Amstutz requested changes
Hi @lukastocker 

Thx a lot for this. I was reading through the texts and noted the types down. However, GitHub became extremely slow while nearing 100 proposed changes, so I stopped. We should, however, go through the rest once merged. I made it up to Input / Text (in alphabetical order).

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Button/Bulky/base.php
> + *   the widht of the box in the background. Clicking the button won't activate any actions.
```suggestion
 *   the width of the box in the background. Clicking the button won't activate any actions.
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Button/Bulky/engaged.php
> + *   ILIAS shows a button with a glyph and the title "Engaged". The button looks different than the base bulky button.
```suggestion
 *   ILIAS shows a button with a glyph and the title "Engaged". The button looks different from the base bulky button.
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Button/Bulky/with_tooltip.php
> + *   ILIAS shows an icon titled "Goto ILIAS". Hovering over the text will show you following tooltips: "tooltip: ilias"
```suggestion
 *   ILIAS shows an icon titled "Goto ILIAS". Hovering over the text will show you the following tooltips: "tooltip: ilias"
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Button/Close/base.php
> + *   ILIAS shows a grey box with an dark grey "X" in the right corner. Clicking the "X" won't activate any action.
```suggestion
 *   ILIAS shows a gray box with a dark gray "X" in the right corner. Clicking the "X" won't activate any action.
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Button/Close/base.php
> + *  In some cases, additional CSS will be needed for placing the button
```suggestion
 *  In some cases, additional CSS will be required for placing the button
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Button/Minimize/base.php
> + *  In some cases, additional CSS will be needed for placing the button
```suggestion
 *  In some cases, additional CSS will be required for placing the button
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Button/Month/base.php
> + *   a long kombination of numbers/letters and additionally the selected month (e.g. 03-2020).
```suggestion
 *   a long combination of numbers/letters and additionally the selected month (e.g. 03-2020).
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Button/Primary/with_load_anim.php
> + *   "Working..." and the button's color will change to grey. During that process you can not click the button. After a
```suggestion
 *   "Working..." and the button's color will change to gray. During that process you cannot click the button. After a
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Button/Primary/with_tooltip.php
> + *   ILIAS shows an active button titled "Goto ILIAS". Hovering over the button will show you a tooltip with following
```suggestion
 *   ILIAS shows an active button titled "Goto ILIAS". Hovering over the button will show you a tooltip with the following
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Button/Shy/unavailable_action.php
> + *   ILIAS shows a small button titled "Unavailable". The button's background is colored dark grey. Clicking the button
```suggestion
 *   ILIAS shows a small button titled "Unavailable". The button's background is colored dark gray. Clicking the button
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Button/Shy/with_tooltip.php
> + *   ILIAS shows a small button titled "Goto ILIAS". Hovering over the button will show a tooltip with following contents:
```suggestion
 *   ILIAS shows a small button titled "Goto ILIAS". Hovering over the button will show a tooltip with the following contents:
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Button/Shy/with_tooltip.php
> + *   "tooltip: ilias" and "tooltip: learning managemend system".
```suggestion
 *   "tooltip: ilias" and "tooltip: learning management system".
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Button/Standard/engaged.php
> + *   ILIAS shows a grey, active button titled "Engaged". The button looks different to the base standard button.
```suggestion
 *   ILIAS shows a gray, active button titled "Engaged". The button looks different from the base standard button.
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Button/Standard/unavailable_action.php
> + *   ILIAS shows a inactive button titled "Unavailable". The button is more prominent as compared to the base standard button.
```suggestion
 *   ILIAS shows an inactive button titled "Unavailable". The button is more prominent as compared to the base standard button.
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Button/Tag/base.php
> + *   ILIAS shows four different buttons titled "simple tag" in following order:
```suggestion
 *   ILIAS shows four different buttons titled "simple tag" in the following order:
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Button/Tag/base.php
> + *   2. with unavailable action: five grey buttons which are not clickable. A click won't activate any actions.
```suggestion
 *   2. with unavailable action: five gray buttons which are not clickable. A click won't activate any actions.
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Button/Tag/base.php
> + *   3. with additional class(es): a very broad button with a loading animation at the right side.
```suggestion
 *   3. with additional class(es): a very broad button with a loading animation on the right side.
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Button/Toggle/base.php
> + *   ILIAS shows a switch. Clicking onto the switch will result to the switch moving to the right side and opening a
```suggestion
 *   ILIAS shows a switch. Clicking onto the switch will result in the switch moving to the right side and opening a
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Button/Toggle/with_tooltip.php
> + *   Hovering over the switch shows following tooltips: "tooltip: ilias" and "tooltip: learning management system".
```suggestion
 *   Hovering over the switch shows the following tooltips: "tooltip: ilias" and "tooltip: learning management system".
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Chart/ProgressMeter/FixedSize/maximum_configuration.php
> + *   display. The inner bar is colored grey and takes up the half of the display. A triangle marks the needed value at
```suggestion
 *   display. The inner bar is colored gray and takes up the half of the display. A triangle marks the needed value at
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Chart/ProgressMeter/FixedSize/maximum_configuration.php
> + *   80%. The informations "Your Score 75%" and "80% Required Score" are positioned within the progress meter.
```suggestion
 *   80%. The information "Your Score 75%" and "80% Required Score" are positioned within the progress meter.
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Chart/ProgressMeter/FixedSize/only_comparison_value.php
> + *   Example for rendering a fixed size Progress Meter with an diagnostic score only
```suggestion
 *   Example for rendering a fixed size Progress Meter with a diagnostic score only
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Chart/ProgressMeter/FixedSize/only_comparison_value.php
> + *   The inner bar is colored grey and takes up half of the display. A triangle marks the needed value at 75%. The
```suggestion
 *   The inner bar is colored gray and takes up half of the display. A triangle marks the needed value at 75%. The
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Chart/ProgressMeter/FixedSize/only_comparison_value.php
> + *   informations "0%" and "75%" are displayed within the progress meter.
```suggestion
 *   information "0%" and "75%" are displayed within the progress meter.
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Chart/ProgressMeter/FixedSize/user_reached_required.php
> + *   marks the needed value at 75%. The informations "80%" and "75%" are positioned within the progress meter.
```suggestion
 *   marks the needed value at 75%. The information "80%" and "75%" are positioned within the progress meter.
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Chart/ProgressMeter/Mini/maximum_configuration.php
> + *   ILIAS shows a rounded progress meter with a red colored bar. The bar takes up half of the display. A grey bar marks
```suggestion
 *   ILIAS shows a rounded progress meter with a red colored bar. The bar takes up half of the display. A gray bar marks
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Chart/ProgressMeter/Mini/reached_100_percent.php
> + *   Example for rendering a mini Progress Meter when 100% are reached
```suggestion
 *   Example for rendering a mini Progress Meter when 100% is reached
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Chart/ProgressMeter/Standard/maximum_configuration.php
> + *   progress meter. The inner bar is colored grey and takes up half of the progress meter. A triangle marks the needed value
```suggestion
 *   progress meter. The inner bar is colored gray and takes up half of the progress meter. A triangle marks the needed value
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Chart/ProgressMeter/Standard/maximum_configuration.php
> + *   at "80%". The informations "Your Score 75%" and "80% Required Score" are positioned within the progress meter.
```suggestion
 *   at "80%". The information "Your Score 75%" and "80% Required Score" are positioned within the progress meter.
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Chart/ProgressMeter/Standard/only_comparison_value.php
> + *   the needed value at 75%. The informations "0%" and "75%" are also positioned within the progress meter.
```suggestion
 *   the needed value at 75%. The information "0%" and "75%" are also positioned within the progress meter.
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Chart/ProgressMeter/Standard/only_comparison_value.php
> + *   Example for rendering a standard Progress Meter with an comparison value only
```suggestion
 *   Example for rendering a standard Progress Meter with a comparison value only
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Chart/ProgressMeter/Standard/user_reached_required.php
> + *   marks the needed value at 75%. The Informations "80%" and "75%" are positioned within the progress meter.
```suggestion
 *   marks the needed value at 75%. The Information "80%" and "75%" are positioned within the progress meter.
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Counter/Status/base.php
> + *   ILIAS shows a rendered glyph with a counter. The counter consists of a white colored number within a grey circle.
```suggestion
 *   ILIAS shows a rendered glyph with a counter. The counter consists of a white colored number within a gray circle.
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Counter/Status/multiple_glyphs.php
> + *   The counters consist of a white number each and are highlighted red resp. grey
```suggestion
 *   The counters consist of a white number each and are highlighted red resp. gray.
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Counter/Status/with_js.php
> + *   ILIAS shows differennt JS-exmaples which can get altered directly:
```suggestion
 *   ILIAS shows different JS-exmaples which can get altered directly:
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Counter/Status/with_novelty.php
> + *   ILIAS shows a glyph with two counters. The counter's numbers are white and highlighted red resp. grey.
```suggestion
 *   ILIAS shows a glyph with two counters. The counter's numbers are white and highlighted red resp. gray.
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Deck/base.php
> + *   ILIAS shows nine "Cards" with a title and text each. According to the browser window/desktop size the a different
```suggestion
 *   ILIAS shows nine "Cards" with a title and text each. According to the browser window/desktop size a different
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Deck/repository.php
> + *   ILIAS shows nine cards with a title and text each. Additionally every single card include outlined icons, certificate
```suggestion
 *   ILIAS shows nine cards with a title and text each. Additionally every single card includes outlined icons, certificate
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Deck/user.php
> + *   ILIAS shows seven "Cards" with a title ("Timon Amstutz") and Text (Adress and E-Mail Adress) each. A button "Request
```suggestion
 *   ILIAS shows seven "Cards" with a title ("Timon Amstutz") and Text (Address and E-Mail Address) each. A button "Request
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Deck/xl_card.php
> + *   to the size of the browser window/desktop.
```suggestion
 *   the size of the browser window/desktop.
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Divider/Horizontal/base.php
> + *   ILIAS shows a fine dark grey dividing line within a light grey box.
```suggestion
 *   ILIAS shows a fine dark gray dividing line within a light gray box.
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Divider/Horizontal/with_label.php
> + *   ILIAS shows a bulky white dividing line within a light grey box. The text "Label" is positioned within the line.
```suggestion
 *   ILIAS shows a bulky white dividing line within a light gray box. The text "Label" is positioned within the line.
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Dropdown/Standard/with_buttons_and_links.php
> + *   appropriate website in a new browser tab.,
```suggestion
 *   appropriate website in a new browser tab.
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Dropzone/File/Standard/base.php
> + *   see the file in said small window too. You can upload any amount of files. The window will be closed if you click
```suggestion
 *   see the file in said small window, too. You can upload any number of files. The window will be closed if you click
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Dropzone/File/Wrapper/base.php
> + *   including two buttons named "Save" and "Close". The file will be shown too. You can remove a uploaded file by clicking
```suggestion
 *   including two buttons named "Save" and "Close". The file will be shown too. You can remove an uploaded file by clicking
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Dropzone/File/Wrapper/with_additional_input.php
> + *   written. You can remove a uploaded file by clicking onto the "X" on the right side.
```suggestion
 *   written. You can remove an uploaded file by clicking onto the "X" on the right side.
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Image/Responsive/base.php
> + *   ILIAS shows a rendered image. While changing the sitze of the browser window the image will
```suggestion
 *   ILIAS shows a rendered image. While changing the size of the browser window, the image will
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Image/Responsive/base.php
> + *   decrease in size bit by bit. If the element gets analyzed a text entry for "alt" is shown withing the HTML.
```suggestion
 *   decrease in size bit by bit. If the element gets analyzed, a text entry for "alt" is shown within the HTML.
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Image/Standard/base.php
> + *   ILIAS shows a rendered image with a grey background. While changing the size of the browser window the
```suggestion
 *   ILIAS shows a rendered image with a gray background. While changing the size of the browser window the
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Image/Standard/decorative.php
> + *   ILIAS shows a rendered image with a grey background. While changing the size of the browser window the
```suggestion
 *   ILIAS shows a rendered image with a gray background. While changing the size of the browser window the
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Image/Standard/with_additional_on_load_code.php
> + *   In this example, an alert is popping up a soon as the image is clicked.
```suggestion
 *   In this example, an alert pops up as soon as the image is clicked.
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Input/Container/Filter/Standard/base.php
> + *   Clicking "Reset" will reset all filter.
```suggestion
 *   Clicking "Reset" will reset all filters.
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Input/Container/Form/Standard/base.php
> + *  Clicking "Save" relaods the page.
```suggestion
 *  Clicking "Save" reloads the page.
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Input/Container/Form/Standard/data_processing.php
> + *   Please enter an advertised number in english between 1 and 10 (e.g. "two" and "four").
```suggestion
 *   Please enter an advertised number in English between 1 and 10 (e.g. "two" and "four").
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Input/Container/Form/Standard/data_processing.php
> + *   ILIAS will add those numbers after the input was saved. The output will be displayed in following format:
```suggestion
 *   ILIAS will add those numbers after the input was saved. The output will be displayed in the following format:
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Input/Container/Form/Standard/data_processing.php
> + *   Entering unvalid inputs will result to an error message below the input fields.
```suggestion
 *   Entering invalid inputs will result in an error message below the input fields.
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Input/Container/Form/Standard/with_keys.php
> + *   Your input will be displayed in following format after being saved:
```suggestion
 *   Your input will be displayed in the following format after being saved:
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Input/Field/Checkbox/base.php
> + *   checkbox it will be displayed above (activ = 1).
```suggestion
 *   checkbox it will be displayed above (active = 1).
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Input/Field/Checkbox/disabled.php
> + *   ILIAS shows a section with an checkbox. The checkbox can not get changed.
```suggestion
 *   ILIAS shows a section with a checkbox. The checkbox cannot get changed.
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Input/Field/DateTime/base.php
> + *   ILIAS shows a group of date and time fields in following format:
```suggestion
 *   ILIAS shows a group of date and time fields in the following format:
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Input/Field/DateTime/base.php
> + *   A calendar glyph is displayed next to each field, except for the thrid line: there you can see a clock glyph.
```suggestion
 *   A calendar glyph is displayed next to each field, except for the third line: there you can see a clock glyph.
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Input/Field/DateTime/base.php
> + *   Clicking the glyphs will display following options:
```suggestion
 *   Clicking the glyphs will display the following options:
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Input/Field/Duration/base.php
> + *   A calendar glyph is displayer next to each field, except for line 3 and 4, which display a clock glyph.
```suggestion
 *   A calendar glyph is displayed next to each field, except for line 3 and 4, which display a clock glyph.
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Input/Field/Duration/base.php
> + *   ILIAS shows a group with eight date and time fields. Each are connected are mark the beginning and end of a period of time:
```suggestion
 *   ILIAS shows a group with eight date and time fields. Each mark the beginning and end of a period of time:
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Input/Field/Duration/base.php
> + *   ILIAS reloads the page and displays your selection in a array overview. The selection has to be the same as the output.
```suggestion
 *   ILIAS reloads the page and displays your selection in an array overview. The selection has to be the same as the output.
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Input/Field/File/in_form.php
> + *   files" or dragging a file to the box. Save your selection. ILIAS will confirm your action in following format:
```suggestion
 *   files" or dragging a file to the box. Save your selection. ILIAS will confirm your action in the following format:
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Input/Field/Group/base.php
> + *   validations errors. This is context dependant.
```suggestion
 *   validation errors. This is context dependent.
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Input/Field/Group/base.php
> + *   the page. If the addition of both the inserted numbers equals 10 ILIAS will display following:
```suggestion
 *   the page. If the addition of both the inserted numbers equals 10 ILIAS will display the following:
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Input/Field/Group/disabled.php
> + *   and can not get changed, because the fields are deactivated. Clicking "Save" will reload the page and ILIAS displays
```suggestion
 *   and cannot get changed because the fields are deactivated. Clicking "Save" will reload the page and ILIAS displays
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Input/Field/Hidden/base.php
> + *   ILIAS shows an empty white field. Clicking "Save" relaods the page.
```suggestion
 *   ILIAS shows an empty white field. Clicking "Save" reloads the page.
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Input/Field/Link/base.php
> + *   Now enter a text into the label field and an unvalid URL into the URL field and save your input. An error message
```suggestion
 *   Now enter a text into the label field and an invalid URL into the URL field and save your input. An error message
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Input/Field/Link/base.php
> + *   ILIAS shows two input fields titled "Label" and "URL". You can enter letters and number into the label field. You
```suggestion
 *   ILIAS shows two input fields titled "Label" and "URL". You can enter letters and numbers into the label field. You
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Input/Field/Markdown/base.php
> + *   Example show how to create and render a basic markdown field and attach it to a form.
```suggestion
 *   The Example shows how to create and render a basic markdown field and attach it to a form.
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Input/Field/Markdown/with_limits.php
> + *  Example show how to create and render a basic markdown field and attach it to a form.
```suggestion
 *  The Example shows how to create and render a basic markdown field and attach it to a form.
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Input/Field/MultiSelect/base.php
> + *   ILIAS shows a groupd titled "Take your picks" with checkboxes. You can activate one or more checkboxes. After saving
```suggestion
 *   ILIAS shows a grouped titled "Take your picks" with checkboxes. You can activate one or more checkboxes. After saving
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Input/Field/MultiSelect/base.php
> + *   your selection ILIAS will display your selection in following format:
```suggestion
 *   your selection ILIAS will display your selection in the following format:
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Input/Field/MultiSelect/empty_options.php
> + *   ILIAS shows an empty field with following text: "No options". Clicking "Save" will result into following output:
```suggestion
 *   ILIAS shows an empty field with the following text: "No options". Clicking "Save" will result into the following output:
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Input/Field/Numeric/numeric_inputs.php
> + *   is required (*). You can enter numbers into the fields or choose a number through useing the arrows at the end of the fields.
```suggestion
 *   is required (*). You can enter numbers into the fields or choose a number b< using the arrows at the end of the fields.
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Input/Field/Numeric/numeric_inputs.php
> + *   those inputs results to displaying a error message right above the required field.
```suggestion
 *   those inputs results in displaying an error message right above the required field.
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Input/Field/OptionalGroup/base.php
> + *   Example showing how a dependant group (aka sub form) might be attached to a checkbox.
```suggestion
 *   Example showing how a dependent group (aka sub form) might be attached to a checkbox.
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Input/Field/OptionalGroup/with_required_sub_inputs.php
> + *   ILIAS shows a optional group titled "this input is not required" and a checkbox with a byline.
```suggestion
 *   ILIAS shows an optional group titled "this input is not required" and a checkbox with a byline.
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Input/Field/Password/in_form.php
> + *   the Eyeopen-Glyph will display your input. Clicking that gyph again will hide your input. Clicking "Save" will
```suggestion
 *   the Eyeopen-Glyph will display your input. Clicking that glyph again will hide your input. Clicking "Save" will
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Input/Field/Password/with_contraints.php
> + *   ILIAS will apply your password if following requirements are fullfilled:
```suggestion
 *   ILIAS will apply your password if the following requirements are fulfilled:
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Input/Field/Radio/base.php
> + *   You can only activate one radio button at a time. Save your selection. ILIAS will display your selection in following format:
```suggestion
 *   You can only activate one radio button at a time. Save your selection. ILIAS will display your selection in the following format:
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Input/Field/Select/base.php
> + *   ILIAS will show you your selection in following format:
```suggestion
 *   ILIAS will show you your selection in the following format:
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Input/Field/Select/with_required.php
> + *   Do not choose an option (saving without having choosen an option): ILIAS will display an error message.
```suggestion
 *   Do not choose an option (saving without having chosen an option): ILIAS will display an error message.
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Input/Field/SwitchableGroup/base.php
> + *   Example showing how a dependant group (aka sub form) might be attached to a radio.
```suggestion
 *   Example showing how a dependent group (aka sub form) might be attached to a radio.
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Input/Field/SwitchableGroup/with_disabled.php
> + *   Example showing how a dependant group (aka sub form) might be attached to a radio while being disabled.
```suggestion
 *   Example showing how a dependent group (aka sub form) might be attached to a radio while being disabled.
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Input/Field/Tag/base.php
> + *   Example show how to create and render a basic tag input field and attach it to a
```suggestion
 *   The example shows how to create and render a basic tag input field and attach it to a
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Input/Field/Tag/base_with_data.php
> + *   Example show how to create and render a basic tag input field and attach it to a
```suggestion
 *   Example shows how to create and render a basic tag input field and attach it to a
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Input/Field/Tag/base_with_data.php
> + *   Clicking "Save" reloads the page and displays your input in the following format above teh input field:
```suggestion
 *   Clicking "Save" reloads the page and displays your input in the following format above the input field:
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Input/Field/Tag/disabled.php
> + *   Example show how to create and render a disabled tag input field and attach
```suggestion
 *   The Example shows how to create and render a disabled tag input field and attach
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Input/Field/Text/base.php
> + *   Example show how to create and render a basic text input field and attach it to a
```suggestion
 *   The example shows how to create and render a basic text input field and attach it to a
```

2024-10-25 12:35 UTC, Amstutz commented on src/UI/examples/Input/Field/Text/disabled.php
> + *   Example show how to create and render a disabled text input field and attach it to a
```suggestion
 *   The example shows how to create and render a disabled text input field and attach it to a
```

2024-10-25 13:43 UTC, lukastocker commented on src/UI/examples/Button/Close/base.php
> + *   ILIAS shows a grey box with an dark grey "X" in the right corner. Clicking the "X" won't activate any action.
Nach kurzer Absprache wird "grey" beibehalten, da das einfach britisches Englisch ist. "Gray" schreibt man im amerikanischen Englisch.

2024-10-25 16:14 UTC, Amstutz commented
@klees feel free to proceed as you deem fit, this is good for me.

2024-10-25 17:54 UTC, klees commented
Included as https://github.com/ILIAS-eLearning/ILIAS/commit/a63d1696c598b483a6129e9508916e8d8e1cc957

2024-10-25 17:54 UTC, closed without merging

2024-10-25 17:54 UTC, klees commented
Thanks y'all!