UI/Dropdowns: 42414, close all other Dropdowns
ILIAS-eLearning/ILIAS pull request #8265
Opened 2024-10-28 07:04 UTC by nhaagen

https://mantis.ilias.de/view.php?id=42414

2024-10-28 07:51 UTC, klees approved these changes

2024-10-28 13:40 UTC, thibsy requested changes
Hi @nhaagen,

Thx a lot for your contribution to the UI framework and solving the issue at hand.

We want this issue to be addressed soon, therefore we accept your proposal. However, we are not convinced that exposing a global array of dropdown menus is the best way to do so. Hence please:

- Roadmap: add a roadmap entry that describes we want a better solution for this. E.g. an event listener attached to the document, which either calls the dropdown's show method if the event target is the desired dropdown, or the hide method if the target is something else.

Kind regards,
@Amstutz and @thibsy

2024-10-29 07:50 UTC, nhaagen commented
Hi @thibsy ,
I changed to only store one dropdown, but of course, the issue is still the same.
Roadmap-entry is in.

2024-10-29 10:20 UTC, thibsy approved these changes
Thx a lot @nhaagen for improving the fix already. This LGTM, so I'll merge right away.

2024-10-29 10:23 UTC, merged