UI/Mainbar: 42574, keep context and focus slate entries
ILIAS-eLearning/ILIAS pull request #8497
Opened 2024-11-21 13:39 UTC by nhaagen

https://mantis.ilias.de/view.php?id=42574

2024-11-25 11:38 UTC, klees approved these changes

2024-11-25 11:40 UTC, klees commented
Hi @thibsy and @Amstutz,

this replaces some functionality (from jquery-ui?) that we implicitly have relied upon. Looks straight forward to me...

Kind regards!

2024-12-02 07:30 UTC, thibsy requested changes
#### Review 8497 (https://github.com/ILIAS-eLearning/ILIAS/pull/8497)

Hi @nnhaagen,

Thx a lot for your contribution to the UI framework.

Before we can merge this, please implement the following changes:

- [ ] Docu: this code looks very specific to jQuery-UI. Could you please provide a comment that links to the [`:focusable` selector](https://api.jqueryui.com/focusable-selector/), or check if this complex logic is really necessary for our use-case. Maybe the `tabindex` is sufficient?
- [ ] `tagName`: please use `instanceof` checks instead of this attribute and hard-coded strings. You can e.g. use `element.ownerDocument.defaultView.HTMLButtonElement`.

Kind regards,
@thibsy

2025-01-14 11:51 UTC, thibsy approved these changes
Hi @nhaagen, sorry for the delay here. This mostly LGTM now, so I will go ahead and merge this. For future reference, please try to avoid using globals like this and access them via the element.

2025-01-14 11:52 UTC, thibsy commented
@nhaagen, actually you need to rebase first. But I'll merge right after :)

2025-01-14 17:13 UTC, merged