Dashboard: refactor modals for multi manage
ILIAS-eLearning/ILIAS pull request #8522
Opened 2024-11-26 15:11 UTC by iszmais

https://mantis.ilias.de/view.php?id=42438

This PR refactors the modals on the dashboard to modern form modal dialogs without async confirmation and removes the legacy confirmation form.

2024-11-26 16:30 UTC, iszmais commented
Hello,

@lscharmer As announced I removed the async rendering of confirmations from the dashboard and integrated the modal into the new UI structure. Pls have a look at the code and the conceptional result.

Due to the usages of the new form, we need to slightly adapt the input of ref_ids for every manageable component within the dashboard. Therefore:
@klees please review `StudyProgramme` and `LearningSequence`
@alex40724 please review `Repository` (RecomendedContent)

Greetings,
@iszmais

2024-11-26 16:40 UTC, lscharmer requested changes

2024-11-26 16:40 UTC, lscharmer commented on Services/Dashboard/Block/classes/class.ilDashboardBlockGUI.php
> +                        $id.nextElementSibling.style.display = 'none';
Please extract this code into it's own file.

2024-11-26 16:40 UTC, lscharmer commented on Services/Dashboard/Block/classes/class.ilDashboardBlockGUI.php
> +                        let modal = $id.closest('.modal-content');
```suggestion
                        const modal = $id.closest('.modal-content');
```

2024-11-26 16:40 UTC, lscharmer commented on Services/Dashboard/Block/classes/class.ilDashboardBlockGUI.php
> +                                    i.closest('li').hidden = true
```suggestion
                                    i.closest('li').hidden = true;
```

2024-11-26 16:40 UTC, lscharmer commented on Services/Dashboard/Block/classes/class.ilDashboardBlockGUI.php
> +                        foreach ($form->getData() as $group) {
Please have a look if you can drop this `foreach` if you use `->withAdditionalTransformation` in line `486` instead. As this is part of input validation IMO this belongs to the managed fields.

2024-11-27 11:24 UTC, klees approved these changes

2024-11-28 16:20 UTC, lscharmer approved these changes

2024-12-03 11:53 UTC, alex40724 approved these changes

2024-12-03 11:55 UTC, merged