[Mantis 0022554] Fix wrong absolute paths (windows)
ILIAS-eLearning/ILIAS pull request #885
Opened 2018-02-14 09:19 UTC by d3r1w

This PR provides a possible solution for the issue described in the mantis ticket [0022554](https://www.ilias.de/mantis/view.php?id=22554)

There were two issues causing this problem:
* Wrong path separator between the base path of the filesystem abstraction and the supplied relativ path.
* Different fopen behaviour under windows let to an access denied error while accessing a directory.

Solution:
* Fallback to ILIAS defined constants to build the absolute path in the old filesystem abstraction.
* Replacement of the wrong path separator in the local filesystem abstraction.

2018-02-14 09:22 UTC, chfsx requested changes

2018-02-14 09:22 UTC, chfsx commented on src/Filesystem/Provider/FlySystem/FlySystemLocalFilesystemFactory.php
> +		$reflaction = new \ReflectionObject($adapter);
Typo in `$reflaction`--> `$reflection`

2018-02-14 09:22 UTC, chfsx commented on src/Filesystem/Provider/FlySystem/FlySystemLocalFilesystemFactory.php
> +use ReflectionClass;
Is `ReflectionClass` needed?

2018-02-14 09:30 UTC, d3r1w commented
Thx for the quick review @chfsx

2018-03-23 08:08 UTC, chfsx approved these changes

2018-03-23 08:08 UTC, merged

2018-03-23 08:11 UTC, chfsx commented
Thank you very much @d3r1w !