0022583: ilMimeTypeUtil: Some minor issues
ILIAS-eLearning/ILIAS pull request #892
Opened 2018-02-21 08:01 UTC by bseglias

https://www.ilias.de/mantis/view.php?id=22583

2018-02-21 08:09 UTC, chfsx requested changes

2018-02-21 08:09 UTC, chfsx commented on Services/Utilities/classes/class.ilMimeTypeUtil.php
> +		if (strpos($path_to_file, 'http://') !== FALSE || strpos($path_to_file, 'https://') !== FALSE) {
Hi @bseglias could you change `FALSE` to lowercase `false`? Thanks!

2018-02-21 08:36 UTC, chfsx commented
Hi @alex40724 LGTM, are these changes for you OK as well?

2018-02-21 08:36 UTC, chfsx approved these changes

2018-02-22 14:47 UTC, alex40724 commented
The bug report does not state how to reproduce any bug. What exactly do I need to do? What behaviour is fixed? The code changes look good, but if there is no bug, I would only put this into the trunk.

2018-03-01 10:59 UTC, chfsx commented
@mjansenDatabay would it be possible for you to add a sentence about Reproducibility in the mantis ticket? Thanks in advance!

2018-03-01 13:29 UTC, mjansenDatabay commented
@chfsx What do you mean by 'Reproducibility'? There is no current issue with the ILIAS core code base. I noticed the issues just by reviewing the existing code, because I have to rely on \ilObjMediaObject::getMimeType in a plugin (which I cannot ATM).

2018-03-08 06:57 UTC, chfsx commented
@mjansenDatabay for my part of the PR this is fine, many thanks! For me it's definitely a bug when writing "wrong" code or code which may break. there is no need fo a Fatal or something like that. The current code potentially leads to problem and you already found one using your plugin.

@alex40724 it's up to you whether you accept your party or not, feel free to give a feedback accordingly. Benjamin will adjust the PR then.

2018-03-08 09:35 UTC, alex40724 commented
Personally I tend to not accept bugs/code changes in stable releases, if I cannot reproduce a bug. 

@mjansenDatabay: Please at least write a short description what kind of bug you get in your plugin and that this change fixes this bug. Then it is ok for me.

2018-03-08 09:38 UTC, alex40724 approved these changes

2018-03-30 10:36 UTC, mjansenDatabay commented
@alex40724 The bug ist: If you pass a string like 'https://www.youtube.com/watch?v=WSgP85kr6eU', you will get 'application/octet-stream'.

I added some tests, see: https://github.com/ILIAS-eLearning/ILIAS/pull/944

2018-03-30 15:30 UTC, merged

2018-03-30 15:35 UTC, alex40724 commented
Great, thanks. I merged this to 5.3/trunk.