Update to newest simplesamlphp
ILIAS-eLearning/ILIAS pull request #902
Opened 2018-02-28 09:17 UTC by legionth

Updates the simplesamlephp package to the newest version 1.15.3.

References:
https://packagist.org/packages/simplesamlphp/simplesamlphp

2018-02-28 09:28 UTC, legionth commented
Ping @mjansenDatabay

2018-02-28 18:15 UTC, mjansenDatabay requested changes
Please add the relevant information in the "extra" section.

2018-03-01 08:03 UTC, legionth commented
Added the "information" additionally in the extra section. Have a look.

2018-03-01 08:58 UTC, mjansenDatabay requested changes

2018-03-01 08:58 UTC, mjansenDatabay commented on libs/composer/composer.json
>  			"last_update": "2017-07-12",
Please update this date.

2018-03-01 09:17 UTC, legionth commented
Solved changes. Have a look @mjansenDatabay

2018-03-01 09:30 UTC, mjansenDatabay requested changes

2018-03-01 09:30 UTC, mjansenDatabay commented on libs/composer/composer.json
>  			"last_update_by": "Michael Jansen <mjansen@databay.de>",
"last_update_by" is also missing :-)

2018-03-01 11:05 UTC, legionth commented on libs/composer/composer.json
>  			"last_update_by": "Michael Jansen <mjansen@databay.de>",
See newest commit

2018-03-01 11:06 UTC, legionth commented
Updated the PR and rebased it. The update of the dependencies although updated the development dependencies. I rebased the branch to avoid these updates.

2018-04-28 11:49 UTC, mjansenDatabay commented
@legionth Can you please update your branch to the current 5.3.x revision, then update the lib. to v. 1.15.4, and finally adopt the changes I made for the files in `./Services/Saml/`in the trunk?

Many thanks in advance.

2018-05-04 07:39 UTC, legionth commented
Hey @mjansenDatabay,

updated to recommended simplesaml version. Also cherry-picked the mentioned commits.

Happy "Review" :sweat_smile:

2018-05-14 13:48 UTC, mjansenDatabay approved these changes

2018-05-14 13:59 UTC, merged