KS Emoticon Glyphs 5.4
ILIAS-eLearning/ILIAS pull request #908
Opened 2018-03-03 10:43 UTC by alex40724

Feature Request:
https://www.ilias.de/docu/goto_docu_wiki_wpage_4698_1357.html

2018-03-03 10:47 UTC, alex40724 commented
Two questions:
- Any idea why this is not appearing in the KS docs with these code changes? What is missing?
- Is this the way to proceed with the other emoticon glyphs?

2018-03-05 15:08 UTC, Amstutz requested changes
Thanks for this commit. I commented on some rather minor details. Note that I would also love to have a "dislike" emo. However, I do not have a strong opinion on this.

Concerning your questions:
- Worked like a charm on my local installation. Did you click on the "Refresh Entries"-Button? Note that this button only appears in Dev-Mode and if you activated the manage system style setting in the setup.
- Yes, this seems correct to me. After all, the def. by using unicodes is what makes them glyphs and not icons or graphical buttons to me.

2018-03-05 15:08 UTC, Amstutz commented on src/UI/Component/Glyph/Factory.php
> +	 *       The Like Glyph uses the "thumbs up" unicode emoji U+1F44D
Add Period. Any hints about this "special unicode", any reference. Ist this some kind of standard. Maybe note, that this is not from the default bootstrap set, which is fine as long as we have a JF dec. for that.

2018-03-05 15:08 UTC, Amstutz commented on src/UI/Component/Glyph/Factory.php
> +	 *       Clicking toggles the state of the user expression. Clicking also updates the respective counter.
Is it possible to somehow add a hover effect to this? Currently there is none.

2018-03-05 15:08 UTC, Amstutz commented on src/UI/Component/Glyph/Factory.php
> +	 *       The Love Glyph uses the "red heart" unicode emoji U+2764
Same as above, period, reference etc.

2018-03-12 14:09 UTC, klees commented
https://github.com/MorbZ/OpenSansEmoji is an Emoji-Font with Apache 2.0 License.

2018-03-12 14:12 UTC, matthiaskunkel commented
Jour Fixe, 12 MAR 2018: We accept this PR for trunk. Please introduce monochrome glyphs for all needed emoticons.

2018-03-12 14:12 UTC, Amstutz commented
We would like to help working out a "ILIAS" default Glyph-Font set. Contact us. Note that: All Glyphs MUST be taken from the Bootstrap Glyphicon Halflings set. Exceptions MUST be approved by the JF. So it is oke, to propose new Glyphs.

2018-03-22 13:52 UTC, merged