Reduce code duplication in Forum Notification Mails
ILIAS-eLearning/ILIAS pull request #949
Opened 2018-04-03 10:53 UTC by legionth

Removes the code duplication in the notification mails of the forum.

2018-04-03 11:42 UTC, mjansenDatabay commented
I suggest to add typehints and return type declarations to all new methods.

2018-04-03 12:48 UTC, mjansenDatabay requested changes
I suggest to add typehints and return type declarations to all new methods.

2018-04-04 11:18 UTC, mjansenDatabay commented on Modules/Forum/classes/class.ilForumMailNotification.php
> +		string $subject,
@legionth I suggest to rename this to `$subjectLanguageVariable` oder `$subjectLanguageId`

Furthermore you pass the **subject** here, but the method is named `addBodyToMailWithoutAttachments`

2018-04-04 11:18 UTC, mjansenDatabay commented on Modules/Forum/classes/class.ilForumMailNotification.php
> +	 * @param string $subject - Language id of subject
@legionth I suggest to rename this to `$subjectLanguageVariable` oder `$subjectLanguageId`

2018-04-04 11:18 UTC, mjansenDatabay commented on Modules/Forum/classes/class.ilForumMailNotification.php
> +		$this->addMailSubject($subject);
@legionth You set the **subject** here, but the method is named `addMailBody`

2018-04-04 11:18 UTC, mjansenDatabay commented on Modules/Forum/classes/class.ilForumMailNotification.php
> +		string $subject,
@legionth I suggest to rename this to `$subjectLanguageVariable` oder `$subjectLanguageId`

Furthermore you pass the **subject** here, but the method is named `addBodyToMailWithoutAttachments`

2018-04-04 11:18 UTC, mjansenDatabay commented on Modules/Forum/classes/class.ilForumMailNotification.php
> +	 * @param string $subject - Language id of subject
@legionth I suggest to rename this to `$subjectLanguageVariable` oder `$subjectLanguageId`

2018-04-04 11:18 UTC, mjansenDatabay commented on Modules/Forum/classes/class.ilForumMailNotification.php
> +					$this->addBodyToMailWithoutAttachments('frm_noti_subject_del_thread', $rcp, $customText, 'content_deleted_thread');
@legionth I recommend to case the arguments ((int) / (string) etc.)

2018-04-04 11:18 UTC, mjansenDatabay commented on Modules/Forum/classes/class.ilForumMailNotification.php
> +					$this->addBodyToMailWithAttachments('frm_noti_subject_new_post', $rcp, $customText, 'new_post');
@legionth I recommend to case the arguments ((int) / (string) etc.)

2018-04-04 11:18 UTC, mjansenDatabay commented on Modules/Forum/classes/class.ilForumMailNotification.php
> +					$this->addBodyToMailWithAttachments('frm_noti_subject_act_post', $rcp, $customText, 'new_post');
@legionth I recommend to case the arguments ((int) / (string) etc.)

2018-04-04 11:18 UTC, mjansenDatabay commented on Modules/Forum/classes/class.ilForumMailNotification.php
> +					$this->addBodyToMailWithAttachments('frm_noti_subject_answ_post', $rcp, $customText, 'new_post');
@legionth I recommend to case the arguments ((int) / (string) etc.)

2018-04-04 11:18 UTC, mjansenDatabay commented on Modules/Forum/classes/class.ilForumMailNotification.php
> +					$this->addBodyToMailWithAttachments('frm_noti_subject_upt_post', $rcp, $customText, 'content_post_updated');
@legionth I recommend to case the arguments ((int) / (string) etc.)

2018-04-04 11:18 UTC, mjansenDatabay commented on Modules/Forum/classes/class.ilForumMailNotification.php
> +					$this->addBodyToMailWithAttachments('frm_noti_subject_cens_post', $rcp, $customText, 'content_censored_post');
@legionth I recommend to case the arguments ((int) / (string) etc.)

2018-04-04 11:18 UTC, mjansenDatabay commented on Modules/Forum/classes/class.ilForumMailNotification.php
> +					$this->addBodyToMailWithAttachments('frm_noti_subject_uncens_post', $rcp, $customText, 'forums_the_post', $date);
@legionth I recommend to case the arguments ((int) / (string) etc.)

2018-04-04 11:18 UTC, mjansenDatabay commented on Modules/Forum/classes/class.ilForumMailNotification.php
> +					$this->addBodyToMailWithoutAttachments('frm_noti_subject_del_post', $rcp, $customText, 'content_deleted_post');
@legionth I recommend to case the arguments ((int) / (string) etc.)

2018-04-04 11:18 UTC, mjansenDatabay commented on Modules/Forum/classes/class.ilForumMailNotification.php
> +		if ($date === null) {
@legionth Is it a valid case that `$date` equals `null`. Do we have to change the primitive type hint in the method signature?

2018-04-04 11:50 UTC, legionth commented on Modules/Forum/classes/class.ilForumMailNotification.php
> +		$this->addMailSubject($subject);
Renamed the method

2018-04-04 11:51 UTC, legionth commented
Renamed the methods in the latest commit and fixed your remarks @mjansenDatabay

2018-04-04 13:30 UTC, mjansenDatabay approved these changes

2018-04-04 13:30 UTC, mjansenDatabay commented on Modules/Forum/classes/class.ilForumMailNotification.php
> +					$this->sendMailWithAttachments('frm_noti_subject_cens_post', (int) $rcp, (string) $customText, 'content_censored_post');
@legionth Maybe the date is missing here

2018-04-04 13:30 UTC, mjansenDatabay commented on Modules/Forum/classes/class.ilForumMailNotification.php
> +					$this->sendMailWithAttachments('frm_noti_subject_upt_post', (int) $rcp, (string) $customText, 'content_post_updated');
@legionth The date is missing here

2018-04-04 13:30 UTC, merged