Remove usage of globals in ilChatroomSettingsGUI
ILIAS-eLearning/ILIAS pull request #978
Opened 2018-04-09 12:35 UTC by legionth

2018-04-09 12:39 UTC, mjansenDatabay commented
#22851

2018-04-09 14:51 UTC, mjansenDatabay requested changes

2018-04-09 14:51 UTC, mjansenDatabay commented on Modules/Chatroom/classes/gui/class.ilChatroomSettingsGUI.php
> +		global $DIC;
Please check if you can use ...

```php
$this->ilCtrl       = $DIC->ctrl();
$this->ilLng       = $DIC->language();
```
... provided by the base class.

2018-04-10 06:47 UTC, legionth commented
Implemented your suggestions @mjansenDatabay . Have a look

2018-04-10 07:07 UTC, legionth commented
Rebased the branch. And added implemented your suggestions. Have a look @mjansenDatabay

2018-04-10 07:19 UTC, mjansenDatabay approved these changes

2018-04-10 07:20 UTC, merged